### ISSUE TITLE
ESAPI: Have Esys_TR_SetAuth() handle large passwords

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tss#1008]
Currently, Esys_TR_SetAuth() is restricted to authValues shorter or equal to the nameAlg digest size.
The TPM 2.0 library spec part 1 recommends hashing authVaules with the nameAlg if they exceed the nameAlg digest size, but to keep then in the plain if they are shorter.

The ESAPI should adopt this behavior. We shall implement this here and also propose it to TCG.

**Comment by AndreasFuchsSIT** [comment]
This of course also has to touch Esys_Create, Esys_CreatePrimary, Esys_CreateLoaded, Esys_NV_DefineSpace

**Comment by tstruk** [comment]
@AndreasFuchsSIT I don't get that. Since The TPM 2.0 spec recommends this, why do we need to propose it to TCG?

**Comment by AndreasFuchsSIT** [comment]
@tstruk TPM2 spec recommends it. TSS spec does not contain it. We need to propose it as mandatory behaviour for the TSS spec.

**Comment by williamcroberts** [comment]
So does PR #1929 address all of this? What about hierarchy authorizations? Do sequence objects come through that API?
