### ISSUE TITLE
Replace C++ comments in C source code with C comments

### ISSUE THREAD

**Issue by danintel** [tpm2-software/tpm2-tss#1009]
Replace C++ comments with C comments in C source code.
For example:
-    // Initialized the system context structure.
+    /* Initialize the system context structure. */

**Comment by williamcroberts** [comment]
> Replace C++ comments with C comments in C source code.
> For example:
> 
> *	// Initialized the system context structure.

That's C99.

> 
> *	/* Initialize the system context structure. */
>

**Comment by danintel** [comment]
Yes it is.
I was called out on it, so the same rule should apply to everyone.
Or we can change the rules.

**Comment by williamcroberts** [comment]
C comments (#1009)
> 
> Yes it is.
> I was called out on it, so the same rule should apply to everyone.
> Or we can change the rules.

https://github.com/tpm2-software/tpm2-tss/blob/master/doc/coding_standard_c.md

rules say // is ok.

**Comment by tstruk** [comment]
The main thing is that it should be consistent, and since we mostly use C style, this change is probably the right thing to do.

**Comment by williamcroberts** [comment]
> According to:
> https://github.com/tpm2-software/tpm2-
> tss/blob/master/doc/coding_standard_c.md
> C++ comments are not OK:

It's not acceptable for block comments, but is acceptable for line comments.

>
