### ISSUE TITLE
Fix coverity scan defects in esys_crypto.c

### ISSUE THREAD

**Issue by tstruk** [tpm2-software/tpm2-tss#1011]
*** CID 1468838:  Null pointer dereferences  (REVERSE_INULL)
/src/tss2-esys/esys_crypto.c: 987 in iesys_cryptogcry_KDFe()
981                 if (label != NULL) {
982                     size_t lsize = strlen(label) + 1;
983                     r = iesys_crypto_hash_update(cryptoContext, (uint8_t *) label, lsize);
984                     goto_if_error(r, "Error hash update", error);
985                 }
986     
>>>     CID 1468838:  Null pointer dereferences  (REVERSE_INULL)
>>>     Null-checking "partyUInfo" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
987                 if (partyUInfo != NULL) {
988                     r = iesys_crypto_hash_update2b(cryptoContext, (TPM2B *) partyUInfo);
989                     goto_if_error(r, "Error hash update2b", error);
990                 }
991     
992                 if (partyVInfo != NULL) {

** CID 1468837:  Null pointer dereferences  (REVERSE_INULL)
/src/tss2-esys/esys_crypto.c: 992 in iesys_cryptogcry_KDFe()

________________________________________________________________________________________________________
*** CID 1468837:  Null pointer dereferences  (REVERSE_INULL)
/src/tss2-esys/esys_crypto.c: 992 in iesys_cryptogcry_KDFe()
986     
987                 if (partyUInfo != NULL) {
988                     r = iesys_crypto_hash_update2b(cryptoContext, (TPM2B *) partyUInfo);
989                     goto_if_error(r, "Error hash update2b", error);
990                 }
991     
>>>     CID 1468837:  Null pointer dereferences  (REVERSE_INULL)
>>>     Null-checking "partyVInfo" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
992                 if (partyVInfo != NULL) {
993                     r = iesys_crypto_hash_update2b(cryptoContext,  (TPM2B *) partyVInfo);
994                    goto_if_error(r, "Error hash update2b", error);
995                 }
996                 r = iesys_crypto_hash_finish(&cryptoContext, (uint8_t *) stream, &hash_len);
997                 goto_if_error(r, "Error", error);

**Comment by danintel** [comment]
Clever check--checking for NULL dereferences before a NULL check in a function.
