### ISSUE TITLE
Magic number in tests

### ISSUE THREAD

**Issue by RSynch** [tpm2-software/tpm2-tss#1024]
In file /test/integration/esys-firmware-read.int.c, line 50-54:
```
   if (r == TPM2_RC_COMMAND_CODE) {
        LOG_INFO("Command TPM2_FieldUpgradeData not supported by TPM.");
        r = 77; /* Skip */
        goto error;
    }
```
The magic return value 77 appears in a few more integration tests:
esys-createloaded.int.c
esys-ecc-parameters.int.c
esys-field-upgrade.int.c
esys-get-time.int.c

**Comment by AndreasFuchsSIT** [comment]
thanks a lot for the report.
Return code 77 in autotools means that a test was skipped. This happens e.g. on rev1.38 commands if we have rev1.16 TPM.
(see https://www.gnu.org/software/automake/manual/html_node/Scripts_002dbased-Testsuites.html)

**Comment by RSynch** [comment]
I see your point, but would it not be better to define the different exit values somewhere and then write something like
```
return TEST_SKIP;
```
or 
```
return TEST_FAIL;
```
instead of the number itself?
