### ISSUE TITLE
Unnecessary startup calls leading to many log messages

### ISSUE THREAD

**Issue by RSynch** [tpm2-software/tpm2-tss#1025]
When executing make check, the resulting logs (both the summary and the separate files) contain these lines for every single test:
```
WARNING:esys:src/tss2-esys/api/Esys_Startup.c:236:Esys_Startup_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_Startup.c:102:Esys_Startup() Esys Finish ErrorCode (0x00000100) 
```
This is because in main-esapi.c Esys_Startup is called which would not be necessary.
Although this does not affect the test results, removing the unnecessary function call would keep the logs clear for the real problems.
The below files show the results with and without Startup in esapi-main.
The results are the same, except that the above messages no longer appear.
[test-suite_withoutStartup.log](https://github.com/tpm2-software/tpm2-tss/files/2039230/test-suite_withoutStartup.log)
[test-suite.log](https://github.com/tpm2-software/tpm2-tss/files/2039231/test-suite.log)

**Comment by AndreasFuchsSIT** [comment]
Yes, we've discussed this before in #911 

Maybe we can silence the corresponding code path.
@RSynch What do you think ? Would that suit your need ?

**Comment by tstruk** [comment]
We can just check if (rc != TPM2_RC_INITIALIZE) in Esys_Startup_Finish() and only then print the warning.

**Comment by tstruk** [comment]
Fixed by https://github.com/tpm2-software/tpm2-tss/pull/1080
