### ISSUE TITLE
Wrong value of TPM2_NUM_PCR_BANKS

### ISSUE THREAD

**Issue by tstruk** [tpm2-software/tpm2-tss#1026]
Setting TPM2_NUM_PCR_BANKS to 3 worked fine when SHA512 was disabled.
When enabled the Tss2_Sys_GetCapability() fails to numarshal TPML_PCR_SELECTION.
This should be set to 4 or ideally derived from the number of enabled hashes. 
See related discussion in tools: https://github.com/tpm2-software/tpm2-tools/issues/1021

**Comment by AndreasFuchsSIT** [comment]
See my comments on #1027 

VMWare vTPM is one of the unusual TPMs with a bunch of active banks.

But apparently the TCG did not update the TSS spec in order to accomodate for this one TPM that behaves different from all others.

**Comment by flihp** [comment]
We just took this issue back to the TSS WG and we all agreed that the additional overhead of supporting extra PCR banks is a small price to pay for compatibility. We'll be working to hopefully convince VMWare and other vTPM providers to support a small number of banks (2 is ideal) to keep hashing overhead down. The overhead of having 4+ hashes carried out for each extend is non negligible for systems like IMA where an extend operation may be carried out every time a file is read from disk.

So the TSS WG has actually proposed that we increase the value of `TPM2_NUM_PCR_BANKS` from 4 to 16 just to future proof implementations. Embedded implementations that are counting bytes of stack space carefully can themselves tailor this value to their specific environments.

Based on this, if we agree that 16 PCR banks is an acceptable limit we should re-open #1027 and update the patch from 8 to 16. Thoughts?

**Comment by AndreasFuchsSIT** [comment]
Agreed.
Let's however mention the deviation from the linked spec revision in README.md
Preferably prominently in its own section.
