### ISSUE TITLE
Tests do no proper cleanup at the end

### ISSUE THREAD

**Issue by RSynch** [tpm2-software/tpm2-tss#1030]
Currently, a number of tests do not clean up after their test execution (esys-policy-regression.int.c for example does not undefine defined NV space).

Other tests do a cleanup, but not under all circumstances (esys-nv-ram-counter.int.c does undefine its defined NV space, but this is skipped in case an error is returned earlier).

There are more similar issues that leave the TPM in a state where following tests are doomed to fail. When the tests are run against the simulator, this is not a problem since every test starts its own simulator and discards it when finished. If however the tests shall ever run on a HW TPM (even if it is only to prove the TSS is working properly), the tests should be fixed.

The right way to achieve this (fixing each test individually or a more generic approach) remains to be discussed.

**Comment by tstruk** [comment]
Fixed by https://github.com/tpm2-software/tpm2-tss/pull/1060
