### ISSUE TITLE
Configure won't pass gcry_mac_open in -lgcrypt

### ISSUE THREAD

**Issue by nugatorium** [tpm2-software/tpm2-tss#1032]
I am using CentOS 7 and have libgcrypt-devel-1.5.3-14.el7.x86_64 installed.  

After generating the configure file and then running it I get to here:
The error:
```
checking gcrypt.h usability... yes
checking gcrypt.h presence... yes
checking for gcrypt.h... yes
checking for gcry_mac_open in -lgcrypt... no
configure: error: Missing required library: gcrypt.
```

Other than installing another OS, has anyone else run into this and solved it?  I can't seem to find any information on what to do next.

**Comment by AndreasFuchsSIT** [comment]
We are using libgcrypt 1.6 and above or what's packaged as libgcrypt20 on debian/ubuntu. They also contain a libgcrypt11 package.

The 1.6 release dates back to 2013 (https://github.com/gpg/libgcrypt/releases/tag/libgcrypt-1.6.0).

So I wonder if latest libgcrypt on CentOS 7 is really 5 years old other whether there is a second package based on the 2013 API extension.

Also you may expect an OpenSSL based backend soon(ish). Maybe for 2.1. That may help too...

**Comment by nugatorium** [comment]
`$ rpm -qv libgcrypt
libgcrypt-1.5.3-14.el7.x86_64`

Okay, that would explain it most likely.  Thanks!
