### ISSUE TITLE
TCTI dynamic init convenience library

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#1046]
The TCTI dynamic loading protocol has been adopted in the tools, the tabrmd and also in the esys implementation. Each has it's own implementation. For the sake of efficiency and consistency (much easier to keep behavior consistent when there's only one implementation) we should collect these implementations in a small convenience library (possibly just a static one?).

**Comment by AndreasFuchsSIT** [comment]
See https://github.com/tpm2-software/tpm2-tss/wiki/TCTI-loader-library

**Comment by tstruk** [comment]
That's already done in #1470
