### ISSUE TITLE
SPDX-License identifiers

### ISSUE THREAD

**Issue by PeterHuewe** [tpm2-software/tpm2-tss#1050]
What is your opinion on adding SPDX-License identifiers to our source code files like:
    SPDX-License-Identifier:	BSD-3-Clause
This would make it easier to parse / check the license for packagers and distributions.
And the question is whether we then could remove the boiler plate text of the license in each file, as possible per: https://spdx.org/spdx-specification-21-web-version#h.twlc0ztnng3b

**Comment by tstruk** [comment]
On 06/08/2018 05:16 AM, Peter Huewe wrote:
> What is your opinion on adding SPDX-License identifiers to our source code files like:
> SPDX-License-Identifier: BSD-3-Clause
> This would make it easier to parse / check the license for packagers and distributions.
Hi Peter,
Yes, we do have plans to introduce SPDX License tags in TSS.
If you have any patches please send a PR.
That would me very much appreciated.
Thanks,
-- 
Tadeusz

**Comment by PeterHuewe** [comment]
I think i could do that easily enough, I just wanted to get confirmation first.
So short spdx (i.e. removing the license text in each file, keeping copyrights) it is?

**Comment by tstruk** [comment]
On 06/08/2018 01:27 PM, Peter Huewe wrote:
> I think i could do that easily enough, I just wanted to get confirmation first.
> So short spdx (i.e. removing the license text in each file, keeping copyrights) it is?
> 
Yes, this is exactly how it should look like. 
Thanks,
-- 
Tadeusz

**Comment by PeterHuewe** [comment]
Hmm,
can't assign it to me, but I will work on this during the next few days.
If you can assign this to me, please do so.

**Comment by PeterHuewe** [comment]
Quick question:

Most comments in our source are C99 style:
```
/*******************************************************************************
 * Copyright 2017-2018, Fraunhofer SIT sponsored by Infineon Technologies AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
...
```
However of the SPDX projects put the SPDX in the first possible line 
e.g. https://github.com/u-boot/u-boot/tree/master/Licenses
and use C89 tags for C source files.

So what do you prefer:

Option 1:
```
// SPDX-License-Identifier: BSD-2
/*******************************************************************************
 * Copyright 2017-2018, Fraunhofer SIT sponsored by Infineon Technologies AG
 * All rights reserved.
 *******************************************************************************/
```
or 
Option 2:
```
/* SPDX-License-Identifier: BSD-2 */
/*******************************************************************************
 * Copyright 2017-2018, Fraunhofer SIT sponsored by Infineon Technologies AG
 * All rights reserved.
 *******************************************************************************/
```
or 
Option 3:
```
/*******************************************************************************
 * Copyright 2017-2018, Fraunhofer SIT sponsored by Infineon Technologies AG
 * All rights reserved.
 * SPDX-License-Identifier: BSD-2 
 *******************************************************************************/
```
or 
Option 4:
```
/*******************************************************************************
 * SPDX-License-Identifier: BSD-2
 * Copyright 2017-2018, Fraunhofer SIT sponsored by Infineon Technologies AG
 * All rights reserved. 
 *******************************************************************************/
```

**Comment by tstruk** [comment]
I think option 2 is the most common one so let's go with that.
