### ISSUE TITLE
Configure: Check for netstat and other progs

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tss#1059]
We should check for all commandline tools used in the integration tests at configure time it integration tests are enabled.
One that is not checked is `netstat` and I assume `ps`.

This comes after going through some extensive remote debugging that would not have been needed.

**Comment by tstruk** [comment]
The check for ps is still missing. It is part of the procps package (debian/ubuntu) or procps-ng (fedora)

**Comment by tstruk** [comment]
See related https://github.com/tpm2-software/tpm2-tss/issues/790
