### ISSUE TITLE
Incompatibility of TSS with kernel space RM

### ISSUE THREAD

**Issue by RSynch** [tpm2-software/tpm2-tss#1063]
The kernel space resource manager handles unsupported commands (https://github.com/torvalds/linux/commit/095531f891e627e408606f2da4008d3d53e6748a).
When receiving an unsupported command, instead of 0x143 0xb0143 is returned. This is in compliance with the RM Spec (https://trustedcomputinggroup.org/wp-content/uploads/TSS-TAB-and-Resource-Manager-00-91-PublicReview.pdf), Section 4.1.
This leads to problems with the TSS, since the "regular error handling" which is implemented in every Esys source file, does not check for this. 
```    
if (r != TSS2_RC_SUCCESS && (r & TSS2_RC_LAYER_MASK) == 0) {
        LOG_WARNING("Received TPM Error");
        esysContext->state = _ESYS_STATE_INIT;
        goto error_cleanup;
    } else if (r != TSS2_RC_SUCCESS) {
        LOG_ERROR("Received a non-TPM Error");
        esysContext->state = _ESYS_STATE_INTERNALERROR;
        goto error_cleanup;
    }
```
If there are error bits set by the RM, the TSS sets the state of the esysContext to INTERNALERROR and the context can no longer be used.

**Comment by JuergenReppSIT** [comment]
There is a contradiction between the definitions in 
[TAB and Resource Manager Specification Version 1.0 Revision 18]( https://trustedcomputinggroup.org/wp-content/uploads/TSS-2.0-TAB-Resource-Manager-SpecVer1.0-Rev18_review_END030918.pdf)

```
#define TSS2_RESMGRTPM_RC_LAYER ( 11 << TSS2_RC_LAYER_SHIFT)
#define TSS2_RESMGR_RC_LAYER ( 12 << TSS2_RC_LAYER_SHIFT)
```
and
[TSS Overview and Common Structures Specification Version 0.90 Revision 3](https://trustedcomputinggroup.org/wp-content/uploads/TSS_Overview_Common_Structures_Version-0.9_Revision-03_Review_030918.pdf)
```
#define TSS2_RESMGR_RC_LAYER TSS2_RC_LAYER(11) /* base is a TSS2_BASE_RC_* */
#define TSS2_RESMGR_TPM_RC_LAYER TSS2_RC_LAYER(12) /* base is aTPM_RC_* */
```
From V4.14 the Linux kernel uses the constant defined in the RM Spec, while tss2 defines the constant definitions from the Common Structures spec. So for /dev/tpmrm0  in the current tss2 version the check whether a command is implemented would be:
```
(rc == (TPM2_RC_COMMAND_CODE | TSS2_RESMGR_RC_LAYER))

```
ESAPI should not go into state internal error in both cases (11/12).
