### ISSUE TITLE
Missing header in src/tss2-tcti/tcti-mssim.c

### ISSUE THREAD

**Issue by safayetahmedatge** [tpm2-software/tpm2-tss#1064]
tcti-mssim.c uses functions from "string.h" but does not explicitly include "string.h".

The absence of this include breaks the build in an Alpine container. Adding this include statement allows the build to complete with default configuration without errors.

**Comment by tstruk** [comment]
Could you please send a patch for this issue. Thanks

**Comment by safayetahmedatge** [comment]
Thanks for the response. I created a pull request:
https://github.com/tpm2-software/tpm2-tss/pull/1065

**Comment by tstruk** [comment]
Fixed with https://github.com/tpm2-software/tpm2-tss/pull/1065
