### ISSUE TITLE
tpm2-tss 2.0 configure says gcrypt lib missing on CentOS 7

### ISSUE THREAD

**Issue by pscheie** [tpm2-software/tpm2-tss#1069]
It appears something changed from tss 1.4 to 2.0 with respect to gcrypt, at least on CentOS 7.  When I run configure, it fails, saying the gcrypt library is missing, even though I've got CentOS's version 1.5.3-14 installed including the devel package (which is a bit old, but it's what CentOS/RHEL provides).  Here's the output from configure:

...
checking pkg-config is at least version 0.9.0... yes
checking gcrypt.h usability... yes
checking gcrypt.h presence... yes
checking for gcrypt.h... yes
checking for gcry_mac_open in -lgcrypt... no
configure: error: Missing required library: gcrypt.

Compiling tss 1.4 does not have this problem.  I just ran yum update, so CentOS is current.  Does 2.0 require something newer in gcrypt?  Or is there some other problem?

**Comment by pscheie** [comment]
Just to add a bit: It appears that while the configure script for tss 2.0 does checks gcrypt_mac_open(), in 1.4 there is no such check.

**Comment by pscheie** [comment]
It appears libgcrypt added gcry_mac_open in version 1.6, so those of us stuck on RHEL/CentOS 7 may be out of luck for tpm2-tss 2.0.

**Comment by tstruk** [comment]
ESAPI, which was added in TSS 2.0 uses gcry_mac_open() hence the explicit check for it.
If you don't need ESAPI and want to use TSS 2.0 you can still use it by disabling it by:
./configure --enable-esapi=no

**Comment by tstruk** [comment]
BTW Libgcrypt 1.5 and 1.6 are both End Of Life
https://www.gnupg.org/download/index.html#libgcrypt

**Comment by pscheie** [comment]
Ah, thanks for the configure tip.

Yeah, I saw that 1.5 (and even 1.6) is EOL.  Unfortunately, we can't go outside the boundaries of RHEL7.
