### ISSUE TITLE
tpm2-tss cross compilation

### ISSUE THREAD

**Issue by mohamedalgalby** [tpm2-software/tpm2-tss#1074]
Hi,
I'm new to TPM and to Linux too and hope I can get some help here. I'm using TPM2.0 SLB 6970 form Infineon on an embedded gateway board with Zynq-7000 SoC device from Xlinx, so it includes a single-core ARM Cortex™-A9 processor. The board runs a distribution of Linux for embedded systems. Usually, to compile any code for my board, I must source an environement setup script called "**environment-setup-cortexa9hf-neon-oe-linux-gnueabi**" and then I can compile the code file using $CC e.g. $CC -o myfile myfile.c. My quesition is how to compile the **tpm2-tss**, **tpm2-abrmd** and **tpm2-tools** so that I can run TPM 2.0 commands like generating crypto keys and doing simple encryption/decryption stuff on my machine? I tried to source my setup script firstly and then run the following:
./bootstap
./configure --build=i686-pc-linux-gnu --host=arm-oe-linux-gnueabi --target=arm-oe-linux-gnueabi
but I got comiplation error. I guessed it might be an invalid host or target names. 
Another question, if we set host, build and target names correctly, don't we need also to explicitly specify an option for using **$CC** instead of **gcc** for the ./configure command?
Thank you.
Mohamed Al-Galby

**Comment by williamcroberts** [comment]
> -----Original Message-----
> From: mohamedalgalby [mailto:notifications@github.com]
> Sent: Sunday, July 1, 2018 3:27 AM
> To: tpm2-software/tpm2-tss <tpm2-tss@noreply.github.com>
> Cc: Subscribed <subscribed@noreply.github.com>
> Subject: [tpm2-software/tpm2-tss] tpm2-tss cross compilation (#1074)
> 
> Hi,
> I'm new to TPM and to Linux too and hope I can get some help here. I'm using
> TPM2.0 SLB 6970 form Infineon on an embedded gateway board with Zynq-7000
> SoC device from Xlinx, so it includes a single-core ARM Cortex™-A9 processor.
> The board runs a distribution of Linux for embedded systems. Usually, to compile
> any code for my board, I must source an environement setup script called
> "environment-setup-cortexa9hf-neon-oe-linux-gnueabi" and then I can compile
> the code file using $CC e.g. $CC -o myfile myfile.c. My quesition is how to compile
> the tpm2-tss, tpm2-abrmd and tpm2-tools so that I can run TPM 2.0 commands
> like generating crypto keys and doing simple encryption/decryption stuff on my
> machine? I tried to source my setup script firstly and then run the following:
> ./bootstap
> ./configure --build=i686-pc-linux-gnu --host=arm-oe-linux-gnueabi --target=arm-
> oe-linux-gnueabi but I got comiplation error. I guessed it might be an invalid host

Like what?

> or target names.
> Another question, if we set host, build and target names correctly, don't we need
> also to explicitly specify an option for using $CC instead of gcc for the ./configure
> command?

You may need to run --disable-hardening, which is discouraged, but I haven't attempted
Any of those options while cross compiling.

I'm not super familiar with cross compiling and autotools, but I do know that one can
set the variables during either configure or make, either explicitly, or they exported
variable in the environment is used.

Ie all these are the same:
./configure CC=foo

export CC=foo
./configure

CC=foo ./configure

As well as:
make CC=foo

CC=foo make

export CC=foo
make

Other variables like CFLAGS, LDFLAGS, etc should be respected as well.

**Comment by flihp** [comment]
Closing this on account of it going stale. Feel free to reopen the issue when the requested data is available.

**Comment by mohamedalgalby** [comment]
Sorry for the delay. When I sourced my environment setup script  "environment-setup-cortexa9hf-neon-oe-linux-gnueabi"  using this command:
**. /home/sdk/environment-setup-cortexa9hf-neon-oe-linux-gnueabi** 
and then run the configure command with build and host arguments:
**./configure --build=x86_64-pc-linux-gnu --host=arm-oe-linux-gnueabi**
I got the following with an error at the end (**missing header gcrypt.h**):
**Configure: loading site script /home/sdk/site-config-cortexa9hf-neon-oe-linux-gnueabi
./configure: line 2387: -O2: command not found
checking for arm-oe-linux-gnueabi-gcc... arm-oe-linux-gnueabi-gcc  -march=armv7-a -marm -mfpu=neon  -mfloat-abi=hard -mcpu=cortex-a9 --sysroot=/home/sdk/sysroots/cortexa9hf-neon-oe-linux-gnueabi
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether arm-oe-linux-gnueabi-gcc  -march=armv7-a -marm -mfpu=neon  -mfloat-abi=hard -mcpu=cortex-a9 --sysroot=/home/sdk/sysroots/cortexa9hf-neon-oe-linux-gnueabi accepts -g... yes
checking for arm-oe-linux-gnueabi-gcc  -march=armv7-a -marm -mfpu=neon  -mfloat-abi=hard -mcpu=cortex-a9 --sysroot=/home/sdk/sysroots/cortexa9hf-neon-oe-linux-gnueabi option to accept ISO C89... none needed
checking whether arm-oe-linux-gnueabi-gcc  -march=armv7-a -marm -mfpu=neon  -mfloat-abi=hard -mcpu=cortex-a9 --sysroot=/home/sdk/sysroots/cortexa9hf-neon-oe-linux-gnueabi understands -c and -o together... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... arm-oe-linux-gnueabi
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by arm-oe-linux-gnueabi-gcc  -march=armv7-a -marm -mfpu=neon  -mfloat-abi=hard -mcpu=cortex-a9 --sysroot=/home/sdk/sysroots/cortexa9hf-neon-oe-linux-gnueabi... arm-oe-linux-gnueabi-ld  --sysroot=/home/sdk/sysroots/cortexa9hf-neon-oe-linux-gnueabi
checking if the linker (arm-oe-linux-gnueabi-ld  --sysroot=/home/sdk/sysroots/cortexa9hf-neon-oe-linux-gnueabi) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... arm-oe-linux-gnueabi-nm
checking the name lister (arm-oe-linux-gnueabi-nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to arm-oe-linux-gnueabi format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for arm-oe-linux-gnueabi-ld  --sysroot=/home/sdk/sysroots/cortexa9hf-neon-oe-linux-gnueabi option to reload object files... -r
checking for arm-oe-linux-gnueabi-objdump... arm-oe-linux-gnueabi-objdump
checking how to recognize dependent libraries... pass_all
checking for arm-oe-linux-gnueabi-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for arm-oe-linux-gnueabi-ar... arm-oe-linux-gnueabi-ar
checking for archiver @FILE support... @
checking for arm-oe-linux-gnueabi-strip... arm-oe-linux-gnueabi-strip
checking for arm-oe-linux-gnueabi-ranlib... arm-oe-linux-gnueabi-ranlib
checking for gawk... no
checking for mawk... mawk
checking command to parse arm-oe-linux-gnueabi-nm output from arm-oe-linux-gnueabi-gcc  -march=armv7-a -marm -mfpu=neon  -mfloat-abi=hard -mcpu=cortex-a9 --sysroot=/home/sdk/sysroots/cortexa9hf-neon-oe-linux-gnueabi object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for arm-oe-linux-gnueabi-mt... no
checking for mt... mt
configure: WARNING: using cross tools not prefixed with host triplet
checking if mt is a manifest tool... no
checking how to run the C preprocessor... arm-oe-linux-gnueabi-gcc -E  -march=armv7-a -marm -mfpu=neon  -mfloat-abi=hard -mcpu=cortex-a9 --sysroot=/home/sdk/sysroots/cortexa9hf-neon-oe-linux-gnueabi
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if arm-oe-linux-gnueabi-gcc  -march=armv7-a -marm -mfpu=neon  -mfloat-abi=hard -mcpu=cortex-a9 --sysroot=/home/sdk/sysroots/cortexa9hf-neon-oe-linux-gnueabi supports -fno-rtti -fno-exceptions... no
checking for arm-oe-linux-gnueabi-gcc  -march=armv7-a -marm -mfpu=neon  -mfloat-abi=hard -mcpu=cortex-a9 --sysroot=/home/sdk/sysroots/cortexa9hf-neon-oe-linux-gnueabi option to produce PIC... -fPIC -DPIC
checking if arm-oe-linux-gnueabi-gcc  -march=armv7-a -marm -mfpu=neon  -mfloat-abi=hard -mcpu=cortex-a9 --sysroot=/home/sdk/sysroots/cortexa9hf-neon-oe-linux-gnueabi PIC flag -fPIC -DPIC works... yes
checking if arm-oe-linux-gnueabi-gcc  -march=armv7-a -marm -mfpu=neon  -mfloat-abi=hard -mcpu=cortex-a9 --sysroot=/home/sdk/sysroots/cortexa9hf-neon-oe-linux-gnueabi static flag -static works... no
checking if arm-oe-linux-gnueabi-gcc  -march=armv7-a -marm -mfpu=neon  -mfloat-abi=hard -mcpu=cortex-a9 --sysroot=/home/sdk/sysroots/cortexa9hf-neon-oe-linux-gnueabi supports -c -o file.o... yes
checking if arm-oe-linux-gnueabi-gcc  -march=armv7-a -marm -mfpu=neon  -mfloat-abi=hard -mcpu=cortex-a9 --sysroot=/home/sdk/sysroots/cortexa9hf-neon-oe-linux-gnueabi supports -c -o file.o... (cached) yes
checking whether the arm-oe-linux-gnueabi-gcc  -march=armv7-a -marm -mfpu=neon  -mfloat-abi=hard -mcpu=cortex-a9 --sysroot=/home/sdk/sysroots/cortexa9hf-neon-oe-linux-gnueabi linker (arm-oe-linux-gnueabi-ld  --sysroot=/home/sdk/sysroots/cortexa9hf-neon-oe-linux-gnueabi) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-oe-linux-gnueabi-strip... (cached) arm-oe-linux-gnueabi-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of arm-oe-linux-gnueabi-gcc  -march=armv7-a -marm -mfpu=neon  -mfloat-abi=hard -mcpu=cortex-a9 --sysroot=/home/sdk/sysroots/cortexa9hf-neon-oe-linux-gnueabi... gcc3
checking whether make supports nested variables... (cached) yes
checking for arm-oe-linux-gnueabi-pkg-config... no
checking for pkg-config... /home/sdk/sysroots/x86_64-oesdk-linux/usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking gcrypt.h usability... no
checking gcrypt.h presence... no
checking for gcrypt.h... no
configure: error: Missing required header: gcrypt.h.**

I tried also to set the variable (to use $CC instead of gcc) during configure like this:
**./configure --build=x86_64-pc-linux-gnu --host=arm-oe-linux-gnueabi CC=foo**
but I got:
**Configure: loading site script /home/sdk/site-config-cortexa9hf-neon-oe-linux-gnueabi
./configure: line 2387: -O2: command not found
checking for arm-oe-linux-gnueabi-gcc... foo
checking whether the C compiler works... no
configure: error: in `/home/mohamed/Desktop/TPM2.0/tpm2-tss':
configure: error: C compiler cannot create executables
See `config.log' for more details**

**Comment by tstruk** [comment]
You are missing libgcrypt. Please see https://github.com/tpm2-software/tpm2-tss/blob/master/INSTALL.md
for more info about dependencies.
