### ISSUE TITLE
Visual Studio "community" / 2017 support broken

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#1092]
Recent changes in 06db575c3c0d3deded7e2e1d6322e719101d94df broke support for the "community" version of Visual Studio. This is the only version of VS that can be used w/o paying for a license. This is a barrier to entry that we've been trying to avoid.

**Comment by flihp** [comment]
@davidjmaria: can you give us some background on the motivation for the change to the toolset?

**Comment by davidjmaria** [comment]
@flihp I chose to used Clang/LLVM over Clang/C2 mostly because Microsoft is no longer supporting Clang/C2 ([see reply here](https://developercommunity.visualstudio.com/content/problem/52789/clang-with-microsoft-codegen-vs2017-an-internal-er.html)). 

I was under the impression that Clang/LLVM was able to be installed on the "community" version of Visual Studio, but since this is not the case I'll go ahead and submit a PR to change all the builds to use the Clang/C2 toolset again.

**Comment by flihp** [comment]
I've already got a bunch of stuff staged up as I've been trying to figure this out. Mostly I wanted to be sure that if I flip this back that I'm not breaking anything for you. I've already got this staged up so no need to set up a PR.

**Comment by flihp** [comment]
I'm also looking at other options. Do you have any experience with: https://github.com/arves100/llvm-vs2017-integration ? This seems to be the only way to integrate the 'LLVM-vs2014' target with vs2017 (super helpful name they gave the target too). Been digging through the web for data about this currently and it looks like you're right, the Clang/C2 is still marked as 'experimental' in the windows vs2017 installer and like you said, they're deprecating / abandoning the effort.

**Comment by davidjmaria** [comment]
Sounds good, thanks! I have been testing and switching back to Clang/C2 doesn't break anything for me.

**Comment by davidjmaria** [comment]
Sorry, I had missed your second message. I do not have any experience with that specific Clang LLVM VS integration. I was able to get LLVM-vs2014 to work on vs2017 by just installing "Clang for Windows" from [here](http://releases.llvm.org/download.html). There are a couple dependencies, but the installer should automatically install the VS integration. I loosely followed [this guide](https://gist.github.com/InNoHurryToCode/955d63db0d79699fed63fe18eeebf17e) to get it working.

**Comment by flihp** [comment]
Thanks for the links. I'm going to give that a try just for fun. What's not clear to me is whether Clang/C2 is supported by older versions of VS. I would expect not since they've abandoned the project. I thinking supporting VS2017 should be a requirement since it's the only "free" version, but being able to support older versions would be bonus.

**Comment by flihp** [comment]
Made it through the docs provided here and I'm on-board with switching to the 'LLVM-vs2014' platform toolset. The only benefit to reverting to the Clang/C2 stuff would be that it's integrated into the VS2017 installer GUI and therefore easier for dummies like myself to setup. The Clang 6 installer now does the integration with VS2017 based on the links from @davidjmaria above and that's good enough for me. We do however need to update the documentation to reflect this newtool. Will be opening a new issue for that work.
