### ISSUE TITLE
Request: add TPM revision number somehow

### ISSUE THREAD

**Issue by bzhu5** [tpm2-software/tpm2-tss#1094]
Can you please update the README file (or somewhere else, e.g. in the  project description header) to highlight the highest revision that this TSS currently supports?

Because it would be easier for others to see.

thanks.

**Comment by AndreasFuchsSIT** [comment]
Well, the README.md file contains the http-link to the exact specification document that we implement (the filename contains the revision number as well.)

https://github.com/tpm2-software/tpm2-tss/blob/master/include/tss2/tss2_common.h#L12
```
#define TSS2_API_VERSION_1_2_1_108
```
contains the API version.

Do you require more than that ?

**Comment by AndreasFuchsSIT** [comment]
Closing the issue for the moment.
Please re-open it with the concrete proposal on what to add where.
Thanks !
