### ISSUE TITLE
Update README.md for VS PlatformToolset change

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#1095]
See discussion in #1092. Installation instructions for LLVM-vs2014 PlatformToolset are here: https://gist.github.com/InNoHurryToCode/955d63db0d79699fed63fe18eeebf17e

**Comment by tstruk** [comment]
INSTALL.md contains details about the versions of VS, C Runtime libs, and references to setup manuals. That should suffice.
