### ISSUE TITLE
Compilation without MS-Sim

### ISSUE THREAD

**Issue by Evgeniy-Yuriev** [tpm2-software/tpm2-tss#1101]
Good afternoon, dear TPM-TSS developers.
I cannot build/configure the library without MS-Sim.
I have provided --disable-tcti-mssim option, but it prevents linking with the following error:
src/tss2-esys/.libs/src_tss2_esys_libtss2_esys_la-esys_tcti_default.o:(.data.rel+0x44): undefined reference to `Tss2_Tcti_Mssim_Init'

I've made a look to the code, and I find no preprocessor guards in src/tss2-esys/esys_tcti_default.c, for Tss2_Tcti_Mssim_Init. I suppose (Maybe, I am wrong with that), they should be there, if we want to have binaries with TCTI, but without MSSim. 

Thank you.

--
best regards. EY.

**Comment by tstruk** [comment]
This should fix it for you:
https://github.com/tpm2-software/tpm2-tss/pull/1111
please reopen the issue if it doesn't.
