### ISSUE TITLE
Failed to build tpm2-tss

### ISSUE THREAD

**Issue by citypw** [tpm2-software/tpm2-tss#1110]
Hi,

I got some errors after run "./bootstrap":

--------------------------
configure.ac:44: error: possibly undefined macro: AC_SUBST
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:53: error: possibly undefined macro: AS_IF
configure.ac:58: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:214: error: possibly undefined macro: AC_MSG_WARN
autoreconf: /usr/bin/autoconf failed with exit status: 1
---------------------------

I got the same results on both Debian 9 and Debian 10. Any ideas what went wrong?

**Comment by joshuagl** [comment]
Discussed with @citypw via IRC, they were missing the autoconf-archive package.

Feel free to close.

**Comment by citypw** [comment]
Thanks. It works!

**Comment by fearTheUnknown** [comment]
Just wanna add additional info for those who are having **this issue with CentOS 8 on aarch64**.

The default **"yum" repository of CentOS 8 aarch64** might **not see this "autoconf-archive" package available**. In that case, you can enable the PowerTool repository and install the package with the following command:

> sudo dnf --enablerepo=PowerTools -y install autoconf-archive

Thank you.
