### ISSUE TITLE
logging infrastructure docs

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#1122]
We've had someone documenting their experience debugging use of the TSS2 on the mailing list recently (https://lists.01.org/pipermail/tpm2/2018-August/000826.html) and they were completely unaware of the TSS2_LOG environment variable. They got to the bottom of their issue by using `strace` but simply setting TSS2_LOG to the right value (or maybe building with it properly enabled) would have got them the nice debug message we have setup in the device TCTI: https://github.com/tpm2-software/tpm2-tss/blob/4f437009056d7e4ecf6609ad2cd3e70861063c04/src/tss2-tcti/tcti-device.c#L280

I looked briefly but was unable to find any documentation for this logging stuff. Is this hidden somewhere or do we not have any yet? If not, a page on the wiki seems like a good first step.

**Comment by tstruk** [comment]
@flihp Is this what you were looknig for?
https://github.com/tpm2-software/tpm2-tss/blob/master/doc/logging.md

**Comment by AndreasFuchsSIT** [comment]
@flihp is this sufficient or do you which for more ?

**Comment by tstruk** [comment]
The only thing I would add is to list the modules we have.
Other than that it looks OK to me.

**Comment by flihp** [comment]
The content isn't installed. It's not mentioned in the manpages either AFAIK. Might be something we can solve with just a URL but I'd think adding a line or two about the environment variable to the manual pages shouldn't be too bad.
