### ISSUE TITLE
Help writing C programs to learn about TPM

### ISSUE THREAD

**Issue by ChaosEater999** [tpm2-software/tpm2-tss#1128]
I have only recently started learning about TPM. Tried installing tpm2-tss, tpm2-abrmd, and tpm2-tools on my linux system and I can test the functionalities using the IBM TPM simulator (since I don't have a hw tpm). 
Now i want to start writing basic C codes to use the same functionalities using the TPM simulator, but am having a hard time starting. I have checked the test scripts, but am unable to understand most of it due to my limited proficiency in C.
Can someone provide any basic example C programs like just connecting to the TPM simulator running on the same machine and getting random numbers back from it? Or something similar to start with so that I can understand how the things are working from a beginner level, since searching for the same on the internet didn't help.

**Comment by AndreasFuchsSIT** [comment]
Have a look here https://github.com/tpm2-software/tpm2-tss/blob/master/test/integration/esys-get-random.int.c and here https://github.com/tpm2-software/tpm2-tss/blob/master/test/integration/main-esapi.c

And for user questions please consider the mailing-list https://lists.01.org/mailman/listinfo/tpm2
This place is for bugs.
