### ISSUE TITLE
regarding a storing a data in nv memory of tpm , without using authorisation or key storing techniques. 

### ISSUE THREAD

**Issue by manojsai17** [tpm2-software/tpm2-tss#1130]
Hello,

actually main problem is we interfaced slb 9670(tpm-2.0) with 16 bit msp430 controller which does not support linux kernel or any OS.

now our task is to store a 100 byes of data in NV memory, without any authorisation technique, as simple as possible.

please guide me in that way.

slb 9670 is interfaced with msp430 controller through SPI protocol.

I able to read device id , version id of slb9670 , so spi communication is working fine with our controller .

what is packet format to be send with our data , i am not able to understand the TCG documents .

theoretically iam able to understand we have to do nvdefinespace , nvwrite ,nvread .. internaly what is the format i have to be send not able to understand

can you please guide me , or share any code snippet .

sorry if i trouble you or any irrelevant questions.

Regards,
Manoj,
mail : abbarajumanojsai@gmail.com
+91-9063249308

**Comment by AndreasFuchsSIT** [comment]
Have a look here https://github.com/tpm2-software/tpm2-tss/blob/master/test/integration/esys-nv-ram-ordinary-index.int.c and here https://github.com/tpm2-software/tpm2-tss/blob/master/test/integration/main-esapi.c

And for user questions please consider the mailing-list https://lists.01.org/mailman/listinfo/tpm2
This place is for bugs.
