### ISSUE TITLE
regarding a storing a data in nv memory of tpm , without using authorisation or key storing techniques

### ISSUE THREAD

**Issue by manojsai17** [tpm2-software/tpm2-tss#1136]
Hello ,

actually main problem is we interfaced slb 9670(tpm-2.0) with 16 bit msp430 controller which does not support linux kernel or any OS.

now our task is to store a 100 byes of data in NV memory, without any authorisation technique, as simple as possible.

please guide me in that way.

slb 9670 is interfaced with msp430 controller through SPI protocol.

I able to read device id , version id of slb9670 , so spi communication is working fine with our controller .

what is packet format to be send with our data , i am not able to understand the TCG documents .

theoretically iam able to understand we have to do nvdefinespace , nvwrite ,nvread .. internaly what is the format i have to be send not able to understand

can you please guide me , or share any code snippet .

sorry if i trouble you or any irrelevant questions.

Regards,
Manoj,
mail : abbarajumanojsai@gmail.com
+91-9063249308

**Comment by AndreasFuchsSIT** [comment]
The code snippets you are looking for are there: https://github.com/torvalds/linux/blob/master/drivers/char/tpm/tpm_tis_spi.c (this is under GPL license !)

You probably want to write a TCTI module supporting SPI on your uC. Then you can use the code in this project here.

Until you have the SPI protocol running, you probably don't need anything from this project.

**Comment by manojsai17** [comment]
Hi Adreas ,

iam able to read and write slb9670 (Tpm 2.0) registers , like reading
device id , Fifo ..so spi communication is fine with my controller by
accessing slb9670.

**Comment by AndreasFuchsSIT** [comment]
Well then send e.g. a TPM2_GetRandom `{0x80, 1, 0, 0, 0,12, 0, 0, 0x01, 0x7B, 0x00, 0x0a}` command via the SPI fifo and don't forget the state machine for command ready, etc...

This is still TPM driver stuff... All inside the kernel code...

Once this is working, implement a TCTI wrapper around this driver code (see https://trustedcomputinggroup.org/wp-content/uploads/TSS_TCTI_Version-1.0_Revision-05_Review_END030918.pdf) and when this works, use this TCTI in a SAPI or ESAPI application.

P.S. If you develop the TCTI wrapper in public then people might be able to help you.

**Comment by manojsai17** [comment]
Hi Andreas , thanks for response ,

Yeah i done by this task by acessing fifo registers by send some data and
received the response also.

right now i strucked in accessing the nv memory , how to do i.e storing
some plain data in nv memory with out using any authorisation and key
techniques .

**Comment by manojsai17** [comment]
regarding nv  , iam able to understand that we have to do 3 steps , nv
define space,nvwrite, nvread.

**Comment by AndreasFuchsSIT** [comment]
see here https://github.com/tpm2-software/tpm2-tss/blob/master/test/integration/esys-nv-ram-ordinary-index.int.c

If you want to skip auth, then just set the size to 0...

good luck

**Comment by manojsai17** [comment]
Hi andreas, TPM2B_AUTH auth = {.size = 0,
.buffer={10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
20, 21, 22, 23, 24, 25, 26, 27, 28, 29}};
should i set like this

**Comment by manojsai17** [comment]
#ifdef TEST_SESSION
    ESYS_TR session = ESYS_TR_NONE;
    TPMT_SYM_DEF symmetric = {.algorithm = TPM2_ALG_AES,
                              .keyBits = {.aes = 128},
                              .mode = {.aes = TPM2_ALG_CFB}
.........


should i define TEST_SESSION or not ?
