### ISSUE TITLE
"TPM2_PolicyAuthorize" tackle the PCR brittleness.

### ISSUE THREAD

**Issue by Nilesh-Deshmukh** [tpm2-software/tpm2-tss#1149]
Hi ,

I have just started learning the TPM2 world, and really amazed by "TPM2_PolicyAuthorize" tackle the PCR brittleness.
I have understood the other discussion but not sure how to user TRAIL session for "TPM2_PolicyAuthorize"
Please share the sample if anyone has..

**Comment by AndreasFuchsSIT** [comment]
@Nilesh-Deshmukh This is not really a tss issue, so I'll close it and would refer you to the mailinglist.

Nevertheless, there is an example in our integration test suit. See https://github.com/tpm2-software/tpm2-tss/blob/master/test/integration/esys-policy-authorize.int.c#L166
Hope this helps.
