### ISSUE TITLE
How TPM use PCR0-1 to ensure BIOS not corrupted

### ISSUE THREAD

**Issue by GaohangPuppy** [tpm2-software/tpm2-tss#1156]
When a system boot up, CRTM will measure BIOS and extend to PCR0. And if any solder away the EEPROM from motherboard replace a malicious one. How CRTM detect BIOS corrupted, as system shutdown, PCR0 will be reset to 0, and will extend a malicious BIOS hash to PCR0.

**Comment by AndreasFuchsSIT** [comment]
I'm sorry, but this seems to be a question for the Trusted Computing Group or a HW vendor.
It certainly is not related to the TPM Software Stack.
