### ISSUE TITLE
Application link fails: Cannot find -lgcrypt

### ISSUE THREAD

**Issue by dwmw2** [tpm2-software/tpm2-tss#1169]
See https://bugzilla.redhat.com/show_bug.cgi?id=1638961

I added `BuildRequires: pkgconfig(tss2-esys)` to my package and attempted to build it, but it failed with the error above.

I'm not sure why `-lgcrypt` is in the `Libs` section of your `tss2-esys.pc` file. That puts it on *my* application link command, but that shouldn't be necessary just because *your* library happens to be built against it. That's none of my business.

The only time it needs to be on my link command is if I'm using static linking, and so it does want to be in your `Libs.private` but not `Libs`.

If there is some reason you really want applications to link to it directly and you really do want it in `Libs`, then the packages need to require the distro's corresponding `libgcrypt-devel` package.

**Comment by AndreasFuchsSIT** [comment]
@flihp You introduce this with the comment 
```
Still bugging me that gcrypt doesn't ship a pkgconfig file. No interest
in supplying one either, not a good look: https://dev.gnupg.org/T2037.
Some distros provide one but I don't know that we can rely on this. So
for now the ESAPI pkgconfig file doesn't identify the dependency on
libgcrypt. We do include the -lgcrypt flag though.
```

Do you see any issue in moving -lgcrypt from Libs to Libs.private ?

**Comment by flihp** [comment]
While I appreciate you asking, I'll point out that I'm not in MAINTAINERS any longer. So long as you and @tstruk agree you should keep moving forward. If you all need a second opinion this is relevant to packaging so I'd ask @martinezjavier
