### ISSUE TITLE
Wrong man3 directory in library installation

### ISSUE THREAD

**Issue by mrcdb** [tpm2-software/tpm2-tss#1179]
Hello,

I am building the tpm2-tss tool (master branch on commit `c42f7aaaa18fde2cb2cdbbf95b94960af06ada18`) as described in the installation procedure on a CentOS 7.5.1804 host with Kernel 4.19.0 and I get the following error when I issue `sudo make install`:

```
 /usr/bin/mkdir -p '/usr/local/share/man/man3'
 /usr/bin/install -c -m 644 man/man3/Tss2_Tcti_Device_Init.3 man/man3/Tss2_Tcti_Mssim_Init.3 ./doc/man/ESYS_CONTEXT.3 ./doc/man/ESYS_TR.3 ./doc/man/ESYS_TR_defines.3 ./doc/man/Esys_ActivateCredential.3 ./doc/man/Esys_Certify.3 ./doc/man/Esys_CertifyCreation.3 ./doc/man/Esys_ChangeEPS.3 ./doc/man/Esys_ChangePPS.3 ./doc/man/Esys_Clear.3 ./doc/man/Esys_ClearControl.3 ./doc/man/Esys_ClockRateAdjust.3 ./doc/man/Esys_ClockSet.3 ./doc/man/Esys_Commit.3 ./doc/man/Esys_ContextLoad.3 ./doc/man/Esys_ContextSave.3 ./doc/man/Esys_Create.3 ./doc/man/Esys_CreatePrimary.3 ./doc/man/Esys_DictionaryAttackLockReset.3 ./doc/man/Esys_DictionaryAttackParameters.3 ./doc/man/Esys_Duplicate.3 ./doc/man/Esys_ECC_Parameters.3 ./doc/man/Esys_ECDH_KeyGen.3 ./doc/man/Esys_ECDH_ZGen.3 ./doc/man/Esys_EC_Ephemeral.3 ./doc/man/Esys_EncryptDecrypt.3 ./doc/man/Esys_EventSequenceComplete.3 ./doc/man/Esys_EvictControl.3 ./doc/man/Esys_FlushContext.3 ./doc/man/Esys_GetCapability.3 ./doc/man/Esys_GetCommandAuditDigest.3 ./doc/man/Esys_GetRandom.3 ./doc/man/Esys_GetSessionAuditDigest.3 ./doc/man/Esys_GetTestResult.3 ./doc/man/Esys_GetTime.3 ./doc/man/Esys_Hash.3 ./doc/man/Esys_HashSequenceStart.3 ./doc/man/Esys_HierarchyChangeAuth.3 ./doc/man/Esys_HierarchyControl.3 '/usr/local/share/man/man3'
/usr/bin/install: cannot stat ‘./doc/man/Esys_HashSequenceStart.3’: No such file or directory
/usr/bin/install: cannot stat ‘./doc/man/Esys_HierarchyChangeAuth.3’: No such file or directory
/usr/bin/install: cannot stat ‘./doc/man/Esys_HierarchyControl.3’: No such file or directory
[... many others like these...]
make[1]: *** [install-man3] Error 1
make[1]: Leaving directory `/home/user/repos/tpm2-tss'
make: *** [install-am] Error 2
```
It looks like that all the doc files are under `./doc/man/man3`, and not `./doc/man`. I have tried to copy all the files under `/doc/man/man3` in the `/doc/man` dir and the installation completes successfully.

**Comment by tstruk** [comment]
There are some man3 files are in man/man3, (that's the TCTI man pages) and some that supposed to be auto-generated by doxygen into doc/man/ as instructed in https://github.com/tpm2-software/tpm2-tss/blob/master/Makefile.am#L53
I think the issue is that we don't check if doxygen it is installed in the system in out configure script.
If you run ./configure with --disable-doxygen-doc then it should get rid of the problem for you.
You can also try to install doxygen tool. I'll add a check for it into configure.

**Comment by mrcdb** [comment]
Confirm that running the install command with `doxygen` package installed solves the issue. Thanks!
