### ISSUE TITLE
Udev configuration on Ubuntu 18.04 host not applied

### ISSUE THREAD

**Issue by mrcdb** [tpm2-software/tpm2-tss#1188]
I have run the installer for `tpm2-tss` on a Ubuntu 18.04.1 LTS host and by default the `udev` configuration is installed in `/usr/local/lib/udev/rules.d/tpm-udev.rules`. Nonetheless, the configuration is never applied (not after `udevadm control --reload` nor after a reboot).  I have updated the `udevadm` logging verbosity and I see that the `/usr/local/lib/udev/rules.d/*` is not even queried by default, as the daemon only checks for `/lib/udev/rules.d/` content.
Copying the `tpm-udev.rules` to the second directory and reloading the rules works just fine. Maybe `udev` changed its default config in Ubuntu 18.04?

**Comment by diabonas** [comment]
The udev rules directory is distribution-specific, so if you are building from source, you need it to set it to the appropriate value yourself using the [`--with-udevrulesdir`](https://github.com/tpm2-software/tpm2-tss/blob/master/INSTALL.md#--with-udevrulesdir) configure option. If this happens with the official Ubuntu package, that's a packaging issue that should be reported in your distribution's bug tracker.

**Comment by mrcdb** [comment]
The issue happended when I was building from source only. Thanks for the clarification!
