### ISSUE TITLE
AppVeyor image update breaks build

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#1197]
809279c3d25336e70d7383d18a59a19d4ab158d8 held us back to the previous image after the update at the end of September. This solution was only good for one release cycle due to the way `previous` works. Their release cycle was pretty quick (< 2 months) and now we need a real update.

**Comment by tstruk** [comment]
Fixed by https://github.com/tpm2-software/tpm2-tss/pull/1206
