### ISSUE TITLE
--disable-doxygen-doc still requires doxygen

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#1204]
We now check for the existence of doxygen when we try to build the documentation and fail if it's not available (a very good thing). Unfortunately this check still happens even if the caller supplies the `--disable-doxygen-doc` option to the configure script. I would expect that if the caller explicitly disables the doxygen docs (possibly because they can't install it) that we shouldn't fail the configure script if doxygen isn't installed.

**Comment by tstruk** [comment]
https://github.com/tpm2-software/tpm2-tss/blob/master/configure.ac#L292
How come?
