### ISSUE TITLE
switch to config.h

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tss#1232]
Use a config header vs command line arguments so we don't overflow the command line length.

**Comment by AndreasFuchsSIT** [comment]
I like this !
autoheaders, right ?

**Comment by williamcroberts** [comment]
> -----Original Message-----
> From: Andreas Fuchs [mailto:notifications@github.com]
> Sent: Monday, December 24, 2018 4:12 PM
> To: tpm2-software/tpm2-tss <tpm2-tss@noreply.github.com>
> Cc: Roberts, William C <william.c.roberts@intel.com>; Author
> <author@noreply.github.com>
> Subject: Re: [tpm2-software/tpm2-tss] switch to config.h (#1232)
> 
> I like this !
> autoheaders, right ?
yes
