### ISSUE TITLE
Display some warning as "variable 'ESYSCRY_LDFLAGS' is defined but no program" when bootstrap

### ISSUE THREAD

**Issue by ch155260** [tpm2-software/tpm2-tss#1233]
Build tpm2-tss burch 2.1.x will get below warning.
```
[root@localhost tpm2-tss]# ./bootstrap
Generating file lists: src_vars.mk
libtoolize: putting auxiliary files in `.'.
libtoolize: linking file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: linking file `m4/libtool.m4'
libtoolize: linking file `m4/ltoptions.m4'
libtoolize: linking file `m4/ltsugar.m4'
libtoolize: linking file `m4/ltversion.m4'
libtoolize: linking file `m4/lt~obsolete.m4'
configure.ac:36: installing './config.guess'
configure.ac:36: installing './config.sub'
configure.ac:37: installing './install-sh'
configure.ac:37: installing './missing'
Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
Makefile-test.am:70: warning: variable 'ESYSCRY_LDFLAGS' is defined but no program or
Makefile-test.am:70: library has 'ESYSCRY' as canonical name (possible typo)
Makefile.am:176:   'Makefile-test.am' included from here
```

Before build tpm2-tss have install below package.
```
yum install -y autoconf-archive libcmocka libcmocka-devel net-tools m4 libtool automake libgcrypt-devel openssl-devel uthash-devel  autoconf gnulib lcov
```

OS:CentOS7.6

Please help me fix the problem, thanks.

**Comment by AndreasFuchsSIT** [comment]
Yep, this was fixed in https://github.com/tpm2-software/tpm2-tss/commit/b9f2e4c53e1e667dd03606509c0eb9a5c2af6182#diff-e0c15ec40866d72889825a0191fb5945

I guess we should backport this then...

@tstruk Can you do this ? I'm not up to date on the stable branches status...

**Comment by tstruk** [comment]
This should be on 2.1.x branch now.

**Comment by tstruk** [comment]
We probably need a 2.1.1 to call it closed. I will start tagging for 2.2.0 and 2.1.1 this or early next week.

**Comment by tstruk** [comment]
@ch155260 this is a new 2.1.1 package with the fix:
https://github.com/tpm2-software/tpm2-tss/archive/2.1.1_rc1.tar.gz
could you please verify and les us know if this can be closed.

**Comment by tstruk** [comment]
No update, assume it's fixed
