### ISSUE TITLE
ESAPI: Potentially leaking Sessions

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tss#1251]
After 
https://github.com/tpm2-software/tpm2-tss/blob/master/src/tss2-esys/api/Esys_StartAuthSession.c#L410
all errors result in a leak of a session handle, cluttering the TPM.

We need to flush the session in the error handler. And I'd argue that we can do so synchronously.
Also this should be in 2.2...

@tstruk agreed ?

**Comment by tstruk** [comment]
Fixed with #1253
