### ISSUE TITLE
Why is doxygen required?

### ISSUE THREAD

**Issue by msa2** [tpm2-software/tpm2-tss#1268]
If I wanted just to build libraries to use, why does it want doxygen? First it thinks it is ok, but then it suddendly refuses to proceed!!

```
checking for doxygen... no
configure: WARNING: doxygen not found - will not generate any doxygen documentation
checking for perl... /usr/bin/perl
checking for doxygen... no
configure: error: Missing required program 'doxygen': ensure it is installed and on PATH.
```

**Comment by msa2** [comment]
Hmm.. maybe I followed wrong instructions.... oh well...

**Comment by tstruk** [comment]
The default configuration requires doxygen as it produces html docs. If you don't wan't this you can run configure and pass --disable-doxygen-doc flag to it. See ./configure --help
