### ISSUE TITLE
Client Certificate

### ISSUE THREAD

**Issue by roberto497** [tpm2-software/tpm2-tss#1290]
I need to create a .csr file where the private key should only be in the TPM, I will send this .csr to my server, generate the .pem using the server CA and release this certificate in IIS, then I will return the .crt to the machine , and I will need to make requests to the server, have some tutorial on how to do this step by step?

**Comment by AndreasFuchsSIT** [comment]
I'd recommend just using https://github.com/tpm2-software/tpm2-tss-engine and following the standard openssl methods...
The readme over there also contains some info on creating a self-signed cert.
