### ISSUE TITLE
Ubuntu OS - Are there any instructions to enable fTPM on Intel NUC8i5BEH

### ISSUE THREAD

**Issue by mohandatla** [tpm2-software/tpm2-tss#1292]
I am trying to use fTPM present in Intel NUC, but i did not find standard wiki/support instructions to enable the TPM. Opening an issue in case if any knows already. Thank you for your help.

**Comment by yunyings** [comment]
There's no specific TPM configuration in NUC Visual BIOS(at least from what I can see on my NUC7i5DNH). Make sure VT/VT-d/PTT is enabled in BIOS Security tab, this should be enough to use fTPM. 

Once system boot up, check if tpm device is available:
`# ls -l /dev/tpm*`
If tpm device is available, it should be working fine.

If not, check dmesg for any tpm related errors:
`# dmesg | grep -i tpm`

**Comment by mohandatla** [comment]
Thank you yunyings. Yesterday I found that /dev/tpm* is not present and found an error in dmesg that TPM init failed. Today after I looked/verified BIOS, restarted the machine the tpm driver module tpm_crb loaded successfully and I could see /dev/tpm0 present. I have no idea what triggered reboot fixed the issue.

**Comment by mohandatla** [comment]
Just for information, here the things i have done,
- Installed Ubuntu 16.4 desktop on Intel NUC kit NUC8i5BEH by following steps here https://www.ubuntu.com/download/iot/intel-nuc-desktop
Note that during installation, I found below error using USB boot
"ACPI Exception: AE_BAD_PARAMETER, Could not install PciConfig handler for Root Bridge PCI0" Not sure what it is though but continued the recovery step, it installed the Linux OS successfully.

- Make sure the VT/VT-d/PTT is enabled.
- Verified using the below steps yun mentioned,
check if tpm device is available:
# ls -l /dev/tpm*
If tpm device is available, it should be working fine.
If not, check dmesg for any tpm related errors:
# dmesg | grep -i tpm
