### ISSUE TITLE
On Windows, the esys-crypto project can't compile due to lack of openssl dependency

### ISSUE THREAD

**Issue by shensongwu** [tpm2-software/tpm2-tss#1307]
On Windows, the esys-crypto project can't compile due to lack of openssl lib and header file.
Could you help to update this part in the document and code? Which version of openssl could be used?

**Comment by AndreasFuchsSIT** [comment]
On Linux we run against 1.0.2 and 1.1.0 without problem.

**Comment by davidjmaria** [comment]
@shensongwu 
Win64 OpenSSL v1.0.2 works without any issues for me, this is what the appveyor build uses as well. 

If you're building it yourself make sure to put all of the files in the correct directories. 
- The lib files should be in C:\OpenSSL-Win64\lib
- The include directory should be at C:\OpenSSL-Win64\include\openssl
- The dlls/exe should be in C:\OpenSSL-Win64\bin
