### ISSUE TITLE
Bug in async and regression with kernel 5.0

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tss#1315]
See discussion at https://github.com/tpm2-software/tpm2-tools/issues/1356

**Comment by AndreasFuchsSIT** [comment]
For this project, I think that the O_NONBLOCK flag should be guarded by the TCTI_ASYNC ifdefs

@tstruk am I correct ?

**Comment by AndreasFuchsSIT** [comment]
Once we're fixing this, we should also reeval the partial reads.
That spawned a different error message according to https://github.com/tpm2-software/tpm2-tools/issues/1356#issuecomment-471322206

**Comment by tstruk** [comment]
There is no need to wrap the O_NONBLOCK with TCTI_ASYNC ifdefs because the driver in kernels 4.19 and earlier ignore it anyway.
