### ISSUE TITLE
ESYS: Bug in Session-Attribute setting & response decryption

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tss#1316]
There was a bug introduce in 18600770725a892faa8d7044867466337708fffd that disable the response-encrypt flag for TPM, I think.
In any case, currently the function for response decryption in ESYS is never triggered.

Noticed, because 2454df67a34b0729a2379d0df8c6fad617af3343 introduce a bug that breaks decryption, but was not detected because of the former bug.

**Comment by AndreasFuchsSIT** [comment]
PR #1318 is still using Tss2_Sys_GetEncryptParam() out of sequence. The NO_ENCRYPT_PARAM error merely has precedence over BAD_SEQUENCE. The PR fixes the functionality for now, but we need a proper rework before release.

**Comment by tstruk** [comment]
This one should be closed together with https://github.com/tpm2-software/tpm2-tss/issues/1332

**Comment by AndreasFuchsSIT** [comment]
Actually, #1318 uses a non-spec compliant behavior of Tss2_Sys_GetEncryptParam() that we need to (properly) fix before the next release.
I.e. we will have to create a table of encryt/decrypt possible inside esapi (basically a copy of the same functionality in sapi) because SAPI cannot communicate `encrypt-flag-possible` to esapi via the standardized api.

**Comment by tstruk** [comment]
Fixed with https://github.com/tpm2-software/tpm2-tss/pull/1338
