### ISSUE TITLE
SYS: EncryptDecrypt falsely allows command parameter encryption

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tss#1331]
This should be 0, since the first parameter is a TPMI_YES_NO, not a TPM2B.
https://github.com/tpm2-software/tpm2-tss/blob/2a3c59c2b5b0fdf5578ba4c083f698cefeb3bc7e/src/tss2-sys/api/Tss2_Sys_EncryptDecrypt.c#L77

**Comment by tstruk** [comment]
Good catch
