### ISSUE TITLE
TPM2B_PUBLIC.size incorrectly set to 0

### ISSUE THREAD

**Issue by jeffpferreira** [tpm2-software/tpm2-tss#1337]
In several integration tests the size of a `TPM2B_PUBLIC` is set to zero before calling `Esys_CreatePrimary()`. See for example [esys-create-session-auth.int.c](https://github.com/tpm2-software/tpm2-tss/blob/5d632d292edc723e61beea1d8e3ea0ede0ee7fcd/test/integration/esys-create-session-auth.int.c#L115). The spec, Level 00 Revision 01.16, says the following about sized buffers, the `size` field of structs, and `TPM2B_PUBLIC` in particular:

Part 2, 4.13:

In some structures, a size field is present to indicate the number of octets in some subsequent part of the structure. ... This semantic applies when the size field determines the number of octets to unmarshal. However, in some cases, the subsequent structure is self-defining. If the size precedes a parameter that is not an octet array, then the unmarshaled size of that parameter is determined by its data type. ... When the “=” decoration is present, a value of zero is not allowed for the size.

Part 2, 10.4.1

When the type of the second parameter in the TPM2B_ structure is not BYTE, the value of the size field shall either be zero indicating that no structure is to be unmarshaled; or it shall be identical to the number of octets unmarshaled for the second parameter.

NOTE 1: If the TPM2B_ defines a structure and not an array of octets, then the structure is self-describing and the TPM will be able to determine how many octets are in the structure when it is unmarshaled. If that number of octets is not equal to the size parameter, then it is an error.

Part 2, 12.2.5, Table 185:

size= : size of the publicArea. NOTE The “=” will force the TPM to try to unmarshal a TPMT_PUBLIC and check that the unmarshaled size matches the value of size. If all the required fields of a TPMT_PUBLIC are not present, the TPM will return an error (generally TPM_RC_SIZE) when attempting to unmarshal the TPMT_PUBLIC.

Taken together these paragraphs from the spec indicate that the `size` field in `TPM2B_PUBLIC` can either be
1) zero, in which case the `TPMT_PUBLIC` field is not unmarshaled by the TPM. OR
2) non-zero, in which case the TPM checks the unmarshaled size equals the `size` field. If the check fails an error is returned.

But in practice when I run my own test program which calls `Esys_CreatePrimary()` with `TPM2B_PUBLIC.size==0` I get no errors from both a simulated TPM (ibmswtpm1332) and a hardware TPM (SLB9670). When I trace my program into [tss2-mu](https://github.com/tpm2-software/tpm2-tss/tree/master/src/tss2-mu) I can clearly see that `TPM2_PUBLIC.size` is marshaled into `cmdBuffer` (as the value 0) and the marshal code proceeds to marshal `TPM2B_PUBLIC.publicArea` as well. This behavior makes sense from the spec (`size` is only used to check the unmarshaled data on the TPM) but I would expect the TPM to return an error with `size==0`. Clearly I am misunderstanding the spec or the TPM marshal/unmarshal code is not following the spec.

Further confusing the matter, a similarly defined structure `TPM2B_SENSITIVE_CREATE` in Part 2, 11.1.12, is defined with the same 'size=' decoration. In that case the spec explicitly says size "may not be zero" and that "The userAuth and data parameters in this buffer may both be zero length but the minimum size of this parameter will be the sum of the size fields of the two parameters of the TPMS_SENSITIVE_CREATE." Which is to say the `size` field should be at least 4. This guidance is violated in [esys-create-password-auth.int.c](https://github.com/tpm2-software/tpm2-tss/blob/5d632d292edc723e61beea1d8e3ea0ede0ee7fcd/test/integration/esys-create-password-auth.int.c#L186) where size==1.

**Comment by tstruk** [comment]
Your understanding of the spec is correct. The size needs to be set to the correct value for the TPM to be able to unmarshall it. The problem is that it would be quite hard for the application to set it correctly beforehand, especially for some more complex TPM2B structures. This is set by the MU code *after* the whole structure is marshalled. See https://github.com/tpm2-software/tpm2-tss/blob/5d632d292edc723e61beea1d8e3ea0ede0ee7fcd/src/tss2-mu/tpm2b-types.c#L206

**Comment by jeffpferreira** [comment]
Thanks for clarifying.

**Comment by AndreasFuchsSIT** [comment]
More information can be found in https://trustedcomputinggroup.org/wp-content/uploads/TSS_SAPI_Version-1.1_Revision-22_review_030918.pdf Section 3.8.3.4 on page 34.
The size field is ignored and auto-set. If you want to signal the omission of an optional parameter, you can pass NULL.
The rational was already given by tstruk above.

**Comment by tstruk** [comment]
And for the full picture, it is also described here:
https://trustedcomputinggroup.org/wp-content/uploads/TSS_Marshaling_v1.0_r03_Public-Review.pdf in section 3.3.2

**Comment by jeffpferreira** [comment]
Thanks for the specification references. They make it clear that the size field for complex TPM2B structures will be ignored with the actual size computed by the marshal implementation.

To limit confusion does it then make sense to open a new issue to address the inconsistent use of the size field in complex TPM2B structures in the integration tests? Some tests set size==0 and some tests set size!=0. The same issue could also be opened with tpm2-tools.

**Comment by tstruk** [comment]
This should probably be consistent, but instead of creating a new issue could you create a patch to clean it up please. Thanks

**Comment by jeffpferreira** [comment]
OK, I'd be happy to.
