### ISSUE TITLE
"make dist" shall not include Makefile-fuzz-generated.am

### ISSUE THREAD

**Issue by dilyanpalauzov** [tpm2-software/tpm2-tss#1346]

**Comment by tstruk** [comment]
For make dist, GEN_FUZZ should not be set thus Makefile-fuzz-generated.am should not be generated.

**Comment by dilyanpalauzov** [comment]
The aim shall be to have “make dist” working correctly under all circumstances.

**Comment by tstruk** [comment]
If GEN_FUZZ is undefined the Makefile-fuzz-generated.am is an empty file so no issue there.
