### ISSUE TITLE
GEN_FUZZ=1 ./bootstrap && make distclean keeps sometimes $(top_builddir)/test/fuzz/Tss2_Sys_Vendor_TCG_Test_Complete.fuzz.cpp

### ISSUE THREAD

**Issue by dilyanpalauzov** [tpm2-software/tpm2-tss#1349]
GEN_FUZZ=1 ./bootstrap creates $(top_builddir)/test/fuzz/Tss2_Sys_Vendor_TCG_Test_Complete.fuzz.cpp.  “make distclean” deletes this file, if the build is not VPATH, hence $(top_builddir) == $(top_srcdir), and ./configure was called with “--with-fuzzing=libfuzzer --enable-tcti-fuzzing --disable-tcti-device --disable-tcti-mssim”.

Unless there is a reason why the files are deleted only when ./configure was called this way, “make distclean” (DISTCLEANFILES in Makefile-fuzz-generated.am) shall be independent of any Automake conditionals and work in $(top_builddir).

**Comment by tstruk** [comment]
Tss2_Sys_Vendor_TCG_Test_Complete.fuzz.cpp is appended to DISTCLEANFILES in Makefile-fuzz-generated.am the same way as every other *.fuzz.cpp file so I don't see any reason why it shouldn't be cleaned, and testing this quickly I don't see any leftovers after make distclean. Please reopen if you still see this issue.
