### ISSUE TITLE
bootstrap warnings

### ISSUE THREAD

**Issue by tstruk** [tpm2-software/tpm2-tss#1356]
$ ./bootstrap
Makefile-fuzz.am:35: warning: variable 'FUZZ_LDADD' is defined but no program or
Makefile-fuzz.am:35: library has 'FUZZ' as canonical name (possible typo)
Makefile.am:161:   'Makefile-fuzz.am' included from here

**Comment by 2raziel3** [comment]
I am getting the same warning, any update ?

**Comment by AndreasFuchsSIT** [comment]
That's non-critical. We just have to rename the variable to FUZZLDADD or something similar.
We are falsely matching Autotools naming convention of _LDADD suffixes.
Good first issue...

**Comment by 2raziel3** [comment]
@AndreasFuchsSIT thanks for the info
