### ISSUE TITLE
Uninitialized variable is referenced in Esys_Quote

### ISSUE THREAD

**Issue by MinghuaWang** [tpm2-software/tpm2-tss#1362]
```
TSS2_RC
Esys_Quote_Async(
    ESYS_CONTEXT *esysContext,
    ESYS_TR signHandle,
    ESYS_TR shandle1,
    ESYS_TR shandle2,
    ESYS_TR shandle3,
    const TPM2B_DATA *qualifyingData,
    const TPMT_SIG_SCHEME *inScheme,
    const TPML_PCR_SELECTION *PCRselect)
{
    TSS2_RC r;
    LOG_TRACE("context=%p, signHandle=%"PRIx32 ", qualifyingData=%p,"
              "inScheme=%p, PCRselect=%p",
              esysContext, signHandle, qualifyingData, inScheme, PCRselect);
    TSS2L_SYS_AUTH_COMMAND auths;
    RSRC_NODE_T *signHandleNode ;         // (1)
    ......

     /* Retrieve the metadata objects for provided handles */
    r = esys_GetResourceObject(esysContext, signHandle, &signHandleNode);     // (2) 
    return_state_if_error(r, _ESYS_STATE_INIT, "signHandle unknown.");

    r = Tss2_Sys_Quote_Prepare(esysContext->sys,
                               (signHandleNode == NULL) ? TPM2_RH_NULL
                                : signHandleNode->rsrc.handle, qualifyingData,    // (3)
                               inScheme, PCRselect);
    return_state_if_error(r, _ESYS_STATE_INIT, "SAPI Prepare returned error.");

    /* Calculate the cpHash Values */
    r = init_session_tab(esysContext, shandle1, shandle2, shandle3);
    return_state_if_error(r, _ESYS_STATE_INIT, "Initialize session resources");
    iesys_compute_session_value(esysContext->session_tab[0],
                &signHandleNode->rsrc.name, &signHandleNode->auth);  // (4)
    ......
}
```

In this function, the variable 'signHandleNode' is not initialized at (1) and since it a stack variable, it may have an arbitrary value that as same as some variable used by the previous function at this stack location. 

At (2), esys_GetResourceObject is possible to return error without 'signHandleNode' being assigned. The further reference to 'signHandleNode' occurred at (3) and (4) could lead to arbitrary memory read violation.

More specifically, there is a memcpy operation in iesys_compute_sesion_value and the source memory to be copied from is signHandleNode->auth. So if signHandleNode is an arbitrary address, the memory content copied will make no sense for the destination. Besides, if signHandleNode->auth is an arbitrary value or maliciously controlled, the size of bytes to be copied is also arbitrary or controlled, and this will lead to memory overwritten and thus further causing heap corruption or code execution if some code pointer got overwritten.  

The fix could be to initializing 'signHandleNode' at (1), i.e., "RSRC_NODE_T *signHandleNode  = NULL;". 

By the way, many other Esys_XXX_Async functions have the same problem.

**Comment by AndreasFuchsSIT** [comment]
Hmmm... (2)+1 will return if an error is returned, so that (3) is never visited.
And as you said, (2) will only not assign signHandleNode if an error is returned.
Or will (2) ever not assign without an error ?

Are you sure that this is not a false-positive of your code analysis tool ?

**Comment by MinghuaWang** [comment]
I reviewed the code and found that was a false positive. 

But there is another problem here. (2) will return success if signHandle is ESYS_TR_NONE, and in this case 'signHandleNode' will be NULL. So at(4) there would be a NULL deref. 

This bug exists in many Esys_xxx_Async functions, which I reported via email several weeks ago.

**Comment by AndreasFuchsSIT** [comment]
ESYS_TR_NONE is a non-allowed value (which also does not make sense for signHandle). And since it comes for the application facing API this is sooooo far away from a security bug, and not even a bug.

We should consider adding an extra safety check here, since we follow defensive programming at most places.

P.S. Please do not bother the Incident-guys unless you know for sure that it's a bug and has security implications.

**Comment by MinghuaWang** [comment]
Yeah, adding a check there is good for this case. 

Esys_xxx are the functions you intend to expose to users to use for applications. So without dev document, the user can pass any value for the parameters. If the invoke of the function can lead to a crash, why it is not even a bug?

**Comment by AndreasFuchsSIT** [comment]
The developer documentation / doxygen and thus man-page says:
https://github.com/tpm2-software/tpm2-tss/blob/c3fc89d0270884f27421b8f1d094ac6bf5016d69/src/tss2-esys/api/Esys_Quote.c#L146
Thus, handing in ESYS_TR_NONE is not such a signature key as described.

You can make the library fail in many ways. If you pass a random value for a pointer parameter, the library will also segfault when dereferencing it. Of course the latter is undetectable for the library, whilst the former is and we want to fail gracefully, so we want to add a check, but either case is primarily an application bug.

But as I said, we want to give developers some help in detecting errors in their applications during development and runtime, so we should add a check.

**Comment by tstruk** [comment]
All should be fixed in this commit: https://github.com/tpm2-software/tpm2-tss/commit/cb5cb5230b90322c22dd7ca590dbdcd0ebe36401
