### ISSUE TITLE
ERROR:marshal:src/tss2-mu/tpms-types.c:77:Tss2_MU_TPMS_PCR_SELECTION_Marshal() sizeofSelect value 255/4 too big

### ISSUE THREAD

**Issue by S-Dinesh13** [tpm2-software/tpm2-tss#1367]
I'm trying to use the TPM2.0 in my laptop with Ubuntu16.04. I have installed the relevant packages by building from the source such as:

1) https://github.com/tpm2-software/tpm2-tss
2) https://github.com/tpm2-software/tpm2-abrmd
3) https://sourceforge.net/projects/ibmswtpm2

-> I have verified tpm_tis by grepping the dmesg log.
    [    0.831509] tpm_tis MSFT0101:00: 2.0 TPM (device-id 0xFE, rev-id 4)

-> I successfully started tpm2-abrmd.service
    ● tpm2-abrmd.service - TPM2 Access Broker and Resource Management Daemon
   Loaded: loaded (/lib/systemd/system/tpm2-abrmd.service; disabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-04-01 19:27:44 IST; 17s ago
 Main PID: 25123 (tpm2-abrmd)
    Tasks: 6
   Memory: 2.1M
      CPU: 17ms
   CGroup: /system.slice/tpm2-abrmd.service
           └─25123 /usr/local/sbin/tpm2-abrmd

Apr 01 19:27:44 LAO000314U systemd[1]: Stopped TPM2 Access Broker and Resource Management Daemon.
Apr 01 19:27:44 LAO000314U systemd[1]: Starting TPM2 Access Broker and Resource Management Daemon...
Apr 01 19:27:44 LAO000314U systemd[1]: Started TPM2 Access Broker and Resource Management Daemon.

-> tpm2_server started listening on port 2322
    TPM command server listening on port 2321
     Platform server listening on port 2322

-> ls -als /sys/class/tpm/tpm0/device/
total 0
0 drwxr-xr-x  5 root root    0 Apr  1 19:36 .
0 drwxr-xr-x 30 root root    0 Apr  1 11:46 ..
0 lrwxrwxrwx  1 root root    0 Apr  1 11:46 driver -> ../../../bus/platform/drivers/tpm_tis
0 -rw-r--r--  1 root root 4096 Apr  1 19:35 driver_override
0 lrwxrwxrwx  1 root root    0 Apr  1 18:41 firmware_node -> ../../LNXSYSTM:00/LNXSYBUS:00/MSFT0101:00
0 -r--r--r--  1 root root 4096 Apr  1 19:35 modalias
0 drwxr-xr-x  2 root root    0 Apr  1 19:35 power
0 lrwxrwxrwx  1 root root    0 Apr  1 19:35 subsystem -> ../../../bus/platform
0 drwxr-xr-x  3 root root    0 Apr  1 11:46 tpm
0 drwxr-xr-x  3 root root    0 Apr  1 11:46 tpmrm
0 -rw-r--r--  1 root root 4096 Apr  1 18:41 uevent

-> I'm able to read the PCR values of the device using tpm2-tools installed from Ubuntu repository.

-> I try to run ./tpm2-tss/test/tpmclient/tpmclient.int , I get the below error:
    WARNING:marshal:src/tss2-mu/tpm2b-types.c:349:Tss2_MU_TPM2B_NV_PUBLIC_Unmarshal() Size not zero 
ERROR:marshal:src/tss2-mu/tpms-types.c:77:Tss2_MU_TPMS_PCR_SELECTION_Marshal() sizeofSelect value 255/4 too big 
WARNING:marshal:src/tss2-mu/tpm2b-types.c:347:Tss2_MU_TPM2B_ECC_POINT_Unmarshal() Size not zero 

Is there any step-by-step documentation which could help me to validate the TPM2.0 chip with this source code?

What is the right procedure to test and perform operations using Enhanced System API? As I need to develop a test application using ESAPI.

**Comment by AndreasFuchsSIT** [comment]
To test with the physical tpm, you can run the following:
https://github.com/tpm2-software/tpm2-tss/blob/30c033f66d3d1e887e60cf6668aa10e162b05df2/README.md#running-tests-on-physical-tpm-device
(Note that you have to turn off the tabrmd for this though)

A good starting point for using ESAPI is either all tests that start with `Esys_*` under `tests/integration` or the https://github.com/tpm2-software/tpm2-tools which also use ESAPI in their current master.

Also you can have a look at https://github.com/tpm2-software/tpm2-tss-engine or https://github.com/tpm2-software/tpm2-totp which also both use ESAPI.

Wrt the errors on tpmclient.int, I have no idea what's happening there. Could you maybe provide the exact commit-id that you're working from ?

**Comment by tstruk** [comment]
On 4/1/19 7:14 AM, S-Dinesh13 wrote:
> -> I'm able to read the PCR values of the device using tpm2-tools installed from Ubuntu repository.
> 
> -> I try to run ./tpm2-tss/test/tpmclient/tpmclient.int , I get the below error:
> WARNING:marshal:src/tss2-mu/tpm2b-types.c:349:Tss2_MU_TPM2B_NV_PUBLIC_Unmarshal() Size not zero
> ERROR:marshal:src/tss2-mu/tpms-types.c:77:Tss2_MU_TPMS_PCR_SELECTION_Marshal() sizeofSelect value 255/4 too big
> WARNING:marshal:src/tss2-mu/tpm2b-types.c:347:Tss2_MU_TPM2B_ECC_POINT_Unmarshal() Size not zero
> 
> Is there any step-by-step documentation which could help me to validate the TPM2.0 chip with this source code?
> 
> What is the right procedure to test and perform operations using Enhanced System API? As I need to develop a test application using ESAPI.
> 

Looks like the issue disappeared from github. Strange...

Anyway, are you running against your tpm hardware or tpm simulator (tpm2_server)?
From the description you provide I understand that you want to use the hw.
In this case you don't need to start the simulator.
Also the tpmclient.int isn't the best choice to test the HW.
Thanks,
-- 
Tadeusz

**Comment by AndreasFuchsSIT** [comment]
`configure: error: TPM device provided does not exist or is not writable` basically says it. `/dev/tpm0` is not writable. you should `sudo chmod go+rw /dev/tpm0`.

Alternatively, I'd still recommend using the tpm2-tools which is much more convenient...

**Comment by S-Dinesh13** [comment]
> `configure: error: TPM device provided does not exist or is not writable` basically says it. `/dev/tpm0` is not writable. you should `sudo chmod go+rw /dev/tpm0`.
>
@AndreasFuchsSIT Yes, you are right about that. My other user did not have any read-write permission. But, my initial error w.r.t the Marshal/Unmarshal error still persists. Am I missing something? Or am I performing some extra steps?
 
> Alternatively, I'd still recommend using the tpm2-tools which is much more convenient...
>
I'm using the tpm2-tools' source to validate and analyze the steps that need to be performed in order to get control over the TPM hardware using ESAPI.

**Comment by AndreasFuchsSIT** [comment]
Honestly, the tpmclient.int test is an old and undocumented mess that we want to get rid of asap. Also since it does not give good error messages.
If you could point out where inside tpmclient.int the error occurs, we might be able to find something out.
Maybe you could `gdb` through it with `n` and help us narrow it down.

**Comment by S-Dinesh13** [comment]
- tpmclient.int seems to be some sort of wrapper written in shell script. So, I beleive the below output would be expected while executing using GDB:

---------------------------
>tpm2-tss/test/tpmclient/tpmclient.int": not in executable format: File format not recognized
----------------------------

- While trying to run ./tpm2-tss/test/tpmclient/test_tpmclient_tpmclient_int-tpmclient.int.o as super user, this is what is get:

-----------------------------
>Reading symbols from test_tpmclient_tpmclient_int-tpmclient.int.o...done.
>(gdb) run
Starting program: /home/software/tpm2-tss/test/tpmclient/test_tpmclient_tpmclient_int-tpmclient.int.o 
/bin/bash: /home/software/tpm2-tss/test/tpmclient/test_tpmclient_tpmclient_int-tpmclient.int.o: Permission denied
/bin/bash: line 0: exec: /home/software/tpm2-tss/test/tpmclient/test_tpmclient_tpmclient_int-tpmclient.int.o: cannot execute: Permission denied
During startup program exited with code 126.
-----------------------------

- I have tried putting `set -x` to tpmclient and I see:

------------------------
>exec /home/software/tpm2-tss/test/tpmclient/.libs/lt-tpmclient.int
WARNING:marshal:src/tss2-mu/tpm2b-types.c:349:Tss2_MU_TPM2B_NV_PUBLIC_Unmarshal() Size not zero 
ERROR:marshal:src/tss2-mu/tpms-types.c:77:Tss2_MU_TPMS_PCR_SELECTION_Marshal() sizeofSelect value 255/4 too big 
WARNING:marshal:src/tss2-mu/tpm2b-types.c:347:Tss2_MU_TPM2B_ECC_POINT_Unmarshal() Size not zero
------------------------
Is there any other steps that I can try?

Thanks
S.Dinesh

**Comment by tstruk** [comment]
> * tpmclient.int seems to be some sort of wrapper written in shell script. So, I beleive the below output would be expected while executing using GDB:
> 
> > tpm2-tss/test/tpmclient/tpmclient.int": not in executable format: File format not recognized

Yes, they are libtool wrappers. You need to use libtool to run it:
$ libtool execute gdb test/tpmclient/tpmclient.int

> > exec /home/software/tpm2-tss/test/tpmclient/.libs/lt-tpmclient.int
> > WARNING:marshal:src/tss2-mu/tpm2b-types.c:349:Tss2_MU_TPM2B_NV_PUBLIC_Unmarshal() Size not zero
> > ERROR:marshal:src/tss2-mu/tpms-types.c:77:Tss2_MU_TPMS_PCR_SELECTION_Marshal() sizeofSelect value 255/4 too big
> > WARNING:marshal:src/tss2-mu/tpm2b-types.c:347:Tss2_MU_TPM2B_ECC_POINT_Unmarshal() Size not zero
> 
> Is there any other steps that I can try?

Yes, please run it under gdb as above, set a breakpoint at marshal:src/tss2-mu/tpms-types.c:77
(gdb) b marshal:src/tss2-mu/tpms-types.c:77
then run it, and when it hits the breakpoint run backtrace:
(gdb) bt
That way we can see where is was triggered from.

**Comment by tstruk** [comment]
Assuming the issue is solved now
