### ISSUE TITLE
tss2-esys.pc hardcodes -lgcrypt on 2.1.x

### ISSUE THREAD

**Issue by jacmet** [tpm2-software/tpm2-tss#1371]
Please consider applying https://github.com/tpm2-software/tpm2-tss/pull/1173 to the 2.1.x / 2.2.x series as well, as those branches still hardcodes -lgcrypt in the .pc file leading to the issues explained in https://github.com/tpm2-software/tpm2-tss/issues/1169 - Thanks

**Comment by AndreasFuchsSIT** [comment]
I gues we only need the second half of #1173 since that's actually a bug.
The first half (aka changing the default) should be left as is for a bugfix-release IMHO.

**Comment by jacmet** [comment]
Yes, I agree. That is what I'm doing here with a local patch for Buildroot as well.

**Comment by AndreasFuchsSIT** [comment]
According to the tags here: https://github.com/tpm2-software/tpm2-tss/commit/a5ff71abeda9a5aea269812de32afb79ef3fcb4d that commit should already be part of 2.2.0, 2.2.1 and 2.2.2

Do you really need this for the 2.1.x series as well ? We recommend going to 2.2.x at this moment if suitable...

**Comment by jacmet** [comment]
Sorry, you are right - It is indeed part of 2.2.0. Buildroot (current development and the current LTS release is using 2.1.x: https://git.buildroot.net/buildroot/tree/package/tpm2-tss/tpm2-tss.mk
Is there any specific reason to move to 2.2.x for our LTS? How long will 2.1.x be supported?

**Comment by AndreasFuchsSIT** [comment]
1.) 2.2.x could be considered a maintenance release I guess. Biggest changes are QNX support and partial reads. So the most boring release ever...

2.) That's the question of the year... ;-)
As long as we have requests for it, I guess ?

Frankly, we're still figuring that out; whether and for how long does it make sense to support minor versions with bugfix-releases. Especially since we're aiming for 2-4 minor releases per year... That would leave us in cherry-pick hell... 

IMHO, the most recent, yes of course. 1 earlier, yes for some time; question is how log. 2 and more earlier, the extra effort starts eating more time than we gain...

I'll let @tstruk voice an opinion about this... ;-)

**Comment by jacmet** [comment]
The effort is very much appreciated! I know the pain, maintaining multiple release series for Buildroot as well. As a user of the tpm2 sw stack, one of the imho most important things is to have a written down release/support schedule (and stick to it :P)

**Comment by tstruk** [comment]
The 2.1.x branch is still maintained so you are right, the https://github.com/tpm2-software/tpm2-tss/pull/1173 (or part of it) should be also applied to 2.1.x. The plan was to support 2.1.x for as long as there will be requests to maintain it, but no longer than a year after 2.1.0 release. After that users should switch to a newer version. I'll spin a 2.1.3 rc-0 this week.

**Comment by AndreasFuchsSIT** [comment]
I guess we should put this into writing; 1 year after release...
or should we say, 1/2 year after the next (minor) release ?

**Comment by tstruk** [comment]
Yes, It's on my to do list.
I guess 1/2 year after minor release might turn into "maintain forever".
1 year after the first release is more specific. And this is a general rule, not something set in stone.

**Comment by AndreasFuchsSIT** [comment]
What I meant was:
2.0.x gets bugfixes until 1/2 year after 2.1.0
2.1.x gets bugfixes until 1/2 year fater 2.2.0
That would leave us with approx 9 months of bugfix support or 2-3 old versions at any given time...

Or we say 2 most recent versions, aka 2.2.0 ends 2.0.x and 2.3.0 ends 2.1.x ?

**Comment by jacmet** [comment]
@AndreasFuchsSIT that sounds good to me. Alternatively, you could select a release once in a while (E.G. the first release of the year) and make it a long term support release, that you could then support for a longer time (E.G. for at least 1 year), and other releases for a shorter time (perhaps only until the next release is out) - Up to you.

**Comment by tstruk** [comment]
Fixed with https://github.com/tpm2-software/tpm2-tss/commit/e863cc6b798cf8d7d78d3f950b1ad7ced0b32877

**Comment by jacmet** [comment]
@tstruk thanks!
