### ISSUE TITLE
memory leak in iesys_cryptossl_pk_encrypt

### ISSUE THREAD

**Issue by MinghuaWang** [tpm2-software/tpm2-tss#1380]
OPENSSL_free(label_copy) is needed at the end of the function, otherwise there will be memory leak.

**Comment by AndreasFuchsSIT** [comment]
```
The EVP_PKEY_CTX_set0_rsa_oaep_label() macro sets the RSA OAEP label to label and its length to len. If label is NULL or len is 0, the label is cleared. The library takes ownership of the label so the caller should not free the original memory pointed to by label. The padding mode must have been set to RSA_PKCS1_OAEP_PADDING.
```
see https://www.openssl.org/docs/man1.1.1/man3/EVP_PKEY_CTX_set0_rsa_oaep_label.html

So it's correct to only free if EVP_PKEY_CTX_set0_rsa_oaep_label fails as done here
https://github.com/tpm2-software/tpm2-tss/blob/d7c85ed9ba65ec549c1c416741b9f57e9f250e62/src/tss2-esys/esys_crypto_ossl.c#L680-L681
