### ISSUE TITLE
esys-default-tcti failure without MsSim

### ISSUE THREAD

**Issue by Evgeniy-Yuriev** [tpm2-software/tpm2-tss#1382]
Hello.

I've discovered, that, being disabled (via configure), mssim produces an error in unit-test:
esys-default-tcti cannot receive default tcti for mssim (quite reasonably) and do with one test failed.
I suppose an ifdef is missed, for test_tcti_mssim actuation.
tpm2-tss version is 2.1.3.

**Comment by AndreasFuchsSIT** [comment]
Thanks !
