### ISSUE TITLE
Release 2.2.3 with nonceCaller.size fixed

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tss#1387]
see https://github.com/tpm2-software/tpm2-tss/pull/1386

**Comment by AndreasFuchsSIT** [comment]
2.2.3_rc0 and 2.1.4_rc0 release...

**Comment by flihp** [comment]
Any interest in pulling #1391 into the 2.2.3 RC?

**Comment by flihp** [comment]
#1392 as well?

**Comment by AndreasFuchsSIT** [comment]
I wouldn't consider those fixed bugs but enhancements, and thus IMHO wouldn't include them.
OK with you ?

**Comment by flihp** [comment]
Can't build on windows from a release tarball w/o #1391. Feels like a bug to me. The MAINTAINERS file is cosmetic so your desegregation. Either way I'm trying to keep from doing a release immediately after you wrap up this one. #1391 would warrant that.

**Comment by AndreasFuchsSIT** [comment]
Ok, good point...
So I'll add #1391 and #1379 to 2.2.3 for an rc1 then...
