### ISSUE TITLE
Failed to open device file /dev/tpmrm0:

### ISSUE THREAD

**Issue by shravan2915** [tpm2-software/tpm2-tss#1390]
I am running ubuntu 16.04 (kernel 4.4.0-146-generic ) on a ThinkPad and using the tpm2-tss and tpm2-tss-engine package. While trying to make a post request (using curl) with tpm2tss as the engine I get the following error/warnings. Note: The POST succeeds. But, I am not sure why I get these error messages or the repetitive nature of it.

ls /dev/tpm*
/dev/tpm0

Note: I don't see a similar error message running ubuntu 18.04 on a NUC device. Although, I notice a different result with ls operation
ls /dev/tpm*
/dev/tpm0
/dev/tpmrm0

`WARNING:esys:src/tss2-esys/esys_tcti_default.c:139:tcti_from_file() Could not load TCTI file: libtss2-tcti-default.so 
WARNING:esys:src/tss2-esys/esys_tcti_default.c:139:tcti_from_file() Could not load TCTI file: libtss2-tcti-tabrmd.so 
ERROR:tcti:src/tss2-tcti/tcti-device.c:399:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpmrm0: No such file or directory 
WARNING:esys:src/tss2-esys/esys_tcti_default.c:85:tcti_from_init() TCTI init for function 0x7fc2e1b5ccd0 failed with a000a 

WARNING:esys:src/tss2-esys/esys_tcti_default.c:139:tcti_from_file() Could not load TCTI file: libtss2-tcti-default.so 
WARNING:esys:src/tss2-esys/esys_tcti_default.c:139:tcti_from_file() Could not load TCTI file: libtss2-tcti-tabrmd.so 
ERROR:tcti:src/tss2-tcti/tcti-device.c:399:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpmrm0: No such file or directory 
WARNING:esys:src/tss2-esys/esys_tcti_default.c:85:tcti_from_init() TCTI init for function 0x7fc2e1b5ccd0 failed with a000a 

WARNING:esys:src/tss2-esys/esys_tcti_default.c:139:tcti_from_file() Could not load TCTI file: libtss2-tcti-default.so 
WARNING:esys:src/tss2-esys/esys_tcti_default.c:139:tcti_from_file() Could not load TCTI file: libtss2-tcti-tabrmd.so 
ERROR:tcti:src/tss2-tcti/tcti-device.c:399:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpmrm0: No such file or directory 
WARNING:esys:src/tss2-esys/esys_tcti_default.c:85:tcti_from_init() TCTI init for function 0x7fc2e1b5ccd0 failed with a000a 

WARNING:esys:src/tss2-esys/esys_tcti_default.c:139:tcti_from_file() Could not load TCTI file: libtss2-tcti-default.so 
WARNING:esys:src/tss2-esys/esys_tcti_default.c:139:tcti_from_file() Could not load TCTI file: libtss2-tcti-tabrmd.so 
ERROR:tcti:src/tss2-tcti/tcti-device.c:399:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpmrm0: No such file or directory 
WARNING:esys:src/tss2-esys/esys_tcti_default.c:85:tcti_from_init() TCTI init for function 0x7fc2e1b5ccd0 failed with a000a'

**Comment by AndreasFuchsSIT** [comment]
Actually, you can ignore this. it means that /dev/tpm0 was opened successfully...

The sequence is: tcti-default, tcti-tabrmd, /dev/tpmrm0, /dev/tpm0

As long as /dev/tpm0 does not appear, it should've worked.

I guess we need to document that or think about different logging here...

**Comment by shravan2915** [comment]
Thanks Andreas. Could we flip it to a warning? I suppose if all options fail we could log an error. Just my 2 cents.

**Comment by shravan2915** [comment]
Is it possible to modify this in my version of code? 
The sequence is: tcti-default, tcti-tabrmd, /dev/tpmrm0, /dev/tpm0
I would like to use only /dev/tpm0

**Comment by williamcroberts** [comment]
Yes, you would just not use NULL as your TCTI and initialize one for /dev/tpm0.

You can do it one of two ways:
1. shared or static linking directly to device TCTI library (libtss2-tcti-device) is probably what you want and can be accomplished by using the function:
```C
TSS2_RC Tss2_Tcti_Device_Init (
    TSS2_TCTI_CONTEXT *tctiContext,
    size_t *size,
    const char *conf);
```

2. The other more complicated way is to replicate the loading logic in tpm2-tools within your client application and specify the TCTI

Im not sure if we need to standardize the complete loading of TCTIs from env variables within the tss code, or if that will always remain application specific.

**Comment by AndreasFuchsSIT** [comment]
This is reather a tpm2-tss-engine question, I guess.
Try
```
export TPM2TSSENGINE_TCTI=device
```

That only works, if your tpm2-tss-engine package was compiled with `--enable-tctienvvar`

**Comment by AndreasFuchsSIT** [comment]
I hope you could work it out. If not, please feel free to ask on the ML or at the tpm2-tss-engine project.

**Comment by shravan2915** [comment]
@AndreasFuchsSIT @williamcroberts Thanks. This issue is resolved with above suggestions.

**Comment by skboddula** [comment]
Hi All,

We are working on developing embedded iot edge gateway project with yocto rocko branch ( kernel 4.08 ). Currently working on setting up TPM2 & TSS2 Software packages tpm2-tss, tpm2-abrmd, tpm2-tools and tpm2-tss-engine. Managed to install all these packages and able to perform basic operations using TPM regarding like rsa encrypton/decryptiopn. But while trying to generate openssl certificates with tpm2tss as crypto engine I get the following error/warnings..

WARNING:esys:src/tss2-esys/esys_tcti_default.c:139:tcti_from_file() Could not load TCTI file: libtss2-tcti-default.so
WARNING:esys:src/tss2-esys/esys_tcti_default.c:139:tcti_from_file() Could not load TCTI file: libtss2-tcti-tabrmd.so
ERROR:tcti:src/tss2-tcti/tcti-device.c:399:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpmrm0: No such file or directory
WARNING:esys:src/tss2-esys/esys_tcti_default.c:85:tcti_from_init() TCTI init for function 0x7fc2e1b5ccd0 failed with a000a

For 'ls' query for TPM devices, found following result didn't see any tpmrm0 device file. Read somewhere that tpmrm0 kernel resource manager support was added from kernel version > 4.12, if that is the case can anyone advice on how to integrate tpm2-tss-engine for openssl crypto operations for kernel versions <4.12.

ls /dev/tpm*
/dev/tpm0

Installed following versions: tpm2-abrmd_2.0.1
			     tpm2-tss_2.0.0
			     tpm2-tools_3.1.1
			     tpm2-tss-engine_0.9.9 ( integrated from meta-security openembedded layer )

Thanks,
Shiva.
