### ISSUE TITLE
tss user / group creation

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#1393]
https://github.com/tpm2-software/tpm2-abrmd/issues/613 brings up relevant points about assumptions made about the existence of the `tss` user account / group. Since tpm2-tss took over the udev rules we now have the `tss` user and group hard coded: https://github.com/tpm2-software/tpm2-tss/commit/0075f88466d791b2b58c60adafed87ec814441df

I figure we can make the name of the user / group a configure time option without much trouble. I don't see a viable way to guarantee that the user / group exist at install time without changing the default to 'root'. Anyone overriding this default explicitly via configure script would be taking on responsibility for ensuring they exist (likely in a package script). There was also mention of using some systemd mechanism: https://www.freedesktop.org/software/systemd/man/sysusers.d.html

Any strong opinions on this one @AndreasFuchsSIT @tstruk @williamcroberts?

**Comment by AndreasFuchsSIT** [comment]
I guess that we should upstream the user/group assignment to udev to begin with...
sysusers.d is nice, but of no help if /dev/tpmrm0 is not correctly chown'ed...

But the configure-option would be a nice addition anyways...
