### ISSUE TITLE
make clean shall not delete AUTHORS

### ISSUE THREAD

**Issue by dilyanpalauzov** [tpm2-software/tpm2-tss#1402]
Makefile generates the AUTHORS file from gitlog and includes this file on `make dist`.

`make clean` deletes AUTHORS.

My understanding is, that once one unpacks a tarball, calls `./configure && make clean && make dist`, an identical tarball will be created.

This is not going to work with tpm2-tss, as for the `make dist` outside of a git repository, the AUTHORS file cannot be recreated after `make clean` for `make dist`.

Looking at the [Standard Targets for Users in the GNU Coding Standards](https://www.gnu.org/prep/standards/html_node/Standard-Targets.html#Standard-Targets) I find no standard target, which would be entitled to delete AUTHORS.

**Comment by flihp** [comment]
Good point. When I set this up I think my rationale was that the build generates the authors file so having the build 'clean' it made sense. When you're building from a release tarbal and running `make clean` deletes the AUTHORS file this makes a lot less sense :smile:
