### ISSUE TITLE
ERROR:tcti:src/tss2-tcti/tcti-device.c:319:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: No such file or directory

### ISSUE THREAD

**Issue by bcleki** [tpm2-software/tpm2-tss#1408]
Hi,
    I am trying to access(read/write) non vol partition of TPM2.0 , i have hardware that i can test on, i am trying to reuse( have changed couple of function calls ) one of test application (attaching file) from the tpm2-tss repo, i am able to successfully compile it, 

[TPM.txt](https://github.com/tpm2-software/tpm2-tss/files/3175080/TPM.txt)

it is throwing me an error when i run it on the hardware, 

ERROR:tcti:src/tss2-tcti/tcti-device.c:319:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: No such file or directory
Failed to initialize device TCTI context: 0xa000a

tpm2-abrmd daemon is already up and running.

Any suggestions please.

**Comment by flihp** [comment]
Any reason you're not using the tpm2_nv(read|write) utilities from https://github.com/tpm2-software/tpm2-tools?

**Comment by bcleki** [comment]
i am trying to access through code rather than using shell commands.

**Comment by AndreasFuchsSIT** [comment]
I'm sorry, but the code you're using there is a complex mixture from the test-cases. This tcti_proxy stuff is something you definitively don't want in your application.

I'd recommend calling Esys_Initialize(&ctx, NULL, NULL); Esys_NV_Write(), ... etc

That will auto-detect the tcti for you and use the abrmd if necessary or open /dev/tpm0 if needed.

I hope this takes you down the correct path.
A hopefully somewhat better example for you to start from would be this project: https://github.com/tpm2-software/tpm2-totp/blob/master/src/libtpm2-totp.c

**Comment by bcleki** [comment]
I tried calling Esys_Initialize(&ctx, NULL, NULL); 
I am getting below error.

WARNING:esys:src/tss2-esys/esys_tcti_default.c:137:tcti_from_file() Could not load TCTI file: libtss2-tcti-default.so 
WARNING:esys:src/tss2-esys/esys_tcti_default.c:137:tcti_from_file() Could not load TCTI file: libtss2-tcti-tabrmd.so 
ERROR:tcti:src/tss2-tcti/tcti-device.c:319:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpmrm0: No such file or directory 
WARNING:esys:src/tss2-esys/esys_tcti_default.c:83:tcti_from_init() TCTI init for function 0x7f1516b0bc50 failed with a000a 
ERROR:tcti:src/tss2-tcti/tcti-device.c:319:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: No such file or directory 
WARNING:esys:src/tss2-esys/esys_tcti_default.c:83:tcti_from_init() TCTI init for function 0x7f1516b0bc50 failed with a000a 
Esys_Initialize FAILED! Response Code : 0x70002
WARNING:tcti:src/util/io.c:248:socket_connect() Failed to connect to host ::1, port 2321: errno 99: Cannot assign requested address 
WARNING:esys:src/tss2-esys/esys_tcti_default.c:83:tcti_from_init() TCTI init for function 0x7f15142382a0 failed with a000a 
ERROR:esys:src/tss2-esys/esys_tcti_default.c:213:get_tcti_default() No standard TCTI could be loaded 
ERROR:esys:src/tss2-esys/esys_context.c:67:Esys_Initialize() Initialize default tcti. ErrorCode (0x00070002)

**Comment by bcleki** [comment]
I tried using abrmd, i am getting the below error, i am using the library versions

tpm2-abrmd 2.0.2
tpm2-tools 3.1.2
tpm2-tss 2.1.2

Failed to initialize tabrmd TCTI context: 0xa000b
WARNING:esys:src/tss2-esys/esys_tcti_default.c:137:tcti_from_file() Could not load TCTI file: libtss2-tcti-default.so
WARNING:esys:src/tss2-esys/esys_tcti_default.c:137:tcti_from_file() Could not load TCTI file: libtss2-tcti-tabrmd.so
ERROR:tcti:src/tss2-tcti/tcti-device.c:319:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpmrm0: No such file or directory
WARNING:esys:src/tss2-esys/esys_tcti_default.c:83:tcti_from_init() TCTI init for function 0x7f54bf3a4c50 failed with a000a
ERROR:tcti:src/tss2-tcti/tcti-device.c:319:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: No such file or directory
WARNING:esys:src/tss2-esys/esys_tcti_default.c:83:tcti_from_init() TCTI init for function 0x7f54bf3a4c50 failed with a000a
WARNING:tcti:src/util/io.c:248:socket_connect() Failed to connect to host ::1, port 2321: errno 99: Cannot assign requested address
WARNING:esys:src/tss2-esys/esys_tcti_default.c:83:tcti_from_init() TCTI init for function 0x7f54bcad12a0 failed with a000a
ERROR:esys:src/tss2-esys/esys_tcti_default.c:213:get_tcti_default() No standard TCTI could be loaded
ERROR:esys:src/tss2-esys/esys_context.c:67:Esys_Initialize() Initialize default tcti. ErrorCode (0x00070002)
Esys_Initialize FAILED! Response Code : 0x70002

**Comment by AndreasFuchsSIT** [comment]
Could you check via `ls -l /dev/tpm*` that /dev/tpm0 or /dev/tpmrm0 actually exist, and (more importantly) if you are allowed to write to them ?

**Comment by bcleki** [comment]
Sorry for late reply, was tied pick other task. looks like i was not passing /dev/tpm to the container, now that error is gone. I am facing new issue

WARNING:esys:src/tss2-esys/esys_tcti_default.c:137:tcti_from_file() Could not load TCTI file: libtss2-tcti-default.so
WARNING:esys:src/tss2-esys/esys_tcti_default.c:137:tcti_from_file() Could not load TCTI file: libtss2-tcti-tabrmd.so

ERROR:esys:src/tss2-esys/esys_iutil.c:993:esys_GetResourceObject() Error: Esys handle does not exist (70018).
ERROR:esys:src/tss2-esys/api/Esys_NV_Write.c:195:Esys_NV_Write_Async() nvIndex unknown. ErrorCode (0x00070018)
ERROR:esys:src/tss2-esys/api/Esys_NV_Write.c:94:Esys_NV_Write() Error in async function ErrorCode (0x00070018)
ERROR:esys:src/tss2-esys/esys_iutil.c:993:esys_GetResourceObject() Error: Esys handle does not exist (70018).
ERROR:esys:src/tss2-esys/api/Esys_NV_Read.c:190:Esys_NV_Read_Async() authHandle unknown. ErrorCode (0x00070018)
Error esys nv write

ERROR:esys:src/tss2-esys/api/Esys_NV_Read.c:91:Esys_NV_Read() Error in async function ErrorCode (0x00070018)
ERROR:esys:src/tss2-esys/esys_iutil.c:993:esys_GetResourceObject() Error: Esys handle does not exist (70018).
ERROR:esys:src/tss2-esys/api/Esys_NV_UndefineSpace.c:180:Esys_NV_UndefineSpace_Async() nvIndex unknown. ErrorCode (0x00070018)
ERROR:esys:src/tss2-esys/api/Esys_NV_UndefineSpace.c:82:Esys_NV_UndefineSpace() Error in async function ErrorCode (0x00070018)
Error esys nv readCleanup NvHandle failed.

**Comment by AndreasFuchsSIT** [comment]
Did you try tpm2_nv_write/read from the tpm2-tools, do they work now ?
Besides that, it looks like programming errors on how you call Esys_NV_Write.
Without your code, I cannot help you.

**Comment by bcleki** [comment]
Yes tpm2_nv_write/read work fine, Here is the code
[TPM.txt](https://github.com/tpm2-software/tpm2-tss/files/3252826/TPM.txt)

Error with the latest code 

WARNING:esys:src/tss2-esys/esys_tcti_default.c:137:tcti_from_file() Could not load TCTI file: libtss2-tcti-default.so
WARNING:esys:src/tss2-esys/esys_tcti_default.c:137:tcti_from_file() Could not load TCTI file: libtss2-tcti-tabrmd.so
WARNING:esys:src/tss2-esys/api/Esys_NV_DefineSpace.c:334:Esys_NV_DefineSpace_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_NV_DefineSpace.c:119:Esys_NV_DefineSpace() Esys Finish ErrorCode (0x000009a2)
ERROR: Esys_NV_DefineSpace(0x9A2) -
WARNING:esys:src/tss2-esys/api/Esys_ReadPublic.c:325:Esys_ReadPublic_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/esys_tr.c:218:Esys_TR_FromTPMPublic_Finish() Error ReadPublic ErrorCode (0x00000184)
ERROR:esys:src/tss2-esys/esys_tr.c:308:Esys_TR_FromTPMPublic() Error TR FromTPMPublic ErrorCode (0x00000184)
ERROR: Esys_TR_FromTPMPublic(0x184) -
ERROR:esys:src/tss2-esys/esys_tr.c:344:Esys_TR_Close() Error: Esys handle does not exist (70018).
ERROR: Esys_NV_ReadPublic(0x70018) -
Failed to define NV area at index 0x1000000 File larger than TPM2_MAX_NV_BUFFER_SIZE, got 9223372036854775807 expected 2048

Thanks in advance

**Comment by AndreasFuchsSIT** [comment]
`ERROR: Esys_NV_DefineSpace(0x9A2)` is an authorization failure.
I recommend using the tool `tpm2_rc_decode` for this.
So either you have change the password of the owner in advance (default is 0-length) or you are using a password even though the default password is used.
That would be the ESYS-related potential issues here.
Or of course there could be some weird stuff happening with memory corruptions that I did not search for.

**Comment by bcleki** [comment]
Ok thanks for responding, my goal is to define index with the password and perform write/read with that password.

**Comment by Muthukumar-S1979** [comment]
Hi @williamcroberts & etal, 

Do we have any solution for this 0x700018 issue , which was discussed above.
I have used tools api to define NV , Write in to NV RAM and am just try to create my own test app to read the same offset that i have used in NV Define. Below are the commands and its associated auth permisssion

1) ./tpm2_nvdefine -Q -x 0x1500016 -a 0x40000001 -s 32 -t "ownerread|policywrite|ownerwrite"   
2) echo "pleafooase123abc" > nv.test_w    
3) ./tpm2_nvwrite -Q -x 0x1500016 -a 0x40000001 nv.test_w   
4) ./tpm2_nvread -x 0x1500016 -a 0x40000001  
pleafooase123abc    <<< OUTPUT DATA , read via tpm2_nvead() >>>

Now , I tried to run the sample app shared in this link . I just taken 
https://github.com/tpm2-software/tpm2-totp/blob/master/src/libtpm2-totp.c 


**DEBUG LOG:**
Initializing
init_rand()
init_rsa()
init_ecc()
Engine name: TPM2-TSS engine for OpenSSL
Init result: 1 
Setting owner auth to empty auth.
Setting parent auth to empty auth.
READ RandomNumber from NVRAM
ERROR:tcti:src/tss2-tcti/tcti-device.c:440:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: No such file or directory 
WARNING:tcti:src/tss2-tcti/tctildr.c:62:tcti_from_init() TCTI init for function 0x7f251061018b failed with a000a 
WARNING:tcti:src/tss2-tcti/tctildr.c:92:tcti_from_info() Could not initialize TCTI named: tcti-device 
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:150:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-default.so 
B4 NVREAD
ERROR:esys:src/tss2-esys/esys_iutil.c:1086:esys_GetResourceObject() Error: Esys handle does not exist (70018). 
**ERROR:esys:src/tss2-esys/api/Esys_NV_Read.c:180:Esys_NV_Read_Async() authHandle unknown. ErrorCode (0x00070018)** 
ERROR:esys:src/tss2-esys/api/Esys_NV_Read.c:82:Esys_NV_Read() Error in async function ErrorCode (0x00070018) 
B4 chkrc() FROM NVREAD
**ERROR in tpm2_nv_read (tpm2_nvread.c:189): 0x00070018**
ERROR in main (tpm2_nvread.c:131): 0x00070018

**QUERY**:
------------------------------------------------------------
Why "esys:src/tss2-esys/api/Esys_NV_Read.c:180:Esys_NV_Read_Async() authHandle unknown. ErrorCode (0x00070018)" is not getting the AUTHHANDLE (0x40000001 - RH_OWNER) which i have already given in Esys_NV_Read() API ???
---------------------------------------------------
**Attached the test code : tpm2_nvread.c**
[tpm2_nvread.txt](https://github.com/tpm2-software/tpm2-tss/files/4651738/tpm2_nvread.txt)

Looking forward for your valuable reply.

BR,
Muthukumar

**Comment by williamcroberts** [comment]
> Hi @williamcroberts & etal,
> @AndreasFuchsSIT
> 
> Do we have any solution for this 0x700018 issue , which was discussed above.
> I have used tools api to define NV , Write in to NV RAM and am just try to create my own test app to read the same offset that i have used in NV Define. Below are the commands and its associated auth permisssion
> 
> 1. ./tpm2_nvdefine -Q -x 0x1500016 -a 0x40000001 -s 32 -t "ownerread|policywrite|ownerwrite"
> 2. echo "pleafooase123abc" > nv.test_w
> 3. ./tpm2_nvwrite -Q -x 0x1500016 -a 0x40000001 nv.test_w
> 4. ./tpm2_nvread -x 0x1500016 -a 0x40000001
>    pleafooase123abc    <<< OUTPUT DATA , read via tpm2_nvead() >>>
> 
> Since above "tpm2_nvread" command line API is working as expected, now i tried to create a test application which does the same thing of tpm2_nvread . I have used Esys APIs to read the nv ram. But unfortunately i am getting below "0x00070018" . Since command line "tpm2_nvread" is working fine ,not sure what am i missing in my test code .
> **Attached test code for reference**
> 
> **DEBUG LOG:**
> Initializing
> init_rand()
> init_rsa()
> init_ecc()
> Engine name: TPM2-TSS engine for OpenSSL
> Init result: 1
> Setting owner auth to empty auth.
> Setting parent auth to empty auth.
> READ RandomNumber from NVRAM
> ERROR:tcti:src/tss2-tcti/tcti-device.c:440:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: No such file or directory
> WARNING:tcti:src/tss2-tcti/tctildr.c:62:tcti_from_init() TCTI init for function 0x7f251061018b failed with a000a
> WARNING:tcti:src/tss2-tcti/tctildr.c:92:tcti_from_info() Could not initialize TCTI named: tcti-device
> ERROR:tcti:src/tss2-tcti/tctildr-dl.c:150:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-default.so
> B4 NVREAD
> ERROR:esys:src/tss2-esys/esys_iutil.c:1086:esys_GetResourceObject() Error: Esys handle does not exist (70018).
> **ERROR:esys:src/tss2-esys/api/Esys_NV_Read.c:180:Esys_NV_Read_Async() authHandle unknown. ErrorCode (0x00070018)**
> ERROR:esys:src/tss2-esys/api/Esys_NV_Read.c:82:Esys_NV_Read() Error in async function ErrorCode (0x00070018)
> B4 chkrc() FROM NVREAD
> **ERROR in tpm2_nv_read (tpm2_nvread.c:189): 0x00070018**
> ERROR in main (tpm2_nvread.c:131): 0x00070018
> 
> ## **QUERY**:
> ## Why "esys:src/tss2-esys/api/Esys_NV_Read.c:180:Esys_NV_Read_Async() authHandle unknown. ErrorCode (0x00070018)" is not getting the AUTHHANDLE (0x40000001 - RH_OWNER) which i have already given in Esys_NV_Read() API ???
> **Attached the test code : tpm2_nvread.c**
> [tpm2_nvread.txt](https://github.com/tpm2-software/tpm2-tss/files/4651995/tpm2_nvread.txt)
> 
> **NOTE : LIBRARY VERSIONS**
> 
> * tpm2-tools-3.X
> * tpm2-tss-2.3.1
> * tpm2-tss-engine-e1bba
> * tpm2-abrmd 2.3.1-31-ga160b06-dirty
> 
> Looking forward for your valuable reply.
> 
> cc @bcleki
> 
> BR,
> Muthukumar

Didn't you ask this on the mailing list, I already responded:
  - https://lists.01.org/hyperkitty/list/tpm2@lists.01.org/thread/3X5C6IQ77W2QPOAWIJOCE5A4ISCVXJHL/
