### ISSUE TITLE
2 new resource leaks reported by coverity

### ISSUE THREAD

**Issue by tstruk** [tpm2-software/tpm2-tss#1425]
1:
*** CID 1479603:  Resource leaks  (RESOURCE_LEAK)
/src/tss2-esys/esys_iutil.c: 1406 in iesys_get_name()
1400         TSS2_RC r;
1401         r = iesys_crypto_hash_start(&cryptoContext, publicInfo->publicArea.nameAlg);
1402         return_if_error(r, "crypto hash start");
1403     
1404         r = Tss2_MU_TPMT_PUBLIC_Marshal(&publicInfo->publicArea,
1405                                         &buffer[0], sizeof(TPMT_PUBLIC), &offset);
>>>     CID 1479603:  Resource leaks  (RESOURCE_LEAK)
>>>     Variable "cryptoContext" going out of scope leaks the storage it points to.
1406         return_if_error(r, "Marshaling TPMT_PUBLIC");
1407     
1408         r = iesys_crypto_hash_update(cryptoContext, &buffer[0], offset);
1409         return_if_error(r, "crypto hash update");
1410     
1411         r = iesys_crypto_hash_finish(&cryptoContext, &name->name[len_alg_id],

2: 
*** CID 1479602:    (RESOURCE_LEAK)
/src/tss2-esys/esys_iutil.c: 1358 in iesys_nv_get_name()
1352         r = iesys_crypto_hash_start(&cryptoContext, publicInfo->nvPublic.nameAlg);
1353         return_if_error(r, "Crypto hash start");
1354     
1355         r = Tss2_MU_TPMS_NV_PUBLIC_Marshal(&publicInfo->nvPublic,
1356                                            &buffer[0], sizeof(TPMS_NV_PUBLIC),
1357                                            &offset);
>>>     CID 1479602:    (RESOURCE_LEAK)
>>>     Variable "cryptoContext" going out of scope leaks the storage it points to.
1358         return_if_error(r, "Marshaling TPMS_NV_PUBLIC");
1359     
1360         r = iesys_crypto_hash_update(cryptoContext, &buffer[0], offset);
1361         return_if_error(r, "crypto hash update");
1362     
1363         r = iesys_crypto_hash_finish(&cryptoContext, &name->name[len_alg_id],
/src/tss2-esys/esys_iutil.c: 1361 in iesys_nv_get_name()
1355         r = Tss2_MU_TPMS_NV_PUBLIC_Marshal(&publicInfo->nvPublic,
1356                                            &buffer[0], sizeof(TPMS_NV_PUBLIC),
1357                                            &offset);
1358         return_if_error(r, "Marshaling TPMS_NV_PUBLIC");
1359     
1360         r = iesys_crypto_hash_update(cryptoContext, &buffer[0], offset);
>>>     CID 1479602:    (RESOURCE_LEAK)
>>>     Variable "cryptoContext" going out of scope leaks the storage it points to.
1361         return_if_error(r, "crypto hash update");
1362     
1363         r = iesys_crypto_hash_finish(&cryptoContext, &name->name[len_alg_id],
1364                                          &size);
1365         return_if_error(r, "crypto hash finish");
1366

**Comment by MinghuaWang** [comment]
There was a previous issue that had reported the 2nd memory leak for iesys_nv_get_name:  https://github.com/tpm2-software/tpm2-tss/issues/1361

**Comment by tstruk** [comment]
Fixed in commit https://github.com/tpm2-software/tpm2-tss/commit/0664db8e1fd1ad8452c5bc05562271407f44696e
