### ISSUE TITLE
RC from macro in TCTI header not compliant with the spec

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#1431]
The transmit & receive functions should return BAD_REFERENCE if the context parameter is NULL per the spec (section 3.2.5.1 & 3.2.5.2). The `Tss2_Tcti_Transmit` macro from the headers returns BAD_CONTEXT in this case though, as does the `Receive` macro. The header from the spec gets this wrong too which makes sense since we basically copy / pasted our headers into the spec.

**Comment by tstruk** [comment]
Not only transmit & receive, but also finalize, cancel, getPollHandles, setLocality, and makeSticky are incorrect in the same way.
