### ISSUE TITLE
Configuring fails with error: Invalid policy. Valid policies: git-directory, minor-version.

### ISSUE THREAD

**Issue by rickydjohn** [tpm2-software/tpm2-tss#1438]
I am following the instructions mentioned [here](https://github.com/tpm2-software/tpm2-tools/wiki/Getting-Started#installing) to test TPM. While configuring tpm2-tss, i am seeing the below error. I installed the latest version of autoconf-archive from [here](http://mirror.team-cymru.com/gnu/autoconf-archive/autoconf-archive-2018.03.13.tar.xz). 

```
root@aic1:~/tpm2-tss# ./configure --enable-unit
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
configure: error: Invalid policy. Valid policies: git-directory, minor-version.
root@aic1:~/tpm2-tss# uname -r
4.19.0-0.bpo.4-amd64
root@aic1:~/tpm2-tss# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.5 (stretch)
Release:	9.5
Codename:	stretch
```

Please help.

**Comment by AndreasFuchsSIT** [comment]
Your autoconf-archive version is too old, specifically the file ax_is_release.m4
This is what we do in CI:
```
wget http://ftpmirror.gnu.org/autoconf-archive/autoconf-archive-2019.01.06.tar.xz
tar xJf autoconf-archive-2019.01.06.tar.xz
cp autoconf-archive-2019.01.06/m4/ax_code_coverage.m4 m4/
cp autoconf-archive-2019.01.06/m4/ax_is_release.m4 m4/
cp autoconf-archive-2019.01.06/m4/ax_prog_doxygen.m4 m4/
```

**Comment by akela92** [comment]
Hi, i have the same problem and the solution given here is not working. Is there anything else I can do? I am trying to run a TPM in a Raspberry Pi.
Thanks in advance

**Comment by rickydjohn** [comment]
@AndreasFuchsSIT , I tried this. I copied the configuration to the tpm-tss m4 directory. That did not work. I even built the source and that did not help either. I think there is something more to it.

**Comment by AndreasFuchsSIT** [comment]
I'm pretty certain it should work.
Did you copy the m4 file before the `./bootstrap` step ?
That's important.

**Comment by kgold2** [comment]
FWIW, many months later, I get the same error when trying to build abrmd.  This Ubuntu 16 xenial with everything up to date.

**Comment by williamcroberts** [comment]
This works on 16.04 in our docker image build:
```
autoconf_archive=autoconf-archive-2018.03.13
wget "http://mirror.kumi.systems/gnu/autoconf-archive/$autoconf_archive.tar.xz"
tar -xf $autoconf_archive.tar.xz
cd $autoconf_archive
./configure --prefix=/usr
make -j $(nproc)
sudo make install
```

FYI 16.04 is EOL in April.
