### ISSUE TITLE
windows build for libtss2-tctildr

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#1453]
can't merge code w/o support for windows too

**Comment by AndreasFuchsSIT** [comment]
So far, we only supported TBS as default or a self-initialized tcti for windows. At least for feature-parity, we wouldn't need Windows support in the first iteration.

**Comment by flihp** [comment]
Our supported configuration for windows won't change here: no dynamic loading (LoadLibrary), only direct linking to TBS & MSSIM TCTIs. Still gotta implement the VS build stuff to build the TctiLdr library and remove bits from the esys build.

**Comment by flihp** [comment]
fixes for this are spread across #1470
