### ISSUE TITLE
Cannot make the build as described in ibmtpm.doc

### ISSUE THREAD

**Issue by EuclidGH** [tpm2-software/tpm2-tss#1469]
**In file included from TpmBuildSwitches.h:74,
                 from Implementation.h:65,
                 from Tpm.h:66,
                 from CryptRand.c:62:
CryptRand.c: In function ‘CryptRandomStir’:
CompilerDependencies.h:145:34: error: ‘dfResult’ is used uninitialized in this function [-Werror=uninitialized]
 #   define  NOT_REFERENCED(x) (x = x)
                                                            ^
cc1: all warnings being treated as errors
make: *** [makefile:79: CryptRand.o] Error 1**

How can I fix it? I tried to follow code lines and find out the error of "dfResult" but without success.

**Comment by AndreasFuchsSIT** [comment]
Sorry, but you will have to ask at the ibmtpm project https://sourceforge.net/projects/ibmswtpm2/
