### ISSUE TITLE
3 integration tests failing on physical TPM

### ISSUE THREAD

**Issue by vmleti** [tpm2-software/tpm2-tss#1479]
Hi,

I am running the integration tests on the configured TPM device. Of the 60 tests, I am failing the following three:

test/integration/esys-clear-control.int
test/integration/esys-clockset.int
test/integration/esys-policy-nv-undefine-special.int

Is there any advice on what I can check to get these tests to pass? I am passing all of the unit tests. Please let me know if there is other information I can provide.

Thank you

**Comment by vmleti** [comment]
Hi,
My test-suite.log failed being generated. I have saved the output from my terminal below.


[tpm-integration-log.txt](https://github.com/tpm2-software/tpm2-tss/files/3433196/tpm-integration-log.txt)

**Comment by joholl** [comment]
The output of each test is written to a dedicated log file. You can find them in the same directory:

- test/integration/esys-clear-control.log
- test/integration/esys-clockset.log
- test/integration/esys-policy-nv-undefine-special.log

Could you post these instead?

**Comment by vmleti** [comment]
Yes, here they are!
Thank you
[esys-clear-control.log](https://github.com/tpm2-software/tpm2-tss/files/3436669/esys-clear-control.log)
[esys-clockset.log](https://github.com/tpm2-software/tpm2-tss/files/3436673/esys-clockset.log)
[esys-policy-nv-undefine-special.log](https://github.com/tpm2-software/tpm2-tss/files/3436677/esys-policy-nv-undefine-special.log)

**Comment by vmleti** [comment]
Thank you; I will download get the update
I am using an Ubuntu 16.04 VM with a vTPM
