### ISSUE TITLE
sapi and tcti not appearing in /usr/include

### ISSUE THREAD

**Issue by vmleti** [tpm2-software/tpm2-tss#1484]
Hi,

I have been seeing that people are able to do #include <sapi/tpm20.h> and similarly #include <tcti/...> in their .c files because folders "sapi" and "tcti" are in /usr/include. I have installed this tss library, but is there anything I need to do additionally so that I can find sapi and tcti in /usr/include?

Thank you very much

**Comment by AndreasFuchsSIT** [comment]
Those include files are very very old and very wrong... ;-)

Since version 2.0, we have everything under /usr/include/tss2
