### ISSUE TITLE
test: Create test for async esys calls

### ISSUE THREAD

**Issue by joholl** [tpm2-software/tpm2-tss#1487]
There are tests for the **synchronous** esys calls which in turn call their async equivalents. Nonetheless, we should be testing the **asynchronous** behavior, as well. I think one test with a few calls should suffice.

In particular, we should test the behavior when you call sync/async sys/esys functions right after an async call.

**Comment by tstruk** [comment]
This is what FAPI tests do when configured with --enable_fapi_async_tests
