### ISSUE TITLE
TPM2B_PRIVATE_KEY_RSA key size of (TPM2_MAX_RSA_KEY_BYTES * 5) / 2?

### ISSUE THREAD

**Issue by pdxjohnny** [tpm2-software/tpm2-tss#1490]
It looks like the spec also has a note (2) on `TPM2B_PRIVATE_KEY_RSA->buffer` being able to be `(TPM2_MAX_RSA_KEY_BYTES * 5) / 2`. Is this something that should be considered in the `tpm2_types.h`?

https://github.com/tpm2-software/tpm2-tss/blob/18d98012d6e007398a76354ffe43f0ca23faff83/include/tss2/tss2_tpm2_types.h#L1416-L1420

![image](https://user-images.githubusercontent.com/5950433/62580778-ee3caf80-b85b-11e9-817b-2c49a6cc604b.png)

**Comment by tstruk** [comment]
On 8/6/19 3:13 PM, John Andersen wrote:
> It looks like the spec also has a note (2) on |TPM2B_PRIVATE_KEY_RSA->buffer| being able to be |(TPM2_MAX_RSA_KEY_BYTES * 5) / 2|. Is this something that should be considered in the |tpm2_types.h|?

It is already there. See #def TPM2_PRIVATE_VENDOR_SPECIFIC_BYTES
and the definition of struct TPM2B_PRIVATE_VENDOR_SPECIFIC.

-- 
Tadeusz

**Comment by pdxjohnny** [comment]
Ah okay, thanks!
