### ISSUE TITLE
Skip and Failed tests due to "Received TPM Error" and "Device or Resource Busy"

### ISSUE THREAD

**Issue by vmleti** [tpm2-software/tpm2-tss#1491]
Hello,

I am setting up this library on a Ubuntu 16.04 machine and I have tests failing or skipped due to "Received TPM Error" and "Device or Resource Busy". Please note that I am running "make -j$(nproc) check" with sudo.

Attached is my log from the tests.

Any help or advice would be greatly appreciated.

[test-suite.log](https://github.com/tpm2-software/tpm2-tss/files/3494354/test-suite.log)

**Comment by tstruk** [comment]
Hi @vmleti you can not run parallel tests on /dev/tpm0. The tpm driver will not allow this.
See: the note at the end of https://github.com/tpm2-software/tpm2-tss#running-tests-on-physical-tpm-device
