### ISSUE TITLE
duplicated test case in test/unit/tcti-device.c

### ISSUE THREAD

**Issue by liuqun** [tpm2-software/tpm2-tss#1495]
It seems that the test case `tcti_device_transmit_success()` was run twice during unit testing:
https://github.com/tpm2-software/tpm2-tss/blob/3440cdeb6b5a3233d45fbb47e7de2f141405e5bb/test/unit/tcti-device.c#L373-L378

**Comment by tstruk** [comment]
Looks like a copy&paste issue.
