### ISSUE TITLE
TPM factory reset functionality

### ISSUE THREAD

**Issue by lubo-svk** [tpm2-software/tpm2-tss#1507]
Hello, 
this is not an issue related directly to the library but more to the missing TPM 2.0 documentation.
I'm trying to implement factory reset functionality one will use if the password's for TPM are lost. The same functionality that is on PC's in BIOS.  I was asking this question directly our TPM manufacturer but I didn't get any response.
We have a custom Yocto Linux build using Infineout TPM's. 
I'm trying to find someone here to point me in the right direction.
Thanks

**Comment by tstruk** [comment]
Have you tried using tpm2_clear command?

**Comment by lubo-svk** [comment]
Hi, the tpm2_clear would do the trick if you know the lockout password. If you look at the implementation [tpm2_clear](https://github.com/tpm2-software/tpm2-tools/blob/d2cf40237ba5f617e2b1650c135df092acd682e8/tools/tpm2_clear.c#L69) you can see that the lockout password is required. Does it mean then that if the lockout password is set there is no way to clear the TPM without setting knowing the password?

**Comment by diabonas** [comment]
If you want to replicate the way the firmware uses to clear the TPM, you should operate on the platform hierarchy instead of the lockout hierarchy (the latter is the default for tpm2_clear). So `tpm2_clear -c platform` should work provided that the platform authorisation hasn't been set earlier in the boot process.

**Comment by lubo-svk** [comment]
I don't understand what does it mean: 

> platform authorization hasn't been set earlier in the boot process

Does it mean that I should set up the TPM in a way that it should be possible to use tpm2_clear when the PCR0 register equals 0?

What I read and understand so far is that I can create an object with authorization tied to the PCR0 equals to 0 and during the boot process I can read this object and use it for authorization. But this solution seems a little bit over-engineered to me :)

**Comment by diabonas** [comment]
No, what I mean is that if you control the boot process, you should be able to use `tpm2_clear -c platform` without any authorisation to clear the TPM. To prevent the user from doing the same on the running system, you would then set the platform authorisation yourself using `tpm2_changeauth -c platform <passphrase>`. Ideally you should use a high-entropy random value as the passphrase to avoid having a static string that the user can possibly exfiltrate from the firmware.

**Comment by lubo-svk** [comment]
Does it mean then that the platform password is cleared on every boot cycle? I didn't find this information in any documentation.

**Comment by diabonas** [comment]
See the [Trusted Platform Module Library Family "2.0" Specification - Part 2: Structures, Revision 1.38](https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-1-Architecture-01.38.pdf#page=92), Section 13.3:

> On TPM Reset or TPM Restart, *platformAuth* is set to an EmptyAuth, and *platformPolicy* is set to an Empty Policy.

**Comment by lubo-svk** [comment]
Ok, thanks for your help and explanation. It works now.
