### ISSUE TITLE
C++ dependency even when fuzzing is no

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tss#1508]
`AC_PROG_CXX` is included even when fuzzing is not enabled. I only see C++ required support for the fuzzing tests. Can we move this out and conditionally include it for fuzzing only? Introduced by @pdxjohnny  in 4eab6da6bb87.

**Comment by pdxjohnny** [comment]
Ah yes for sure. I didn't think about segmenting the compiler too at the time

**Comment by casantos** [comment]
This is causing build failures on Buildroot:

http://autobuild.buildroot.net/results/13f5e37b47b255da4158bec34e5459136f7e60d4
http://autobuild.buildroot.net/results/1c26db2509c79e00c0de1165945277eaa57b149f
http://autobuild.buildroot.net/results/b7b6b7b7aca79e847b442cbd2305427d91fe5d70
http://autobuild.buildroot.net/results/1cd5a82a0e799aa5027e2e2c03b246332cc3a15d
http://autobuild.buildroot.net/results/d7ec878907f714377c83e9a496e97cbf9382d787
http://autobuild.buildroot.net/results/1c7f0c1b3ce4871cd87bd6059b1f0a6dc4e74a9c
http://autobuild.buildroot.net/results/196b81d580325607c8da90beeb79e1f6b8ab8b47
http://autobuild.buildroot.net/results/f90f7b4ac710b56686635f8ae27059c11b963e47

**Comment by williamcroberts** [comment]
Reverted: https://github.com/tpm2-software/tpm2-tss/commit/60c26e4c4faba6ba12469485653e17092b510840
