### ISSUE TITLE
RFC: Gitter

### ISSUE THREAD

**Issue by joholl** [tpm2-software/tpm2-tss#1513]
Many newer repositories have their own [gitter](https://gitter.im) channel. It's basically an own chat channel for your repository (or namespace or anything) which you can link via badge. Take [keylime](https://github.com/keylime/keylime) for example with its gitter badge. They have a dedicated channel for their ecosystem. This would be a refreshing alternative to the mailing list.

What do you think?

**Comment by AndreasFuchsSIT** [comment]
+1 from me.
Heard Slack as alternative, but I like gitter's SSO with Github-ID...

**Comment by joholl** [comment]
If there are no objections, I suggest creating a Gitter channel and adding a badge to the README. Gitter does not let me do this with my GitHub account.

**Comment by AndreasFuchsSIT** [comment]
@tstruk You agree, then I'll open and PR...

**Comment by tstruk** [comment]
Sure, go ahead.

**Comment by AndreasFuchsSIT** [comment]
Ok, I cannot since I'm not admin of the tpm2-software namespace as a whole.
@tstruk I guess you'll have to create the gitter.
