### ISSUE TITLE
Implement ECC input parameter padding

### ISSUE THREAD

**Issue by joholl** [tpm2-software/tpm2-tss#1518]
I noticed that for some TPMs and some ECC keys, LoadExternal fails. I'll give an example for ECC P256  keys. The public key is a point on the curve which consists of two coordinates *x* and *y* which are 256 bit (or 32 byte) each. The private key is a scalar *a* with 256 bit (32 byte) as well.

The problem arises when one of these parameters *x*, *y* or *a* are small enough to have one or more leading zero bytes. In this case, the user can transmit a lower number of bytes to the TPM (e.g. 31 instead of 32 bytes). I discovered this because the tool `tpm_loadexternal` was failing on me in some cases if fed with openssl generated keys.

Unfortunately, padding is not very well defined in the spec. There is only [this](https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-1-Architecture-01.38.pdf#%5B%7B%22num%22%3A1706%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C70%2C300%2C0%5D) paragraph which basically states:

> When  ECC  parameters  are  input  parameters  to  the  TPM,  the  padding  is  optional

#### Loading an unpadded public key together with its private key 
If one coordinate *x* or *y* is unpadded and the corresponding private key is given, everything will work fine. (Tested for both simulator and SLM9670)

#### Loading an unpadded public key **without private key**
If one coordinate *x* or *y* is unpadded and the corresponding private key is **not** given, the TPM **MAY** return `TPM_RC_KEY`. This is documented in the [latest errata](https://trustedcomputinggroup.org/wp-content/uploads/TPM2.0-Library-Spec-v1.38-Errata_v1.8_for_publication_fixed_references.pdf#%5B%7B%22num%22%3A107%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C69%2C246%2C0%5D).

#### Loading an public key with an unpadded private key
I have not tested this. This is the most undocumented case.

#### Suggested solution
I suggest adding ECC input parameter padding for both public key coordinates as well as the private key to the TSS. That means if a ECC key parameter for a given curve is smaller than expected, leading zeros should be added. Personally, I would add that feature to the SAPI.

**Comment by AndreasFuchsSIT** [comment]
I'd add this to ESAPI, so SAPI does not alter any parameters. ESAPI already does.

**Comment by joholl** [comment]
Yes, that makes sense. I'll take a look into it and keep you updated.

**Comment by tstruk** [comment]
That shouldn't be SAPI not ESAPI, but tools. And it should be quite easy to do it in tools. Maybe something like this below ???
```
diff --git a/lib/tpm2_openssl.c b/lib/tpm2_openssl.c
index bbcff8a4..8a3d2ac3 100644
--- a/lib/tpm2_openssl.c
+++ b/lib/tpm2_openssl.c
@@ -722,13 +722,13 @@ static bool load_public_ECC_from_key(EC_KEY *k, TPM2B_PUBLIC *pub) {
         goto out;
     }
 
-    X->size = BN_bn2bin(x, X->buffer);
+    X->size = BN_bn2binpad(x, X->buffer, x_size);
     if (X->size != x_size) {
         LOG_ERR("Error converting X point BN to binary");
         goto out;
     }
 
-    Y->size = BN_bn2bin(y, Y->buffer);
+    Y->size = BN_bn2binpad(y, Y->buffer, y_size);
     if (Y->size != y_size) {
         LOG_ERR("Error converting Y point BN to binary");
         goto out;

```

**Comment by joholl** [comment]
I disagree. Your patch will solve the problem when parsing pem key files using the tools.

However, feeding the ESAPI with unpadded keys (without using the tools) leads to a problem which can and should be fixed. While your patch should probably be added to the tools, at the same time we should fix the ESAPI problem.

**Comment by tstruk** [comment]
I see your point, but if we start implicitly fixing input parameters under the API, especially in cases where it is not quite obvious in the specification what the parameters format should be, we may end up in bunch of backwards compatibility braking changes in the future. This should be fixed in the tools first and then if other users will run into the same issue we can point them at the tools example.

**Comment by joholl** [comment]
Hmm, I think I do not quite understand. I do not see where such a fix might break backwards compatibility. IMHO it does never hurt to pad ECC params that are too small in size.

If I understand you correctly, your point is that passing an 31-byte buffer to the ESAPI is an bug to begin with. However, passing unpadded parameters is indeed an option that is explicitly permitted by the Spec in _some_ cases. Implementing ECC param padding just eliminates any problems that might arise in the cases where is not well-defined (or where an error MAY be returned).

Correct me if I'm wrong but I see no good reason to pass a 31-byte buffer to the TPM when a 32-byte buffer is expected (according to the ECC curve) - even though it is works in some cases.

**Comment by joholl** [comment]
As @tstruk pointed out in #1527 there is indeed an issue with adding this to the ESAPI. Padding the public portion of the key changes its name from name<sub>unpadded</sub> to name<sub>padded</sub>. This might be a problem if the user assumes name<sub>unpadded</sub> because it is used to calculate authHMAC for the HMAC session.

Sorry for the inconvenience.
