### ISSUE TITLE
Revisit libtss2-tcti-default.so

### ISSUE THREAD

**Issue by diabonas** [tpm2-software/tpm2-tss#1525]
According to https://github.com/tpm2-software/tpm2-tss/issues/1482#issuecomment-516363966, `libtss2-tcti-default.so` is supposed to be set by distributions to the desired TCTI using an alternatives system. Since version 2.3.0, we [install `libtss2-tcti-default.so` by default as a symbolic link to `libtss2-tcti-device.so`](https://github.com/tpm2-software/tpm2-tss/pull/1486), so unless distributions take manual action, only the device TCTI will ever be used, even if tpm2-abrmd or a TPM simulator are available.

Apparently this change has not been picked up on by distributions: all the [distributions shipping tpm2-tss 2.3](https://repology.org/project/tpm2-tss/versions) I checked simply package the default symlink (sometimes split off in a separate development package). The only exception is Arch Linux, where we completely [remove the file](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/tpm2-tss&id=bb510aa72c60258d621aa36edc4574e11a1cfa5e#n34) since we don't have an alternatives system.

As a result of this decision, tpm2-abrmd is broken when `libtss2-tcti-default.so` is installed since it will never be used by default. This causes downstream problems, see https://github.com/fwupd/fwupd/pull/1397#issuecomment-534976663.

Since we already have an [auto-detection mechanism](https://github.com/tpm2-software/tpm2-tss/blob/master/src/tss2-tcti/tctildr-dl.c#L33-L54) in place that does the thing most people want (if `libtss2-tcti-default.so` exists, use it, otherwise try tpm2-abrmd, direct device access and the simulator in order), I suggest removing `libtss2-tcti-default.so` from the default installation: it is great to be able to be able to configure a fixed TCTI in this way, but most people are not aware of this option and will be taken aback if tpm2-abrmd doesn't work out of the box with the default installation.

**Comment by tstruk** [comment]
Don't the distros do whatever suits them anyway? Don't they use custom post-install .deb or .rpm hooks to adjust whatever gets installed?

**Comment by diabonas** [comment]
Distributions certainly have control over the files that get packaged, but most will simply distribute the files installed by `make install` by default. Usually this is a good thing since it keeps the distro packages close to a "plain" installation, which makes it easier to reproduce problems reported downstream.

But even for a manual installation, I don't see the benefit of installing `libtss2-tcti-default.so` for everybody: having the file means users are forced to use `/dev/tpm0` by default (not even the more convenient `/dev/tpmrm0`), if they want to use tpm2-abrmd instead or don't have a TPM at all and need to use the simulator, they will have to get active themselves and modify the symlink. IMHO the existing auto-detection mechanism is what most users want and expect. `libtss2-tcti-default.so` is useful if you know what you're doing and want to fix a specific TCTI, but in this case you can easily create the symlink yourself.
