### ISSUE TITLE
Could not load tcti, got: "(null)"

### ISSUE THREAD

**Issue by homepods** [tpm2-software/tpm2-tss#1530]
I am using Arch Linux with latest update. 
Before everything worked perfectly. Now I have errors.

For some reason, **TCTI** when fired in the initramfs and udev, it doens't seem to work anymore. After loading the kernel (with a backup key) I can unseal the key but not the udev.
I have all the rules set and exported the variable.

> export TPM2TOOLS_TCTI="device:/dev/tpm0"

```
ERROR:tcti:src/tss2-tcti/tcti-device.c:439:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpmrm0: No such file or directory
WARNING:tcti:src/tss2-tcti/tctildr.c:62:tcti_from_init() TCTI init for function 0x7f36914deec0 failed with a000a 
WARNING:tcti:src/tss2-tcti/tctildr.c:92:tcti_from_info() Could not initialize TCTI named: tcti-device 
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:150:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-device.so.0 
ERROR:tcti:src/tss2-tcti/tcti-device.c:439:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: No such file or directory 
WARNING:tcti:src/tss2-tcti/tctildr.c:62:tcti_from_init() TCTI init for function 0x7f36914deec0 failed with a000a 
WARNING:tcti:src/tss2-tcti/tctildr.c:92:tcti_from_info() Could not initialize TCTI named: tcti-device 
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:150:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-device.so.0 
WARNING:tcti:src/tss2-tcti/tctildr.c:62:tcti_from_init() TCTI init for function 0x7f36914df2d0 failed with a000a 
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:248:tctildr_get_default() No standard TCTI could be loaded 
ERROR:tcti:src/tss2-tcti/tctildr.c:418:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI 
ERROR: Could not load tcti, got: "(null)"
```

**Comment by diabonas** [comment]
> export TPM2TOOLS_TCTI="device:/dev/tpm0"

That doesn't appear to have worked properly, the error message
> ```
> ERROR: Could not load tcti, got: "(null)"
> ```
indicates that `TPM2TOOLS_TCTI` isn't set as far as tpm2-tools are concerned.

Furthermore
> ```
> ERROR:tcti:src/tss2-tcti/tcti-device.c:439:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: No such file or directory 
> ```
means that your TPM isn't available in the initramfs. I suspect you forgot to include the appropriate drivers: when using Arch and mkinitcpio, you need something like `add_all_modules /tpm/` in your install hook, see e.g. tpm2-totp for an [example](https://github.com/tpm2-software/tpm2-totp/blob/a144c275678e080f5d81dfc65fbcdeef2108d7ef/dist/initcpio/install/tpm2-totp.in#L11).

Anyway, this is not a bug in tpm2-tss, but a support question regarding tpm2-tools and should be directed to the [TPM2 mailing list](https://lists.01.org/mailman/listinfo/tpm2).

**Comment by homepods** [comment]
@diabonas Thanks for your reply. 
Well, I still believe it's a bug but I don't know in what order. **Is the Linux Kernel, or the tss?**

I have passed many times this loop but it seemed a black hole. Just freezing and moved forward didnt know why. Now after you suggested, increased my confidence and moved forward. 

After more research, I found a solution to add `rng_core.default_quality=1000` in the kernel initrd.
The whole confing makes no sense now, as I pass kernel variables that I don't really understand.

Can we make these updates somehow more inclusive so that code is consistent? I mean can we look to develop using an genomic architecture where A=BCDEF..... so we can keep variablle options more consistent throughtout updates? Whey do we often end up in having different handlers for variables which do the same thing????

**Comment by diabonas** [comment]
> Well, I still believe it's a bug but I don't know in what order. **Is the Linux Kernel, or the tss?**

In order to access the TPM, you need to have the appropriate kernel modules loaded. An initramfs is a minimal environment where only necessary modules are included to save space and increase speed. If you want to use certain devices, you therefore need to add these modules yourself. This is well-documented, see e.g. the [mkinitcpio man page](http://jlk.fjfi.cvut.cz/arch/manpages/man/mkinitcpio.8.en), neither tpm2-tss nor the Linux kernel (nor mkinitcpio) are to blame for this.

> After more research, I found a solution to add `rng_core.default_quality=1000` in the kernel initrd.

That has absolutely nothing to do with the error you showed above: this option initialises the pool faster, which might be necessary to make the tpm2-tools commands run *faster* during early boot, see e.g. https://github.com/tpm2-software/tpm2-tools/issues/1760. The error above indicated that tpm2-tools couldn't be run *at all* since no TPM to connect to was available.

> Can we make these updates somehow more inclusive so that code is consistent? I mean can we look to develop using an genomic architecture where A=BCDEF..... so we can keep variablle options more consistent throughtout updates? Whey do we often end up in having different handlers for variables which do the same thing????

I don't know what you mean by that: `rng_core.default_quality=1000` is an option of the Linux kernel, not part of the tpm2-software project in any way.

**Comment by Tsingv** [comment]
In mkinitcpio.conf, add "tpm_tis tpm_tis_core" to MODULES. Works for me.
