### ISSUE TITLE
Bring Tss2_Sys_ReadClock() upto the Rev 1.38 specs.

### ISSUE THREAD

**Issue by tstruk** [tpm2-software/tpm2-tss#1534]
In Rev 1.38 both audit or encrypt are allowed.

**Comment by AndreasFuchsSIT** [comment]
This is not fixed yet.
The header of SAPI needs to be extended by auth-arrays...

See:
https://github.com/tpm2-software/tpm2-tss/blob/master/include/tss2/tss2_sys.h#L1788-L1797

**Comment by tstruk** [comment]
@AndreasFuchsSIT right, Thanks for the reminder :+1: 
see https://github.com/tpm2-software/tpm2-tss/pull/1663
