### ISSUE TITLE
Outdated TCTI man pages

### ISSUE THREAD

**Issue by joholl** [tpm2-software/tpm2-tss#1540]
The man pages [tss2-tcti-device](https://github.com/tpm2-software/tpm2-tss/blob/master/man/tss2-tcti-device.7.in) and [tss2-tcti-mssim](https://github.com/tpm2-software/tpm2-tss/blob/master/man/tss2-tcti-mssim.7.in) seem to contain outdated information. For instance, the stack is called `Intel "TPM2 Software Stack"` the mssim is `tcti-socket`. Additionally, those are the only TCTI man pages.

Are the TCTI man pages still a thing? If so, we should update them.  Also, we should write man pages for the other TCTI modules.

**Comment by tstruk** [comment]
The only other one is tcti-tbs, which is windows specific, thus it has no man page.
Will update the mssim and device.

**Comment by joholl** [comment]
Oh right, thank you for clarification.

**Comment by AndreasFuchsSIT** [comment]
Man-pages for device and mssim would be nice. Maybe we can update them with the swtpm-content after merging that... :-)

**Comment by tstruk** [comment]
With these:
man/tss2-tcti-device.7.in
man/tss2-tctildr.7.in
man/tss2-tcti-mssim.7.in
man/tss2-tcti-swtpm.7.in
we should have everything covered.
