### ISSUE TITLE
Failed to start TPM2 Access Broker and Resource Management Daemon

### ISSUE THREAD

**Issue by dino99** [tpm2-software/tpm2-tss#1541]
From Ubuntu Focal : systemd 243-2ubuntu1 & tpm2-abrmd 2.2.0-1

That error is flooding  the journal log, and slow down the network url resolution.
Digging that issue, that link gave me explanation and solution:
https://www.reddit.com/r/linuxquestions/comments/dhinl0/what_is_tpm2abrmdservice_and_why_does_it_try_fail/

so i've checked my hardware:
ls /dev | grep tpm0 ===> nothing found; so going to disable that service

sudo systemctl disable tpm2-abrmd.service
[sudo] password for oem:
Synchronizing state of tpm2-abrmd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable tpm2-abrmd
Removed /etc/systemd/system/multi-user.target.wants/tpm2-abrmd.service.

After restarting the session, the error is no more logged, and url network resolution is now as fast as it have to.

That is a workaround to stop the logging flood and restore a fast network.

**Comment by AndreasFuchsSIT** [comment]
Looks like a bug for https://github.com/tpm2-software/tpm2-abrmd
Maybe @flihp may want to have a look.

My initial guess is that this is about the service-file reuesting restarts on failure. If no tpm0 is found it should probably not restart.

**Comment by flihp** [comment]
I haven't been able to find a way to tell systemd that a failure isn't recoverable. Had another report of this here: https://github.com/tpm2-software/tpm2-abrmd/issues/661. The most sane thing I can come up with is to disable the autorestart systemd stuff. Any better suggestions?

**Comment by AndreasFuchsSIT** [comment]
@dino99 Please refer to the linked issue over at tpm2-abrmd
@flihp Posted some ideas over there...
