### ISSUE TITLE
2.3.1 release tarball does not contain bootstrap script

### ISSUE THREAD

**Issue by mou** [tpm2-software/tpm2-tss#1543]
Steps to reproduce:
1. Download 2.3.1 release tarball from "Releases" section of this repository
2. Unpack archive
3. cd into created dirictory. ls bootstrap

**Comment by diabonas** [comment]
When building from a release tarball, you can skip running `bootstrap` and directly use `configure` since the necessary files have already been generated.

**Comment by mou** [comment]
Thanks for clarification. But should this be  mentioned in docs?

Also it's a little complicates creating debian packages. Because existing packages uses bootstrap for dh_autoreconf. So for anybody who wants to build updated package from upstream there are two options: 1) figure out how to alter debian nuild rules 2) create orig upstream tarball from git checkout to preserve bootstrap

**Comment by mou** [comment]
sorry, i was wrong. updated deb packages does not rely on bootstrap
