### ISSUE TITLE
test/unit/tctildr fails on s390x

### ISSUE THREAD

**Issue by superm1** [tpm2-software/tpm2-tss#1547]
Version 2.3.1 of tpm2-tss was recently uploaded into Debian unstable and this particular unit test is failing the test suite on the s390x architecture.  It passes on other architectures.

```
[==========] Running 24 test(s).
[ RUN      ] tcti_from_init_null_init
[       OK ] tcti_from_init_null_init
[ RUN      ] tcti_from_init_init_fail
WARNING:tcti:src/tss2-tcti/tctildr.c:50:tcti_from_init() TCTI init for function 0x2aa2f6017c0 failed with 6134 
[       OK ] tcti_from_init_init_fail
[ RUN      ] tcti_from_init_calloc_fail
ERROR:tcti:src/tss2-tcti/tctildr.c:56:tcti_from_init() Memory allocation for tcti failed: Success 
[       OK ] tcti_from_init_calloc_fail
[ RUN      ] tcti_from_init_second_init_fail
WARNING:tcti:src/tss2-tcti/tctildr.c:62:tcti_from_init() TCTI init for function 0x2aa2f6017c0 failed with 6134 
[       OK ] tcti_from_init_second_init_fail
[ RUN      ] tcti_from_init_success
[       OK ] tcti_from_init_success
[ RUN      ] tcti_from_info_info_null
ERROR:tcti:src/tss2-tcti/tctildr.c:83:tcti_from_info() TCTI info function failed 
[       OK ] tcti_from_info_info_null
[ RUN      ] tcti_from_info_info_fail
WARNING:tcti:src/tss2-tcti/tctildr.c:50:tcti_from_init() TCTI init for function 0x2aa2f6017c0 failed with 6134 
WARNING:tcti:src/tss2-tcti/tctildr.c:92:tcti_from_info() Could not initialize TCTI named: (null) 
[       OK ] tcti_from_info_info_fail
[ RUN      ] tcti_from_info_success
[       OK ] tcti_from_info_success
[ RUN      ] test_conf_parse_null
ERROR:tcti:src/tss2-tcti/tctildr.c:122:tctildr_conf_parse() 'name_conf' param may NOT be NULL 
[       OK ] test_conf_parse_null
[ RUN      ] test_conf_parse_bad_length
[  ERROR   ] --- Test failed with exception: Segmentation fault(11)
[  FAILED  ] test_conf_parse_bad_length
[ RUN      ] test_conf_parse_empty_str
[       OK ] test_conf_parse_empty_str
[ RUN      ] test_conf_parse_no_colon
[       OK ] test_conf_parse_no_colon
[ RUN      ] test_conf_parse_name_colon
[       OK ] test_conf_parse_name_colon
[ RUN      ] test_conf_parse_name_colon_conf
[       OK ] test_conf_parse_name_colon_conf
[ RUN      ] tctildr_init_ex_null_test
[       OK ] tctildr_init_ex_null_test
[ RUN      ] tctildr_init_null_test
[       OK ] tctildr_init_null_test
[ RUN      ] tctildr_init_conf_fail_test
[  ERROR   ] --- Test failed with exception: Segmentation fault(11)
[  FAILED  ] tctildr_init_conf_fail_test
[ RUN      ] tctildr_init_ex_default_fail
ERROR:tcti:src/tss2-tcti/tctildr.c:418:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI 
[       OK ] tctildr_init_ex_default_fail
[ RUN      ] tctildr_init_ex_from_file_fail
ERROR:tcti:src/tss2-tcti/tctildr.c:418:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI 
[       OK ] tctildr_init_ex_from_file_fail
[ RUN      ] tctildr_init_ex_calloc_fail_test
[       OK ] tctildr_init_ex_calloc_fail_test
[ RUN      ] tctildr_init_ex_success_test
[       OK ] tctildr_init_ex_success_test
[ RUN      ] tctildr_finalize_null_ref_test
[       OK ] tctildr_finalize_null_ref_test
[ RUN      ] tctildr_finalize_null_ctx_test
[       OK ] tctildr_finalize_null_ctx_test
[ RUN      ] tctildr_finalize_test
[       OK ] tctildr_finalize_test
[==========] 24 test(s) run.
[  PASSED  ] 22 test(s).
[  FAILED  ] 2 test(s), listed below:
[  FAILED  ] test_conf_parse_bad_length
[  FAILED  ] tctildr_init_conf_fail_test

 2 FAILED TEST(S)
FAIL test/unit/tctildr (exit status: 2)
```

Full build log is available here: https://buildd.debian.org/status/fetch.php?pkg=tpm2-tss&arch=s390x&ver=2.3.1-1&stamp=1573411429&raw=0

**Comment by superm1** [comment]
FWIW I set up a chroot using `qemu-user-static` and wasn't reproducing this on the `master` branch, but did on `2.3.x` branch.  I did a bunch of bisecting and kept finding really weird root commits like ee0a6ca390b6236b5505c315067055ee19828b27 being the cause.  I finally convinced myself it's not a code caused problem but a compiler induced problem and decided to look at compile flags on `2.3.x` vs `master`.

The 2.3.x build was getting compiled with `-D_FORTIFY_SOURCE=2` and `-O2`.  I tried to modify some flags on the master build to make it fail too the same way.

Sure enough adding `-O2` to `src/tss2-tcti/tctildr.c` causes the exact same failure:
```
# make -j16 test/unit/tctildr V=1
# gcc -DHAVE_CONFIG_H -O2 -I.     -I./src -I./include/tss2 -I./test/fuzz/tcti -std=c99 -Wall -Wextra -Wformat-security -Werror -fstack-protector-all -fpic -fPIC -Wno-missing-braces -Wstrict-overflow=5    -I./src/tss2-mu -I./src/tss2-sys -I./src/tss2-esys -Wno-unused-parameter -Wno-missing-field-initializers -g -MT src/tss2-tcti/test_unit_tctildr-tctildr.o -MD -MP -MF src/tss2-tcti/.deps/test_unit_tctildr-tctildr.Tpo -c -o src/tss2-tcti/test_unit_tctildr-tctildr.o `test -f 'src/tss2-tcti/tctildr.c' || echo './'`src/tss2-tcti/tctildr.c
# make -j16 test/unit/tctildr V=1
# ./test/unit/tctildr
```

Recompiling without `-O2` fixes it.

**Comment by superm1** [comment]
Oh!  I think I know why it root caused to that commit...

```
AX_IS_RELEASE(dash-version)
AX_CHECK_ENABLE_DEBUG([info])
```
https://www.gnu.org/software/autoconf-archive/ax_is_release.html
https://www.gnu.org/software/autoconf-archive/ax_check_enable_debug.html

Sure enough, making this modification fixes 2.3.1.
```
diff --git a/configure.ac b/configure.ac
index f2661b69..a220ec58 100644
--- a/configure.ac
+++ b/configure.ac
@@ -4,7 +4,7 @@
 # All rights reserved.

 AC_INIT([tpm2-tss],
-        [2.3.1],
+        [2.3.1-test],
         [https://github.com/tpm2-software/tpm2-tss/issues],
         [],
         [https://github.com/tpm2-software/tpm2-tss])
```

**Comment by AndreasFuchsSIT** [comment]
hmmm... disabling optimization feels more like a workaround that a fix for the root cause...

Just a gut feeling that there is some uninitialized memory hidden in that test...

@flihp Could you have a look into the actual code, since you wrote it and figure out if there's something in there ?

**Comment by AndreasFuchsSIT** [comment]
Could you maybe run the test with `export TSS2_LOG=all+trace` ?
Or maybe run `libtool --mode=execute valgrind test/unit/tctildr` to see where exactly it segfaults ?

That should give use some more info on the flow...
Following the code, it seams that https://github.com/tpm2-software/tpm2-tss/blob/76641c1e6b016979973fead7a24bb8fca4ee8325/src/tss2-tcti/tctildr.c#L125 gets optimized away maybe, but I'm wondering why that may be the case ?

**Comment by superm1** [comment]
Unfortunately walking through with a debugger like `gdb` or `valgrind` isn't possible with `qemu-user-static` due to the missing ptrace system call support.

Running `export TSS2_LOG=all+trace` before the test doesn't yield anymore.  On 2.3.1:
```
[ RUN      ] test_conf_parse_bad_length
[  ERROR   ] --- Test failed with exception: Segmentation fault(11)
[  FAILED  ] test_conf_parse_bad_length
[ RUN      ] test_conf_parse_empty_str
debug:tcti:src/tss2-tcti/tctildr.c:120:tctildr_conf_parse() name_conf: ""
[       OK ] test_conf_parse_empty_str
[ RUN      ] test_conf_parse_no_colon
debug:tcti:src/tss2-tcti/tctildr.c:120:tctildr_conf_parse() name_conf: "foo"
debug:tcti:src/tss2-tcti/tctildr.c:136:tctildr_conf_parse() TCTI name: "foo"
[       OK ] test_conf_parse_no_colon
[ RUN      ] test_conf_parse_name_colon
debug:tcti:src/tss2-tcti/tctildr.c:120:tctildr_conf_parse() name_conf: "foo:"
debug:tcti:src/tss2-tcti/tctildr.c:147:tctildr_conf_parse() TCTI name: "foo"
[       OK ] test_conf_parse_name_colon
[ RUN      ] test_conf_parse_name_colon_conf
debug:tcti:src/tss2-tcti/tctildr.c:120:tctildr_conf_parse() name_conf: "foo:bar"
debug:tcti:src/tss2-tcti/tctildr.c:147:tctildr_conf_parse() TCTI name: "foo"
debug:tcti:src/tss2-tcti/tctildr.c:152:tctildr_conf_parse() TCTI conf: "bar"
[       OK ] test_conf_parse_name_colon_conf
[ RUN      ] tctildr_init_ex_null_test
[       OK ] tctildr_init_ex_null_test
[ RUN      ] tctildr_init_null_test
[       OK ] tctildr_init_null_test
[ RUN      ] tctildr_init_conf_fail_test
[  ERROR   ] --- Test failed with exception: Segmentation fault(11)
[  FAILED  ] tctildr_init_conf_fail_test
[ RUN      ] tctildr_init_ex_default_fail
```

Manually modifying and inserting a print statement before the first access to `name_conf` I can see it's first access causes the segfault in both those tests.  On 2.3.1 it's first access is a `LOG_DEBUG` statement.  In master it's `strlen()` (due to ffca561b2de43df0a9f7f9c0e717fca943f2c38b)

**Comment by AndreasFuchsSIT** [comment]
Sorry for bothering you thus much, but does backporting ffca561 to 2.3.1 solve your problem ?
Then I'd release 2.3.2 with this fixed...

**Comment by superm1** [comment]
No it doesn't, as I mentioned above it happens with the first call to strlen on master too if I turn on optimization.

**Comment by AndreasFuchsSIT** [comment]
If strlen() gets inline by -O2 and the --wrap is ignored during compilation, then that would be a pretty ugly gcc bug...
Sorry for being so hesitant, but -O0 just does not feel right to me...
Do you depend on -O0 for release or can we keep diving for the reason ?

**Comment by superm1** [comment]
>If strlen() gets inline by -O2 and the --wrap is ignored during compilation, then that would be a pretty ugly gcc bug...

The first access to `name_conf` in 2.3.1 via `LOG_DEBUG` (IE before `strlen`) call segfaults.  So that makes me wonder if this is actually _two_ separate problems related to optimization?

> Sorry for being so hesitant, but -O0 just does not feel right to me...
> Do you depend on -O0 for release or can we keep diving for the reason ?

Well we tried to carry the PR as a distro patch and it unfortunately it doesn't help because distro `CFLAGS` (`-g -O2`) get applied after the `-O0` and still cause the fail:
```
gcc -DHAVE_CONFIG_H -I.   -Wdate-time -D_FORTIFY_SOURCE=2  -I./src -I./include/tss2 -I./test/fuzz/tcti -O2 -std=c99 -Wall -Wextra -Wformat-security -fstack-protector-all -fpic -fPIC -Wno-missing-braces -Wstrict-overflow=5   -I./src/tss2-mu -I./src/tss2-sys -I./src/tss2-esys -Wno-unused-parameter -Wno-missing-field-initializers -O0 -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -c -o test/unit/tctildr-tctildr.o `test -f 'test/unit/tctildr.c' || echo './'`test/unit/tctildr.c
gcc -DHAVE_CONFIG_H -I.   -Wdate-time -D_FORTIFY_SOURCE=2  -I./src -I./include/tss2 -I./test/fuzz/tcti -O2 -std=c99 -Wall -Wextra -Wformat-security -fstack-protector-all -fpic -fPIC -Wno-missing-braces -Wstrict-overflow=5   -I./src/tss2-mu -I./src/tss2-sys -I./src/tss2-esys -Wno-unused-parameter -Wno-missing-field-initializers -O0 -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -c -o src/tss2-tcti/test_unit_tctildr-tctildr.o `test -f 'src/tss2-tcti/tctildr.c' || echo './'`src/tss2-tcti/tctildr.c
```
https://launchpadlibrarian.net/451273983/buildlog_ubuntu-focal-s390x.tpm2-tss_2.3.1-2_BUILDING.txt.gz

As it's just a unit test that passes in boundary conditions and only fails on one architecture that doesn't typically ship systems with physical tpms and only fails when optimized I'm not personally too invested in diving much deeper, but up to you :)

**Comment by superm1** [comment]
Also, it fails with `-O1` on master so it's definitely not the strlen optimization specifically.
```
# gcc -O1 -Q --help=optimizers  | grep strlen
  -foptimize-strlen                     [disabled]
# gcc -O2 -Q --help=optimizers  | grep strlen
  -foptimize-strlen                     [enabled]
```

**Comment by Ikke** [comment]
On Alpine Linux we face the same issue. This is the output of `libtool --mode=execute valgrind test/unit/tctildr`:

```
[ RUN      ] test_conf_parse_bad_length
==22663== Invalid read of size 1
==22663==    at 0x10B21C: tctildr_conf_parse (in /home/buildozer/aports/community/tpm2-tss/src/tpm2-tss-2.3.1/test/unit/tctildr)
==22663==    by 0x10A0D1: test_conf_parse_bad_length (in /home/buildozer/aports/community/tpm2-tss/src/tpm2-tss-2.3.1/test/unit/tctildr)
==22663==    by 0x4CC3619: ??? (in /usr/lib/libcmocka.so.0.7.0)
==22663==    by 0x4CC47BD: _cmocka_run_group_tests (in /usr/lib/libcmocka.so.0.7.0)
==22663==    by 0x1096B1: main (in /home/buildozer/aports/community/tpm2-tss/src/tpm2-tss-2.3.1/test/unit/tctildr)
==22663==  Address 0xf100d is not stack'd, malloc'd or (recently) free'd
==22663==
[  ERROR   ] --- Test failed with exception: Segmentation fault(11)
[  FAILED  ] test_conf_parse_bad_length
```
Please let me know if I need to provide more information.

**Comment by superm1** [comment]
> On Alpine Linux we face the same issue. This is the output of `libtool --mode=execute valgrind test/unit/tctildr`:
> 
> ```
> [ RUN      ] test_conf_parse_bad_length
> ==22663== Invalid read of size 1
> ==22663==    at 0x10B21C: tctildr_conf_parse (in /home/buildozer/aports/community/tpm2-tss/src/tpm2-tss-2.3.1/test/unit/tctildr)
> ==22663==    by 0x10A0D1: test_conf_parse_bad_length (in /home/buildozer/aports/community/tpm2-tss/src/tpm2-tss-2.3.1/test/unit/tctildr)
> ==22663==    by 0x4CC3619: ??? (in /usr/lib/libcmocka.so.0.7.0)
> ==22663==    by 0x4CC47BD: _cmocka_run_group_tests (in /usr/lib/libcmocka.so.0.7.0)
> ==22663==    by 0x1096B1: main (in /home/buildozer/aports/community/tpm2-tss/src/tpm2-tss-2.3.1/test/unit/tctildr)
> ==22663==  Address 0xf100d is not stack'd, malloc'd or (recently) free'd
> ==22663==
> [  ERROR   ] --- Test failed with exception: Segmentation fault(11)
> [  FAILED  ] test_conf_parse_bad_length
> ```
> 
> Please let me know if I need to provide more information.

Could you see if valgrind changes with https://github.com/tpm2-software/tpm2-tss/commit/ffca561b2de43df0a9f7f9c0e717fca943f2c38b on 2.3.1? That would confirm if there are actually two problems.

**Comment by AndreasFuchsSIT** [comment]
Ok, so here's the plan:
If this also does not work, we'll rewrite the unit test to use an actual string of length [MAX_PATH + 1] instead of wrapping strlen and let strlen do it job regularly.

**Comment by Ikke** [comment]
@superm1 @AndreasFuchsSIT I've applied that patch, and valgrind appears to still gives the same output.

**Comment by superm1** [comment]
@Ikke thanks for checking.  Then we're going with the changing the unit test approach.  New patch is here: https://github.com/tpm2-software/tpm2-tss/pull/1549 (1ce7209)

**Comment by Ikke** [comment]
Confirmed that the test is succeeding with that commit applied.
