### ISSUE TITLE
No effect from --with-tctidefaultconfig

### ISSUE THREAD

**Issue by jhealyt** [tpm2-software/tpm2-tss#1552]
I have recompiled tpm2-tss with:

    `--with-tctidefaultconfig=/dev/tpmrm0`

So then I get the OpenSSL library to retrieve 50 kB of random data using 'tcti-device'.

It takes OpenSSL a few seconds to retrieve those 50 kB, and so while that's happening, I try to do:

    tpm2_getrandom 8

This call to "tpm2_getrandom" fails with:

```
ERROR:tcti:src/tss2-tcti/tcti-device.c:440:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: Device or resource busy 
ERROR: tcti init allocation routine failed for library: "device" options: "(null)"
ERROR: Could not load tcti, got: "device"
```

so it seems that the aforementioned flag is having no effect.

I'm trying to force 'tcti-device' to use /dev/tpmrm0 instead of /dev/tpm0

**Comment by jhealyt** [comment]
Here's the full list of options I'm using:

TPM2_TSS_CONF_OPTS += --disable-tcti-mssim --with-tctidefaultmodule=libtss2-tcti-device.so --with-tctidefaultconfig=/dev/tpmrm0

**Comment by healy-tpk** [comment]
Note the 2nd line of the error:

`ERROR: tcti init allocation routine failed for library: "device" options: "(null)"`

It looks as though the string "/dev/tpmrm0" is not being passed to the tcti-device library (or maybe it is being passed, but on the other side it's not being parsed properly).

**Comment by jhealyt** [comment]
Ok I have managed to get all the tpm2 tools (e.g. tpm2_getrandom) to use "/dev/tpmrm0" by putting the following line in my "~/.profile" file:

` export TPM2TOOLS_TCTI="device:/dev/tpmrm0"`

. . .however tpm2-tss-engine is still using "/dev/tpm0" and I can't find any way to get it to use "/dev/tpmrm0" instead.

**Comment by AndreasFuchsSIT** [comment]
That's all kind of weird, since the code is here:
https://github.com/tpm2-software/tpm2-tss/blob/727fc47ea15941c29bac993c39fb1d2e5987f9ac/src/tss2-tcti/tctildr-dl.c#L176
https://github.com/tpm2-software/tpm2-tss/blob/727fc47ea15941c29bac993c39fb1d2e5987f9ac/src/tss2-tcti/tctildr-dl.c#L221
https://github.com/tpm2-software/tpm2-tss/blob/727fc47ea15941c29bac993c39fb1d2e5987f9ac/src/tss2-tcti/tctildr-dl.c#L223

Could you maybe post the config.h file from the tpm2-tss compilation ?

Also could you `export TSS2_LOG=tcti+debug` and search for "Attempting to initialize TCTI defined during compilation" ?

**Comment by jhealyt** [comment]
Here's config.h:

```
/* config.h.  Generated from config.h.in by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* DISABLE WEAK CRYPTO ALGORITHMS */
/* #undef DISABLE_WEAK_CRYPTO */

/* "The default TCTIs configuration string" */
#define ESYS_TCTI_DEFAULT_CONFIG "/dev/tpmrm0"

/* "The default TCTI library file" */
#define ESYS_TCTI_DEFAULT_MODULE "libtss2-tcti-device.so"

/* Define to 1 if you have the declaration of `cygwin_conv_path', and to 0 if
   you don't. */
/* #undef HAVE_DECL_CYGWIN_CONV_PATH */

/* Define if you have the GNU dld library. */
/* #undef HAVE_DLD */

/* Define to 1 if you have the `dlerror' function. */
#define HAVE_DLERROR 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define if you have the _dyld_func_lookup function. */
/* #undef HAVE_DYLD */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define if you have the libdl library or equivalent. */
#define HAVE_LIBDL 1

/* Define if libdlloader will be built on this platform */
#define HAVE_LIBDLLOADER 1

/* Define to 1 if you have the `gcrypt' library (-lgcrypt). */
/* #undef HAVE_LIBGCRYPT */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define if you have the shl_load function. */
/* #undef HAVE_SHL_LOAD */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strndup' function. */
#define HAVE_STRNDUP 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to the sub-directory where libtool stores uninstalled libraries. */
#define LT_OBJDIR ".libs/"

/* "Trace log level" */
#define MAXLOGLEVEL 6

/* Define if debugging is disabled */
#define NDEBUG 1

/* disable use of dlopen */
/* #undef NO_DL */

/* OpenSSL cryptographic backend */
#define OSSL 1

/* Name of package */
#define PACKAGE "tpm2-tss"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "https://github.com/tpm2-software/tpm2-tss/issues"

/* Define to the full name of this package. */
#define PACKAGE_NAME "tpm2-tss"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "tpm2-tss 2.3.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "tpm2-tss"

/* Define to the home page for this package. */
#define PACKAGE_URL "https://github.com/tpm2-software/tpm2-tss"

/* Define to the version of this package. */
#define PACKAGE_VERSION "2.3.1"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* TCTI ASYNC MODE */
/* #undef TCTI_ASYNC */

/* TCTI FOR DEV TPM */
#define TCTI_DEVICE 1

/* TCTI FOR FUZZING */
/* #undef TCTI_FUZZING */

/* TCTI FOR MS SIMULATOR */
/* #undef TCTI_MSSIM */

/* TCTI PARTIAL READ MODE */
/* #undef TCTI_PARTIAL_READ */

/* Enable extensions on AIX 3, Interix.  */
#ifndef _ALL_SOURCE
# define _ALL_SOURCE 1
#endif
/* Enable GNU extensions on systems that have them.  */
#ifndef _GNU_SOURCE
# define _GNU_SOURCE 1
#endif
/* Enable threading extensions on Solaris.  */
#ifndef _POSIX_PTHREAD_SEMANTICS
# define _POSIX_PTHREAD_SEMANTICS 1
#endif
/* Enable extensions on HP NonStop.  */
#ifndef _TANDEM_SOURCE
# define _TANDEM_SOURCE 1
#endif
/* Enable general extensions on Solaris.  */
#ifndef __EXTENSIONS__
# define __EXTENSIONS__ 1
#endif


/* Version number of package */
#define VERSION "2.3.1"

/* Define to 1 if on MINIX. */
/* #undef _MINIX */

/* Define to 2 if the system does not provide POSIX.1 features except with
   this defined. */
/* #undef _POSIX_1_SOURCE */

/* Define to 1 if you need to in order for `stat' and other things to work. */
/* #undef _POSIX_SOURCE */

```

**Comment by jhealyt** [comment]
I have managed to get everything working fine by changing the code I use to load the engine into LibOpenSSL. Previously I had:
`
ENGINE_ctrl(tpm2_engine, TPM2TSS_SET_TCTI, 0, "device", NULL)`

but I have changed it to:

`ENGINE_ctrl(tpm2_engine, TPM2TSS_SET_TCTI, 0, "device:/dev/tpmrm0", NULL)`

Note though, that I **_### should not have had to do this_**.

**Comment by AndreasFuchsSIT** [comment]
> ```
> /* "The default TCTIs configuration string" */
> #define ESYS_TCTI_DEFAULT_CONFIG "/dev/tpmrm0"
> 
> /* "The default TCTI library file" */
> #define ESYS_TCTI_DEFAULT_MODULE "libtss2-tcti-device.so"
> ```

So the correct values are set, but it still does not do what it shall ?
What does the logoutput say ?

Regarding the engine:
- It uses the tpm2-tss defaults firstly. I don't know why that's not working here
- It allows overriding those defaults with engine controls. That's totally the way to do this.

The point is why is it not working with the setting of the tcti in tpm2-tss...

**Comment by jhealyt** [comment]
> Also could you export TSS2_LOG=tcti+debug and search for "Attempting to initialize TCTI defined during compilation" ?

I did this, and there's nothing in the output that matches that string

**Comment by AndreasFuchsSIT** [comment]
Is "Attempting to connect using standard TCTI" instead part of the log ?

If so, then the `#ifdef` is in the wrong branch...

**Comment by jhealyt** [comment]
> Is "Attempting to connect using standard TCTI" instead part of the log ?
> If so, then the #ifdef is in the wrong branch...

Where would I find this log? It's not coming out of my build system anyway (I'm using buildroot for embedded Linux)

**Comment by diabonas** [comment]
> ` ENGINE_ctrl(tpm2_engine, TPM2TSS_SET_TCTI, 0, "device", NULL)`

The default configuration is only applied when no TCTI module is specified and the therefore the default module is used. You explicitly specified the "device" TCTI with no configuration options, so it is expected that an empty configuration string is used instead of `ESYS_TCTI_DEFAULT_CONFIG`. Try using
```
ENGINE_ctrl(tpm2_engine, TPM2TSS_SET_TCTI, 0, NULL, NULL)
```

**Comment by tstruk** [comment]
If this is still not working as expected please reopen this issue against tpm2-tss-engine
