### ISSUE TITLE
typos in struct tctis[]

### ISSUE THREAD

**Issue by chrisxjzhu** [tpm2-software/tpm2-tss#1553]
In src/tss2-tcti/tctildr-dl.c
```
    {
        .file = "libtss2-tcti-device.so.0",
        .conf = "/dev/tpmrm0",
        .description = "Access libtss2-tcti-device.s0 with /dev/tpmrm0",
    },
    {
        .file = "libtss2-tcti-device.so.0",
        .conf = "/dev/tpm0",
        .description = "Access libtss2-tcti-device.s0 with /dev/tpmrm0",
    },
```
Look at the two 'description' lines
1. Shouldn't it be '.so' instead of '.s0' ?
2. It should be '/dev/tpm0' in the second description line.

**Comment by AndreasFuchsSIT** [comment]
.so.0 should be ok, I guess, since .so are usually only installed with -dev packages on distros...
The 2. is true though...

**Comment by diabonas** [comment]
>     1. Shouldn't it be '.so' instead of '.s0' ?

This refers to <code>libtss2-tcti-device.s*0*</code> in the description (with a zero instead of an "o"), it should rather be `libtss2-tcti-device.so.0` indeed.
