### ISSUE TITLE
Small fixes for non Windows/Linux hosts

### ISSUE THREAD

**Issue by dmgstz** [tpm2-software/tpm2-tss#1555]
Wonder if it would be possible to get these two fixed, as they complicate porting this code to another platforms/compilers:

In tcti-common.c, please do not include unistd if the platform is not Windows, I mean the lines below:

#ifndef _WIN32
#include <unistd.h>
#endif

unistd is not an standard C header.

If the platfrom does not support POLLING, then make TSS2_TCTI_POLL_HANDLE an alias for void* instead of void:

typedef void TSS2_TCTI_POLL_HANDLE;

Otherwise esys_context.c complains about sizeof an uncomplete type (sizeof(void)).

*handles = calloc(*count, sizeof(TSS2_TCTI_POLL_HANDLE));

These are minor things, I really like the architecture so far, it would be appreciated if you fixed these small things, specially for people that are porting this code to other platforms! Thank you.

**Comment by AndreasFuchsSIT** [comment]
ok. PR welcome... ;-)

**Comment by AndreasFuchsSIT** [comment]
Fixed by #1866
