### ISSUE TITLE
Build errors while trying to build for solution file in Windows

### ISSUE THREAD

**Issue by bhupeshpant19jan** [tpm2-software/tpm2-tss#1558]
Hi, 

I am trying to build tpm2-tss on Windows with the latest SDK version and platform toolset but I am seeing multiple build errors. 
I cloned the project and opened the solution file and updated the Windows SDK version to **10.0.17763.0**  and Platform Toolset: **Visual Studio 2017 (v141)**. The SDK version that I am using is more updated from the one mentioned in the documentation. I don't see any harm in using more advanced toolset or SDK version.
![image](https://user-images.githubusercontent.com/5937254/69318446-0c070800-0bf2-11ea-987a-3f5b2dbb6a53.png)

As per the project build description for windows ([Link](https://github.com/tpm2-software/tpm2-tss/blob/master/INSTALL.md)), building the project with UCRT toolchain should be as simple as opening the solution file and building the project.

The build errors I am getting with all these configurations are basic coding errors that seem more compiler configuration-specific. 

![image](https://user-images.githubusercontent.com/5937254/69317813-a0706b00-0bf0-11ea-84cc-1aa0e609c1e7.png)

I think the documentation for windows builds is not updated. Please help me in fixing these errors or if you have the updated build steps please share.

Thanks!

**Comment by AndreasFuchsSIT** [comment]
So the only thing I can do is point you to our appveyor config:
https://github.com/tpm2-software/tpm2-tss/blob/1c99117f4d102fd465655ed86aca58909a13c10d/.appveyor.yml#L1-L15

**Comment by bhupeshpant19jan** [comment]
Hi @AndreasFuchsSIT, thanks for the reply.
I don't see any specific configuration in this yml file that could impact the build in the way I want.
I also cross-checked my yml and it looks exactly the same.

![image](https://user-images.githubusercontent.com/5937254/69366084-6a5fd500-0c4a-11ea-9e38-30e8cdea184d.png)

**Comment by tstruk** [comment]
You need to configure your VS environment to use the clang back-end. The default C compiler is not supported. Please follow the steps described here: https://devblogs.microsoft.com/cppblog/clang-llvm-support-in-visual-studio/

**Comment by bhupeshpant19jan** [comment]
I am able to compile using **Visual Studio 2017 - Clang with Microsoft CodeGen (v141_clang_c2)**.

**Comment by paulduongemail** [comment]
@bhupeshpant19jan Hi, have you build it successfully with v141_clang_c2?

**Comment by bhupeshpant19jan** [comment]
@paulduongemail , Yes I did. Please note it was with vs2017. 
In vs2019 they have given the clang plugin which is different from that of vs2017.
