### ISSUE TITLE
missing /dev/tpm0

### ISSUE THREAD

**Issue by treyweaver** [tpm2-software/tpm2-tss#1563]
I am running Ubuntu 18:04 Mate

I start the server as superuser:

> tpm_server &
> [1] 4079
> root@treys-IG-Server:~# TPM command server listening on port 2321
> Platform server listening on port 2322

Then I run:

> root@treys-IG-Server:~# tpm2-abrmd -o --tcti=mssim
> (process:4096): WARNING *: 11:47:15.114: tcti_conf before: "device:/dev/tpm0"
> (tpm2-abrmd:4096): WARNING *: 11:47:15.114: tcti_conf after: "mssim"
> Command IPv4 client accepted
> Platform IPv4 client accepted
> 

But /dev/tpm0 is missing; and so the tools do not run.  And my code that uses /dev/tpm0 won't run.

This is right out of the start guide.  Last week this was working.

**Comment by AndreasFuchsSIT** [comment]
The simulator is running on tcp and tcti=mssim connects via tcp.
/dev/tpm0 is only for hardware tpms.

The tools should be connecting to tpm2-abrmd via tcti=abrmd (which uses dbus internally).

Hope this helps.
