### ISSUE TITLE
tcti device default value vs tctildr load preference

### ISSUE THREAD

**Issue by joholl** [tpm2-software/tpm2-tss#1564]
The tctildr load preference is "first `/dev/tpm0` then `/dev/tpmrm0`.

https://github.com/tpm2-software/tpm2-tss/blob/d5cca2a51434c0d0fe7cf4237b161d498baed02d/src/tss2-tcti/tctildr-dl.c#L41-L50

However, when passing a `NULL` conf string to `Tss2_Tcti_Device_Init()`, the tcti-device chooses `/dev/tpm0` by default.

https://github.com/tpm2-software/tpm2-tss/blob/d5cca2a51434c0d0fe7cf4237b161d498baed02d/src/tss2-tcti/tcti-device.c#L62

For the tools, this means not specifying a tcti will result in using `/dev/tpmrm0` (assuming tabrmd is not installed) but passing `--tcti device`, will result in using `/dev/tpm0`. This is not what I would expect.

What do you think about having tcti-device try `/dev/tpmrm0` first and fallback to `/dev/tpm0` if a `NULL` conf string is passed to `Tss2_Tcti_Device_Init()`?

**Comment by AndreasFuchsSIT** [comment]
Agreed...
