### ISSUE TITLE
Tss2_MU_TPMU_ENCRYPTED_SECRET_Marshal and Tss2_MU_TPMU_ENCRYPTED_SECRET_Unmarshal not exported by libtss2-mu

### ISSUE THREAD

**Issue by whooo** [tpm2-software/tpm2-tss#1565]
Tss2_MU_TPMU_ENCRYPTED_SECRET_Marshal and Tss2_MU_TPMU_ENCRYPTED_SECRET_Unmarshal are not exported by libtss2-mu while they are defined in tss2_mu.h.
If libtss2-mu.so is not stripted the symbols are there:
$ readelf -Ws src/tss2-mu/.libs/libtss2-mu.so.0.0.0  | grep Tss2_MU_TPMU_ENCRYPTED_SECRET
   376: 0000000000033bc7   604 FUNC    LOCAL  DEFAULT   12 Tss2_MU_TPMU_ENCRYPTED_SECRET_Marshal
   388: 0000000000033e23   679 FUNC    LOCAL  DEFAULT   12 Tss2_MU_TPMU_ENCRYPTED_SECRET_Unmarshal
But after strip the symbols are no longer there.

Checked both the master branch and 2.3.1, same issue.

**Comment by AndreasFuchsSIT** [comment]
That's weird... PR welcome...
