### ISSUE TITLE
Problem mixing salted and unsalted sessions

### ISSUE THREAD

**Issue by dgptha** [tpm2-software/tpm2-tss#1574]
When mixing salted and unsalted sessions (StartAuthSession with and without the tpmKey parameter) we have found that if an unsalted session happens after a salted session commands executed in the unsalted session fail with an authorization failure. For example when performing a PCR_Event command in the unsalted session we get the following error:

```
WARNING:esys:src/tss2-esys/api/Esys_PCR_Event.c:295:Esys_PCR_Event_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_PCR_Event.c:100:Esys_PCR_Event() Esys Finish ErrorCode (0x000009a2) 
ERROR on line: "54" in file: "/home/tpm2/tpm2-lib/include/tpm2-lib/util/log.h": Esys_PCR_Event(0x9A2) - tpm:session(1):authorization failure without DA implications
```

During a quick and dirty debugging we have found that deleting the salt in the ESYS_CONTEXT (i.e., setting `ectx->salt.size = 0`) in between sessions allows us to mix salted and unsalted sessions. Solving the issue.

A high level description of the faulty scenario:

 1. StartAuthSession(salted)
 2. Perform TPM2 command (like the PCR_Event from the previous error)
 3. Flush Session
 4. StartAuthSession(unsalted)
 5. Perform TPM2 command <--- Fails here
 6. Flush Session

Deleting the salt between steps 3 and 4 solves the issue.

We are not even sure if this a bug or if we are using the tpm2-tss library wrong. Do we need to perform additional operations? Something more than just flushing the session?

Sorry, but right now we don't have a small program to demonstrate the problem. We are using tpm2-tss release 2.3.1.

Thanks for your help.

**Comment by tstruk** [comment]
Could you make sure that you pass ESYS_TR_NONE as the tpmKey param when you call Esys_StartAuthSession() to start the unsalted session. That should set the salt size to 0.

**Comment by dgptha** [comment]
Thanks for the answer. Unfortunately setting tpmKey to ESYS_TR_NONE doesn't work.

I set `TSS2_LOG` to `esys+TRACE` before launching the binary (i.e., launched as `TSS2_LOG=esys+TRACE ./my_binary`).
After execution of faulty scenario shown in my previous message I can see that when executing step 1 (starting a salted session) the tpmKey is set (`tpmKey=418369`):

`trace:esys:src/tss2-esys/api/Esys_StartAuthSession.c:194:Esys_StartAuthSession_Async() context=0x555a8b63dc20, tpmKey=418369, bind=fff,nonceCaller=(nil), sessionType=00, symmetric=0x7ffdd6dd9732,authHash=000b`

And in step 4 (starting an unsalted session) the tpmKey is set to ESYS_TR_NONE (`tpmKey=fff`):

`trace:esys:src/tss2-esys/api/Esys_StartAuthSession.c:194:Esys_StartAuthSession_Async() context=0x555a8b63dc20, tpmKey=fff, bind=fff,nonceCaller=(nil), sessionType=00, symmetric=0x7ffdd6dd9732,authHash=000b`

I tried to follow a little bit the implementation of `Esys_StartAuthSession` to see where the esys context salt was set. From what I could see it happens in `iesys_compute_encrypted_salt`. In that function we can see the following code executed when the `tpmKeyNode` is 0 (which means that `tpmKey` was set to ESYS_TR_NONE):

```
    if (tpmKeyNode == 0) {
        encryptedSalt->size = 0;
        return TSS2_RC_SUCCESS;
    }
```

My supposition is that there is an error here. Not only the `encryptedSalt` variable should be set to the empty buffer (`size = 0`), but also the esys context salt, effectively resetting it. Something like:

```
    if (tpmKeyNode == 0) {
        encryptedSalt->size = 0;
        esys_context->salt->size = 0; // reset esys_context salt
        return TSS2_RC_SUCCESS;
    }
```
If I'm not wrong this would force the behavior you describe. But again it's just a supposition. There might be better ways to solve the issue. For once, I don't understand why the salt remains in the esys context once we leave the session, i.e., I would expect the salt to be removed/reset once the auth session is flushed with `Esys_FlushContext`. But there might be a reason to keep that data.

**Comment by tstruk** [comment]
Looks to me like there is something left in the context making it "stateful".
Could you try reverting the other of steps 3 and 4. Something like this:

1 StartAuthSession(salted)
2 Perform TPM2 command (like the PCR_Event from the previous error)
3 StartAuthSession(unsalted)
4 Flush Session(salted)
5 Perform TPM2 command 
6 Flush Session(unsalted)

**Comment by tstruk** [comment]
Could you please verify if this issue still exist on the latest master. We have fixed some issues around authentication with Esys_StartAuthSession()

**Comment by dgptha** [comment]
I will try it shortly and let you know. I wanted to create an executable showing the problem I found, but didn't have the time. Hopefully I won't have to do it :)

**Comment by dgptha** [comment]
I tested with the master head commit f8fb4d15. Unfortunately the problem remains, nothing has changed. I will write a test I can exchange with you.

**Comment by tstruk** [comment]
That would be a big help. Thanks

**Comment by dgptha** [comment]
Here you can find a test program for the issue we are discussing.
I tested them against the master branch of tpm2-tss as requested.
The only difference between the two attached files is that in one you will have to execute the bootstrap script for compiling it and in the other (0.1.0) no.
You will find some instructions to build the test in the readme file inside the tars.

[tpm2-tss-bug.tar.gz](https://github.com/tpm2-software/tpm2-tss/files/4106167/tpm2-tss-bug.tar.gz)

[tpm2-tss-bug-0.1.0.tar.gz](https://github.com/tpm2-software/tpm2-tss/files/4106168/tpm2-tss-bug-0.1.0.tar.gz)

Hope this helps us to know if there is actually a bug in the tss library or it's just me using it wrong.
Let me know if you have any question.

**Comment by tstruk** [comment]
@dgptha yes, that was a bug in esys. The old salt value was still used in the _finish call to calculate session key, which shouldn't happen for an unsalted session. Instead of conditionally set the salt.size to zero in _Async call let's zero out the whole salt struct in the _finish call. PR #1610
