### ISSUE TITLE
BadAuth when calling StartAuthSession

### ISSUE THREAD

**Issue by ionut-arm** [tpm2-software/tpm2-tss#1590]
Hello,

While writing tests for a Rust wrapper of the ESAPI layer I've found that calling `Esys_StartAuthSession` always gets a BadAuth response code if any of the session parameters is used - regardless of whether the said session is set to encrypt/decrypt/audit/none of the above. 

You can see the wrapper code here: https://github.com/parallaxsecond/rust-tss-esapi/blob/master/src/lib.rs#L244

and the test code does the following:
```
        #[test]
        fn test_encrypted_start_sess() {
            let mut context = Context::new(Tcti::Mssim).unwrap();
            let encrypted_sess = context.start_auth_session(
                NO_SESSIONS,
                ESYS_TR_NONE,
                ESYS_TR_NONE,
                &[],
                TPM2_SE_HMAC,
                utils::TpmtSymDefBuilder::aes_256_cfb(),
                TPM2_ALG_SHA256,
            ).unwrap();
            let session_attr = utils::TpmaSession::new()
                .with_flag(TPMA_SESSION_DECRYPT)
                .with_flag(TPMA_SESSION_ENCRYPT) 
                .with_flag(TPMA_SESSION_AUDIT);                                                       
            context.set_session_attr(encrypted_sess, session_attr).unwrap();                          
                                                                                                      
            context.start_auth_session(                                                               
                (encrypted_sess, ESYS_TR_NONE, ESYS_TR_NONE),                                         
                ESYS_TR_NONE,                                                                         
                ESYS_TR_NONE,                                                                         
                &[],                                                                                  
                TPM2_SE_HMAC,                                                                         
                utils::TpmtSymDefBuilder::aes_256_cfb(),                                              
                TPM2_ALG_SHA256,                                                                      
            ).unwrap();                                                                               
        } 
```

I'm not sure if this is a problem in our code (or in the way I understand the `StartAuthSession` method), in the TSS stack or in the simulator (although I've tried with 3 different simulators - all of which might be using the same code underneath, though).
In the IBM simulator, the error is returned by in `CheckSessionHMAC`.

**Comment by AndreasFuchsSIT** [comment]
Do these sessions work on other commands where sessions are optional, such as GetRandom ?
This might give us a first hint.
Also, which version of esys do you use ?

**Comment by ionut-arm** [comment]
GetRandom seems to work correctly - getting `inconsistent attributes (associated with session number 1)` if a session without encrypt/decrypt/audit is used, but is successful otherwise.

I'm using version number 2.3.0, I believe. I can try updating to latest, just saw that 2.3.1 added some fixes for HMAC calculation for policy sessions.

**Comment by ionut-arm** [comment]
I've updated to 2.3.2 - still same response code.

**Comment by AndreasFuchsSIT** [comment]
Ok, I added a test for this: https://github.com/AndreasFuchsSIT/tpm2-tss/commit/ecaf027637d337c01cc3686a8b87c4701334eed6 and the code
https://github.com/AndreasFuchsSIT/tpm2-tss/blob/ecaf027637d337c01cc3686a8b87c4701334eed6/test/integration/esys-create-session-auth.int.c#L240-L263
does fail.

So this is a bug and must be fixed and backported.
