### ISSUE TITLE
Extracting ekPub and ekcert is failing in Windows

### ISSUE THREAD

**Issue by bhupeshpant19jan** [tpm2-software/tpm2-tss#1591]
We have written a cross-plat TPM library based on the TPM2-TSS library. Our TPM library is compiled for Linux and Windows. While in Linux it is working fine, it is failing in Windows. I am trying to extract ekPub and ekCert but I am getting following errors respectively.

```
`Processing Action: ekpub
ERROR:esys:esys_iutil.c:1086:esys_GetResourceObject() Error: Esys handle does not exist (70018).
ERROR:esys:api\Esys_ReadPublic.c:170:Esys_ReadPublic_Async() objectHandle unknown. ErrorCode (0x00070018)
ERROR:esys:api\Esys_ReadPublic.c:81:Esys_ReadPublic() Error in async function ErrorCode (0x00070018)
ERROR:esys:esys_tr.c:357:Esys_TR_Close() Error: Esys handle does not exist (70018).
WARN : File=d:\myworkingdirectory\private\attestation\linuxtpm\lib\tss2wrapper.cpp,Function=Tss2Wrapper::GetEkPub,Line=54 : GetEkPub : tpm2-tss exception : message=Failed to read public portion, code=458776
WARNING:esys:api\Esys_NV_ReadPublic.c:309:Esys_NV_ReadPublic_Finish() Received TPM Error
ERROR:esys:esys_tr.c:210:Esys_TR_FromTPMPublic_Finish() Error NV_ReadPublic ErrorCode (0x0000018b)
ERROR:esys:esys_tr.c:321:Esys_TR_FromTPMPublic() Error TR FromTPMPublic ErrorCode (0x0000018b)
WARNING:esys:api\Esys_NV_ReadPublic.c:309:Esys_NV_ReadPublic_Finish() Received TPM Error
ERROR:esys:esys_tr.c:210:Esys_TR_FromTPMPublic_Finish() Error NV_ReadPublic ErrorCode (0x0000018b)
ERROR:esys:esys_tr.c:321:Esys_TR_FromTPMPublic() Error TR FromTPMPublic ErrorCode (0x0000018b)
WARNING:esys:api\Esys_EvictControl.c:326:Esys_EvictControl_Finish() Received TPM Error
ERROR:esys:api\Esys_EvictControl.c:114:Esys_EvictControl() Esys Finish ErrorCode (0x0000014c)
ERROR:esys:esys_tr.c:357:Esys_TR_Close() Error: Esys handle does not exist (70018).
Error: tpm2-tss exception : message=Failed to persist EK in TPM NVRAM, code=332


D:\myWorkingDirectory\private\Attestation\LinuxTpm\x64\Debug\IntegrationTests_WindowsTPM.exe (process 22232) exited with code 1.
Press any key to close this window . . .`
```

I am seeing a first error from here,

```
    /* All objects with a TR-handle larger than ESYS_TR_MIN_OBJECT must have
       been initialized previously. Therefore the TR handle was erroneous. */
    if (esys_handle >= ESYS_TR_MIN_OBJECT) {
        LOG_ERROR("Error: Esys handle does not exist (%x).",
                  TSS2_ESYS_RC_BAD_TR);
        return TSS2_ESYS_RC_BAD_TR;
```

Here the esys_handle is coming **4137** which is greater than ESYS_TR_MIN_OBJECT (**4096**).  The handle value is created by logic present in TSS library. [here](https://github.com/tpm2-software/tpm2-tss/blob/7ef8c4168038320d664a159829a02cd188d8f66b/src/tss2-esys/esys_context.c#L78).
 
I am curious that while creating the new handle Tss library is using the following logic
 ```
/* Use random number for initial esys handle value to provide pseudo
       namespace for handles */
    (*esys_context)->esys_handle_cnt = ESYS_TR_MIN_OBJECT + (rand() % 6000000);
```
then what is the purposes of  below validation?
As per above logic the handle should always be b/w  ESYS_TR_MIN_OBJECT  and 6000000?

```
  /* All objects with a TR-handle larger than ESYS_TR_MIN_OBJECT must have
       been initialized previously. Therefore the TR handle was erroneous. */
    if (esys_handle >= ESYS_TR_MIN_OBJECT) {
        LOG_ERROR("Error: Esys handle does not exist (%x).",
                  TSS2_ESYS_RC_BAD_TR);
        return TSS2_ESYS_RC_BAD_TR;
```

**Comment by AndreasFuchsSIT** [comment]
Well, ESYS_TR handles are NOT tpm handles.

You have to call Esys_TR_FromTpmPublic to turn a tpm handle into an ESYS_TR handle.
If that's the error then I'm more curious why it's actually working on Linux.

If that's not the error, then your original code snipped that issues these errors would help.

________________________________

**Comment by bhupeshpant19jan** [comment]
I need more time to look into it to understand why it is working for Linux and failing for Windows.
While debugging I realized that the code is failing due to the missing object in the list.
If you take a look at this [line](https://github.com/tpm2-software/tpm2-tss/blob/7ef8c4168038320d664a159829a02cd188d8f66b/src/tss2-esys/esys_iutil.c#L1051), this line is 
trying to search the given command handle in the list, only if doesn't exist there it will fall to that check I mentioned earlier ( **if (esys_handle >= ESYS_TR_MIN_OBJECT)** ). Now I am trying to identify why the object goes missing from the **esys_context->rsrc_list**.
```
    /* The typical case is that we have a resource object already within the
       esys context's linked list. We iterate through the list and search
       for the corresponding object and return it if found.
       If no object is found, this can be an erroneous handle number or it
       can be because of a reference "global" object that does not require
       previous initialization. */
    for (esys_object_aux = esys_context->rsrc_list; esys_object_aux != NULL;
         esys_object_aux = esys_object_aux->next) {
        if (esys_object_aux->esys_handle == esys_handle) {
            *esys_object = esys_object_aux;
            return TPM2_RC_SUCCESS;
        }
    }
```

**Comment by AndreasFuchsSIT** [comment]
If you could provide us with a short test-case of what's failing ?
Then we could
- reproduce the bug
- fix the bug
- add the test to the test-suit...

**Comment by bhupeshpant19jan** [comment]
Sure, I am working on it, please give me some time. Thanks.

**Comment by bhupeshpant19jan** [comment]
I am able to address this issue  by going through the tss code and understanding how TSS_TR handles lifetime has to be maintained. the fix is done at my end to address the issue.
Thanks/
