### ISSUE TITLE
All operations fail with errno 1: Operation not permitted.

### ISSUE THREAD

**Issue by reanimus** [tpm2-software/tpm2-tss#1599]
Lately, it seems my TPM is no longer able to be accessed via any of the tpm2 commands. I've tried accessing via both tpm0 and tpmrm0 as both my regular user and root, and all return the same response for basically anything I try to do:

```
ERROR:tcti:src/tss2-tcti/tcti-device.c:290:tcti_device_receive() Failed to read response from fd 3, got errno 1: Operation not permitted 
ERROR:esys:src/tss2-esys/api/Esys_SelfTest.c:273:Esys_SelfTest_Finish() Received a non-TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_SelfTest.c:95:Esys_SelfTest() Esys Finish ErrorCode (0x000a000a) 
ERROR: Esys_SelfTest(0xA000A) - tcti:IO failure
ERROR: Unable to run tpm2_selftest
```

I'm running on Linux 5.4.13-gentoo and using the latest master. My laptop is a Dell XPS 9560.

**Comment by tstruk** [comment]
Could you check the version of your TPM in BIOS. It looks like there are some Dell specific issues with TPM in this platform: https://www.dell.com/community/XPS/XPS-9560-TPM-woes-again/td-p/6204784

**Comment by reanimus** [comment]
Well, I was on 1.12.1 (the version described on the page), but the error persists even after updating to 1.18.0. The TPM bug you describe was fixed in v1.16.0 according to https://fwupd.org/lvfs/devices/com.dell.uefi34578c72.firmware

**Comment by reanimus** [comment]
This looks like some sort of kernel regression.

I installed version 4.19.97 of the kernel and tried it out. It completed selftest successfully. I just updated back to 5.4.13 and the issue returned.

I'm not sure when this issue began specifically -- the earliest kernel with the gentoo patchsets in the 5.x series is 5.4.10, which still has the issue. I could possibly use some of the aufs5 kernels in gentoo (as it has the gentoo patches as well and also has a few more 5.x versions). It'll take me a bit to bisect it though.

**Comment by reanimus** [comment]
Nevermind, the latest aufs kernel (5.3.7) doesn't exhibit this behavior. So somewhere between 5.3.7 and 5.4.10, there was a change that breaks things.

**Comment by reanimus** [comment]
Worth noting that the error on 5.4.7-ck is errno 14: Bad address

**Comment by tstruk** [comment]
So this should be reported on linux-integrity@vger.kernel.org. It would help a lot if you could bisect the offensive commit.
