### ISSUE TITLE
Unable to retrieve AIK Cert and AIK Pub key  in Windows.

### ISSUE THREAD

**Issue by bhupeshpant19jan** [tpm2-software/tpm2-tss#1607]
My application consuming tss2 library in windows is failing while trying to extract AIK Pubkey and cert during metadata handle retrieval. 
	
```
Processing Action: aikcert
WARNING:esys:api\Esys_NV_ReadPublic.c:309:Esys_NV_ReadPublic_Finish() Received TPM Error
ERROR:esys:esys_tr.c:210:Esys_TR_FromTPMPublic_Finish() Error NV_ReadPublic ErrorCode (0x0000018b)
ERROR:esys:esys_tr.c:321:Esys_TR_FromTPMPublic() Error TR FromTPMPublic ErrorCode (0x0000018b)
Error: tpm2-tss exception : message=Failed to open ESYS_TR, code=395
```

Based on the tool, tpm2_rc_decode, the err code:- **0x0000018b** corresponds to invalid handle but I don't see anything invalid. I have also verified the index number, seems okay to me. Please take a look once.

```
/ TCG spec-defined constants
#define EK_CERT_INDEX 0x01c00002
#define EK_NONCE_INDEX 0x01c00003
#define EK_TEMPLATE_INDEX 0x01c00004
#define EK_PUB_INDEX 0x81001000
#define AIK_PUB_INDEX 0x81001001
#define AIK_CERT_INDEX 0x01800000
```
		
I am referring the TG -TSS Marshalling/unmarshalling API specification for ret code and general awareness.
I debugged into tss2 library and seems like failure is coming from tpm2-tss-2.3.1\src\tss2-sys\api\Tss2_Sys_Execute.c line number: 134.  IN the below call to Tss2_MU_UINT32_Unmarshal  rval = ctx->rsp_header.responseCode; // return 395
 
```
rval = Tss2_MU_UINT32_Unmarshal(ctx->cmdBuffer,
                                    ctx->maxCmdSize,
                                    &ctx->nextData,
                                    &ctx->rsp_header.responseCode);
    if (rval)
        return rval;
```
   
In my case the Tss2_MU_UINT32_Unmarshal() API seems to be failing with rval returning as Success 0 but the rsp_header.responseCode is populated as 395 and later in the tss code,  it is used as a return value.
What does response/error code : **395** correspond to. The various error codes associated with  &ctx->rsp_header.responseCode is not documented anywhere? At least I can't find it.

I am stuck at the moment and need some help around this. Sample code to retrieve AIK would also help me.

Please note: My test code is working in Linux.

**Comment by tstruk** [comment]
395 decimal == 0x0000018b hex, which is the Invalid handle error code returned by the TPM.
Could you verify that the NV index you are trying to read exists on your TPM.
You can do that with:
 $ tpm2_getcap handles-nv-index
As for examples you can have a look at https://github.com/tpm2-software/tpm2-tools/blob/master/tools/tpm2_nvreadpublic.c or https://github.com/tpm2-software/tpm2-tools/blob/master/tools/tpm2_nvread.c

**Comment by bhupeshpant19jan** [comment]
Thanks @tstruk for the prompt response. I checked and found the index values were incorrect. 

I made changes as per windows documentation and it worked. 

```
#define AIK_PUB_INDEX 0x81001001
#define AIK_CERT_INDEX 0x01800000
```
now using

```
constexpr auto AIK_CERT_INDEX = 0x01C101D0;
constexpr auto AIK_PUB_INDEX = 0x81000000 + 2;
```
