### ISSUE TITLE
Unable to make install because of /doxygen-doc/man/ files are missing

### ISSUE THREAD

**Issue by chenxizf** [tpm2-software/tpm2-tss#1624]
I am using tpm2-tss 2.3.2 release, and running on centos 7.

I ran the command below
$ ./bootstrap  (No error)

$ ./configure --prefix=/usr (No error)
  tpm2-tss 2.3.2
  esapi:              yes
  tctidefaultmodule:  libtss2-tcti-default.so
  tctidefaultconfig:
  unit:               no
  fuzzing:            none
  debug:              no
  maxloglevel:        trace
  doxygen:            1
  tcti-device-async:  no
  tcti-partial-read:  no
  crypto backend:     ossl

$ make -j5 (No error)

$ sudo make install (**Get the error below**)

... ... 
 /bin/mkdir -p '/usr/share/man/man3'
 /bin/install -c -m 644 man/man3/Tss2_Tcti_Device_Init.3 man/man3/Tss2_Tcti_Mssim_Init.3 man/man3/Tss2_TctiLdr_Fi
nalize.3 man/man3/Tss2_TctiLdr_FreeInfo.3 man/man3/Tss2_TctiLdr_GetInfo.3 man/man3/Tss2_TctiLdr_Initialize.3 ./do
xygen-doc/man/ESYS_CONTEXT.3 ./doxygen-doc/man/ESYS_TR.3 ./doxygen-doc/man/ESYS_TR_defines.3 ./doxygen-doc/man/Es
ys_ActivateCredential.3 ./doxygen-doc/man/Esys_Certify.3 ./doxygen-doc/man/Esys_CertifyCreation.3 ./doxygen-doc/m
an/Esys_ChangeEPS.3 ./doxygen-doc/man/Esys_ChangePPS.3 ./doxygen-doc/man/Esys_Clear.3 ./doxygen-doc/man/Esys_Clea
rControl.3 ./doxygen-doc/man/Esys_ClockRateAdjust.3 ./doxygen-doc/man/Esys_ClockSet.3 ./doxygen-doc/man/Esys_Comm
it.3 ./doxygen-doc/man/Esys_ContextLoad.3 ./doxygen-doc/man/Esys_ContextSave.3 ./doxygen-doc/man/Esys_Create.3 ./
doxygen-doc/man/Esys_CreatePrimary.3 ./doxygen-doc/man/Esys_DictionaryAttackLockReset.3 ./doxygen-doc/man/Esys_Di
ctionaryAttackParameters.3 ./doxygen-doc/man/Esys_Duplicate.3 ./doxygen-doc/man/Esys_ECC_Parameters.3 ./doxygen-d
oc/man/Esys_ECDH_KeyGen.3 ./doxygen-doc/man/Esys_ECDH_ZGen.3 ./doxygen-doc/man/Esys_EC_Ephemeral.3 ./doxygen-doc/
man/Esys_EncryptDecrypt.3 ./doxygen-doc/man/Esys_EventSequenceComplete.3 ./doxygen-doc/man/Esys_EvictControl.3 ./
doxygen-doc/man/Esys_FlushContext.3 ./doxygen-doc/man/Esys_GetCapability.3 ./doxygen-doc/man/Esys_GetCommandAudit
Digest.3 ./doxygen-doc/man/Esys_GetRandom.3 ./doxygen-doc/man/Esys_GetSessionAuditDigest.3 ./doxygen-doc/man/Esys
_GetTestResult.3 ./doxygen-doc/man/Esys_GetTime.3 '/usr/share/man/man3'
/bin/install: cannot stat ‘./doxygen-doc/man/ESYS_CONTEXT.3’: No such file or directory
/bin/install: cannot stat ‘./doxygen-doc/man/ESYS_TR.3’: No such file or directory
/bin/install: cannot stat ‘./doxygen-doc/man/ESYS_TR_defines.3’: No such file or directory
/bin/install: cannot stat ‘./doxygen-doc/man/Esys_ActivateCredential.3’: No such file or directory
/bin/install: cannot stat ‘./doxygen-doc/man/Esys_Certify.3’: No such file or directory

... ... 

/bin/install: cannot stat ‘./doxygen-doc/man/Esys_GetSessionAuditDigest.3’: No such file or directory
/bin/install: cannot stat ‘./doxygen-doc/man/Esys_GetTestResult.3’: No such file or directory
/bin/install: cannot stat ‘./doxygen-doc/man/Esys_GetTime.3’: No such file or directory
make[1]: *** [install-man3] Error 1
make[1]: Leaving directory `/root/rpmpkg-src/tpm2-tss-2.3.2'
make: *** [install-am] Error 2

Could anyone help to take a look why it is failing?
I have doxygen installed.
$ doxygen -version
1.8.5

**Comment by diabonas** [comment]
> $ doxygen -version
> 1.8.5

Your doxygen version is too old: tpm2-tss [uses the `MAN_SUBDIR` option](https://github.com/tpm2-software/tpm2-tss/blob/0f98b0f4d1df96ae619740908d56b04d683d2db6/Doxyfile.in#L1978), which was [introduced in doxygen 1.8.7](http://www.doxygen.nl/manual/changelog.html#log_1_8_7).

**Comment by chenxizf** [comment]
Thanks @diabonas for the answer!
