### ISSUE TITLE
Potentially obsolete policy

### ISSUE THREAD

**Issue by joholl** [tpm2-software/tpm2-tss#1625]
See the two folders **policy** and **policies** [here](https://github.com/tpm2-software/tpm2-tss/tree/master/test/data/fapi).

The file tpm2-tss/test/data/fapi/**policies**/pol_password.json seems to be obsoleted by tpm2-tss/test/data/fapi/**policy**/pol_password.json. It's the only policy in this folder and not referenced in the code.

@AndreasFuchsSIT What do you think?

**Comment by AndreasFuchsSIT** [comment]
I guess the `policies` folder is a typo or something.

**Comment by tstruk** [comment]
```
$ find test/data/fapi/ -type d
test/data/fapi/
test/data/fapi/policy
test/data/fapi/policies
```
If policies dir is a typo can we merge the two together?

**Comment by AndreasFuchsSIT** [comment]
yes
