### ISSUE TITLE
side effects from using AM_PATH_LIBGCRYPT

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#1628]
3c98f73266361b3194da957f47c20c116b0a4ad1 reworked some of the autoconf stuff adding the use of `AM_PATH_LIBGCRYPT`. This macro is not part of autoconf or autoconf-archive. Instead it's shipped by distros in the libgcrypt-dev package. Using this macro makes the bootstrapping process dependent on libgcrypt-dev which may not be desirable / intended and has side effects. I don't believe this will effect builds from release tarballs since autoconf has already done it's job by then (generated `configure), but anyone building from git will need to install libgcrypt-dev now even if they're not using it in the build (building against libcrypto).

If this new behavior is intentional we should add a note in the CHANGELOG (new build dependency), and updated the INSTALL file to reflect this new dependency.

**Comment by tstruk** [comment]
I have a patch that adds libgcrypt-dev to INSTALL.md as a dependency.
We are also missing libcurl-dev in the list.

**Comment by AndreasFuchsSIT** [comment]
@tstruk Mind to send the PR ?
