### ISSUE TITLE
Get rid of HAVE_STRNDUP from tctildr.c

### ISSUE THREAD

**Issue by tstruk** [tpm2-software/tpm2-tss#1633]
The configure script checks if the system provides the strndup() function, and sets a HAVE_STRNDUP macro accordingly. This is then used in tctildr.c that implements its own version of the function, in case the system does not provide it. There are some issues with that however:
1. It is not consistent because in FAPI (ifapi_profiles.c) we use strndup without using the same method as in tctildr.c. (Not to mention tpm2-tools)
2. The unit tests are failing in some configurations because cmocka and __wrap_strndup doesn't quite work with that and copy_info unit tests bind to the private strndup instead of wrapping the glibc provided strndup (as in https://travis-ci.org/tstruk/tpm2-tss/jobs/652708765?utm_medium=notification for example). resulting in "FAIL: test/unit/tctildr-getinfo"

The solution will be to get rig on the local implementation of strndup() from tctildr.c, and just check if the system provides it in configure script by replacing AC_CHECK_FUNCS([strndup])
with AC_CHECK_FUNC([strndup], [], [AC_MSG_ERROR([strndup not found])])

**Comment by tstruk** [comment]
Even better example:
https://travis-ci.org/tstruk/tpm2-tss/jobs/653511202?utm_medium=notification

**Comment by remuswu1019** [comment]
It still happened, I use debian 9.12.
[test-suite.log](https://github.com/tpm2-software/tpm2-tss/files/4435789/test-suite.log)
