### ISSUE TITLE
Wrong hmac calculation for response when executing TPM2_CC_Clear command

### ISSUE THREAD

**Issue by idesai** [tpm2-software/tpm2-tss#1641]
If this command is authorized using lockoutAuth, the HMAC in the response shall use the new lockoutAuth value (that is, the Empty Buffer) when computing the response HMAC. 

The fix may be to [conditionally](https://github.com/tpm2-software/tpm2-tss/blob/d8fd8c0ad935fb2022b9967d613c4776a35955e1/src/tss2-sys/api/Tss2_Sys_GetRspAuths.c#L77) retrieve response auths when executing clear command.

**Comment by tstruk** [comment]
The spec only mentions the lockout auth, but I wonder if this is true in all cases, since tpm_clear sets all ownerAuth, endorsementAuth, and lockoutAuth to an Empty Buffer. I have a fix PR for this, could you have a look please
https://github.com/tpm2-software/tpm2-tss/pull/1648

**Comment by tstruk** [comment]
The spec is correct, it only needs to be done for lockoutAuth.
