### ISSUE TITLE
Running TPM2.0 on Yocto Based Platform

### ISSUE THREAD

**Issue by Darsh-Dev** [tpm2-software/tpm2-tss#1679]
Hi,
I am following the steps,
1. As per the guidelines of AWS we followed the given steps provided in Link 
(https://aws.amazon.com/blogs/iot/using-a-trusted-platform-module-for-endpoint-device-security-in-aws-iot-greengrass/) 
2. libp11-Tool (Installed as per AWS) 
3. TPM-PKCS11 (Installed as per AWS) 
4. TPM-Tool (Installed through Meta-security layer, binary created in /usr/bin ) 
5. TPM-TSS(Installed through Meta-security layer in yocto) 
6. TPM-ABRMD (Installed through Meta-security in yocto,binary created in /usr/sbin/tpm2-abrmd ,but version is undefined)

**Problem facing:**
Using the PKCS11 Provider for AWS IoT Greengrass hardware security.
**step 1:** cd tpm2-pkcs11/tools/
**step 2:** ./tpm2_ptool.py init --pobj-pin=123456 --path=/opt/tpm2-pkcs11/
Running this script throws unusual state of TPM.
```
"Traceback (most recent call last):
  File "/home/root/infineon-tpm/tpm2-pkcs11/tools/tpm2_pkcs11/commandlets_store.py", line 96, in __call__
    ctx = tpm2.createprimary(ownerauth, pobjauth)
  File "/home/root/infineon-tpm/tpm2-pkcs11/tools/tpm2_pkcs11/tpm2.py", line 35, in createprimary
    stderr)
RuntimeError: Could not execute tpm2_createprimary: tpm2_createprimary: invalid option -- 'p'
Could not execute tpm2_createprimary: tpm2_createprimary: invalid option -- 'p'

```
**step 3:** we tried to edit tpm2_createprimary command in tpm2.py
```
-            'tpm2_createprimary', '-p', 'hex:%s' % objauth.decode(), '-o', ctx,
+            'tpm2_createprimary',','-P','hex:%s' % objauth.decode(), '-C', ctx,
```
Running this script again shows
```
"Traceback (most recent call last):
  File "/home/root/infineon-tpm/tpm2-pkcs11/tools/tpm2_pkcs11/commandlets_store.py", line 96, in __call__
    ctx = tpm2.createprimary(ownerauth, pobjauth)
  File "/home/root/infineon-tpm/tpm2-pkcs11/tools/tpm2_pkcs11/tpm2.py", line 35, in createprimary
    stderr)
RuntimeError: Could not execute tpm2_createprimary: ERROR: Unable to run tpm2_createprimary
Could not execute tpm2_createprimary: ERROR: Unable to run tpm2_createprimary"
```
Help will be appreciated here.

**Comment by AndreasFuchsSIT** [comment]
Just to be sure; The guidance at AWS gives certain commitIds that should be checked out.
Did you do so for all of the git repositories ?
The problem you're describing hints at a inconsistent combination between tpm2-tools (here: https://github.com/tpm2-software/tpm2-tools) who changed their command line parameters for the 4.0 release and the tpm2-pkcs11 library (here: https://github.com/tpm2-software/tpm2-pkcs11) which is still under heavy development.

So I'd recommend double checking the correct commit ids and then I'd test latest stable from tpm2-pkcs11 which is 1.1.0 I think together with the 4.1.0 release of tpm2-tools.

Then, it's a issue for the tpm2-pkcs11 project or just something to discuss on the mailinglist (https://lists.01.org/postorius/lists/tpm2.lists.01.org/) or gitter (chat in the lower right at https://tpm2-software.github.io/)

**Comment by AndreasFuchsSIT** [comment]
P.S. Or follow my instructions from https://youtu.be/NFQ22SBlejk

**Comment by Darsh-Dev** [comment]
@AndreasFuchsSIT ,

We are not able to resolve the issue yet, we have two different approaches,  

Approach : 1
=========

### Download the following repositories:

> git clone https://github.com/tpm2-software/tpm2-tss
> git clone https://github.com/tpm2-software/tpm2-tools
> git clone https://github.com/tpm2-software/tpm2-abrmd
> git clone https://github.com/tpm2-software/tpm2-pkcs11
> git clone https://github.com/OpenSC/libp11.git
 

> wget https://github.com/autoconf-archive/autoconf-archive/archive/v2018.03.13.tar.gz
> tar -xvf v2018.03.13.tar.gz
> cp -r autoconf-archive-2018.03.13/m4/ tpm2-tss/
> cp -r autoconf-archive-2018.03.13/m4/ tpm2-abrmd/
> cp -r autoconf-archive-2018.03.13/m4/ tpm2-tools/
> cp -r autoconf-archive-2018.03.13/m4/ tpm2-pkcs11/

### Step 1

> cd libp11
> git checkout libp11-0.4.9
> vi Makefile(remove examples build property)((https://github.com/OpenSC/libp11/issues/32))
> ./bootstrap
> ./configure
> or 
> ./configure OPENSSL_CFLAGS="-I/opt/openssl-1.0.2d/include" OPENSSL_LIBS="-L/opt/openssl-1.0.2d/lib -lcrypt"
> make -j4
> sudo make install
> cd ..
> 

### Step 2

> cd tpm2-tss
> git checkout 740653a12e203b214cba2f07b5395ffce74dfc03
> ./bootstrap -I m4
> ./configure --with-udevrulesdir=/etc/udev/rules.d --with-udevrulesprefix=70-
> or 
> ./configure  --disable-doxygen-doc --with-dbuspolicydir=/etc/dbus-1/system.d --with-systemdsystemunitdir=/lib/systemd/system --with-systemdpresetdir=/lib/systemd/system-preset datarootdir=/usr/share
> make -j4
> sudo make install
> sudo useradd --system --user-group tss
> sudo udevadm control --reload-rules && sudo udevadm trigger
> sudo ldconfig(if ask for symbolic link create a soft link bwteen files provided as both are copy of each other)
> root@imx8qxpaiml:/usr/lib# rm -rf libOpenVG.so
> root@imx8qxpaiml:/usr/lib# ln -s libOpenVG.3d.so libOpenVG.so 
> cd ..

### Step 3

> cd tpm2-abrmd
> git checkout 2.1.1
> ./bootstrap -I m4
> ./configure --with-dbuspolicydir=/etc/dbus-1/system.d \
> with-systemdsystemunitdir=/lib/systemd/system \
> with-systemdpresetdir=/lib/systemd/system-preset \
> datarootdir=/usr/share

> or 
> PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./configure --with-dbuspolicydir=/etc/dbus-1/system.d --with-systemdsystemunitdir=/lib/systemd/system --with-systemdpresetdir=/lib/systemd/system-preset --datarootdir=/usr/share 
> 
> make -j4
> sudo make install
> sudo ldconfig
> sudo pkill -HUP dbus-daemon
> sudo systemctl daemon-reload
> sudo systemctl enable tpm2-abrmd.service
> sudo systemctl start tpm2-abrmd.service
> dbus-send --system --dest=org.freedesktop.DBus --type=method_call \
> print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames \
> | grep "com.intel.tss2.Tabrmd" || echo "ERROR: abrmd was not installed correctly!"
> cd ..

### Step 4

> cd tpm2-tools
> git checkout 3e8847c9a52a6adc80bcd66dc1321210611654be
> or git checkout remotes/origin/4.1.X
> ./bootstrap -I m4
> ./configure
> or 
> PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./configure
> **faced dependecy issue while configure:**
> checking for libcurl... no
> configure: error: Package requirements (libcurl) were not met:
> No package 'libcurl' found
> Consider adjusting the PKG_CONFIG_PATH environment variable if you
> installed software in a non-standard prefix.
> Alternatively, you may set the environment variables CURL_CFLAGS
> and CURL_LIBS to avoid the need to call pkg-config.
> See the pkg-config man page for more details.

### Step 5
**tpm2_createprimary** is not working with yocto build,

> $ cd /tpm2-pkcs11/tools
> ./tpm2_ptool.py init --pobj-pin=123456 --path=/opt/tpm2-pkcs11/ 

> **error:**
> ['tpm2_createprimary', '-H', 'e', u'hex:04a7384b4595dbcd684e9976721b7e9597befd4a5d79440b0c482c4c30af99a1', '-C', '/tmp/tmpinb2wb/context.out', '-g', 'sha256', '-G', 'rs]
> Traceback (most recent call last):
>   File "/home/root/infineon-tpm/tpm2-pkcs11/tools/tpm2_pkcs11/commandlets_store.py", line 96, in __call__
>     ctx = tpm2.createprimary(ownerauth, pobjauth)
>   File "/home/root/infineon-tpm/tpm2-pkcs11/tools/tpm2_pkcs11/tpm2.py", line 35, in createprimary
>     stderr)
> RuntimeError: **Could not execute tpm2_createprimary: ERROR: Got arguments but the tool takes no arguments**

Found one reference TPM (https://www.semanticscholar.org/paper/Hardware-Root-of-Trust-for-Linux-Based-Edge-Gateway-Al-Galby-Arezou/447bf604da40c27970503117627d6fd812a4352b)

I run the following commands, 
> root@imx8qxpaiml:~/infineon-tpm/tpm2-tools# 
> tpm2_createprimary -H e -g sha256 -G rsa -C primary.ctx
> respone:ObjectAttribute: 0x00030072
> CreatePrimary Succeed ! Handle: 0x800000ff

tpm2_createprimary working fine, but not with script.

### Step 6
Copied the same arguments in tpm2.py and run the script again,

```
diff --git a/tools/tpm2_pkcs11/tpm2.py b/tools/tpm2_pkcs11/tpm2.py
index bd95036..1d3b31b 100644
--- a/tools/tpm2_pkcs11/tpm2.py
+++ b/tools/tpm2_pkcs11/tpm2.py
@@ -17,14 +17,17 @@ class Tpm2(object):
 
     def createprimary(self, ownerauth, objauth):
         ctx = os.path.join(self._tmp, "context.out")
+       print("##########Debugging ##############")
+       print(ctx)
         cmd = [
-            'tpm2_createprimary', '-p', 'hex:%s' % objauth.decode(), '-o', ctx,
+            'tpm2_createprimary','-H','e','hex:%s' % objauth.decode(), '-C', ctx,
             '-g', 'sha256', '-G', 'rsa'
         ]
 
         if ownerauth and len(ownerauth) > 0:
-            cmd.extend(['-P', ownerauth])
-
+            cmd.extend(['-E', ownerauth])
+       print("DEbuggning TPM")
+       print(cmd) 
         p = Popen(cmd, stdout=PIPE, stderr=PIPE, env=os.environ)
         _, stderr = p.communicate()
         if (p.wait()):
```

> cd /tpm2-pkcs11/tools
> ./tpm2_ptool.py init --pobj-pin=123456 --path=/opt/tpm2-pkcs11/
> 

> **error:**
> ['tpm2_createprimary', '-H', 'e', u'hex:04a7384b4595dbcd684e9976721b7e9597befd4a5d79440b0c482c4c30af99a1', '-C', '/tmp/tmpinb2wb/context.out', '-g', 'sha256', '-G', 'rs]
> Traceback (most recent call last):
>   File "/home/root/infineon-tpm/tpm2-pkcs11/tools/tpm2_pkcs11/commandlets_store.py", line 96, in __call__
>     ctx = tpm2.createprimary(ownerauth, pobjauth)
>   File "/home/root/infineon-tpm/tpm2-pkcs11/tools/tpm2_pkcs11/tpm2.py", line 35, in createprimary
>     stderr)
> RuntimeError: **Could not execute tpm2_createprimary: ERROR: Got arguments but the tool takes no arguments**
> 

Approach : 2
============

In parallel we tried to build meta-security from different branch from Yocto, master-next branch which is having below versions of tools
- tpm2-tools_4.1.1.bb 
- tpm2-abrmd_2.3.0.bb
- tpm2-pkcs11_0.9.9.bb
- tpm2-tss_2.3.2.bb
- tpm2-tss-engine_1.0.1.bb
- tpm2-totp_0.2.0.bb

This is building but unfortunately while running we are facing issues too,

> **$ tpm2_getrandom 4**
> error:
> ** (process:4097): CRITICAL **: failed to allocate dbus proxy object: Error calling StartServiceByName for com.intel.tss2.Tabrmd: GDBus.Error:org.freedesktop.DBus.Error)
> WARNING:tcti:../tpm2-tss-2.3.2/src/tss2-tcti/tctildr.c:62:tcti_from_init() TCTI init for function 0xffffa44d61c8 failed with a0008 
> WARNING:tcti:../tpm2-tss-2.3.2/src/tss2-tcti/tctildr.c:92:tcti_from_info() Could not initialize TCTI named: tcti-abrmd 
> ERROR:tcti:../tpm2-tss-2.3.2/src/tss2-tcti/tctildr-dl.c:150:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-tabrmd.so.0 
> ERROR:tcti:../tpm2-tss-2.3.2/src/tss2-tcti/tctildr-dl.c:248:tctildr_get_default() No standard TCTI could be loaded 
> ERROR:tcti:../tpm2-tss-2.3.2/src/tss2-tcti/tctildr.c:418:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI 
> ERROR: Could not load tcti, got: "(null)"

tried even this solution **export TPM2TOOLS_DEVICE_FILE=/dev/tpmrm0**, but no luck 

Thanks

**Comment by AndreasFuchsSIT** [comment]
Hi @Darsh-Dev, does tpm2_getrandom 5 work in approach 1 ?
Also, I'd still recommend trying more recent versions of everything, since there were many changes in pkcs11 especially.
Maybe try tpm2-tss 2.4.x, tpm2-tools 4.2.x and tpm2-pkcs11 1.1.x if you don't like master.

Also you may want to attempt --enable-unit --enable-integration and make check for each of the components. (this also needs the tpm_server).

Maybe have a look at the .travis.yml files and .ci directory of each of the projects to understand how we do our testing...

**Comment by Darsh-Dev** [comment]
Hi @AndreasFuchsSIT ,

Yes, tpm2_getrandom working fine in approach 1.
```
root@imx8qxpaiml:~/tpm# tpm2_getrandom 5
0x5D 0xF3 0x9D 0x05 0xBD
``` 
I will check other given suggestions and update.
Thanks
