### ISSUE TITLE
Warnings on Esys_ReadPublic

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tss#1694]
In the tpm2-pkcs11 project, I attempt to readpublic for the SRK, and then I check the RC for not there and move on... however I get these error logs:
```
WARNING:esys:src/tss2-esys/api/Esys_ReadPublic.c:320:Esys_ReadPublic_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/esys_tr.c:231:Esys_TR_FromTPMPublic_Finish() Error ReadPublic ErrorCode (0x0000018b) 
ERROR:esys:src/tss2-esys/esys_tr.c:321:Esys_TR_FromTPMPublic() Error TR FromTPMPublic ErrorCode (0x0000018b) 
```
I could call Esys_GetCapability() and check for the handle to avoid this, but it's another round trip call to the TPM. Should we silence these errors too?

**Comment by AndreasFuchsSIT** [comment]
I guess a warning would be sufficient, but I wouldn't want to silence in completely.
GetCapability(handles) is the intended way I suppose.

**Comment by williamcroberts** [comment]
Filed a bug against tpm2-pkcs11: https://github.com/tpm2-software/tpm2-pkcs11/issues/522

**Comment by Bab95** [comment]
WARNING:esys:api\Esys_NV_ReadPublic.c:309:Esys_NV_ReadPublic_Finish() Received TPM Error
ERROR:esys:esys_tr.c:210:Esys_TR_FromTPMPublic_Finish() Error NV_ReadPublic ErrorCode (0x0000008b)
ERROR:esys:esys_tr.c:321:Esys_TR_FromTPMPublic() Error TR FromTPMPublic ErrorCode (0x0000008b)

I am getting these logs is this something to worry about? or these are fixed?
