### ISSUE TITLE
Error while run the tpm2_tools.py

### ISSUE THREAD

**Issue by Darsh-Dev** [tpm2-software/tpm2-tss#1696]
Hi, 

I am facing issue with version of TPM-software packages 

Packages | Version
-- | --
tpm-quote-tools | 1.0.4-r0
tpm-tools | 1.3.9.1-r0
tpm-tools-native | 1.3.9.1-r0
tpm2-abrmd | 2.3.0-r0
tpm2-abrmd-native | 2.3.0-r0
tpm2-pkcs11 | 1.1.0-r0
tpm2-tools | 4.1.1-r0
tpm2-totp | 0.9.9-r0
tpm2-tss | 2.3.2-r0
tpm2-tss-engine | 1.0.1-r0
Python | 3.7

Issue with Resource manager d-bus 

> ./tpm2_ptool.py init --path=/opt/tpm2-pkcs11/

Error Logs:
```
issue:Traceback (most recent call last):
  File "/opt/tpm2-pkcs11/tools/tpm2_pkcs11/commandlets_store.py", line 86, in __call__
    ctx = tpm2.createprimary(ownerauth, pobjauth)
  File "/opt/tpm2-pkcs11/tools/tpm2_pkcs11/tpm2.py", line 33, in createprimary
    stderr)
RuntimeError: Could not execute tpm2_createprimary: b'\n** (process:22876): CRITICAL **: 14:25:39.293: failed to allocate dbus proxy object: Error calling StartServiceB'
Could not execute tpm2_createprimary: b'\n** (process:22876): CRITICAL **: 14:25:39.293: failed to allocate dbus proxy object: Error calling StartServiceByName for com.'
root@stm32mp1-av96:/opt/tpm2-pkcs11/tools# find / -iname RuntimeError: Could not execute tpm2_createprimary: b'\n** (process:22876): CRITICAL **: 14:25:39.293: failed to
 allocate dbus proxy object: Error calling StartServiceB'
Could not execute tpm2_createprimary: b'\n** (process:22876): CRITICAL **: 14:25:39.293:find: unrecognized: Could
 failed to allocate dbuBusyBox v1.29.3 () multi-call binary.
```

**Comment by PeterHuewe** [comment]
Hi,
`./tpm2_ptool.py` is part of https://github.com/tpm2-software/tpm2-pkcs11 not tpm2-tss.
Please close this and report in the correct project.

That said, it looks like some dbus problem. Is your `abrmd` correctly running?
Do other simple commands like tpm2_getrandom work?

**Comment by Darsh-Dev** [comment]
@PeterHuewe thanks for update.

**Comment by williamcroberts** [comment]
FYI moved to: https://github.com/tpm2-software/tpm2-pkcs11/issues/475
