### ISSUE TITLE
Esys_Quote returns a SHA1 digest irrespective of the hashAlg specificed in pcrSelection.hash field.[Windows]

### ISSUE THREAD

**Issue by vinaykotak** [tpm2-software/tpm2-tss#1698]
I am calling Esys_Quote to generate a pcr quote for the set of pcr values. Inspite of specifying the hashAlg to be SHA256, the generated quote is a SHA1 quote. Running this on a Windows 10 machine. Below is the code used to set the pcrSelection fields. 
`
auto pcrSel = unique_c_ptr<TPML_PCR_SELECTION>(
            (TPML_PCR_SELECTION*)calloc(1, sizeof(TPML_PCR_SELECTION)));
    pcrSel->count = 1;
    const auto SIZE_OF_OCTET { 8 };
    pcrSel->pcrSelections[0].sizeofSelect = pcrCount / SIZE_OF_OCTET;
    pcrSel->pcrSelections[0].hash = TPM2_ALG_SHA256;
    pcrSel->pcrSelections[0].pcrSelect[0] = (pcrMask & 0xff);
    pcrSel->pcrSelections[0].pcrSelect[1] = (pcrMask & 0xff00) >> 8;
    pcrSel->pcrSelections[0].pcrSelect[2] = (pcrMask & 0xff0000) >> 16;
    pcrSel->pcrSelections[0].pcrSelect[3] = (pcrMask & 0xff000000) >> 24;
`
Note: I tried the same code on Ubuntu 18.04 and it works fine.

**Comment by JuergenReppSIT** [comment]
Did "the generated quote is a SHA1 quote" mean that the digest was computed for the SHA1 bank, and what scheme did you use for the signing key?

**Comment by vinaykotak** [comment]
Yes, the generated quote is a SHA1 quote. The signing key is an RSA with its scheme hashAlg set to SHA1. Could that be causing this?

**Comment by JuergenReppSIT** [comment]
Yes the hashAlg from the scheme is used to compute the digest.

**Comment by vinaykotak** [comment]
Cool. Thanks a lot.
