### ISSUE TITLE
Issue with calling Esys_Import for a key handle without authValue and authPolicy.

### ISSUE THREAD

**Issue by vinaykotak** [tpm2-software/tpm2-tss#1699]
I have AIK key created under the Storage Hierarchy and its created without any auth policy and the auth value was not specified when creating the key.
I am using this key to seal some data remotely and trying to unseal it on the tpm that has the AIK. 
When I trying to import the public object using  the AIK handle, with the session handle set to ESYS_TR_PASSWORD, the command fails with error "tpm:handle(1):the type of the value is not appropriate for the use". 
From what I have read, if no auth policy is set and auth Value is not provided, the default auth value is an empty password. In that case, what should be the session handle value?
I tried to use ESYS_TR_NONE also and even that does not work.
Any help will be greatly appreciated.

**Comment by AndreasFuchsSIT** [comment]
Could you post the specific piece of code that you're using ?
It's hard to assess this way...
My first guess would be that you passed a session for a key or a key for a session handle, but need a look at the code...

**Comment by AndreasFuchsSIT** [comment]
P.S. Here's some code from our test-suit for Import:
https://github.com/tpm2-software/tpm2-tss/blob/6da95b04b4f22284d5b40cc03fa19e6dc514339f/test/integration/esys-import.int.c#L411-L422

**Comment by vinaykotak** [comment]
Hi Andreas, I was able to get past the Esys_Import issue. But I am hitting an issue with the Esys_Load() now. I am hitting a policy check failed error. Here is the code that does this. 

`
unique_c_ptr<TPM2B_PRIVATE> outPriv;
    TPM2B_PRIVATE* tmpPriv;

    TPMT_SYM_DEF_OBJECT symAlg;
    symAlg.algorithm = TPM2_ALG_NULL;
    ret = Esys_Import(this->ctx->Get(), ekHandle.get(),
            ESYS_TR_PASSWORD, ESYS_TR_NONE, ESYS_TR_NONE,
            nullptr, &inPub, &inPriv, &seed, &symAlg, &tmpPriv);
    if (ret != TSS2_RC_SUCCESS) {
        throw Tss2Exception("Failed to import encrypted data", ret);
    }
    outPriv.reset(tmpPriv);

    //
    // Load imported key
    //
    unique_esys_tr loadedData(this->ctx->Get());
    ret = Esys_Load(this->ctx->Get(), ekHandle.get(),
            ESYS_TR_PASSWORD, ESYS_TR_NONE, ESYS_TR_NONE,
            outPriv.get(), &inPub, loadedData.get_ptr());
    if (ret != TSS2_RC_SUCCESS) {
        throw Tss2Exception("Failed to load encrypted data", ret);
    }`

I am sending the same ESYS_TR_PASSWORD session handle to both Esys_Import and Esys_Load. Import works but Load does not.

**Comment by AndreasFuchsSIT** [comment]
What exactly is the error code you're getting ?

**Comment by vinaykotak** [comment]
Tpm Error code:2461. That translates to "tpm:session(1):a policy check failed" when I run it through tpm2_rc_decode.
Is this policy failure for the parent key handle or could it also be for the public key that we are trying to load.

**Comment by AndreasFuchsSIT** [comment]
So for the load command, only the parent key is authorized; since it is used for decrypting the blob.
The child key is authorized upon usage of the child.

If it were the public key being loaded, it would point to parameter(1) instead of session(1).

How did you generate the parent / ekHandle ?

**Comment by AndreasFuchsSIT** [comment]
I'll close this assuming it worked out
