### ISSUE TITLE
Test results with Ubuntu 20.04

### ISSUE THREAD

**Issue by KishoreRedlapalli** [tpm2-software/tpm2-tss#1702]
Are the compilation and CI tests certified to run on ubuntu 20.04?

**Comment by AndreasFuchsSIT** [comment]
No, not yet.

We'd need a `ubuntu-20.04.docker` file over at
https://github.com/tpm2-software/tpm2-software-container

And then an entry at
https://github.com/tpm2-software/tpm2-tss/blob/0783420b3db7c6c66ce597ab3dd0df5b053a2be2/.travis.yml#L10-L17

I guess #1701 gives us the necessary changes for OpenSSL version
