### ISSUE TITLE
Question: Would RSA 3072 bit EK keys create issues?

### ISSUE THREAD

**Issue by stefanberger** [tpm2-software/tpm2-tss#1715]
I am going to add support for RSA 3072 bit keys to the libtpms's TPM 2 implementation. In swtpm we create the EKs via the swtpm_setup tool. Now the question is whether to create the largest size of RSA keys that are possible, so create an RSA endorsement key with 3072 bits if libtpms can do it. I am wondering whether current or past/recent versions of your TPM 2 management stack would have issues with 3072 bit RSA EK keys. The EK key is only used for decryption as far as I can see and the blobs handed to it would be bigger. If there was indeed and issue then it would probably be better to create 2048 bit keys by default and let the user choose 3072 bit keys if needed, but then on the other hand it would be better to not have the user deal with this detail.

**Comment by williamcroberts** [comment]
The EK should follow the EK spec:
https://trustedcomputinggroup.org/resource/tcg-ek-credential-profile-for-tpm-family-2-0/

Their is no greater than 2048 RSA EK. Why no just do an EC key if you want stronger properties?

Now that's if you follow the spec, or you literally mean EK and not just "a primary key in the endorsement hierarchy". If you mean just a primary key in the endorsement hierarchy, have at it, I don't know why a 3072 wouldn't work. Theirs nothing in the TSS or tools code bases that would preclude this, just TPM support.

**Comment by AndreasFuchsSIT** [comment]
I agree with Bill here. Though, IMHO libtss2-fapi.so should not really care about this, if you adapt / extend the cryptographic profiles configs accordingly...

**Comment by stefanberger** [comment]
3072 RSA keys will come with the next version of the TPM 2 profile and libtpms 0.8.0 would support it. Question is now whether it 'should' support it or whether this is too early...

One issue is that an older version of IBM TSS2 has issues with larger context sizes returned by the TPM 2 when doing a TPM2_ContextSave and later on TPM2_ContextLoad. I hope the Intel tss2 stack doesn't have this issue.. ?

**Comment by williamcroberts** [comment]
> 3072 RSA keys will come with the next version of the TPM 2 profile and libtpms 0.8.0 would support it. Question is now whether it 'should' support it or whether this is too early...
> 
> One issue is that an older version of IBM TSS2 has issues with larger context sizes returned by the TPM 2 when doing a TPM2_ContextSave and later on TPM2_ContextLoad. I hope the Intel tss2 stack doesn't have this issue.. ?

I don't see any limitations in our code base's buffer size. We try not to make any assumptions like that. I can't guarentee without testing it, I think the simulator can be configured to support bigger RSA keysizes and we could test

**Comment by williamcroberts** [comment]
In the sim code
```C
src/Implementation.h:132:#define  MAX_RSA_KEY_BITS           2048
```

**Comment by williamcroberts** [comment]
So its not as simple as I thought, I am actually working up a patch for the heck of it and bumped into an assert that fails on a size check, it seems to be around `#define  MAX_CONTEXT_SIZE               2474`, we define this as 5120 in the tss stack...

Mayeb the newer ibm sim supports it by default...

**Comment by stefanberger** [comment]
@williamcroberts Very good for the 5120. Thanks for letting me know. New versions of the IBM TSS2 stack do increase the size as well.

**Comment by williamcroberts** [comment]
@stefanberger I was hoping the newer IBM sim would work with RSA4096 out of the box, but it's segfaulting, cpHash is null:
```C
    cpHash = GetCpHashPointer(command, hashAlg);
    if(cpHash->t.size == 0)
	{
```

**Comment by stefanberger** [comment]
@williamcroberts It isn't reading an existing Nvchip file, is it? If so, remove the file. Otherwise, I don't know what could be the reason. There may be some case's missing to handle 4096... 4096 is a bit out in the future.

**Comment by williamcroberts** [comment]
I dunno whats going on, but I hacked up 1119 with 3072/4096 support and it all works. Ill share the patch in a second.

**Comment by stefanberger** [comment]
This was needed for 3072 but misses 4096: https://github.com/stefanberger/libtpms/commit/61cb8231692d312d4daa98d2bbc7b50e2c882475#diff-8c891d4fd93c403f0514fcb88ffb5e4e

This also needed to be adapted: https://github.com/stefanberger/libtpms/commit/8016592b34785fc8e77f3d9e098bac6c5a6ba272#diff-9edc7b4910c1c8600ef1cbf16330f87e

**Comment by williamcroberts** [comment]
Here is a patch that adds 3072 and 4096 support, but I have only tested it with a single createprimary call.
[ibmtpm1119-rsa4096.patch.txt](https://github.com/tpm2-software/tpm2-tss/files/4618506/ibmtpm1119-rsa4096.patch.txt)

**Comment by williamcroberts** [comment]
I also had to twiddle:
```C
extern UINT32   s_actionInputBuffer[MAX_CONTEXT_SIZE];          // action input buffer
extern UINT32   s_actionOutputBuffer[MAX_CONTEXT_SIZE];         // action output buffer
```
Those were 1024, too small...

I was able to with no changes to our code base, create a primary key of 3072, create a child key of 4096, load context files (context load and save) and sign with the 4096 key with no problems:

stat sig.dat 
  File: sig.dat
  Size: 512       	Blocks: 8          IO Block: 4096   regular file
Device: fd00h/64768d	Inode: 8914775     Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/wcrobert)   Gid: ( 1000/wcrobert)
Access: 2020-05-12 16:26:26.780010448 -0500
Modify: 2020-05-12 16:26:22.117680309 -0500
Change: 2020-05-12 16:26:22.117680309 -0500
 Birth: -

**Comment by williamcroberts** [comment]
I think we can close this, as I know for a fact that RSA 3072 and RSA 4096 keys work within our stack.
