### ISSUE TITLE
Make esys change the hierarchy type to spec backwards compat

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tss#1750]
Since:
9d48cc7922ad esys: change the hierarchy type according to the spec

Interface types changed from TPMI_RH_HIERARCHY and TPMI_RH_ENABLES to ESYS_TR, which from the API and ABI perspective nothing changed, they are still just UINT32, it sonly the accepted values.

The types have no overlap, can we just keep the backwards compat version and print a warning?

This way we won't actually break existing users, their code will work, but we can urge them along to fix it.

**Comment by tstruk** [comment]
There is no requirement to maintain backwards compatibility when the major version number changes, but we have to maintain it between all minor versions. If we add this "compatibility layer" and release it in 3.0.0, then we will have to maintain it for all 3.x releases.

**Comment by williamcroberts** [comment]
> There is no requirement to maintain backwards compatibility when the major version number changes, but we have to maintain it between all minor versions. If we add this "compatibility layer" and release it in 3.0.0, then we will have to maintain it for all 3.x releases.

Sure, so I am saying, we don't do 3.0. IIRC/IIUC, this is the only breaking change, no? 

It's not hard to maintain, we just make it backwards compat and put a test in place.

**Comment by AndreasFuchsSIT** [comment]
What shall be do here ?
I'd like to close down on 3.0 and we should make a decision.
Has anyone checked if the TPMI_RH_HIERARCHY range is within a reserved range of ESYS_TR or is that far enough apart ?
Then I don't mind a compat version, since the rest of ESYS_TR can be assigned by ESYS to its liking.

**Comment by williamcroberts** [comment]
IIUC, for RH values you have 0x40000000 to 0x4000010F and for ESYS_TR the code currently does:
`esys_handle_cnt = ESYS_TR_MIN_OBJECT + (rand() % 6000000);`. So you would be assigning at most 0x1000 + 6000000 which is 0x5B9D80. So you have a gap of 0x40000000 - 0x5B9D80 = 0x3FA46280 (over 1 billion). I don't know exactly why/how you start handles there with a rand() (doesn't seem like a robust way to namesapce), but perhaps some logic could be added to make sure ESYS_TR's never flow into values above 0x40000000 - 1? 

```C
#define TPM2_RH_FIRST       ((TPM2_RH) 0x40000000) /* R */
#define TPM2_RH_SRK         ((TPM2_RH) 0x40000000) /* R */
#define TPM2_RH_OWNER       ((TPM2_RH) 0x40000001) /* K A P */
#define TPM2_RH_REVOKE      ((TPM2_RH) 0x40000002) /* R */
#define TPM2_RH_TRANSPORT   ((TPM2_RH) 0x40000003) /* R */
#define TPM2_RH_OPERATOR    ((TPM2_RH) 0x40000004) /* R */
#define TPM2_RH_ADMIN       ((TPM2_RH) 0x40000005) /* R */
#define TPM2_RH_EK          ((TPM2_RH) 0x40000006) /* R */
#define TPM2_RH_NULL        ((TPM2_RH) 0x40000007) /* K A P */
#define TPM2_RH_UNASSIGNED  ((TPM2_RH) 0x40000008) /* R */
#define TPM2_RH_LOCKOUT     ((TPM2_RH) 0x4000000A) /* A */
#define TPM2_RH_ENDORSEMENT ((TPM2_RH) 0x4000000B) /* K A P */
#define TPM2_RH_PLATFORM    ((TPM2_RH) 0x4000000C) /* K A P */
#define TPM2_RH_PLATFORM_NV ((TPM2_RH) 0x4000000D) /* C */
#define TPM2_RH_AUTH_00     ((TPM2_RH) 0x40000010) /* A */
#define TPM2_RH_AUTH_FF     ((TPM2_RH) 0x4000010F) /* A */
#define TPM2_RH_LAST        ((TPM2_RH) 0x4000010F) /* R */
```

**Comment by williamcroberts** [comment]
@tstruk shouldn't we do this for 3.0?

**Comment by williamcroberts** [comment]
I think we want this on 3.0, so clients don't go from working --> broken on 3.0 --> working on 3.1. They would have to then deal with < 3.0 and > 3.0 with code changes. We just want them to have noisy logs, but function properly.
