### ISSUE TITLE
Make install with 2.4.1 release assumes root privilege

### ISSUE THREAD

**Issue by bnevis-i** [tpm2-software/tpm2-tss#1753]
I am currently building tpm2-tss with a non-standard PREFIX in order to install them as development libraries rather than system libraries.  This used to work with 2.3.1 but now fails:

```
make  install-data-hook
make[2]: Entering directory '/nfs/work/bnevis/tpm-samples/tpm_seed/tpm2-seed/tpm2-tss'
mv /nfs/work/bnevis/tpm-samples/tpm_seed/tpm2-seed/tpm2-tss/../local/lib/udev/rules.d/tpm-udev.rules /nfs/work/bnevis/tpm-samples/tpm_seed/tpm2-seed/tpm2-tss/../local/lib/udev/rules.d/tpm-udev.rules
mv: '/nfs/work/bnevis/tpm-samples/tpm_seed/tpm2-seed/tpm2-tss/../local/lib/udev/rules.d/tpm-udev.rules' and '/nfs/work/bnevis/tpm-samples/tpm_seed/tpm2-seed/tpm2-tss/../local/lib/udev/rules.d/tpm-udev.rules' are the same file
Makefile:25858: recipe for target 'install-data-hook' failed
make[2]: [install-data-hook] Error 1 (ignored)
(systemd-sysusers && systemd-tmpfiles --create) || \
(    (id -g tss || groupadd -r tss) && (id -u tss || useradd -r -g tss tss) &&     (    (    if [ ! -d /nfs/work/bnevis/tpm-samples/tpm_seed/tpm2-seed/tpm2-tss/../local/var/run/tpm2-tss/eventlog/ ]; then mkdir -p /nfs/work/bnevis/tpm-samples/tpm_seed/tpm2-seed/tpm2-tss/../local/var/run/tpm2-tss/eventlog/; fi) || true) && (    (    if [ ! -d /nfs/work/bnevis/tpm-samples/tpm_seed/tpm2-seed/tpm2-tss/../local/var/lib/tpm2-tss/system/keystore/ ]; then mkdir -p /nfs/work/bnevis/tpm-samples/tpm_seed/tpm2-seed/tpm2-tss/../local/var/lib/tpm2-tss/system/keystore/; fi)) && (all set_fapi_permissions)) || true
Failed to take lock: Permission denied
chmod() of /var/log via /proc/self/fd/3 failed: Operation not permitted
Setting default ACL "u::rwx,g::r-x,g:adm:r-x,m::r-x,o::r-x" on /var/log/journal failed: Operation not permitted
Setting access ACL "u::rwx,g::r-x,g:adm:r-x,m::r-x,o::r-x" on /var/log/journal failed: Operation not permitted
Setting default ACL "u::rwx,g::r-x,g:adm:r-x,m::r-x,o::r-x" on /var/log/journal/f213932de4a049f69c7784d2f54ff3f5 failed: Operation not permitted
Setting access ACL "u::rwx,g::r-x,g:adm:r-x,m::r-x,o::r-x" on /var/log/journal/f213932de4a049f69c7784d2f54ff3f5 failed: Operation not permitted
Setting access ACL "u::rw-,g::r-x,g:adm:r--,m::r--,o::---" on /var/log/journal/f213932de4a049f69c7784d2f54ff3f5/system.journal failed: Operation not permitted
id: ‘tss’: no such user
groupadd: Permission denied.
groupadd: cannot lock /etc/group; try again later.
make[2]: Leaving directory '/nfs/work/bnevis/tpm-samples/tpm_seed/tpm2-seed/tpm2-tss'
make[1]: Leaving directory '/nfs/work/bnevis/tpm-samples/tpm_seed/tpm2-seed/tpm2-tss'
/nfs/work/bnevis/tpm-samples/tpm_seed/tpm2-seed
```

**Comment by tstruk** [comment]
FAPI expects the tss user id and group to be present in the system, and if it is not it tries to create it, which fails in your case.
To make it work you need to create the tss user and group before running "make install"

**Comment by bnevis-i** [comment]
What is the tss user and group used for?  It seems an odd dependency for a library project.

**Comment by tstruk** [comment]
That's the recommended user, which allows none root access to /dev/tpm* or resource manager system dbus name.
https://github.com/tpm2-software/tpm2-abrmd/blob/master/INSTALL.md#system-user--group

**Comment by bnevis-i** [comment]
> That's the recommended user, which allows none root access to /dev/tpm* or resource manager system dbus name.
> https://github.com/tpm2-software/tpm2-abrmd/blob/master/INSTALL.md#system-user--group

When why not have tpm2-abrmd create the tss user instead? 

After doing some more searching, I ran across #1611 -- it seem perhaps the tss user is really needed for some data directories for the feature API?  That would imply that if the feature API is used, the user must be a member of the tss group?

I guess I can work around it by doing a `make install-exec install-tss2HEADERS`

**Comment by AndreasFuchsSIT** [comment]
The user needs to be a member of the group tss for some operations, e.g. Fapi_Provision or CreateKey with type="system".
For other things they don't need to be a member.

**Comment by tstruk** [comment]
@bnevis-i Feel free to reopen this if you have more questions.
