### ISSUE TITLE
test: integration: fapi: info: No call to Fapi_Free after Fapi_GetInfo

### ISSUE THREAD

**Issue by pdxjohnny** [tpm2-software/tpm2-tss#1758]
I'm leaning towards this being an issue with the spec, but I don't know where to create issues for that

> I'm working off https://trustedcomputinggroup.org/wp-content/uploads/TSS_FAPI_v0.94_r09_20may2020.pdf

#### 4.4 Fapi_GetInfo
Fapi_GetInfo() returns a UTF-8 string identifying the version of the FAPI, the TPM, configurations and other relevant
information in a human readable format. The concrete content of this string is implementation specific.

##### 4.4.1 Prototype
```c
TSS2_RC Fapi_GetInfo(
 FAPI_CONTEXT *context,
 char **info);
TSS2_RC Fapi_GetInfo_Async(
 FAPI_CONTEXT *context);
TSS2_RC Fapi_GetInfo_Finish(
 FAPI_CONTEXT *context,
 char **info);
```

##### 4.4.2 Parameters
- context is a pointer to the opaque context blob currently being operated on. context MUST NOT be NULL.
- info returns the FAPI and TPM information. info MUST NOT be NULL.

##### 4.4.3 Return Values
- TSS2_FAPI_RC_BAD_REFERENCE: if the context or info pointer is NULL

![image](https://user-images.githubusercontent.com/5950433/84343362-ce9da400-ab5c-11ea-803d-99605380e63f.png)

![image](https://user-images.githubusercontent.com/5950433/84343376-da896600-ab5c-11ea-9cd8-39cc44985ec4.png)

https://github.com/tpm2-software/tpm2-tss/blob/7d45bc1ecfbb891cee3c913792bde351a527c573/test/integration/fapi-info.int.c#L37-L55

https://github.com/tpm2-software/tpm2-tss/blob/7d45bc1ecfbb891cee3c913792bde351a527c573/src/util/aux_util.h#L16

So the issue here is that we're calling `free`, and the spec says we should be calling `Fapi_Free`. I'm under the impression that either the spec or the test code needs to be changed.

**Comment by pdxjohnny** [comment]
Looks like `Fapi_Free` just calls `free`, should have checked this before creating the issue.

**Comment by williamcroberts** [comment]
> Looks like `Fapi_Free` just calls `free`, should have checked this before creating the issue.

As long as SAFE_FREE and FAPI_Free() all point to the same heap management routines it should be fine. In the case SAFE_FREE and FAPI_free() diverge, then the issue could arise.

The reason Fapi_Free() exists, is that the library and the executable could be linked against different libc versions, so the allocation routine used in the library may not match the de-allocation routine in the executable. So to prevent this, the executable should always call Fapi_Free() for FAPI allocated objects so the proper deallocation routine is used.
