### ISSUE TITLE
Storing Hashes in TPM

### ISSUE THREAD

**Issue by newuser218** [tpm2-software/tpm2-tss#1762]
I wanted to use the TPM to hash a file and then store the result inside the TPM's nonvolatile memory. How should I go about doing that?

**Comment by AndreasFuchsSIT** [comment]
Don't use the TPM just for hashing, does not help you here.
Then use Esys_NV_Write for storing.
Also please only post issues here, see the user mailinglist or slack or gitter for other discussions.
