### ISSUE TITLE
Question:  How should I provide "OwnerAuth" on Windows?

### ISSUE THREAD

**Issue by kwtj43** [tpm2-software/tpm2-tss#1767]
I've searched through the project's issues but didn't find anything on this topic.

Our team is porting the Linux implementation of the 'tpm-provider' (application interface (wraps tpm2-tss for use with golang) to Windows.  On Linux we take ownership of the tpm and specify the owner auth password, which is then used for the tpm2-tss function calls (ex. https://github.com/intel-secl/tpm-provider/blob/64cd53d6fd91b50eb011e1e43d6b0966fbeb473a/nvram.c#L67).

My understanding is that taking ownership is not needed on Windows and I've retrieved the "ownerauth" form the Get-Tpm cmdlet.  Base64 decoding that value and passing the 20 bytes for owner auth returns 0x9a2 (TPM_RC_BAD_AUTH).

What ownerath value should I pass to tpm2-tss?

**Comment by williamcroberts** [comment]
AFAICT, Windows 10 starting at version 1607 does not retain the owner password in the registry and sets it to a high entropy value and discards it. So if you want to use it, you need that value. Have you looked into what is discussed in:
  - https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/change-the-tpm-owner-password

Unfortunately I don't have any Windows device handy to help you out with.

**Comment by williamcroberts** [comment]
You'd probably get more help if you ask on the mailing list:
  - https://lists.01.org/postorius/lists/tpm2.lists.01.org/

**Comment by kwtj43** [comment]
Thanks William.  I created a thread in the mailing list at https://lists.01.org/hyperkitty/list/tpm2@lists.01.org/thread/VKDDFRLSLQJ4LNELBUE4SAJFOIVY7LLX/

**Comment by bzhu5** [comment]
> AFAICT, Windows 10 starting at version 1607 does not retain the owner password in the registry and sets it to a high entropy value and discards it. So if you want to use it, you need that value. Have you looked into what is discussed in:
> 
> * https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/change-the-tpm-owner-password
> 
> Unfortunately I don't have any Windows device handy to help you out with.

looks like in that system, the OwnerAuth is retained by Windows, because it can be retrieved by executing "Get-Tpm" cmdlet.

**Comment by kwtj43** [comment]
Based on some limited debugging on Windows 10 1809, it appears that Windows does not require the owner auth.  Running the application “as administrator” and providing an empty TPM2B_AUTH (with auths[0].sessionHandle = TPM2_RW_PW) allows me to successfully call functions like…

Tss2_Sys_NV_DefineSpace
Tss2_Sys_NV_UndefineSpace
Tss2_Sys_NV_ReadPublic
Tss2_Sys_NV_Write
Tss2_Sys_StartAuthSession
Tss2_Sys_PolicySecret
Tss2_Sys_Create
Tss2_Sys_FlushContext
Tss2_Sys_PolicySecret
Tss2_Sys_Load
Tss2_Sys_EvictControl
