### ISSUE TITLE
FAPI: Default profile ECC

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tss#1784]
Just wanted to discuss, whether we want to switch the default FAPI profile from RSA2k to ECCP256 upon the 3.0 release.
It can still be changed by the user. It's merely the default config file:
https://github.com/tpm2-software/tpm2-tss/blob/ebfe77b41e677de6cd808e3155fe43d606951143/dist/fapi-config.json.in#L2

**Comment by williamcroberts** [comment]
+1 vote for EC

**Comment by tstruk** [comment]
Security wise ECC-P256 provides the same security level as RSA-3072 so it would make more sense to make the ECC-P256 the default. The question is does all the HW out there support ECC since TCG recommends that at least one of them is implemented? Probably we could go the ECC by default, and document somewhere that if the TPM returns TPM2_RC_KEY the user should fallback to RSA.

**Comment by AndreasFuchsSIT** [comment]
I just realized a potential issue here:
For this to work, we need TPMs to carry ECC-based EK certificates. Otherwise, provisioning will fail; or you have to set the ek-certless option in the config.
Can we assume either of this ?
Maybe we should stick with RSA for a year or two, until ECC-EK-certs are the norm.

**Comment by williamcroberts** [comment]
> I just realized a potential issue here:
> For this to work, we need TPMs to carry ECC-based EK certificates. Otherwise, provisioning will fail; or you have to set the ek-certless option in the config.
> Can we assume either of this ?
> Maybe we should stick with RSA for a year or two, until ECC-EK-certs are the norm.

Why make it so static, could you have a list of things to try or an auto keyword? Probe around and look for the "strongest" cert.

**Comment by AndreasFuchsSIT** [comment]
FAPI follows the idea of crypto cleanness. So if you choose ECC in the profile, there is no RSA anywhere in the stack and vice versa. It's the idea of being save against one crypto breaking. So there is no "strongest cert".

We'd have to change the logic and basic assumptions of FAPI crypto profiles if we wanted something like this and rethink the crypto profile idea principles.

**Comment by AndreasFuchsSIT** [comment]
Ok, I extended the log output in the patch so users get some idea of what's happening.
I am ok with failing provisioning with this info, so PR sent.
