### ISSUE TITLE
ESYS: Allow arbitrary lenght Auth values

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tss#1787]
Following the convention of the TPM library spec part 1, an authValue should be hashed by using nameAlg if it exceeds the max size for the authValue (which is the sizeof(nameAlg)).

Add the appropriate code in all esys-function with auth values, Esys_TR_SetAuth, Esys_CreatePrimary, Esys_Create, Esys_NV_DefineIndex, .....

**Comment by tstruk** [comment]
This is a duplicate of https://github.com/tpm2-software/tpm2-tss/issues/1008

**Comment by AndreasFuchsSIT** [comment]
Good point
