### ISSUE TITLE
How to read the public key created in the FAPI_Create Key

### ISSUE THREAD

**Issue by phanisrinivas13** [tpm2-software/tpm2-tss#1797]
Is the value assigned to "unique" field  in object.json the public key of the created key.

**Comment by phanisrinivas13** [comment]
And what is format of the Public key, is it DER format

**Comment by AndreasFuchsSIT** [comment]
Fapi_Export and pathToPublicKeyOfNewParent=NULL then the PublicKey is exported as PEM
Alternative: Fapi_GetTpmBlobs and the PublicKey is a TPM2B_PUBLIC

**Comment by phanisrinivas13** [comment]
Thank you @AndreasFuchsSIT 

I have used Fapi_GetTpmBlobs, the public key received in TPM2B_PUBLIC doesn't give the exact values as per the object.json, sizes are incorrect, Any unmarshalling required.

I will use the Fapi_Export and share the results, use the Fapi_sign, with some data to sign, received the public key in PEM file and compared with the unique on object.json, it matched with modulus, it helped me to move forward

**Comment by AndreasFuchsSIT** [comment]
Are you sure about the bad sizes ?
I mean you have to call Tss2_MU_TPM2B_PUBLIC_Unmarshal on what's returned from GetTpmBlobs, but that should then work.

**Comment by phanisrinivas13** [comment]
I haven't  called the Tss2_MU_TPM2B_PUBLIC_Unmarshal, Let me do it and get back with the results

**Comment by AndreasFuchsSIT** [comment]
I assume this worked ?
If not, please mention and I'll reopen.
