### ISSUE TITLE
Unable to compile tpm2-tss on RHEL8.1

### ISSUE THREAD

**Issue by vinaykotak** [tpm2-software/tpm2-tss#1804]
I am trying to compile tpm2-tss on RHEL8.1 and its failing on the ./configure step with the following error.

**Configure: error: Package requirements (libcrypto) were not met:
Package 'libcrypto', required by 'virtual:world', not found**

I have verified that libcrypto.so is present on the system.

**[vinay@localhost tpm2-tss]$ ls /usr/lib64/libcrypt
libcrypto.so.1.1         libcryptsetup.so.12.5.0  libcrypt.so.1.1.0
libcrypto.so.1.1.1c      libcrypt.so              
libcryptsetup.so.12      libcrypt.so.**

Is it that the repo uses an older version of the lib.

Any help to fix this will be appreciated.

**Comment by tstruk** [comment]
The libcrypto.so library is provided by the openssl-libs package.
See rpm -q --whatprovides /usr/lib64/libcrypt/libcrypt.so.1.1.0
To build tpm2-tss what is needed on top of that is openssl-devel package.

**Comment by vinaykotak** [comment]
Thanks. That fixed the libcrypto issue. But I am running into a similar issue for json-c now. I have the correct json-c package installed that I see it in /usr/lib64/. I have also checked that the dependencies for this package are installed. I am not sure what is missing.
Is it possible that "sudo dnf builddep tpm2-tss" is not installing all the required dependencies?

**Comment by tstruk** [comment]
Do you have the json-c-devel package installed?

**Comment by vinaykotak** [comment]
I tried that and the install is unable to find the package.

**Comment by tstruk** [comment]
https://rpmfind.net/linux/RPM/centos/8.1.1911/powertools/x86_64/Packages/json-c-devel-0.13.1-0.2.el8.x86_64.html

**Comment by tstruk** [comment]
@vinaykotak is it still not working for you?

**Comment by AndreasFuchsSIT** [comment]
I'll assume it's working now
