### ISSUE TITLE
Sporadic initialisation failures of libtss2-tcti-device with tpm2-tss 3.0.0-rc1: "Failed to read response header fd 3, got errno 0: Success"

### ISSUE THREAD

**Issue by diabonas** [tpm2-software/tpm2-tss#1809]
When running tpm2-tss 3.0.0-rc1 on my system (Arch Linux, kernel 5.7.11) with a discrete (Infineon) TPM, initialisation of `libtss2-tcti-device` sporadically fails with the error message "Failed to read response header fd 3, got errno 0: Success":
```
$ TSS2_LOG=all+trace tpm2_getrandom 1
[...]
debug:tcti:src/tss2-tcti/tctildr-dl.c:245:tctildr_get_default() Attempting to connect using standard TCTI: Access libtss2-tcti-device.so.0 with /dev/tpmrm0
trace:tcti:src/tss2-tcti/tctildr-dl.c:136:tcti_from_file() Attempting to load TCTI file: libtss2-tcti-device.so.0
trace:tcti:src/tss2-tcti/tctildr.c:96:tcti_from_info() Attempting to load TCTI info
trace:tcti:src/tss2-tcti/tctildr.c:103:tcti_from_info() Loaded TCTI info named: tcti-device
trace:tcti:src/tss2-tcti/tctildr.c:104:tcti_from_info() TCTI description: TCTI module for communication with Linux kernel interface.
trace:tcti:src/tss2-tcti/tctildr.c:105:tcti_from_info() TCTI config_help: Path to TPM character device. Default value is: TCTI_DEVICE_DEFAULT
trace:tcti:src/tss2-tcti/tctildr.c:61:tcti_from_init() Initializing TCTI for config: /dev/tpmrm0
debug:tcti:src/tss2-tcti/tcti-device.c:437:Tss2_Tcti_Device_Init() Trying to open specified TCTI device file /dev/tpmrm0
trace:tcti:src/tss2-tcti/tcti-device.c:444:Tss2_Tcti_Device_Init() Successfully opened specified TCTI device file /dev/tpmrm0
debug:tcti:src/tss2-tcti/tcti-device.c:449:Tss2_Tcti_Device_Init() Probe device for partial response read support
debug:tcti:src/util/io.c:87:write_all() writing 12 bytes starting at 0x7ffd92fc87b4 to fd 3
debug:tcti:src/util/io.c:101:write_all() wrote 12 bytes to fd 3
debug:tcti:src/tss2-tcti/tcti-device.c:457:Tss2_Tcti_Device_Init() Command sent, reading header
ERROR:tcti:src/tss2-tcti/tcti-device.c:461:Tss2_Tcti_Device_Init() Failed to read response header fd 3, got errno 0: Success
WARNING:tcti:src/tss2-tcti/tctildr.c:79:tcti_from_init() TCTI init for function 0x7f4442afa230 failed with a000a
WARNING:tcti:src/tss2-tcti/tctildr.c:109:tcti_from_info() Could not initialize TCTI named: tcti-device
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-device.so.0
debug:tcti:src/tss2-tcti/tctildr-dl.c:251:tctildr_get_default() Failed to load standard TCTI number 2
[...]
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:254:tctildr_get_default() No standard TCTI could be loaded
ERROR:tcti:src/tss2-tcti/tctildr.c:416:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI
ERROR: Could not load tcti, got: "(null)"
```
This is probably related to enabling partial reads by default in #1745. Inspecting the return value [`sz`](https://github.com/tpm2-software/tpm2-tss/blob/0a2fe438d1b86825e902011c3044bcfa26357f7f/src/tss2-tcti/tcti-device.c#L460) that triggers this error message reveals that it is always `0` if this issue occurs.

**Comment by diabonas** [comment]
BTW, the same thing happens with tpm2-abrmd as well, so with direct access to `/dev/tpm0` instead of using the in-kernel resource manager.

**Comment by AndreasFuchsSIT** [comment]
My guess is; that code for partial read support is not safe to use in async mode ?
https://github.com/tpm2-software/tpm2-tss/blob/965ef058d8df57bc9b6277ca22aed16b5a856a39/src/tss2-tcti/tcti-device.c#L459

Does it work if you wrap it in a `while ()` ?
```
    do {
        TEMP_RETRY (sz, read (tcti_dev->fd, &rsp[rsp_len], TPM_HEADER_SIZE - rsp_len));
    } while (sz == 0);
```
(I know that this is not safe, but it is a test to see if it might work.)

An actual fix would then also be needed at
https://github.com/tpm2-software/tpm2-tss/blob/965ef058d8df57bc9b6277ca22aed16b5a856a39/src/tss2-tcti/tcti-device.c#L452
https://github.com/tpm2-software/tpm2-tss/blob/965ef058d8df57bc9b6277ca22aed16b5a856a39/src/tss2-tcti/tcti-device.c#L467

And we might want to timeout on 2 seconds on this loop also.

**Comment by diabonas** [comment]
> My guess is; that code for partial read support is not safe to use in async mode ?
> 
> https://github.com/tpm2-software/tpm2-tss/blob/965ef058d8df57bc9b6277ca22aed16b5a856a39/src/tss2-tcti/tcti-device.c#L459
>
> Does it work if you wrap it in a `while ()` ?
> 
> ```
>     do {
>         TEMP_RETRY (sz, read (tcti_dev->fd, rsp, TPM_HEADER_SIZE));
>     } while (sz == 0);
> ```
> 
> (I know that this is not safe, but it is a test to see if it might work.)


That sounds plausible, running `tpm2_getrandom 1` with tpm2-tss 3.0.0-rc1 failed 7 from 50 times I tried it, with this workaround it never failed a hundred times in a row.

**Comment by AndreasFuchsSIT** [comment]
Having tried to get a good implementation together for this, this temporary one seems to be my best guess for a fix for now.

It makes the assumption though, that as soon as the kernel has the first byte available, it has all 13 bytes available.
Not pretty, but better than currently, and I don't know how else to check it.

**Comment by tstruk** [comment]
Thanks for testing this @diabonas. This is most likely due to timing. The fd is opened in N_BLOCK mode and we are reading to fast. Reading it multiple times will only create more problems. We need to add a poll() before the read to make sure there is data to be read. I will update to PR and let you test it again.

**Comment by AndreasFuchsSIT** [comment]
@tstruk What's the behavior of poll on old kernel ?
I thought, old kernels did not support poll() on tpm0, right ?

Will this block forever or return immediately ?

**Comment by tstruk** [comment]
It will return immediately with DEFAULT_POLLMASK, which is all bits (EPOLLIN | EPOLLOUT) set.
