### ISSUE TITLE
Files and directories under /var/lib/tpm2-tss/system/keystore are owned by the user that created them

### ISSUE THREAD

**Issue by diabonas** [tpm2-software/tpm2-tss#1810]
The FAPI directory `/var/lib/tpm2-tss/system/keystore` is owned by the user and group `tss` thanks to the [tmpfiles.d configuration](https://github.com/tpm2-software/tpm2-tss/blob/master/dist/tmpfiles.d/tpm2-tss-fapi.conf.in) (or the [manual fallback](https://github.com/tpm2-software/tpm2-tss/blob/965ef058d8df57bc9b6277ca22aed16b5a856a39/Makefile.am#L599-L602)):
```
$ ls -l /var/lib/tpm2-tss /var/lib/tpm2-tss/system
/var/lib/tpm2-tss:
total 0
drwxr-xr-x 1 tss tss 16 2020-07-30 15:40 system

/var/lib/tpm2-tss/system:
total 0
drwxrwxr-x 1 tss tss 42 2020-07-30 15:40 keystore
```
However, files created under these directories, e.g. using `Fapi_Provision`, are owned by the user that created them:
```
$ ls -l /var/lib/tpm2-tss/system/keystore
total 0
drwxr-xr-x 1 diabonas diabonas 26 2020-07-30 14:00 P_ECCP256SHA256
drwxr-xr-x 1 diabonas diabonas  0 2020-07-30 14:00 policy
```
Since this is the system key store, all files should be modifiable by anybody in the `tss` group. The easiest way to achieve this would be setting the permissions of `/var/lib/tpm2-tss/system/keystore` to `2775`, the `setgid` bit makes sure that all files and directories inherit the group of the parent directory (recursively):
```
$ ls -l /var/lib/tpm2-tss/system/keystore
total 0
drwxr-xr-x 1 diabonas tss 26 2020-07-30 14:00 P_ECCP256SHA256
drwxr-xr-x 1 diabonas tss  0 2020-07-30 14:00 policy
```
However this means if a user created system keys, but is no longer part of the `tss` group, they are still able to modify or delete these keys, which is suboptimal. I see no easy way to avoid this issue (using the `setuid` bit to inherit the owner of the parent directory seems to work under BSD, but not under Linux) other than to remove write access to the group to enforce that all files are created by the `tss` user. This would mean that users will have to take care to run library functions using the `tss` user themselves.

**Comment by AndreasFuchsSIT** [comment]
Would it make sense to set `setuid` as well ? Or does that work differently than `setgid` ?

**Comment by diabonas** [comment]
> Would it make sense to set `setuid` as well ? Or does that work differently than `setgid` ?

This works [on BSD](https://www.freebsd.org/doc/handbook/permissions.html#idp50312312) to inherit the owner, so seems generally the correct thing to do, but unfortunately it is [ignored on Linux](https://superuser.com/questions/471844/why-is-setuid-ignored-on-directories) (and other Unix systems).

**Comment by AndreasFuchsSIT** [comment]
I guess it's our best bet then...

**Comment by diabonas** [comment]
Yeah, I think this is the best we can do with Unix permissions alone, see #1814 for the suggested fix.

**Comment by tstruk** [comment]
We could provide an inotifywait script that will monitor the keystore dir for create events and run chown in response. System admins could run it in the background if they wanted.

**Comment by williamcroberts** [comment]
> We could provide an inotifywait script that will monitor the keystore dir for create events and run chown in response. System admins could run it in the background if they wanted.

Yeah, but think of the race conditions. It'll work "most" of the time, tough to debug.

I always had concerns with the library doing the file system IO and not using a service directly, due to DAC issues. Making a service all the users go to would prevent all of this and allow for finer granularity of control

**Comment by diabonas** [comment]
I agree with @williamcroberts, things like these do not tend to map to file system permissions very well. See the hoops I have to jump through in #1814 while still not solving the issue that former members of the `tss` group can continue modifying files they originally created.

**Comment by AndreasFuchsSIT** [comment]
As a long-term fix, we could introduce a dbus-service to do the storage.
For now I guess this is the way to go.

**Comment by williamcroberts** [comment]
> As a long-term fix, we could introduce a dbus-service to do the storage.
> For now I guess this is the way to go.

I made bug #1816 to capture this for future work.
