### ISSUE TITLE
build error :./configure: line 16817: syntax error near unexpected token `$sysconfdir,'

### ISSUE THREAD

**Issue by tim-rj** [tpm2-software/tpm2-tss#1818]
Help wanted, when i install tpm2-tss in SONIC system by build-debian.sh, below error occurs, what i missing?
```
./configure: line 16817: syntax error near unexpected token `$sysconfdir,'
./configure: line 16817: `AX_RECURSIVE_EVAL($sysconfdir, SYSCONFDIR)'
```

**Comment by AndreasFuchsSIT** [comment]
Could you post the build-debian.sh file and/or config.log file ?

Seems like the directory for` --sysconfdir` might not exist. Should usually be /usr/local/etc or /etc

**Comment by diabonas** [comment]
`AX_RECURSIVE_EVAL` is an Autoconf macro from the [Autoconf Archive](https://www.gnu.org/software/autoconf-archive/) that should not be present in `./configure` at all: it is expanded by Autoconf when generating the configure script from `configure.ac`. You either need to install (or maybe upgrade, if you have a really ancient version) autoconf-archive, or use one of the provided [release tarballs](https://github.com/tpm2-software/tpm2-tss/releases/download/2.4.1/tpm2-tss-2.4.1.tar.gz) that include a prgenerated configure script.

**Comment by tim-rj** [comment]
> 
> 
> Could you post the build-debian.sh file and/or config.log file ?
> 
> Seems like the directory for` --sysconfdir` might not exist. Should usually be /usr/local/etc or /etc
@AndreasFuchsSIT please check log and build-debian.sh

[config.log](https://github.com/tpm2-software/tpm2-tss/files/5019389/config.log)

[build_debian.txt](https://github.com/tpm2-software/tpm2-tss/files/5019386/build_debian.txt)

**Comment by tim-rj** [comment]
@AndreasFuchsSIT @diabonas Add one information, at begining, below errors occurs when do 'bootstrap', so i download 'autoconf-archive-2019.01.06.tar.xz' and put some m4 files into folder autoconfig-temp/m4/ which will be copy to /usr/share/aclocal/ later, maybe there still exist some problems, please help check. (We can find that 'autoconf-archive' is already installed in 'build-debian.sh' attahced above @diabonas  )
```
Generating file lists: src_vars.mk
aclocal: installing 'm4/ax_ac_append_to_file.m4' from '/usr/share/aclocal/ax_ac_append_to_file.m4'
aclocal: installing 'm4/ax_ac_print_to_file.m4' from '/usr/share/aclocal/ax_ac_print_to_file.m4'
aclocal: installing 'm4/ax_add_am_macro_static.m4' from '/usr/share/aclocal/ax_add_am_macro_static.m4'
aclocal: installing 'm4/ax_am_macros_static.m4' from '/usr/share/aclocal/ax_am_macros_static.m4'
aclocal: installing 'm4/ax_check_compile_flag.m4' from '/usr/share/aclocal/ax_check_compile_flag.m4'
aclocal: installing 'm4/ax_check_enable_debug.m4' from '/usr/share/aclocal/ax_check_enable_debug.m4'
aclocal: installing 'm4/ax_check_link_flag.m4' from '/usr/share/aclocal/ax_check_link_flag.m4'
aclocal: installing 'm4/ax_code_coverage.m4' from '/usr/share/aclocal/ax_code_coverage.m4'
aclocal: installing 'm4/ax_compute_relative_paths.m4' from '/usr/share/aclocal/ax_compute_relative_paths.m4'
aclocal: installing 'm4/ax_file_escapes.m4' from '/usr/share/aclocal/ax_file_escapes.m4'
aclocal: installing 'm4/ax_is_release.m4' from '/usr/share/aclocal/ax_is_release.m4'
aclocal: installing 'm4/ax_normalize_path.m4' from '/usr/share/aclocal/ax_normalize_path.m4'
aclocal: installing 'm4/ax_prog_doxygen.m4' from '/usr/share/aclocal/ax_prog_doxygen.m4'
aclocal: installing 'm4/ax_valgrind_check.m4' from '/usr/share/aclocal/ax_valgrind_check.m4'
aclocal: installing 'm4/libtool.m4' from '/usr/share/aclocal/libtool.m4'
aclocal: installing 'm4/ltdl.m4' from '/usr/share/aclocal/ltdl.m4'
aclocal: installing 'm4/ltoptions.m4' from '/usr/share/aclocal/ltoptions.m4'
aclocal: installing 'm4/ltsugar.m4' from '/usr/share/aclocal/ltsugar.m4'
aclocal: installing 'm4/ltversion.m4' from '/usr/share/aclocal/ltversion.m4'
aclocal: installing 'm4/lt~obsolete.m4' from '/usr/share/aclocal/lt~obsolete.m4'
aclocal: installing 'm4/pkg.m4' from '/usr/share/aclocal/pkg.m4'
libtoolize: putting auxiliary files in '.'.
libtoolize: linking file './ltmain.sh'
configure.ac:28: installing './compile'
configure.ac:23: installing './config.guess'
configure.ac:23: installing './config.sub'
configure.ac:12: installing './install-sh'
configure.ac:12: installing './missing'
Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
ERROR: ax_is_release.m4 is outdated. ./configure will fail.
Please download from http://ftpmirror.gnu.org/autoconf-archive/autoconf-archive-2019.01.06.tar.xz
```

**Comment by tim-rj** [comment]
> 
> 
> `AX_RECURSIVE_EVAL` is an Autoconf macro from the [Autoconf Archive](https://www.gnu.org/software/autoconf-archive/) that should not be present in `./configure` at all: it is expanded by Autoconf when generating the configure script from `configure.ac`. You either need to install (or maybe upgrade, if you have a really ancient version) autoconf-archive, or use one of the provided [release tarballs](https://github.com/tpm2-software/tpm2-tss/releases/download/2.4.1/tpm2-tss-2.4.1.tar.gz) that include a prgenerated configure script.

@diabonas after update 'release tarballs', configure works fine, but below error occurs:
```

+ sudo make -j5
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /sonic/tpm2-tss/missing aclocal-1.16 -I m4 --install
/sonic/tpm2-tss/missing: line 81: aclocal-1.16: command not found
WARNING: 'aclocal-1.16' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <https://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <https://www.gnu.org/software/autoconf>
         <https://www.gnu.org/software/m4/>
         <https://www.perl.org/>
Makefile:8502: recipe for target 'aclocal.m4' failed
make: *** [aclocal.m4] Error 127

```

**Comment by tim-rj** [comment]
@diabonas @AndreasFuchsSIT Thanks, after updating release tarballs, installation has pass!!
