### ISSUE TITLE
README.md warning

### ISSUE THREAD

**Issue by paulduongemail** [tpm2-software/tpm2-tss#1819]
Hi there,
I'm trying to install tpm2-tss- engine in openssl, I'm running with Ubuntu 20.04
I followed instruction with: https://github.com/tpm2-software/tpm2-tss-engine/blob/master/INSTALL.md
Everything is going fine, untill I run

./configure

I got:

> ...
> configure: creating ./config.status
> config.status: creating Makefile
> config.status: creating Doxyfile
> config.status: executing libtool commands
> config.status: executing depfiles commands
> config.status: error: in `/home/paul/Documents/tpm2-tss':
> config.status: error: Something went wrong bootstrapping makefile fragments
>     for automatic dependency tracking.  Try re-running configure with the
>     '--disable-dependency-tracking' option to at least be able to build
>     the package (albeit without support for automatic dependency tracking).
> See `config.log' for more details

Then I run ./configure --disable-dependency-tracking
and I got:

> ...
> checking that generated files are newer than configure... done
> configure: creating ./config.status
> config.status: creating Makefile
> config.status: creating Doxyfile
> config.status: executing libtool commands
> config.status: executing depfiles commands
>     tpm2-tss 2.2.3
>     esapi:              yes
>     tctidefaultmodule:
>     tctidefaultconfig:
>     unit:               no
>     debug:              no
>     maxloglevel:        trace
>     doxygen:            1
>     tcti-device-async:  no
>     tcti-partial-read:  no
>     crypto backend:     ossl

Seems like okay right?
Then I tried make -j$(nproc)
and I got:

> ...
>   DXGEN  Doxyfile
> warning: Tag 'PERL_PATH' at line 2188 of file 'Doxyfile' has become obsolete.
>          To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
> warning: Tag 'MSCGEN_PATH' at line 2210 of file 'Doxyfile' has become obsolete.
>          To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
> /home/paul/Documents/tpm2-tss/README.md:36: warning: unable to resolve reference to 'INSTALL.md' for \ref command
> /home/paul/Documents/tpm2-tss/README.md:42: warning: unable to resolve reference to 'CONTRIBUTING.md' for \ref command
> /home/paul/Documents/tpm2-tss/README.md:67: warning: unable to resolve reference to 'INSTALL.md' for \ref command
> /home/paul/Documents/tpm2-tss/README.md:36: warning: unable to resolve reference to 'INSTALL.md' for \ref command
> /home/paul/Documents/tpm2-tss/README.md:42: warning: unable to resolve reference to 'CONTRIBUTING.md' for \ref command
> /home/paul/Documents/tpm2-tss/README.md:67: warning: unable to resolve reference to 'INSTALL.md' for \ref command

These warnings did not look good, but I still try to sudo make install and got few warnings.

After this, I skipped the integration test section and directly test if tpm2tss engine was installed in openssl.

I try to run: openssl engine -t -c tpm2tss
and I got:

> 140423545849152:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:../crypto/dso/dso_dlfcn.c:118:filename(/usr/lib/x86_64-linux-gnu/engines-1.1/tpm2tss.so): /usr/lib/x86_64-linux-gnu/engines-1.1/tpm2tss.so: cannot open shared object file: No such file or directory
> 140423545849152:error:25070067:DSO support routines:DSO_load:could not load the shared library:../crypto/dso/dso_lib.c:162:
> 140423545849152:error:260B6084:engine routines:dynamic_load:dso not found:../crypto/engine/eng_dyn.c:414:
> 140423545849152:error:2606A074:engine routines:ENGINE_by_id:no such engine:../crypto/engine/eng_list.c:334:id=tpm2tss

I failed apparently.

So, if I look back, I think the problem is in the step make -j$(nproc) right?

Do you know how to fix that?

Thanks!

**Comment by williamcroberts** [comment]
Smells like an autoconf-archive issue, any luck on building and supplying a particular autoconf archive?
https://gitlab.gnome.org/GNOME/libgdata/-/issues/24

**Comment by tstruk** [comment]
> I try to run: openssl engine -t -c tpm2tss
> and I got:

Is the install of tpm2-tss libs failing or the engine?
After you installed tpm2-tss did you also follow the steps described here:
https://github.com/tpm2-software/tpm2-tss-engine/blob/master/INSTALL.md?

**Comment by paulduongemail** [comment]
Hi there,

Thanks for your helping!

Today I decide to use older version of Ubuntu 18.04 and I went much further this time.

In order to get tpm2-tss-engine running in OpenSSL, I followed these two documents:

https://github.com/tpm2-software/tpm2-tools/blob/master/doc/INSTALL.md

and install rpm2-tss-engine

Version summary:
Ubuntu 18.04
tpm2-tools 4.0.X
tpm2-abrmd default
tpm2-tss-engine v1.1.x
tpm2-tss 2.3.x

The reason why I choose these version is these version give me less error (I don't know why).
After install these, when I run:

openssl engine -t -c tpm2tss

I got:

(tpm2tss) TPM2-TSS engine for OpenSSL
 [RSA, RAND]
     [ available ]

Looks good right? But when I try to run

openssl rand -engine tpm2tss -hex 10

I got:

engine "tpm2tss" set.
ERROR:tcti:src/tss2-tcti/tcti-device.c:440:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpmrm0: No such file or directory 
WARNING:tcti:src/tss2-tcti/tctildr.c:79:tcti_from_init() TCTI init for function 0x7effeaa8ecb0 failed with a000a 
WARNING:tcti:src/tss2-tcti/tctildr.c:109:tcti_from_info() Could not initialize TCTI named: tcti-device 
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:150:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-device.so.0 
ERROR:tcti:src/tss2-tcti/tcti-device.c:440:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: No such file or directory 
WARNING:tcti:src/tss2-tcti/tctildr.c:79:tcti_from_init() TCTI init for function 0x7effeaa8ecb0 failed with a000a 
WARNING:tcti:src/tss2-tcti/tctildr.c:109:tcti_from_info() Could not initialize TCTI named: tcti-device 
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:150:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-device.so.0 
WARNING:tcti:src/util/io.c:252:socket_connect() Failed to connect to host 127.0.0.1, port 2321: errno 111: Connection refused 
WARNING:tcti:src/tss2-tcti/tctildr.c:79:tcti_from_init() TCTI init for function 0x7effeaa8e1b0 failed with a000a 
WARNING:tcti:src/tss2-tcti/tctildr.c:109:tcti_from_info() Could not initialize TCTI named: tcti-socket 
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:150:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-mssim.so.0 
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:248:tctildr_get_default() No standard TCTI could be loaded 
ERROR:tcti:src/tss2-tcti/tctildr.c:415:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI 
139637650760128:error:8007306F:tpm2-tss-engine:esys_ctx_init:Some unknown error occured:src/tpm2-tss-engine-common.c:81:
139637650760128:error:8008206D:tpm2-tss-engine:rand_bytes:Unknown TPM error occured. Please check tpm2tss logs:src/tpm2-tss-engine-rand.c:58:

Can you help me figure out what is wrong this time?

Thanks!

btw I'm a new bee in tpm2-tss and linux, if it's not too tedious please give me more hint.

Thanks again!

**Comment by tstruk** [comment]
It looks to me that you don't have any TPM2 hardware in your system, and you didn't start any software based emulator so it can't connect to anything and gives up after trying all possible options.

**Comment by paulduongemail** [comment]
@tstruk That make a lot of sense, cause I ran command in Ubuntu virtualbox. So I'm suppose to launch a TPM simulator first right?

In this document:
https://github.com/tpm2-software/tpm2-tools/blob/master/doc/INSTALL.md

TPM simulator
$ mkdir ibmtpm && cd ibmtpm
$ wget https://sourceforge.net/projects/ibmswtpm2/files/latest/download -O ibmtpm.tar.gz
$ tar -zxvf ibmtpm.tar.gz
$ cd src
$ make -j5

After make -j5, do I need to do something like: **_sudo cp ibmtpm/src/tpm_server /usr/local/bin_** to launch the simulator?

To be honest, I'm a little confused here, like how to intall and launch a tpm simulator? Do I need to keep it in a single terminal and open another terminal to run the openssl command?

Thanks for you helping! You are very helpful.

**Comment by tstruk** [comment]
@paulduongemail yes, start the simulator in a separate terminal before running the openssl rand command. It should start talking to it then and you should see something like:
Command IPv4 client accepted
Platform IPv4 client accepted
output from the simulator when the tpm2tss will connect to it.

**Comment by paulduongemail** [comment]
@tstruk 
I launch the simulator succesfully

paul@paul-VirtualBox:~/Documents/ibmtpm/src$ tpm_server
LIBRARY_COMPATIBILITY_CHECK is ON
Manufacturing NV state...
Size of OBJECT = 2600
Size of components in TPMT_SENSITIVE = 1096
    TPMI_ALG_PUBLIC                 2
    TPM2B_AUTH                      66
    TPM2B_DIGEST                    66
    TPMU_SENSITIVE_COMPOSITE        962
Starting ACT thread...
TPM command server listening on port 2321
Platform server listening on port 2322
Command IPv4 client accepted
Platform IPv4 client accepted
Platform server listening on port 2322
TPM command server listening on port 2321

but when I try to run openssl rand command, I get rid of some error and get some new error too:

the privious errors:
paul@paul-VirtualBox:~$ openssl rand -engine tpm2tss -hex 10
engine "tpm2tss" set.
ERROR:tcti:src/tss2-tcti/tcti-device.c:440:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpmrm0: No such file or directory 
WARNING:tcti:src/tss2-tcti/tctildr.c:79:tcti_from_init() TCTI init for function 0x7f9b5045fcb0 failed with a000a 
WARNING:tcti:src/tss2-tcti/tctildr.c:109:tcti_from_info() Could not initialize TCTI named: tcti-device 
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:150:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-device.so.0 
ERROR:tcti:src/tss2-tcti/tcti-device.c:440:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: No such file or directory 
WARNING:tcti:src/tss2-tcti/tctildr.c:79:tcti_from_init() TCTI init for function 0x7f9b5045fcb0 failed with a000a 
WARNING:tcti:src/tss2-tcti/tctildr.c:109:tcti_from_info() Could not initialize TCTI named: tcti-device 
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:150:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-device.so.0 
WARNING:tcti:src/util/io.c:252:socket_connect() Failed to connect to host 127.0.0.1, port 2321: errno 111: Connection refused 
WARNING:tcti:src/tss2-tcti/tctildr.c:79:tcti_from_init() TCTI init for function 0x7f9b5045f1b0 failed with a000a 
WARNING:tcti:src/tss2-tcti/tctildr.c:109:tcti_from_info() Could not initialize TCTI named: tcti-socket 
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:150:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-mssim.so.0 
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:248:tctildr_get_default() No standard TCTI could be loaded 
ERROR:tcti:src/tss2-tcti/tctildr.c:415:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI 
140305075483072:error:8007306F:tpm2-tss-engine:esys_ctx_init:Some unknown error occured:src/tpm2-tss-engine-common.c:81:
140305075483072:error:8008206D:tpm2-tss-engine:rand_bytes:Unknown TPM error occured. Please check tpm2tss logs:src/tpm2-tss-engine-rand.c:58:

current errors:
paul@paul-VirtualBox:~$ openssl rand -engine tpm2tss -hex 10
engine "tpm2tss" set.
ERROR:tcti:src/tss2-tcti/tcti-device.c:440:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpmrm0: No such file or directory 
WARNING:tcti:src/tss2-tcti/tctildr.c:79:tcti_from_init() TCTI init for function 0x7f7ed52aecb0 failed with a000a 
WARNING:tcti:src/tss2-tcti/tctildr.c:109:tcti_from_info() Could not initialize TCTI named: tcti-device 
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:150:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-device.so.0 
ERROR:tcti:src/tss2-tcti/tcti-device.c:440:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: No such file or directory 
WARNING:tcti:src/tss2-tcti/tctildr.c:79:tcti_from_init() TCTI init for function 0x7f7ed52aecb0 failed with a000a 
WARNING:tcti:src/tss2-tcti/tctildr.c:109:tcti_from_info() Could not initialize TCTI named: tcti-device 
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:150:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-device.so.0 
WARNING:esys:src/tss2-esys/api/Esys_GetRandom.c:277:Esys_GetRandom_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_GetRandom.c:95:Esys_GetRandom() Esys Finish ErrorCode (0x00000100) 
140182751027648:error:8008206D:tpm2-tss-engine:rand_bytes:Unknown TPM error occured. Please check tpm2tss logs:src/tpm2-tss-engine-rand.c:65:

I compare these errors and I find these two lines are new:
WARNING:esys:src/tss2-esys/api/Esys_GetRandom.c:277:Esys_GetRandom_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_GetRandom.c:95:Esys_GetRandom() Esys Finish ErrorCode (0x00000100) 

Any idea?

Thanks!

**Comment by tstruk** [comment]
Yes, the tpm_simulator is not started. So you could do this:
restart the simulator in a separate terminal, then call tpm2_startup -c -Tmssim, and then call openssl rand.
You can also set a TSS2_LOG="all+none" to quite the tcti warnings when it tries to connect to the TPM device.

**Comment by paulduongemail** [comment]
Yes! It works!
Thank you so much @tstruk !

I think I have my last question, can you be more specified where should I set TSS2_LOG? Pass like a option in OpenSSL command?

**Comment by tstruk** [comment]
> I think I have my last question, can you be more specified where should I set TSS2_LOG? Pass like a option in OpenSSL command?

no, just do:
export TSS2_LOG="all+NONE"
in the terminal where you run the openssl commands.

**Comment by paulduongemail** [comment]
Yes, everything looks fine now!

Thank you @tstruk !

You can close this issue now.
