### ISSUE TITLE
Error while creating key with Fapi_CreateKey

### ISSUE THREAD

**Issue by fbzavaleta** [tpm2-software/tpm2-tss#1823]
I am using the Fapi library to create a key, my environment is Linux and i have a Asus TPM2 module.I created the context, called the Fapi_Initialize function and try to creating the key:

Fapi_CreateKey(fapi_context, "HS/SRK/mySignKey", NULL, NULL, NULL);

and it return:
ERROR:fapi:src/tss2-fapi/ifapi_keystore.c:456:rel_path_to_abs_path() ErrorCode (0x00060020) Key P_RSA2048SHA256/HS/SRK not found. 
ERROR:fapi:src/tss2-fapi/ifapi_keystore.c:497:ifapi_keystore_load_async() ErrorCode (0x00060020) Object P_RSA2048SHA256/HS/SRK not found. 
ERROR:fapi:src/tss2-fapi/fapi_util.c:697:ifapi_load_primary_async() ErrorCode (0x00060020) Could not open: P_RSA2048SHA256/HS/SRK 
ERROR:fapi:src/tss2-fapi/fapi_util.c:1097:ifapi_get_sessions_async() ErrorCode (0x00060020) Load EK 
ERROR:fapi:src/tss2-fapi/fapi_util.c:2992:ifapi_key_create() ErrorCode (0x00060020) Create sessions 
WARNING:esys:src/tss2-esys/api/Esys_FlushContext.c:234:Esys_FlushContext_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_FlushContext.c:89:Esys_FlushContext() Esys Finish ErrorCode (0x000001c4) 
ERROR:fapi:src/tss2-fapi/fapi_util.c:945:ifapi_session_clean() Cleanup Policy Session  failed. 
ERROR:fapi:src/tss2-fapi/api/Fapi_CreateKey.c:229:Fapi_CreateKey_Finish() Key create ErrorCode (0x00060020) 
ERROR:fapi:src/tss2-fapi/api/Fapi_CreateKey.c:109:Fapi_CreateKey() ErrorCode (0x00060020) Key_Create 

Apparently it doesn't find the keystore paths, any ideas?

**Comment by tstruk** [comment]
You may want to call Fapi_Provision() beforehand. See paragraph 5.1 of the Fapi spec for more info:
https://trustedcomputinggroup.org/wp-content/uploads/TSS_FAPI_v0.94_r04_pubrev.pdf

**Comment by fbzavaleta** [comment]
Hi tstruk, thanks for your answer,

When i try to call Fapi_provision(), i get the follow error:
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:739:Fapi_Provision_Finish() Evict control failed ErrorCode (0x0000014c) 
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:120:Fapi_Provision() ErrorCode (0x0000014c) Provision 

On my log system appear : 
tpm tpm0: tpm_try_transmit: tpm_send :  error -5

I am working on Linux-debian, could be any driver?

best regards,

**Comment by AndreasFuchsSIT** [comment]
You probably already have made a key persistent on the handle.
Look at the fapi-profile you're using and change the srk handle from 0x81000001 to something else or call tpm2_evictcontrol if you don't need the current persistent key.
P.S. The current persistent key may stem from tpm2-pkcs11

**Comment by AndreasFuchsSIT** [comment]
I assume everything is working now.
If not, please mention and I'll reopen.
