### ISSUE TITLE
Not able to compile getting undefined reference error.

### ISSUE THREAD

**Issue by SSkum** [tpm2-software/tpm2-tss#1825]
Hi , 
I am beginner to TPM. I have setup my centos8 machine as mention in the README instructions.
After that i tried to include the header file and build one small program.But when i try to call Esys_Initialize() i am getting undefined reference to function error.
This is sample code--

[test.txt](https://github.com/tpm2-software/tpm2-tss/files/5033288/test.txt)

I want to generate random number using esys. I have checked test/integration/esys-get-random.int.c for that i need a esys_context so i called  Esys_Initialize().

Below is error info --
[root@SERVER tpm]# gcc test.c
/tmp/ccUvOoY1.o: In function `main':
test.c:(.text+0x32): undefined reference to `Esys_Initialize'
collect2: error: ld returned 1 exit status

Thanks in advance.

**Comment by tstruk** [comment]
The linker doesn't know where to find Esys_Initialize so it fails. Maybe try something like:
$ gcc -o test test.c `pkg-config --cflags --libs tss2-esys`

**Comment by SSkum** [comment]
Thanks you so much . now it is working for me.
