### ISSUE TITLE
Unit test tcti-pcap does not compile on raspian

### ISSUE THREAD

**Issue by JuergenReppSIT** [tpm2-software/tpm2-tss#1826]
https://github.com/tpm2-software/tpm2-tss/blob/4b7441bbcf760400fd846e090f984586d319d4ae/test/unit/tcti-pcap.c#L36
does not compile on raspian because on raspian sizeof(time_t) is 4 not 8:

> `test/unit/tcti-pcap.c:36:35: error: overflow in conversion from ‘long long unsigned int’ to ‘__time_t’ {aka ‘long int’} changes value from ‘3684526138843’ to ‘-555801125’ [-Werror=overflow]
 #define TCTI_PCAP_TIMESTAMP_SEC   (0x3322110077665544UL / 1000000)
                                   ^
test/unit/tcti-pcap.c:266:22: note: in expansion of macro ‘TCTI_PCAP_TIMESTAMP_SEC’
         tp->tv_sec = TCTI_PCAP_TIMESTAMP_SEC;
                      ^~~~~~~~~~~~~~~~~~~~~~~`

**Comment by tstruk** [comment]
Quick fix: https://github.com/tpm2-software/tpm2-tss/pull/1829
@joholl please have a look let me know if you are fine with it.

**Comment by joholl** [comment]
I did not account for 32-bit platforms where `__time_t` aka `long` is 32 bit.

Your patch does not fix an overflow which occurs in the pcap builder due to the 32 bit longs. I submitted a PR.
