### ISSUE TITLE
How can I install tpm2-tss under Windows? Want some help.

### ISSUE THREAD

**Issue by paulduongemail** [tpm2-software/tpm2-tss#1828]
Hi there,

I went through your repo document, I only find a few paragraphs mentioned Windows. Do you have updated supporting documents or further suggestion about installing tpm2-tss under Windows?

I have a running instance in Ubuntu with you guys help, thank you so much! I appreciate it.

Thanks.

**Comment by tstruk** [comment]
You can build tpm2-tss for windows with Visual Studio 17 with clang backend using this project file https://github.com/tpm2-software/tpm2-tss/blob/master/tpm2-tss.sln
See also https://github.com/tpm2-software/tpm2-tss/blob/master/INSTALL.md#windows for more info.

**Comment by paulduongemail** [comment]
@tstruk 
Hi,

If I understand correctly, the only environment you test for Windows is:
VS 2017 with v141_clang_c2
UCRT 10.0.16299.0
OpenSSL >= 1.0.2
right?

With this configuration I'm suppose to be able to build tpm2-tss right?

So, how could I know if I build it successfully?
Could I run command "openssl engine -t -c tpm2tss" to check?

Or, in order to using tpm2-tss-engine in OpenSSL to generate key and CSR, is there any extra step I need accomplish?

Thanks!

**Comment by williamcroberts** [comment]
> @tstruk
> Hi,
> 
> If I understand correctly, the only environment you test for Windows is:
> VS 2017 with v141_clang_c2
> UCRT 10.0.16299.0
> OpenSSL >= 1.0.2
> right?
> 
> With this configuration I'm suppose to be able to build tpm2-tss right?
> 
> So, how could I know if I build it successfully?
> Could I run command "openssl engine -t -c tpm2tss" to check?

No, that would be for tpm2-tss-engine project, which provides an openssl engine. This project, tpm2-tss, only provides tpm2 API as defined by TCG.

> 
> Or, in order to using tpm2-tss-engine in OpenSSL to generate key and CSR, is there any extra step I need accomplish?

You need to build both the tpm2-tss project, the tpm2-tss-engine project and then install them properly in windows. Ive never done this personally, but those are MS Visual Studio build files, so you need to import the project into Visual Studio and build each project. How to install in windows, I don't know how to do. I generally avoid Windows.

**Comment by paulduongemail** [comment]
@williamcroberts 
Thanks for your info!

So, if I only work with tpm2-tss, at least I can generate TPM key with it right?
e.g. command: tpm2tss-genkey -a rsa -s 2048 myTPMPriKey.pem

Like I asked above, even if I build tpm2-tss successfully, how do I test it or install it?

I know you may don't have the answer cause you haven't worked on it in Windows yet, but my team would like to estimate the risk to use this tech stack in Windows. So please tell me more. I really appreciate.

Thanks.

**Comment by williamcroberts** [comment]
> @williamcroberts
> Thanks for your info!
> 
> So, if I only work with tpm2-tss, at least I can generate TPM key with it right?
> e.g. command: tpm2tss-genkey -a rsa -s 2048 myTPMPriKey.pem

That command belongs to the tpm2-tss-engine project. You would need to build the tpm2-tss-engine project on windows, and that has no VS project files (files with the .vcxproj) like tpm2-tss project does.

> 
> Like I asked above, even if I build tpm2-tss successfully, how do I test it or install it?

I'm not sure exactly, sorry. Its gonna be some form of get it into MS Visual Studios and build it, and the test framework and run the tests, or manually test it with openssl commands.

> 
> I know you may don't have the answer cause you haven't worked on it in Windows yet, but my team would like to estimate the risk to use this tech stack in Windows. So please tell me more. I really appreciate.

Risk on the technology, I would say low. You will need to figure out the building and testing process. So the risk is more on the technical capabilities of your team, since we don't have that work done and documented yet.

> 
> Thanks.

**Comment by williamcroberts** [comment]
I would suggest asking this question on our mailing list, you would reach a wider audience who might be able to help. https://lists.01.org/postorius/lists/tpm2.lists.01.org/

**Comment by paulduongemail** [comment]
Thanks! @williamcroberts 

I'll try with mailing list. And hope you will come up with solution for Windows in the future.

Thanks.

**Comment by paulduongemail** [comment]
@williamcroberts @tstruk 
Hi, I'm trying to build tpm2-tss in VS 2017, I found few lines in file tpm2-tss\src\tss2-esys\esys_crypto_ossl.c

#include <openssl/evp.h>
#include <openssl/aes.h>
#include <openssl/rsa.h>
#include <openssl/engine.h>

but I can not find the folder openssl in tss2-esys source folder, what should I do?

I try to copy those files from C:\OpenSSL-Win64\lib to tss2-esys\openssl folder but I got some errors like:

esys_crypto_ossl.obj : error LNK2019: unresolved external symbol EVP_MD_CTX_new referenced in function iesys_cryptossl_hash_start
esys_crypto_ossl.obj : error LNK2019: unresolved external symbol EVP_MD_CTX_free referenced in function iesys_cryptossl_hash_start

Can you help me out of this? Or where can I find those right openssl header files?

It feels like the files I copied can not work with tpm2-tss.

Thanks!

**Comment by paulduongemail** [comment]
And when I try to build solution in Debug|x64 I also got this warning:

C:\OpenSSL-Win64\lib\libeay32.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'

Then I download libeay64.lib and add it in C:\OpenSSL-Win64\lib. Also I modified file tpm2-tss\src\tss2-esys\tss2-esys.vcxproj
...
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <ClCompile>
      <AdditionalIncludeDirectories>$(SolutionDir);$(SolutionDir)\src;$(SolutionDir)\include\tss2;$(SolutionDir)\src\tss2-mu;$(SolutionDir)\src\tss2-sys;$(SolutionDir)\src\tss2-esys;C:\OpenSSL-Win64\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <PreprocessorDefinitions>_DEBUG;_WINDOWS;_USRDLL;TSS2ESYS_EXPORTS;MAXLOGLEVEL=6;strtok_r=strtok_s;OSSL;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ClCompile>
    <Link>
      **_<AdditionalDependencies>$(OutDir)\tss2-mu.lib;$(OutDir)\tss2-sys.lib;$(OutDir)\tss2-tctildr.lib;C:\OpenSSL-Win64\lib\libeay32.lib;%(AdditionalDependencies)</AdditionalDependencies>_**
      <ModuleDefinitionFile>$(SolutionDir)\lib\tss2-esys.def</ModuleDefinitionFile>
    </Link>
  </ItemDefinitionGroup>
...
I changed libeay32.lib to libeay64.lib, and I successfully get rid of that warning, but I got bunch of new errors:

libeay64.lib(pem_lib.obj) : error LNK2001: unresolved external symbol __iob_func
libeay64.lib(cryptlib.obj) : error LNK2001: unresolved external symbol __iob_func
libeay64.lib(e_capi.obj) : error LNK2001: unresolved external symbol __iob_func
libeay64.lib(gost_eng.obj) : error LNK2001: unresolved external symbol __iob_func
libeay64.lib(ui_openssl.obj) : error LNK2001: unresolved external symbol __iob_func
libeay64.lib(cryptlib.obj) : error LNK2019: unresolved external symbol sscanf referenced in function OPENSSL_cpuid_setup
libeay64.lib(v3_utl.obj) : error LNK2001: unresolved external symbol sscanf
libeay64.lib(cryptlib.obj) : error LNK2019: unresolved external symbol _vsnwprintf referenced in function OPENSSL_showfatal
libeay64.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertOpenStore referenced in function capi_open_store
libeay64.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertCloseStore referenced in function capi_find_key
libeay64.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertEnumCertificatesInStore referenced in function capi_find_cert
libeay64.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertFindCertificateInStore referenced in function capi_find_cert
libeay64.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertDuplicateCertificateContext referenced in function capi_load_ssl_client_cert
libeay64.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertFreeCertificateContext referenced in function capi_rsa_free
libeay64.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertGetCertificateContextProperty referenced in function capi_cert_get_fname
libeay64.lib(gost_eng.obj) : error LNK2019: unresolved external symbol printf referenced in function bind_gost

Do you have any idea?

Thanks!

**Comment by williamcroberts** [comment]
> @williamcroberts @tstruk
> Hi, I'm trying to build tpm2-tss in VS 2017, I found few lines in file tpm2-tss\src\tss2-esys\esys_crypto_ossl.c
> 
> #include <openssl/evp.h>
> #include <openssl/aes.h>
> #include <openssl/rsa.h>
> #include <openssl/engine.h>
> 
> but I can not find the folder openssl in tss2-esys source folder, what should I do?

Thats an external library dependency, you would need to install a development version of openssl on windows.

> 
> I try to copy those files from C:\OpenSSL-Win64\lib to tss2-esys\openssl folder but I got some errors like:
> 
> esys_crypto_ossl.obj : error LNK2019: unresolved external symbol EVP_MD_CTX_new referenced in function iesys_cryptossl_hash_start
> esys_crypto_ossl.obj : error LNK2019: unresolved external symbol EVP_MD_CTX_free referenced in function iesys_cryptossl_hash_start
> 
> Can you help me out of this? Or where can I find those right openssl header files?
> 
> It feels like the files I copied can not work with tpm2-tss.
> 
> Thanks!

I think you need to tell visual studios about OpenSSL
https://stackoverflow.com/questions/11383942/how-to-use-openssl-with-visual-studio

And build the DebugX64 configuration:
https://docs.microsoft.com/en-us/visualstudio/mac/configurations?view=vsmac-2019

**Comment by paulduongemail** [comment]
@williamcroberts @tstruk 
Is me again, after couple of days I got tpm2-tss built finally.

In tss2-esys.vcxproj, you'd better change OpenSSL additional dependency from libeay32.lib to libcrypto.lib
cause in newer version of OpenSSL there is no libeay32.lib or libeay64.lib anymore.

For reference, I configured the project like this:

![Capture03](https://user-images.githubusercontent.com/61701587/91085968-3885ff80-e61c-11ea-9c20-6ad7242d5f01.PNG)

I got no error and all 7 sub-project was compiled ass .dll

I'll keep working on this, but I need further support from you.

Like, cause I'm new to TPM TSS, could you please introduce me they relation between tpm2-tss and tpm2-tss-engine?

Base on my knowledge, if you built tpm2-tss successfully in .dll, you can use the APIs implemented in it as a external lib by copy those .dll files under you personal project.

Then what did tpm engine do? Dose it work like a interface connecting to OpenSSL?

Thanks!

**Comment by williamcroberts** [comment]
> @williamcroberts @tstruk
> Is me again, after couple of days I got tpm2-tss built finally.
> 
> In tss2-esys.vcxproj, you'd better change OpenSSL additional dependency from libeay32.lib to libcrypto.lib
> cause in newer version of OpenSSL there is no libeay32.lib or libeay64.lib anymore.
> 
> For reference, I configured the project like this:
> 
> ![Capture03](https://user-images.githubusercontent.com/61701587/91085968-3885ff80-e61c-11ea-9c20-6ad7242d5f01.PNG)
> 
> I got no error and all 7 sub-project was compiled as .dll
> 
> I'll keep working on this, but I need further support from you.
> 
> Cause I'm a fresh guy in TPM TSS, could you please introduce me the relation between tpm2-tss and tpm2-tss-engine?
> 
> Base on my knowledge, if you built tpm2-tss successfully in .dll, you can use the APIs implemented in it as a external lib by copy those .dll files under you personal project.
> 
> Then what did tpm engine do? Dose it work like a interface connecting to OpenSSL?

tpm2-tss is a set of libraries for getting API level calls, like tss2-esys (ESAPI library) to TPM commands, and getting a response from the TPM back to the application making the API call. Generally, they're the lowest form suitable for interacting with the TPM.

tpm2-tss-engine is an engine for OpenSSL. OpenSSL has an engine interface, where you can configure new engines to allow OpenSSL to work with things other than software cryptography. You can build an engine to work with your specific hardware crypto device. So that project, creates an OpenSSL Engine that interacts with the TPM, so you can use all the familair OpenSSL API's and commandline tools.

**Comment by paulduongemail** [comment]
@williamcroberts 

Great expaination. Thanks!

I just noticed that in order to add an engine into OpenSSL, I need configure OpenSSL first, and OpenSSL will interact with the engine by file libtpm2tss.so

Cause I have a running instance of tpm engine in Ubuntu, can I just copy those related files wo Windows? Do you think it will work?

And, can you explain what are the duties of tpm2-tools and tpm-abrmd? Cause we also need those two projects get involved with right?

**Comment by paulduongemail** [comment]
Never mind, copy won't work I figure it out.

Please just provide some introduction of tpm2-tools and tpm2-abrmd.

Thanks!

**Comment by williamcroberts** [comment]
> Never mind, copy won't work I figure it out.
> 
> Please just provide some introduction of tpm2-tools and tpm2-abrmd.
> 
> Thanks!

tpm2-abrmd I don't think will work on Windows, because it uses dbus. Not exactly sure what tcti one would use to interact with it on Windows, see this bug: https://github.com/tpm2-software/tpm2-tss/pull/82

@AndreasFuchsSIT any ideas?

**Comment by paulduongemail** [comment]
@tstruk @williamcroberts 

Hi,

I have a question, I noticed in your document, in order to get a pri-pub key pair

First, I need to run this command to get a TPM private key
```tpm2tss-genkey -a rsa -s 2048 mykey```

Then I need to run command
```openssl rsa -engine tpm2tss -inform engine -in mykey -pubout -outform pem -out mykey.pub```
in order to get the corresponding public key.

Still now am I on the right track?

So my question is, OpenSSL can generate public key for private key without any extension right? Why do I have to use this tpm-engine? 

Next, do I have to use tpm2tss-genkey for TPM private key generation?

Is there any way to generate TPM private key with tpm engine?

If so, please tell me what's that looks like.

Thanks!

**Comment by AndreasFuchsSIT** [comment]
tpm2tss-genkey will generate a TPM private key and store it in the PEM-file alongside the public key. The private key is of course encrypted with a TPM primary key.

Using the tpm2tss engine informs openssl to use this engine and the private key, since openssl is not intelligent enough to autodetect this from the pem file.

I'll close this for now, since it appears not to be a bug.
