### ISSUE TITLE
Bad return value

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tss#1842]
This should be -1 since it's a ssize_t return type

https://github.com/tpm2-software/tpm2-tss/blob/e025f59723e0c0e2a6c9556643f1e71902af5df2/src/util/io.c#L61

Reported by @PeterHuewe

**Comment by williamcroberts** [comment]
Is this what causes #1842?

**Comment by tstruk** [comment]
Don't these both map to unsigned int? TSS2_TCTI_RC_TRY_AGAIN type is TSS2_RC which is uint32_t
and ssize_t is basically the same. Anyway we could change it to return EAGAIN instead of TSS2_TCTI_RC_TRY_AGAIN and then remap it to TSS2_TCTI_RC_TRY_AGAIN in the higher level code. I will try to put a PR today.

**Comment by tstruk** [comment]
From the first glimpse looks like any error is translated to TSS2_TCTI_RC_IO_ERROR in both mssim_tcti and swtpm_tcti so it should be save just to change it to return EAGAIN. The whole retry logic is implemented around the poll() calls.

**Comment by tstruk** [comment]
PR https://github.com/tpm2-software/tpm2-tss/pull/1843

**Comment by williamcroberts** [comment]
> Don't these both map to unsigned int? TSS2_TCTI_RC_TRY_AGAIN type is TSS2_RC which is uint32_t
> and ssize_t is basically the same. 

ssize_t is signed, size_t is the one you're thinking of.

**Comment by tstruk** [comment]
> > Don't these both map to unsigned int? TSS2_TCTI_RC_TRY_AGAIN type is TSS2_RC which is uint32_t
> > and ssize_t is basically the same.
> 
> ssize_t is signed, size_t is the one you're thinking of.

Right, anyway the PR #1843 should solve it
