### ISSUE TITLE
Missing C++ compatibility in some headers

### ISSUE THREAD

**Issue by diego-santacruz** [tpm2-software/tpm2-tss#1855]
Some of the headers declaring functions lack the typical prelude and postlude for C++ compatibility below
```
#ifdef __cplusplus
extern "C" {
#endif
```
```
#ifdef __cplusplus
}
#endif
```

The headers lacking this are `tss2_rc.h` and `tss2_tctildr.h`.

**Comment by AndreasFuchsSIT** [comment]
Good point, PRs welcome...

**Comment by diego-santacruz** [comment]
I see that it was already added to `tss2_rc.h`, I created a PR for `tss2_tctildr.h`.
