### ISSUE TITLE
TPM_RC_FAILURE on SLB9670 when using PolicySecret, LoadExternal...

### ISSUE THREAD

**Issue by dmgstz** [tpm2-software/tpm2-tss#1865]
I finally found the time to update the SLB9670 chip from firmware 7.40.2098 to 7.83, which is the latest version of the firmware for the SLB9670, however I have not been successful, I came across the same issue as in this link:

https://github.com/tpm2-software/tpm2-tss/issues/1700

The upgrade process requires the use of PolicySecret with a policy Session, however, this fails on the SLB9670 (7.40.2098) with tpm2-tss **when using a session with this command** (it works fine with ESYS_TR_PASSWORD), making the TPM enter into a failure mode which I can only recover it from after a hardware reset. But the upgrade process is irrelevant in this context as the sequence of commands as described below is enough to replicate the behaviour:

I have a trace of what is sent/received over TCTI when using a HMAC session to create the policy session, scenario that fails:

1. First TCTI transmission is the StartAuthSession (0x176) command to create the policy session, which is successful.
2. Second TCTI tranmission is the PolicyAuthValue (0x16B) command to add an authorization to the policy session, which is successful.
3. Third TCTI transmission is PolicySecret command (0x151) to add an authorization to the policy session, which makes the TPM enter failure mode for some reason, and it won't accept any other command after this. (I guess GetCapabilities and TestResult would work fine but I have not tried).

![](https://i.ibb.co/5jvGGvK/image.png)
**Click the image for better quality**

Same trace in text format:

**1. StartAuthSession****

```
TPM: TCTI Transmit, size: 115, state: 1.
TPM: 80:01:00:00:00:73:00:00:01:76:80:00:00:00:40:00:00:07:00:10:3D:38:0D:33:4F:CC:C0:E1:90:5D:9E:CD:D9:06:54:83:00:44:00:20:DB:D7:8E:A0:AB:57:47:5B:C5:04:57:48:AC:8B:F3:7F:2F:C4:E1:65:BF:D9:3D:36
TPM: 8C:99:AD:D1:CC:70:65:88:00:20:DF:75:8D:A5:D9:C6:74:CF:73:32:A9:9D:93:3E:44:B4:8F:23:4E:14:29:30:7A:33:BB:3A:6A:20:EB:40:E0:90:01:00:06:00:80:00:43:00:0B

TPM: TCTI Receive, partial: 0, timeout: -1, state: 2.
TPM: Command Response, size: 32
TPM: 80:01:00:00:00:20:00:00:00:00:03:00:00:01:00:10:45:63:AC:5D:83:7C:68:18:FA:55:D0:ED:2A:5C:EC:42
```
**2. PolicyAuthValue**

```
TPM: TCTI Transmit, size: 75, state: 1.
TPM: 80:02:00:00:00:4B:00:00:01:6B:03:00:00:01:00:00:00:39:02:00:00:00:00:10:3F:C5:E5:09:75:3E:C1:1B:9F:39:4F:62:3E:C5:B2:AF:81:00:20:F6:3A:85:36:D1:09:AD:7B:8E:80:1D:5F:C9:72:63:E3:99:69:56:5B:3B
TPM: 7E:6D:A6:53:42:3F:23:91:4D:20:A6

TPM: TCTI Receive, partial: 0, timeout: -1, state: 2.
TPM: Command Response, size: 67
TPM: 80:02:00:00:00:43:00:00:00:00:00:00:00:00:00:10:60:37:BD:A4:35:63:58:37:99:31:BB:4C:CD:3D:91:7F:81:00:20:B3:47:33:D6:AE:7D:85:95:F2:49:55:76:8D:F9:DA:56:FD:24:0E:F2:9C:24:B0:32:12:EA:55:A1:B3
TPM: 5A:37:B8
```

**3. PolicySecret**

```
TPM: TCTI Transmit, size: 109, state: 1.
TPM: 80:02:00:00:00:6D:00:00:01:51:40:00:00:0C:03:00:00:01:00:00:00:39:02:00:00:00:00:10:FE:85:AD:BB:D2:1C:37:96:7D:3C:1D:C4:9D:85:0D:01:E1:00:20:06:0F:A5:E5:AA:24:2D:B0:73:65:8E:18:95:31:BD:08:89
TPM: AC:6B:14:8B:73:52:36:77:4F:29:C4:5B:08:CA:D7:00:10:E5:EB:22:39:2A:F3:B4:4F:84:15:54:64:27:F7:04:A0:00:00:00:04:0C:00:00:40:00:00:00:00

TPM: TCTI Receive, partial: 0, timeout: -1, state: 2.
TPM: Command Response, size: 10
TPM: 80:01:00:00:00:0A:00:00:01:01
WARNING:esys:C:\Projects\xxxx\third-party\trusted-platform-module\tpmtss\src\tss2-esys\api\Esys_PolicySecret.c:339:Esys_PolicySecret_Finish() Received TPM Error
ERROR:esys:C:\Projects\xxxx\third-party\trusted-platform-module\tpmtss\src\tss2-esys\api\Esys_PolicySecret.c:115:Esys_PolicySecret() Esys Finish ErrorCode (0x00000101)
```

Any ideas? This behaviour does not seem to be documented... This same sequence of commands works fine with a SLM9670 chip (version 13) and with the Microsoft TPM Simulator (with a session or with ESYS_TR_PASSWORD). 

Is it possible that the SLB9670 7.40.2098 supports an old version of the TPM 2.0 standard?

**Comment by dmgstz** [comment]
I think I can get this going using ESYS_TR_PASSWORD, but raised this anyway.

**Comment by PeterHuewe** [comment]
Hi, 
which upgrade tool are you using?
I'm not aware of a upgrade tool that utilizes the tpm2-tss stack

The SLM 9670 has a TPM rev 1.38 firmware, SLB 9670 with FW 7.85 have also rev 1.38 firmware, the SLB 9670 with FW 7.40 is rev 1.16.

Peter (IFX)

**Comment by dmgstz** [comment]
> Hi,
> which upgrade tool are you using?
> I'm not aware of a upgrade tool that utilizes the tpm2-tss stack
> 
> The SLM 9670 has a TPM rev 1.38 firmware, SLB 9670 with FW 7.85 have also rev 1.38 firmware, the SLB 9670 with FW 7.40 is rev 1.16.
> 
> Peter (IFX)

I have a custom platform that uses tpm2-tss, it is baremetal based with no RTOS, I ported tpm2-tss to this platform (so my own SPI driver, FIFO/TIS driver and similar, no linux device drivers), I have also integrated this with the Microsoft TPM simulator using windows sockets in the TCTI interface. All the functionality I have implemented so far works fine with a SLM9670 chip and the TPM simulator, there are some things that do not work with the SLB9670 chip, for example, the ones in this issue or the ones in issue !1700.

There is no such tool as you mentioned, I am porting a piece of code available here:

https://github.com/iavael/infineon-firmware-updater

To this platform that I have so that I can use tpm2-tss to perform a firmware upgrade, the firmware upgrade process requires the PolicySecret command at some stage in the process, and while doing this I came accross the issue I described here.

So the the issue is not really related to the upgrade process, a sequence of commands as I described in the first post would be able to replicate this behaviour (PolicySecret with a session), so believe a combination of tpm2-tss and the SLB9670 with FW 7.40 that is causing this behaviour, main reason why I have been looking to upgrade the TPM firmware available in the platform to 7.83.

**Comment by PeterHuewe** [comment]
Can you generate an example C file / test example that triggers this behavior?
So we can then test it on regular linux based system and work from there.

**Comment by PeterHuewe** [comment]
Other idea is to use the tss supplied with the upgrade tool to perform your upgrade (as this has been tested with the TPM)  and then use the port of this project to continue working from there.

**Comment by PeterHuewe** [comment]
Since this is firstly related to our product, maybe it makes sense to take this offline - feel free to contact me directly at peter.huewe@infineon.com

**Comment by dmgstz** [comment]
> Can you generate an example C file / test example that triggers this behavior?
> So we can then test it on regular linux based system and work from there.

Will do, probably not within today but will @ you when I have it.

> Other idea is to use the tss supplied with the upgrade tool to perform your upgrade (as this has been tested with the TPM) and then use the port of this project to continue working from there.

Yes, I thought about that, but there are some units in the wild that can't be recalled and which will need the upgrade and I thought integrating the sequence of commands in our existing platform would end up being simpler.

Thank you for your time.

**Comment by AndreasFuchsSIT** [comment]
So I guess this is handled via email now...
