### ISSUE TITLE
Why log level use 0 2 3 4 5 6 other than 01 2 3 4 5

### ISSUE THREAD

**Issue by HuKeping** [tpm2-software/tpm2-tss#1867]
As per https://github.com/tpm2-software/tpm2-tss/blob/master/src/util/log.h#L21-L27 

```
#define LOGL_NONE    0
#define LOGL_ERROR   2
#define LOGL_WARNING 3
#define LOGL_INFO    4
#define LOGL_DEBUG   5
#define LOGL_TRACE   6
#define LOGL_UNDEF   0xFF
```

why we skip enum `1` ?

**Comment by AndreasFuchsSIT** [comment]
> Reason is, if you define -DMAXLOGLEVEL or -DMAXLOGLEVEL= which happened unintentionally, then it would set MAXLOGLEVEL to 1 without noticing.

Source: https://github.com/tpm2-software/tpm2-tss/pull/809

**Comment by HuKeping** [comment]
make sense, thansk @AndreasFuchsSIT
