### ISSUE TITLE
__FILE__ breaks reproducible builds

### ISSUE THREAD

**Issue by HuKeping** [tpm2-software/tpm2-tss#1868]
Hi there,

While working on the “reproducible builds” effort we noticed that tpm2-tss could  not be built reproducibly because of  the `__FILE__` macro on src/utils/log.h .

Do we really need this macro and if we could not use it ?

**Comment by AndreasFuchsSIT** [comment]
Without this, debuging user feedback becomes harder.

What exactly is the problem with this makro ? It should only contain the relative path inside the project and thus how does it fail ?

Just the filename (without path) would also be ok IMHO. But is there a makro for that ?

**Comment by HuKeping** [comment]
>  It should only contain the relative path inside the project and thus how does it fail ?

Actually `__FILE__ `would record the full path not relative path. 

Maybe we can add a config to give a fixture value like what openssl project did(https://github.com/openssl/openssl/commit/02f7114a7fbb3f3ac171bae87be8c13bc69e4005  and https://github.com/openssl/openssl/commit/3ba84717a0ac76785935efcca50ab80e1e2f5564)?

In this way, we can let people to choose if they would like to make reproducible binary.

**Comment by HuKeping** [comment]
> Just the filename (without path) would also be ok IMHO. But is there a makro for that ?

We can make one, like "#define __FILENAME__ (strrchr(__FILE__, '/') ? strrchr(__FILE__, '/') + 1 : __FILE__)"

```
$ cat main.c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define __FILENAME__ (strrchr(__FILE__, '/') ? strrchr(__FILE__, '/') + 1 : __FILE__)

int main()
{
	printf("%s:%d:%s\n", __FILE__, __LINE__, __FUNCTION__);
	printf("%s:%d:%s\n", __FILENAME__, __LINE__, __FUNCTION__);

	return 0;
}

$ gcc /home/hukeping/tmp/main.c
$ ./a.out 
/home/hukeping/tmp/main.c:9:main
main.c:10:main
```

**Comment by AndreasFuchsSIT** [comment]
Now that's weird. Here's a snipped from me using the tss:
```
ERROR:esys:src/tss2-esys/api/Esys_FlushContext.c:66:Esys_FlushContext() Error in async function ErrorCode (0x00070018) 
ERROR:fapi:src/tss2-fapi/api/Fapi_NvWrite.c:112:Fapi_NvWrite() ErrorCode (0x00000126) NV_Write 
```

Why are you calling `gcc /home/hukeping/tmp/main.c` ? instead of `(cd gcc /home/hukeping/ && gcc tmp/main.c)` ?

Or for the overall thing; how do you call the configure script ? With an absolute path or with a relative path ?

**Comment by HuKeping** [comment]
> Or for the overall thing; how do you call the configure script ? With an absolute path or with a relative path ?

relative path( cd && ./configure)

> Why are you calling gcc /home/hukeping/tmp/main.c ? instead of (cd gcc /home/hukeping/ && gcc tmp/main.c) ?

It's a quick test for the new macro. 

We integrate tpm2-tss into a product and have a build project for the whole product, but we could not ask our customer to build  it exactly the same dir as what we build, and that's will make the different in binary.

**Comment by williamcroberts** [comment]
We could also probably set __FILENAME__ via a macro that expands during the build rules using the src_dir variable... this way it will be the same for everyone, and then we don't need to get into the / vs \ linux vs windows stuff.

Also, GNU C has: __BASE_FILE__, not sure what to do for windoze, although we do use clang for windows, maybe clangs libc has it? Im clueless with windows.

FYI GCC 8 now has the -fmacro-prefix-map and -ffile-prefix-map options:

-fmacro-prefix-map=old=new

When preprocessing files residing in directory old, expand the __FILE__ and __BASE_FILE__ macros as if the files resided in directory new instead. This can be used to change an absolute path to a relative path by using . for new which can result in more reproducible builds that are location independent. This option also affects __builtin_FILE() during compilation. See also -ffile-prefix-map.

-ffile-prefix-map=old=new

When compiling files residing in directory old, record any references to them in the result of the compilation as if the files resided in directory new instead. Specifying this option is equivalent to specifying all the individual -f*-prefix-map options. This can be used to make reproducible builds that are location independent. See also -fmacro-prefix-map and -fdebug-prefix-map.

**Comment by williamcroberts** [comment]
> Without this, debuging user feedback becomes harder.
> 
> What exactly is the problem with this makro ? It should only contain the relative path inside the project and thus how does it fail ?
> 
> Just the filename (without path) would also be ok IMHO. But is there a makro for that ?

`__BASE_FILE__`

**Comment by williamcroberts** [comment]
```C
#include <stdio.h>

int main() {
        printf("%s\n", __BASE_FILE__);
        return 0;
}
```
```bash
$ gcc -o go a.c
$ ./go
a.c
```

**Comment by williamcroberts** [comment]
> > Or for the overall thing; how do you call the configure script ? With an absolute path or with a relative path ?
> 
> relative path( cd && ./configure), it's in a CMake external project ,and we specify the `WORKING_DIRECTORY`

This is not reproducible because of your build environment, not the one we supply. You could update the build rules to override __FILE__...

`gcc -D__FILE__=\"foo\" -Wno-builtin-macro-redefined -o go a.c`

You could expand upon that and $< should give you the current compilation unit and you can use some other env variable to strip away the part of the path you don't care about. I would imagine CMAKE would give it to you as some env var. We have $(src_dir) in autotools.

Something like this in bash works:
```bash
path=/path/to/file/drive/file/path/
echo ${path#/path/to/file/drive/}
```
You could probably use make $(subst) function.

**Comment by HuKeping** [comment]
In my test, it seems both `__FILE__` and `__BASE_FILE`  both show full path to file?

**Comment by HuKeping** [comment]
> We could also probably set __FILENAME__ via a macro that expands during the build rules using the src_dir variable... this way it will be the same for everyone, and then we don't need to get into the / vs \ linux vs windows stuff.

Agreed, `./configure --srcdir` would work

**Comment by AndreasFuchsSIT** [comment]
I guess I don't get it yet...

**Comment by williamcroberts** [comment]
> I guess I don't get it yet...

They wrote their own build system, that uses absolute paths passed to the compiler, similar to how Android does it IIRC. They probably move build machines, and thus get different paths that expand as __FILE__. So a build of tag A isn't consistent as __FILE__ changes. 

Our build infrastructure is reproducible AFAIK. I gave them some things to try, but I don't see this as a bug on our side. I think we can close this. I think they need to change how they build it, by either passing consistent file paths from the project root to the compiler, so __FILE__ is consistent or some other tricks like overriding __FILE__ via a define passed during compilation, etc.

**Comment by HuKeping** [comment]
Can we pass `src_dir` in autotools to `__FILENAME__ ` and use `__FILENAME__ ` to replace `__FILE__`  in `src/utils/log.h`?

**Comment by williamcroberts** [comment]
@HuKeping  Just redefine __FILE__ in your build scripts. The autotools build scripts included with the project work just fine.

**Comment by HuKeping** [comment]
Do you mean like `gcc -D__FILE__=\"foo\" -Wno-builtin-macro-redefined -o go a.c` ?

**Comment by williamcroberts** [comment]
> Do you mean like `gcc -D__FILE__=\"foo\" -Wno-builtin-macro-redefined -o go a.c` ?

Yes.

**Comment by HuKeping** [comment]
`-Wno-builtin-macro-redefined`   mute the compiler warnings for redefining all things, it might not be a good choice, and it seems not works for old compiler.

**Comment by williamcroberts** [comment]
@HuKeping the more I think about this, if you modify the recipe to produce the object file and pass the filename via a macro, why not just pass that filename/path to the compiler? Sounds to me like you should re-write the rule in your build scripts, since that what you have to do anyways.

Their is nothing really for us to do here, as our autotools build produces a proper and repeatable build. It's only in your build system that this problem manifests.

**Comment by HuKeping** [comment]
Thanks for those clarification @williamcroberts.

Closing.
