### ISSUE TITLE
Specifying nonceCaller in Esys_StartAuthSession has no effect in subsequent commands

### ISSUE THREAD

**Issue by idesai** [tpm2-software/tpm2-tss#1880]
Specifying a [nonceCaller](https://github.com/tpm2-software/tpm2-tss/blob/50bab5fe78bacddbc589c96d2a1533008ec2ce09/src/tss2-esys/api/Esys_StartAuthSession.c#L36:#L42) using the esys-interface has no effect in subsequent commands.
```
    if (nonceCaller == NULL) {
        esysContext->in.StartAuthSession.nonceCaller = NULL;
    } else {
        esysContext->in.StartAuthSession.nonceCallerData = *nonceCaller;
        esysContext->in.StartAuthSession.nonceCaller =
            &esysContext->in.StartAuthSession.nonceCallerData;
    }
```

In subsequent commands, however, the nonceCaller is updated using [random-data](https://github.com/tpm2-software/tpm2-tss/blob/50bab5fe78bacddbc589c96d2a1533008ec2ce09/src/tss2-esys/esys_iutil.c#L561:#L575).
```
TSS2_RC
iesys_gen_caller_nonces(ESYS_CONTEXT * esys_context)
{
    TSS2_RC r;

    for (int i = 0; i < 3; i++) {
        RSRC_NODE_T *session = esys_context->session_tab[i];
        if (session == NULL)
            continue;

        r = iesys_crypto_random2b(&session->rsrc.misc.rsrc_session.nonceCaller,
                                  session->rsrc.misc.rsrc_session.nonceCaller.size);
        return_if_error(r, "Error: computing caller nonce (%x).");
    }
    return TSS2_RC_SUCCESS;
}
```

Two options here:
1. Just remove the option to specify the nonceCaller from Esys_StartAuthSession and update the spec/ documentation.
2. Retain the user-specified nonceCaller throughout the life of the session if one is specified already. In this case, you will have to add Esys-TRSess functions to set and get the nonceCaller.

**Comment by AndreasFuchsSIT** [comment]
nonceCaller here is the TPM2_StartAuthSession parameter nonceCaller. It is used to determine the length of the nonceTpm that the TPM shall produce. (yes I too find it weird to use a buffer length instead of just a value).

It is not the nonceCaller from subsequent authorization cycles.

So they are different things, just both called the same name.

**Comment by idesai** [comment]
> nonceCaller here is the TPM2_StartAuthSession parameter nonceCaller. It is used to determine the length of the nonceTpm that the TPM shall produce. (yes I too find it weird to use a buffer length instead of just a value).
> 
> It is not the nonceCaller from subsequent authorization cycles.
> 
> So they are different things, just both called the same name.

The concern I have is that the nonceCaller usage in StartAuthSession to set the nonceTpm size is also not effective because the individual Esys_<command> calls to iesys_gen_auths->iesys_gen_caller_nonces  resets the nonceCaller size too.

**Comment by drvarun** [comment]
Hi,

Could you two confirm if the nonce field in startAuth command is only used for size determination which TPM produces independently?
