### ISSUE TITLE
Need help install tpm2-tss on TPM 1.2 supported system

### ISSUE THREAD

**Issue by vponnuru23** [tpm2-software/tpm2-tss#1887]
I need help installing tpm2-tss software stack on the Dell Server that has TPM 1.2 chip installed and running ubuntu 18.04 server edition. 

I tried installing the TSS stack using the instructions: https://github.com/tpm2-software/tpm2-tss/blob/master/INSTALL.md.  However installation is not successful. 

The steps are:
1. sudo apt -y update
2. sudo apt -y install autoconf-archive libcmocka0 libcmocka-dev procps iproute2 build-essential git pkg-config gcc libtool automake libssl-dev uthash-dev autoconf doxygen libjson-c-dev libini-config-dev libcurl4-gnutls-dev

3. ./bootstrap
4.  Copied autconf files
cp autoconf-archive-2019.01.06/m4/ax_code_coverage.m4 ../tpm2-tss-master/m4/
cp autoconf-archive-2019.01.06/m4/ax_is_release.m4 ../tpm2-tss-master/m4/
cp autoconf-archive-2019.01.06/m4/ax_prog_doxygen.m4 ../tpm2-tss-master/m4/

5. /configure 
6. make 
I see bunch of warnings..
EADME.md:47: warning: unable to resolve reference to `INSTALL.md' for \ref command

7. make check
estsuite summary for tpm2-tss 3.1.0-dev
============================================================================
 TOTAL: 0
 PASS:  0
 SKIP:  0
 XFAIL: 0
 FAIL:  0
 XPASS: 0
 ERROR: 0
================

8. sudo make install

Error:
/bin/bash: systemd-sysusers: command not found
123
113
/bin/bash: line 1: all: command not found
if [ ! -d "/usr/local/var/run/tpm2-tss/eventlog/" ]; then echo "*** WARNING *** Directory /usr/local/var/run/tpm2-tss/eventlog/ could not be created"; fi
if [ ! -d "/usr/local/var/lib/tpm2-tss/system/keystore/" ]; then echo "*** WARNING *** Directory /usr/local/var/lib/tpm2-tss/system/keystore/ could not be created" 

Need help in resolving the issues...

**Comment by AndreasFuchsSIT** [comment]
tpm2-tss only works with TPM 2.0 systems.
For TPM 1.2 please see the TrouSerS project. But that's abandondware I think.
