### ISSUE TITLE
FAPI not provisioned error (although everything works)

### ISSUE THREAD

**Issue by FadedCoder** [tpm2-software/tpm2-tss#1888]
```
ERROR:fapi:src/tss2-fapi/api/Fapi_List.c:221:Fapi_List_Finish() FAPI not provisioned. 
ERROR:fapi:src/tss2-fapi/api/Fapi_List.c:81:Fapi_List() ErrorCode (0x00060034) Entities_List 
ERROR: Listing FAPI token objects failed.
```
I get this error whenever I'm trying to use the `tpm2_ptool`, like with SSH. Everything seems to work, but getting this error everytime is a bit annoying.

Any way to fix or disable this?

Using [the official tpm2-tss](https://www.archlinux.org/packages/community/x86_64/tpm2-tss/) and tpm2-pkcs11 tools for Arch Linux.

**Comment by heobu** [comment]
I am getting the same error and was about to create an issue for it.
What could be the reason for this? For the most part everything seems to work fine, but this error message can be seen as a result of the execution all the time.

For example, I executed this on the terminal:
`tpm2pkcs11-tool --list-objects`

This error message was the result of that followed by the list of objects as expected.

**Comment by AndreasFuchsSIT** [comment]
the tpm2-pkcs11 project allows for two different backends; ESYS and FAPI.
This means that FAPI is not provisioned. but it will still work with the ESYS backend.
I guess we could turn this into a WARNING, if you prefer this ?

**Comment by joholl** [comment]
I agree that it should be a warning, since it is not a (fatal) error.

**Comment by williamcroberts** [comment]
> the tpm2-pkcs11 project allows for two different backends; ESYS and FAPI.
> This means that FAPI is not provisioned. but it will still work with the ESYS backend.
> I guess we could turn this into a WARNING, if you prefer this ?

Yeah a warning would be nice, I get this question all the time in tpm2-pkcs11 land.

**Comment by williamcroberts** [comment]
> > the tpm2-pkcs11 project allows for two different backends; ESYS and FAPI.
> > This means that FAPI is not provisioned. but it will still work with the ESYS backend.
> > I guess we could turn this into a WARNING, if you prefer this ?
> 
> Yeah a warning would be nice, I get this question all the time in tpm2-pkcs11 land.

The problem with defaulting to a warning or an error is that the failing FAPI call is failing because it's not provisioned... In some contexts, like tpm2-pkcs11 this doesn't cause any issues. In other contexts, like tss2_<tools> it is a fatal error.... So do we always warn, always print an error, etc. Not sure what we default to or how we control the tpm2-tss logging facilities. It would be nice to be able to turn the logging off and on programmatically without the env var so it doesn't affect other calls...

**Comment by AndreasFuchsSIT** [comment]
IMHO, the FAPI is warning.
The application is then responsible to turn the warning into an error.

As a rule of thumb; IMHO we error if we know that it's an error for all applications.
If we know a single application where it's not an error, we go down to a warning.
