### ISSUE TITLE
tpm2-tss installation fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by vponnuru23** [tpm2-software/tpm2-tss#1890]
make installation fails with following error.

collect2: error: ld returned 1 exit status
libtool:   error: error: relink 'src/tss2-fapi/libtss2-fapi.la' with the above command before installing it
make[1]: *** [Makefile:9310: install-libLTLIBRARIES] Error 1

**Comment by JuergenReppSIT** [comment]
I just installed tpm2-tss (current master) on ubuntu 20.04 with:
./bootstrap;./configure;make;sudo make install
without the relink error. Are there any other error messages before the relink error message?

**Comment by vponnuru23** [comment]
home/vish/tpm_install/tpm2-tss/src/tss2-fapi/fapi_util.c:2044: undefined reference to `Esys_TRSess_GetAuthRequired'
collect2: error: ld returned 1 exit status
libtool:   error: error: relink 'src/tss2-fapi/libtss2-fapi.la' with the above command before installing it
make[1]: *** [Makefile:9310: install-libLTLIBRARIES] Error 1
make[1]: Leaving directory '/home/vish/tpm_install/tpm2-tss'
make: *** [Makefile:25224: install-am] Error 2

**Comment by vponnuru23** [comment]
$ make check -- showing the following results; not sure if the report is OK. 

============================================================================
Testsuite summary for tpm2-tss 3.1.0-dev
============================================================================
# TOTAL: 0
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================

**Comment by vponnuru23** [comment]
I could see bunch of issues in the config.log
[config.log](https://github.com/tpm2-software/tpm2-tss/files/5476331/config.log)

**Comment by JuergenReppSIT** [comment]
n 02.11.20 16:42, Viswanath Ponnuru wrote:
> home/vish/tpm_install/tpm2-tss/src/tss2-fapi/fapi_util.c:2044: undefined reference to `Esys_TRSess_GetAuthRequired'
> collect2: error: ld returned 1 exit status

The symbol Esys_TRSess_GetAuthRequired should be available in:

> $ nm -g src/tss2-esys/.libs/libtss2-esys.a| grep Esys_TRSess_GetAuthRequired
> 0000000000001d09 T Esys_TRSess_GetAuthRequired
> $ nm -g src/tss2-esys/.libs/libtss2-esys.so| grep Esys_TRSess_GetAuthRequired
> 000000000008c097 T Esys_TRSess_GetAuthRequired

Did the error message "undefined reference" occur during "make" or during "make install"?
Perhaps there is a problem with the LD_LIBRARY_PATH which points to an old esys library.

**Comment by vponnuru23** [comment]
Error is at during "make install".

**Comment by JuergenReppSIT** [comment]
Is  Esys_TRSess_GetAuthRequired included in the libraries  when you execute the following commands?
nm -g src/tss2-esys/.libs/libtss2-esys.a| grep Esys_TRSess_GetAuthRequired
nm -g src/tss2-esys/.libs/libtss2-esys.so| grep Esys_TRSess_GetAuthRequired

**Comment by vponnuru23** [comment]
After re-installing the operating system; all the installation works fine.  And able to access the tpm2 functionality by executing the commands.  

Thank you for the support.  Closing the issue.
