### ISSUE TITLE
Logitech HID Causes Timeout Failure

### ISSUE THREAD

**Issue by mpalermo73** [tpm2-software/tpm2-tss#1896]
Manjaro (from Arch)
```$ uname -a
Linux aragorn 5.9.3-1-MANJARO #1 SMP PREEMPT Sun Nov 1 14:25:36 UTC 2020 x86_64 GNU/Linux```

```$ fwupdmgr --version
client version: 1.5.0
compile-time dependency versions
        gusb:   0.3.5

daemon version: 1.5.0
```

Logitech HID Plug fails detecting my K750 (wireless, solar, MAC) keyboard.

```Nov 08 07:26:53 aragorn systemd[1]: Starting Firmware update daemon...
Nov 08 07:26:53 aragorn fwupd[181883]: 12:26:53:0576 FuPluginUefi         cannot find default ESP: no volumes of type c12a7328-f81f-11d2-ba4b-00a0c93ec93b
Nov 08 07:26:53 aragorn fwupd[181883]: 12:26:53:0576 FuPluginUefi         failed to add /sys/firmware/efi/esrt/entries/entry0: ESRT GUID '00000000-0000-0000-0000-000000000000' was not valid
Nov 08 07:26:54 aragorn fwupd[181883]: 12:26:54:0069 FuDeviceList         ignoring device 60007842ebf7e1adc09cbb36280a19e74e96703b [logitech_hidpp:FuLogitechHidPpRuntime] existing device 60007842ebf7e1adc09cbb36280a19e74e96703b [logitech_hidpp:FuLogitechHidPpRuntime] already exists
```

and the console gives the timeout error

```$ sudo fwupdmgr get-updates
Failed to connect to daemon: Error calling StartServiceByName for org.freedesktop.fwupd: Failed to activate service 'org.freedesktop.fwupd': timed out (service_start_timeout=25000ms)
```

However if I "stash" that module then fwupdmgr runs fine

```$ sudo mv /usr/lib/fwupd-plugins-3/libfu_plugin_logitech_hidpp.so /usr/lib/fwupd-plugins-3/libfu_plugin_logitech_hidpp.so.bak```

**Comment by diabonas** [comment]
Did you open this bug report in the wrong repository by accident? This is an issue with [fwupd](https://github.com/fwupd/fwupd), so the best place to report this would probably be their issue tracker.

Note that fwupd indeed depends on tpm2-tss for a small subset of its functionality, but this issue appears to be completely unrelated to TPMs.

**Comment by mpalermo73** [comment]
:facepalm:

Yes you're totally right...  Sorry for the mess.

M.
