### ISSUE TITLE
ESAPI restricts session binding to entities involved in a command alone

### ISSUE THREAD

**Issue by idesai** [tpm2-software/tpm2-tss#1897]
I understand ESAPI spec automatically calculates the handles to which the session can bind from the command. What is the reason for this restriction? TPM allows for a session to be bound to any entity.

**Comment by AndreasFuchsSIT** [comment]
I'm sorry, but I have no clue what you mean ? Could you elaborate on the specific thing you're talking about ?

**Comment by idesai** [comment]
as in, if an authvalue is specified for the bind entity, the binding fails and the DA counter is incremented. Here is an example/[PR](https://github.com/tpm2-software/tpm2-tools/pull/2255/commits/bccbc6f6d0726887c9b6ca7ef46d64e70ad61b0c) in the tools where it is happening.

**Comment by AndreasFuchsSIT** [comment]
I guess I don't understand the PR you linked.

So the way it should be working according to the Spec (and hopefully implementation) is:
During startAuthSession you reference a bind-entity via its ESYS_TR. The ESAPI will grap the authvalue of that entity and use it in the session key calculation. It will also store some information to recognize the object again once it's used.
If you use the session to authenticate against an object, the session's referenced bind-entity and the object are compared an if they match, the objects auth is not added. If they mismatch, the objects authValue is added for authentication.

I'm not sure how the "compared" works right now. Inside the TPM the compare uses the concatenation of namehash and authvalue or something IFRC. I don't know what esys is using, or if we left the authvalue out of that comparison.

There's also a test for bind-sessions here:
https://github.com/tpm2-software/tpm2-tss/blob/482ed2ed42edb2e9a818f7b6a1c15fbee2d7c4a3/test/integration/esys-create-session-auth.int.c#L255

My initial guess is that the swaping and unswaping of the contexts makes a problem and thus the "compare" does not work properly anymore ? Could this be ?

**Comment by AndreasFuchsSIT** [comment]
@idesai Can this be closed ?
