### ISSUE TITLE
doc: doxygen: Incorrent first argument for Fapi_CB_Auth

### ISSUE THREAD

**Issue by pdxjohnny** [tpm2-software/tpm2-tss#1901]
https://github.com/tpm2-software/tpm2-tss/blob/965ef058d8df57bc9b6277ca22aed16b5a856a39/doc/doxygen.dox#L1557

shows `FAPI_CONTEXT *` as the first argument, really its `objectPath`

https://github.com/tpm2-software/tpm2-tss/blob/e0636dd6fbec4f286cc908117ecef4d820a50f79/include/tss2/tss2_fapi.h#L678-L682

**Comment by AndreasFuchsSIT** [comment]
Fix via #1902
