### ISSUE TITLE
Would be great if Esys_Finalize() would be a silent NOP when passed NULL pointers

### ISSUE THREAD

**Issue by poettering** [tpm2-software/tpm2-tss#1942]
In many C projects it is customary that passing NULL to destructor/finalizer/free functions is a silent NOP. It makes clean-up codepaths much shorter and easier to read. For example libc's own free() function is a NOP if you pass NULL and it's documented that way.

It would be great if Esys_Finalize() would work the same way. Currently it logs a warning if you pass NULL. All I am asking to remove that, and just return silently.

(Prompted by https://github.com/systemd/systemd/pull/17741#discussion_r540570833 if you care for more context)

(Something similar probably applies to other destructors in the tpm2-tss codebase)

**Comment by AndreasFuchsSIT** [comment]
For the moment you could set TSS2_LOG=all+error in order to silence warnings.

I'm a bit split here. For Esys_Free we do NOP silently, but since these contexts are more than just some memory, I'm not too sure.
Let me think about this for a bit.

**Comment by AndreasFuchsSIT** [comment]
Fixed in #1948
