### ISSUE TITLE
tpm2-tss unit test cross compile

### ISSUE THREAD

**Issue by penpendandan** [tpm2-software/tpm2-tss#1946]
Hello,
I want to cross compile tpm2-tss to use unit test, how can I set parameter of configure 
Thanks

**Comment by williamcroberts** [comment]
Perfect timing, I just had to figure out how to do this and mentioned it here:
  - https://lists.01.org/hyperkitty/list/tpm2@lists.01.org/thread/VUZ7MI3C3Z6XP3HKLYIVK25FPPVQ26JC/

Android NDK has a complete example you can modify your host and build tools:
https://developer.android.com/ndk/guides/other_build_systems#autoconf
