### ISSUE TITLE
Error using tpm2-tss with OpenSSL 1.1.1.1 on Windows.

### ISSUE THREAD

**Issue by vinaykotak** [tpm2-software/tpm2-tss#1947]
I am trying to use tpm2-tss with openSSL version 1.1.1.1 on Windows and it fails due to missing symbols in the openSSL lib. 

` WindowsTpm.lib(esys_crypto_ossl.obj) : error LNK2001: unresolved external symbol EVP_MD_CTX_create
  WindowsTpm.lib(esys_crypto_ossl.obj) : error LNK2001: unresolved external symbol EVP_MD_CTX_destroy`

On investigation, I found that the above mentioned APIs have been replaced with newer API names. I see that the tpm2-tss still uses the old APIs from lower openSSL version. 

Is there a way to make tpm2-tss work with the newer openSSL version?

OpenSSL packages that I am using can be found here. 
https://www.nuget.org/packages/openssl-vc140-static-32_64/

**Comment by JuergenReppSIT** [comment]
The symbol EVP_MD_CTX_create should not occur as symbol in the object files. In include/openssl/evp.h you can find the following  define:
`#define EVP_MD_CTX_create()     EVP_MD_CTX_new()`
So EVP_MD_CTX_new should be used for linking.
Could you please explain what API change you found? I think EVP_MD_CTX_create can be used with version 1.1.1.

**Comment by vinaykotak** [comment]
You are right. The symbols are in evp.h. I looked into it further and the tpm libs were built with the previous openssl version and the obj files that I was using were from that lib. I had to recompile tpm2-tss with the upgraded openssl version and it fixed the issue.

We can close this issue.

Thanks for your help.
