### ISSUE TITLE
simple standalone c/c++ program for encryption and decryption

### ISSUE THREAD

**Issue by drvarun** [tpm2-software/tpm2-tss#1954]
Platform: Intel NUC with PTT (no hardware TPM), Ubuntu 20.04.

Hello,

I am new to TPM and I have tested tpm2-tools. Now after installing tpm2-tss, I am trying to create a simple standalone c/c++ program to do basic encryption/decryption using TPM, however, the documentation is bit confusing. For example, the APIs I need to use are to be called in specific order, specific constants are to be defined and specific header files ought to be included for using a specific API, etc. 

So, can anyone guide me where can I find the getting started guide to create our own C/C++ prgrams with tpm2-tss libraries? I am sure it must be somewhere but unfortunately I am unable to find it.

Thank you :)

**Comment by williamcroberts** [comment]
For symmetric encrypt and decrypt it , it would be recomended to use the ESYS/ESAPI API as you can enable encrypted sessions with the TPM easily compared to the System API or SAPI.

This is probably the simplest example:
  - https://github.com/tpm2-software/tpm2-tss/blob/master/test/integration/esys-encrypt-decrypt.int.c
  
The steps are:
1. Establish a TCTI connection using either the TCTI or TCTILDR libraries.
2. Establish an ESYS Context with that TCTI
3. Create a primary Key Esys_CreatePrimary
4. Create an encryption key with Esys_Create
5. Load that key into the tpm using Esys_Load
6. Encrypt/Decrypt with Esys_EncryptDecrypt or Esys_EncryptDecrypt2.
    - The 2 variant is preferred, but you need to look at the supported commands by your TPM (tpm2_getcap commands)
7. Deinitialize and free everything

Hope this helps

**Comment by AndreasFuchsSIT** [comment]
Bill's reference is correct for symmteric encryption, if your TPM supports that.
For asymmetric, see https://github.com/tpm2-software/tpm2-tss/blob/master/test/integration/esys-rsa-encrypt-decrypt.int.c and https://github.com/tpm2-software/tpm2-tss/blob/master/test/integration/esys-ecdh-keygen.int.c and https://github.com/tpm2-software/tpm2-tss/blob/master/test/integration/esys-ecdh-zgen.int.c

or if you want to use FAPI (only RSA supported there atm) see https://github.com/tpm2-software/tpm2-tss/blob/29c46f0d27942146a909f7f12c0f8f65c45bec93/test/integration/fapi-data-crypt.int.c

No intros available atm, we want to collect them at https://tpm2-software.github.io/tutorials/ but not too much there. Contributions welcome if you have something.
