### ISSUE TITLE
Standalone application compilation

### ISSUE THREAD

**Issue by drvarun** [tpm2-software/tpm2-tss#1955]
Hello,

Following my previous [query](https://github.com/tpm2-software/tpm2-tss/issues/1954), I wanted to know how should I define `sys_context` or `esys_context` in a standalone application? Is there any documentation to refer to?

Also, when I try to compile my basic c program, I get this error
`test.c:(.text+0x63): undefined reference to `Esys_GetCapability'`

I get the same error even when using 
`sudo gcc test.c -I /usr/local/include/ -L /usr/local/lib/`

I double-checked and the library installation is fine and within the above mentioned directories.
In the` test.c` file, I used `#include "tss2/headerfilename.h"` 
How do I solve this compilation error?

**Comment by JuergenReppSIT** [comment]
I have compiled the following small example (inserted from esys-get-rand.c) with:
` gcc esys-get-rand.c -L=/usr/local/lib/ -ltss2-esys -o esys-get-rand`

```
#include <stdio.h>
#include <tss2/tss2_mu.h>
#include <tss2/tss2_esys.h>

int main() {

    TSS2_RC r;

    /* Initialize the ESAPI context */
    ESYS_CONTEXT *ctx;
    r = Esys_Initialize(&ctx, NULL, NULL);
    
    if (r != TSS2_RC_SUCCESS){
        printf("\nError: Esys_Initialize\n");
        exit(1);
    }

    /* Get random data */
    TPM2B_DIGEST *random_bytes;
    r = Esys_GetRandom(ctx, ESYS_TR_NONE, ESYS_TR_NONE, ESYS_TR_NONE, 20,
                       &random_bytes);

    if (r != TSS2_RC_SUCCESS){
        printf("\nError: Esys_GetRandom\n");
        exit(1);
    }

    printf("\n");
    for (int i = 0; i < random_bytes->size; i++) {
        printf("0x%x ", random_bytes->buffer[i]);
    }
    printf("\n");
    exit(0);
}
```

**Comment by drvarun** [comment]
@JuergenReppSIT omg thank you. The code is very simple and clear to understand for TPM newbies like me. I tried compiling it and it worked flawlessly. Thank you :)
