### ISSUE TITLE
Including structures from headers files in src folder.

### ISSUE THREAD

**Issue by drvarun** [tpm2-software/tpm2-tss#1956]
Hello,

I am trying to compile a standalone application for simple encryption and decryption. In that I am trying to use structures like `RSRC_NODE_T`, `IESYS_RESOURCE`, etc. However, these structures are not defined inside the header files created during library installation (`/usr/local/lib/ tss2`)

After searching a while, I found that these structures are defined in various header files in the directory:
`https://github.com/tpm2-software/tpm2-tss/tree/master/src`

So how do I include them in my standalone application?
Also, since these header files are not installed in the standard `/usr/local/lib/tss2` directory, shall I assume that I do not need them for creating a stand alone application for encryption and decryption? If yes, what is the work-around for it?

I refering this file for start :
`https://github.com/tpm2-software/tpm2-tss/blob/master/test/integration/esys-create-primary-hmac.int.c`

**Comment by williamcroberts** [comment]
This is by design. But that test does some goofy things a normal developer wont do. You can drop lines 180-184:
  - https://github.com/tpm2-software/tpm2-tss/blob/master/test/integration/esys-create-primary-hmac.int.c#L180-L184

and drop the internal includes:
```C
#include "esys_iutil.h"
#define LOGMODULE test
#include "util/log.h"
#include "util/aux_util.h"
```
Then just log with printf or whatever logger you are using.

**Comment by drvarun** [comment]
@williamcroberts Thank you. I got it now :p . Just a simple query, the HMAC in the title is related to the creation of authentication session, right? Further, is it possible to create keys, do encryption, decryption, signature, verification without creating an authenfication session first?

Correct me, if I am wrong, the `Esys_StartAuthSession` is mainly to secure communication between the userspace program and the TPM, right?

**Comment by tstruk** [comment]
That's right, Eys_StartAuthSession() is to protect the communication between the device and application.
You can do simple encryption without it. See https://github.com/tpm2-software/tpm2-tss/blob/master/test/integration/esys-rsa-encrypt-decrypt.int.c
