### ISSUE TITLE
segmentation fault in Fapi_Finalize when log_dir is missing from FAPI config

### ISSUE THREAD

**Issue by fishilico** [tpm2-software/tpm2-tss#1959]
When `"log_dir"` is missing from the FAPI configuration file, all `tss2_...` tools produce a segmentation fault in function `Fapi_Finalize`.

This is because with such a configuration, `out->log_dir = DEFAULT_LOG_DIR`: https://github.com/tpm2-software/tpm2-tss/blob/15b9b18c59cf01165032285f99d8216d6b925227/src/tss2-fapi/ifapi_config.c#L73-L78

and `DEFAULT_LOG_DIR` is a read-only string: https://github.com/tpm2-software/tpm2-tss/blob/15b9b18c59cf01165032285f99d8216d6b925227/src/tss2-fapi/fapi_int.h#L37

So `SAFE_FREE((*context)->config.log_dir);` tries to free a read-only string and fails: https://github.com/tpm2-software/tpm2-tss/blob/15b9b18c59cf01165032285f99d8216d6b925227/src/tss2-fapi/api/Fapi_Finalize.c#L81

I hit this bug while trying to use a software TPM in an Arch Linux container (`podman run --rm -ti docker.io/library/archlinux`, using tpm2-tss 3.0.3 and tpm2-tools 5.0) by running:
```sh
pacman -Syu --noconfirm swtpm tpm2-abrmd tpm2-tools
swtpm socket --tpm2 --server port=2321 --daemon --ctrl type=tcp,port=2322 \
    --flags not-need-init --tpmstate dir=/tmp --log file=/tmp/swtpm.log,level=5
mkdir -p /run/dbus && dbus-daemon --system --fork
tpm2-abrmd --allow-root --tcti swtpm:host=127.0.0.1,port=2321 &
export TPM2TOOLS_TCTI=tabrmd:bus_type=system

# Create a configuration without "log_dir"
echo > /etc/tpm2-tss/swtpm_fapi_config.json \
    '{"profile_name": "P_ECCP256SHA256",' \
    '"profile_dir": "/etc/tpm2-tss/fapi-profiles/",' \
    '"user_dir": "~/.local/share/tpm2-tss/user/keystore",' \
    '"system_dir": "/var/lib/tpm2-tss/system/keystore",' \
    '"tcti": "tabrmd:bus_type=system",' \
    '"system_pcrs": [],' \
    '"ek_cert_less": "yes"}'
export TSS2_FAPICONF=/etc/tpm2-tss/swtpm_fapi_config.json
tss2_provision
```

The last command produced a segmentation fault and `gdb` says:
```text
Thread 1 "tss2_provision" received signal SIGSEGV, Segmentation fault.
0x00007ffff79a5342 in free () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff79a5342 in free () at /usr/lib/libc.so.6
#1  0x00007ffff7ef7805 in Fapi_Finalize () at /usr/lib/libtss2-fapi.so.1
#2  0x000055555555c5bb in  ()
#3  0x00007ffff7941152 in __libc_start_main () at /usr/lib/libc.so.6
#4  0x000055555555d02e in  ()
```

This issue could be fixed either by checking that `out->log_dir` is not a read-only string in `Fapi_Finalize`, or by using `out->log_dir = strdup(DEFAULT_LOG_DIR);` in `ifapi_json_IFAPI_CONFIG_deserialize`.

**Comment by williamcroberts** [comment]
> This is because with such a configuration, `out->log_dir = DEFAULT_LOG_DIR`:
> 
> https://github.com/tpm2-software/tpm2-tss/blob/15b9b18c59cf01165032285f99d8216d6b925227/src/tss2-fapi/ifapi_config.c#L73-L78
> 
> and `DEFAULT_LOG_DIR` is a read-only string:
> 
> https://github.com/tpm2-software/tpm2-tss/blob/15b9b18c59cf01165032285f99d8216d6b925227/src/tss2-fapi/fapi_int.h#L37
> 
> So `SAFE_FREE((*context)->config.log_dir);` tries to free a read-only string and fails:
> 
> This issue could be fixed either by checking that out->log_dir is not a read-only string in Fapi_Finalize, or by using out->log_dir = strdup(DEFAULT_LOG_DIR); in ifapi_json_IFAPI_CONFIG_deserialize.

I just fixed a bunch of these in tpm2-abrmd. The way I handled it in there was just to strdup it and check for null over the other approach. Thanks for the bug report, and it just dawned on me, you're the same Nicolas Looss of the SELinux world :-p. Our paths collide again.
