### ISSUE TITLE
ECC Parameters Extraction from TPM

### ISSUE THREAD

**Issue by drvarun** [tpm2-software/tpm2-tss#1963]
Hello,

I am trying to create a simple application where I generate ECC key using `Esys_createprimary()` function. After that I want to use this key to sign using `Esys_sign()` and verify the signature outside TPM. For that:

1. I want to extract all parameters after they key is generated i.e. TPMS_ALGORITHM_DETAIL_ECC Structure. However, it seems that TPM2B_PUBLIC does not contain TPMS_ALGORITHM_DETAIL_ECC Structure. So how can I get all parameters of the generated ECC key? (Except the private part).

2. If I want to introduce random data during primary key generation, is it right to think that it can be done by changing `inPublicECC.publicArea.unique.ecc.x` and `inPublicECC.publicArea.unique.ecc.y` before passing them to `Esys_createprimary()` ?

**Comment by JuergenReppSIT** [comment]
1. You will get the information stored in TPMS_ALGORITHM_DETAIL_ECC with the function Esys_ECC_Parameters which has the parameter curveID.
2. If you do not trust the TPMs random number generator you can use the function TPM2_StirRandom (see TPM specification Part 1 Architecture Section Entropy Source and Collector). In unique the public part of the key is stored. The seed of an SRK primary key will be changed after calling Esys_Clear.
