### ISSUE TITLE
Insufficient error handling in file io

### ISSUE THREAD

**Issue by joholl** [tpm2-software/tpm2-tss#1978]
The `ifapi_io.c` does not handle some error correctly.

## Reproduce

 Write a simple program, initializing the fapi and reading the fapi configuration file (by default `/etc/tpm2-tss/fapi-config.json`):

```
#include "tss2/tss2_fapi.h"

void main(void) {
    FAPI_CONTEXT *ctx;
    Fapi_Initialize(&ctx, NULL);
}
```
Compile:
```
gcc $(pkg-config --cflags --libs tss2-fapi) main.c -o main
```

Execute:
```
TSS2_LOG=all+trace TSS2_FAPICONF=. ./main
```

Or for tracking where the error is:

```
TSS2_LOG=all+trace TSS2_FAPICONF=. strace ./main
```

## The actual problem

Errors due to non-existent files are reported just fine, because `fopen` is error-checked correctly (in this instance). However, the return code of `fseek` is not checked. Therefore, if a directory is given, `fopen` succeeds, `fseek` fails with -1 (`7fffffffffffffff`), and malloc(`7fffffffffffffff + 1`) fails, resulting in an OOM error message.

Similarly, if the permissions prevent reading, the fapi fails much later when trying to parse JSON. This distracts from an actual permissions problem. I did not look further into why that is.

This applies to multiple io library calls:
 * fopen
   * e.g. src/tss2-fapi/ifapi_io.c:67  (as a race condition)
 * fclose
   * never checked (arguable)
 * fseek
   *  src/tss2-fapi/ifapi_io.c:63
 * ftell
   * src/tss2-fapi/ifapi_io.c:64
 * fcntl
    * e.g. src/tss2-fapi/ifapi_io.c:76

**Comment by JuergenReppSIT** [comment]
@joholl Thank you for reporting this interesting case.
I could reproduce the malloc error with the "." file.  But fseek did return 0 in this case.
In my test ftell did return 7fffffffffffffff which is LONG_MAX.
So I will add the missing checks for -1 in ifapi_io.c and additionally check LONG_MAX for ftell.
I tried to reproduce an error related to the permissions for reading you did describe, but
the correct error messages were produced. Do you have a hint under what circumstances the
errors did occur?

**Comment by joholl** [comment]
@JuergenReppSIT You're right. The permissions issue was a mistake on my end.

I just assumed fseek failed, because my strace looked like this:

```c
openat(AT_FDCWD, ".", O_RDONLY)         = 3
fcntl(3, F_SETLK, {l_type=F_WRLCK, l_whence=SEEK_CUR, l_start=0, l_len=0}) = -1 EBADF (Bad file descriptor)
fstat(3, {st_mode=S_IFDIR|0755, st_size=12288, ...}) = 0
fstat(3, {st_mode=S_IFDIR|0755, st_size=12288, ...}) = 0
lseek(3, 0, SEEK_END)                   = 9223372036854775807
close(3)                                = 0
openat(AT_FDCWD, ".", O_RDONLY)         = 3
close(3)                                = 0
```

Thanks for taking care of this so quickly!
