### ISSUE TITLE
./configure will fail on Debian Buster

### ISSUE THREAD

**Issue by KeyvanArj** [tpm2-software/tpm2-tss#1979]
On Debian, by running the following command in `INSTALL` instruction :

```
$ ./configure
``` 

you will get the following error :

```
configure: error: Package requirements (libcurl) were not met:

No package 'libcurl' found

```

To solve it, you can install the following package:

```
$ sudo apt-get install libcurl4-openssl-dev
```

So please adjust the `INSTALL` file for Debian

**Comment by joholl** [comment]
The install instructions clearly list `libcurl development libraries` as a dependency.

See https://github.com/tpm2-software/tpm2-tss/blame/master/INSTALL.md#L54

**Comment by KeyvanArj** [comment]
`libcurl-dev` library is not available in `Debian Buster`, so the developer should use :

```
$ sudo apt-get install libcurl4-openssl-dev
```
