### ISSUE TITLE
Unable to read stored data from TPM NV memory

### ISSUE THREAD

**Issue by PavanKumaryc** [tpm2-software/tpm2-tss#1997]
Hi,
I am very new to TPM, I am working on storing a password in TPM NV memory so far i am successful in building TPM_TSS library and using TPM ESYS api to generate random number from TPM. 
Now I am trying to store password in TPM by defining NV space as follows..
1. Define space in TPM (used Esys_NV_DefineSpace () )
2. Write password (used Esys_NV_Write ())
3. Read Password (used Esys_NV_Read())
When i perform above sequence, password is getting stored perfectly but when i tried to only read/write(to already defined space) i am getting following error.
`WARNING:esys:../tpm2-tss-2.4.3/src/tss2-esys/api/Esys_NV_Read.c:315:Esys_NV_Read_Finish() Received TPM Error                                                            ERROR:esys:../tpm2-tss-2.4.3/src/tss2-esys/api/Esys_NV_Read.c:105:Esys_NV_Read() Esys Finish ErrorCode (0x00000184) `

but when i read the NV index from tpm-tool command(tpm2_nvread -C o  -s 20) it is reading stored password. 
Please help me to resolve this. I am suspecting an issue due to esys_context while reading/writing NV space but not sure.

**Comment by JuergenReppSIT** [comment]
The tpm tools also use Esys_NV_Read. You could check the source code of the tpm tools or the tpm2-tss integration tests
esys-nv.... to see how to use Esys_NV_Read.
