### ISSUE TITLE
keylime build fails on tpm2-tss

### ISSUE THREAD

**Issue by kgold2** [tpm2-software/tpm2-tss#2010]
This may not be a tpm2-tss issue, but it looks like it. Clone the keylime repo at https://github.com/keylime/keylime and run install.sh -o -m.

This installer seems to clone this repo and run autotools. The branch looks like 2.0.x. Here's the error, probably either on configure or make.

checking for doxygen... /usr/bin/doxygen
checking for perl... /usr/bin/perl
checking whether to build with code coverage support... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating Doxyfile
config.status: executing libtool commands
config.status: executing depfiles commands
config.status: error: in /tmp/tmp.gw9rr8aFlE/tpm/tpm2-tss': config.status: error: Something went wrong bootstrapping makefile fragments for automatic dependency tracking. Try re-running configure with the '--disable-dependency-tracking' option to at least be able to build the package (albeit without support for automatic dependency tracking). See config.log' for more details
Makefile:14664: *** missing separator. Stop.
Makefile:14664: *** missing separator. Stop.

**Comment by williamcroberts** [comment]
Are you able to build tpm2-tss on that machine? I wonder if your build machine is missing a dependency. I see issues around this often if your autoconf-archive isn't new enough. You need at least the 2018.03.13 release of autoconf archive.

```bash
autoconf_archive=autoconf-archive-2018.03.13
wget "http://mirror.kumi.systems/gnu/autoconf-archive/$autoconf_archive.tar.xz" 
tar -xf $autoconf_archive.tar.xz 
rm $autoconf_archive.tar.xz
cd $autoconf_archive
./configure --prefix=/usr
make -j $(nproc)
sudo make install
rm -fr $autoconf_archive.tar.xz
```
On distros like ubuntu 20.04 its new enough:
```bash
apt show autoconf-archive
Package: autoconf-archive
Version: 20190106-2.1ubuntu1
<snip>
```

**Comment by tstruk** [comment]
I have opened an issue in keylime to update it to a more recent version if TSS.
https://github.com/keylime/keylime/issues/573

**Comment by williamcroberts** [comment]
It was working before, and the build stopped working, why?
________________________________

**Comment by kgold2** [comment]
I haven't yet gotten it working.  Each distro, distro version, and set of packages seem to have it's own issues.  I'm trying every platform I can to find one where everything works.

**Comment by kgold2** [comment]
Today's attempt, pulling the latest master:

Ubuntu 16 gives:

 DXGEN  Doxyfile
warning: Tag 'PERL_PATH' at line 2220 of file 'Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'MSCGEN_PATH' at line 2242 of file 'Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
/home/kgold/tpm2-tss/README.md:47: warning: unable to resolve reference to 'INSTALL.md' for \ref command
/home/kgold/tpm2-tss/README.md:54: warning: unable to resolve reference to 'CONTRIBUTING.md' for \ref command
/home/kgold/tpm2-tss/README.md:57: warning: unable to resolve reference to 'INSTALL.md' for \ref command
/home/kgold/tpm2-tss/README.md:90: warning: unable to resolve reference to 'INSTALL.md' for \ref command
/home/kgold/tpm2-tss/README.md:200: warning: unable to resolve reference to 'doc/fuzzing.md' for \ref command
/home/kgold/tpm2-tss/README.md:47: warning: unable to resolve reference to 'INSTALL.md' for \ref command
/home/kgold/tpm2-tss/README.md:54: warning: unable to resolve reference to 'CONTRIBUTING.md' for \ref command
/home/kgold/tpm2-tss/README.md:57: warning: unable to resolve reference to 'INSTALL.md' for \ref command
/home/kgold/tpm2-tss/README.md:90: warning: unable to resolve reference to 'INSTALL.md' for \ref command
/home/kgold/tpm2-tss/README.md:200: warning: unable to resolve reference to 'doc/fuzzing.md' for \ref command

Ubuntu 20 gives:

(many of these)
  CCLD     src/tss2-esys/libtss2-esys.la
ar: `u' modifier ignored since `D' is the default (see `U')

(many of these)
/home/kgold/tpm2-tss/README.md:11: warning: Unexpected html tag <img> found within <a href=...> context
/home/kgold/tpm2-tss/README.md:12: warning: Unexpected html tag <img> found within <a href=...> context
/home/kgold/tpm2-tss/README.md:47: warning: unable to resolve reference to `INSTALL.md' for \ref command
/home/kgold/tpm2-tss/README.md:52: warning: Unexpected html tag <img> found within <a href=...> context
/home/kgold/tpm2-tss/README.md:54: warning: unable to resolve reference to `CONTRIBUTING.md' for \ref command

**Comment by williamcroberts** [comment]
All the warnings are superfluous, just ignore them.

The AR warnings seem to be an automake issue: http://gnu-automake.7480.n7.nabble.com/bug-20082-new-warning-from-ar-on-rawhide-systems-td21769.html

The upgrade Doxyfile script (doxygen -u), if we drop those lines, I believe it will cause older doxygen versions blow up, so we just leave it alone.

`/home/kgold/tpm2-tss/README.md:47: warning: unable to resolve reference to 'INSTALL.md' for \ref command`
Doxygen's bug: https://github.com/doxygen/doxygen/issues/7595
