### ISSUE TITLE
 make error DXGEN  Doxyfile

### ISSUE THREAD

**Issue by kgold2** [tpm2-software/tpm2-tss#2018]
ubuntu 16 xenial Many errors building documentation.  A few are:

/home/kgold/tpm2-tss/README.md:2: warning: Unexpected html tag <img> found within <a href=...> context

/home/kgold/tpm2-tss/README.md:47: warning: unable to resolve reference to `INSTALL.md' for \ref command

/home/kgold/tpm2-tss/README.md:192: warning: unable to resolve reference to `doc/fuzzing.md' for \ref command

**Comment by tstruk** [comment]
This is a doxygen issue: https://github.com/doxygen/doxygen/issues/7595
Looks like it's fixed in doxygen v1.8.19

**Comment by jfboismenu** [comment]
Hi, I'm getting the same error in 1.9.1. I've left notes notes on doxygen/doxygen#7595

**Comment by kgold2** [comment]
> Looks like it's fixed in doxygen v1.8.19

Ubuntu 20 focal has this.  That's pretty recent.  Advice?  I'd hate to abandon Ubuntu just because some man pages can't build.

doxygen/focal,now 1.8.17-0ubuntu2 amd64 [installed]

**Comment by williamcroberts** [comment]
@tstruk any reason we don't build the docs in the release tarball? Then folks can get release tarballs and avoid this?

**Comment by williamcroberts** [comment]
@kgold2  there are a few solutions to your problem:
  - Ignore it as the docs are still fine
  - Grab a release tarball, like https://github.com/tpm2-software/tpm2-tss/releases/download/3.0.3/tpm2-tss-3.0.3.tar.gz
    - **Note**: It is an error to grab the Github generated "Source code" zip or tarballs, they are the same as a git clone without 
         the .git directory, so you'll still be building the docs.
  - Configure with --disable-doxygen-doc
  - Remove doxygen-doc executable, the build will skip building the docs IIUC

**Comment by kgold2** [comment]
> @tstruk any reason we don't build the docs in the release tarball? Then folks can get release tarballs and avoid this?

Seems right to me.  Build them locally, commit them to git, and avoid all the doxygen incompatibilities.  (That's what I do.)

**Comment by kgold2** [comment]
>     * Configure with --disable-doxygen-doc

This works.
