### ISSUE TITLE
RHEL 7.9 coding_standard_c.md

### ISSUE THREAD

**Issue by kgold2** [tpm2-software/tpm2-tss#2024]
make on RHEL 7.9 yields many errors of this form:

home/kgold/tpm2-tss/doc/coding_standard_c.md:188: warning: explicit link request to 'ifndef' could not be resolved
/home/kgold/tpm2-tss/doc/coding_standard_c.md:189: warning: explicit link request to 'define' could not be resolved
/home/kgold/tpm2-tss/doc/coding_standard_c.md:191: warning: explicit link request to 'include' could not be resolved
/home/kgold/tpm2-tss/doc/coding_standard_c.md:192: warning: explicit link request to 'include' could not be resolved
/home/kgold/tpm2-tss/doc/coding_standard_c.md:194: warning: explicit link request to 'include' could not be resolved
/home/kgold/tpm2-tss/doc/coding_standard_c.md:196: warning: explicit link request to 'include' could not be resolved
/home/kgold/tpm2-tss/doc/coding_standard_c.md:202: warning: explicit link request to 'endif' could not be resolved
/home/kgold/tpm2-tss/doc/coding_standard_c.md:210: warning: explicit link request to 'include' could not be resolved
/home/kgold/tpm2-tss/doc/coding_standard_c.md:211: warning: explicit link request to 'include' could not be resolved
/home/kgold/tpm2-tss/doc/coding_standard_c.md:213: warning: explicit link request to 'include' could not be resolved
/home/kgold/tpm2-tss/doc/coding_standard_c.md:215: warning: explicit link request to 'include' could not be resolved
/home/kgold/tpm2-tss/doc/coding_standard_c.md:216: warning: explicit link request to 'include' could not be resolved
/home/kgold/tpm2-tss/doc/coding_standard_c.md:218: warning: explicit link request to 'include' could not be resolved
/home/kgold/tpm2-tss/doc/coding_standard_c.md:219: warning: explicit link request to 'include' could not be resolved
/home/kgold/tpm2-tss/doc/logging.md:33: warning: explicit link request to 'define' could not be resolved
/home/kgold/tpm2-tss/doc/logging.md:34: warning: explicit link request to 'include' could not be resolved
/home/kgold/tpm2-tss/doc/logging.md:38: warning: explicit link request to 'define' could not be resolved
/home/kgold/tpm2-tss/doc/logging.md:39: warning: explicit link request to 'define' could not be resolved
/home/kgold/tpm2-tss/doc/logging.md:40: warning: explicit link request to 'include' could not be resolved

**Comment by williamcroberts** [comment]
These are **warnings not errors**. doxygen can be noisy, theirs a lot of bugs in doxygen itself, like this https://github.com/doxygen/doxygen/issues/7595, but these are issues in doxygen, not out project.

Depending on the version of doxygen used, you'll get varying mileage, but in general as long as you get a doxygen-doc output directory, and something like `google-chrome doxygen-doc/html/index.html` then you're good to go.

We've just learned to live with the noise, as the generated documentation far outweighs these superfluous warnings as well as lets us publish the results to something like ReadTheDocs as things change:
  - https://tpm2-tss.readthedocs.io/en/latest/

Closing this, as their isn't really anything I have found to help silence these errors consistently across doxygen versions. If you want the noise gone, and to speed up local builds, configure option `--disable-doxygen-doc`
