### ISSUE TITLE
RHEL 79. make install fails with Failed to create the FAPI directories

### ISSUE THREAD

**Issue by kgold2** [tpm2-software/tpm2-tss#2025]
/bin/mkdir -p '/usr/local/lib/udev/rules.d'
 /bin/install -c -m 644 dist/tpm-udev.rules '/usr/local/lib/udev/rules.d'
make  install-data-hook
make[2]: Entering directory `/home/kgold/tpm2-tss'
(id -g tss 2>/dev/null || groupadd -r tss) && (id -u tss 2>/dev/null || useradd -r -g tss tss) || echo "*** WARNING *** Failed to create the tss user and group"
59
59
systemd-tmpfiles --create || echo "*** WARNING *** Failed to create the FAPI directories with the correct permissions"
(    if [ ! -d "/usr/local/var/run/tpm2-tss/eventlog/" ]; then echo "*** WARNING *** Directory /usr/local/var/run/tpm2-tss/eventlog/ could not be created"; fi)
*** WARNING *** Directory /usr/local/var/run/tpm2-tss/eventlog/ could not be created
(    if [ ! -d "/usr/local/var/lib/tpm2-tss/system/keystore/" ]; then echo "*** WARNING *** Directory /usr/local/var/lib/tpm2-tss/system/keystore/ could not be created"; fi)
*** WARNING *** Directory /usr/local/var/lib/tpm2-tss/system/keystore/ could not be created
if [ ! -z "" ]; then \
	mv /usr/local/lib/udev/rules.d/tpm-udev.rules /usr/local/lib/udev/rules.d/tpm-udev.rules; \
fi

**Comment by williamcroberts** [comment]
@tstruk is their anyway to hide this make stanza from the output, silent rules?

Perhaps we put it in a script to make it a little cleaner in the output?

I don't like seeing the `*** WARNING ***` in the logz, and have to check and see if it was actually echo'd or not.

**Comment by tstruk** [comment]
Yes, it's a bit too noisy alright.

**Comment by williamcroberts** [comment]
The default location is usually `/usr/local/lib/pkgconfig` which sometimes isn't on distro package config paths. Ubuntu has it set up:
```
pkg-config --variable=pc_path pkg-config
/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig
```
