### ISSUE TITLE
Test installation with systemd tools

### ISSUE THREAD

**Issue by JuergenReppSIT** [tpm2-software/tpm2-tss#2027]
The generic build test for Ubuntu 20.04 did not use the systemd tools:

```
2021-03-12T23:27:49.8252791Z Ubuntu
2021-03-12T23:27:49.8253159Z 20.04.2
...
2021-03-12T23:29:18.4520559Z checking for systemd-sysusers... no
2021-03-12T23:29:18.4528742Z checking for systemd-tmpfiles... no
```

So the fall-back for the directory creation was executed during installation.
There should be at least one test which uses the systemd tools for the creation of the directories.

**Comment by tstruk** [comment]
> There should be at least one test which uses the systemd tools for the creation of the directories.
I'm sure if I understand correctly. Do you want a CI setup that actually tests the systemd tools?
There are some that do use these, for instance Fedora 32: 
https://github.com/tpm2-software/tpm2-tss/pull/2026/checks?check_run_id=2099774531#step:3:1181
https://github.com/tpm2-software/tpm2-tss/pull/2026/checks?check_run_id=2099774531#step:3:2783
https://github.com/tpm2-software/tpm2-tss/pull/2026/checks?check_run_id=2099774531#step:3:2786

**Comment by JuergenReppSIT** [comment]
I  did not take into account that only a warning is produced if e.g. the keystore directory can't be created during installation. After I saw that the systemd tools are not used for Ubuntu 20.04 I thought that this test case was not covered. So we can close the issue.
@tstruk Do you think we should backport  PR #2026?

**Comment by tstruk** [comment]
Yes, it should be backported to 3.0.x. I will take care of that.
