### ISSUE TITLE
JSONC_CFLAGS and CURL_CFLAGS ignored when building `libtss2_fapi`

### ISSUE THREAD

**Issue by safayetahmedatge** [tpm2-software/tpm2-tss#2033]
### The Issue
Issue arises when trying to build the tpm2-tss for QNX 7.1.

The QNX SDP doesn't come with `json-c`. The `json-c` library must be built and installed to a (sysroot) DESTDIR. 

Also, there is no `pkg-config` files for `libcurl`.

Additionally, the `--with-sysroot` option to the configure script is ignored.

As a result, for `json-c` and `libcurl`, the following environment variables have to be set:

- `JSONC_CFLAGS`
- `JSONC_LIBS`
- `CURL_CFLAGS`
- `CURL_LIBS`

However, the build still reports errors about missing `"json-c/json.h"`.

### Possible Fix
Currently, the CFLAGS and LDFLAGS for libfapi are listed as follows:
https://github.com/tpm2-software/tpm2-tss/blob/3c1e7173b3dedc08afa537ed34cee0b4a744000f/Makefile.am#L549-L550

Should  `$(JSONC_CFLAGS)` and `$(CURL_CFLAGS)` be added as shown below?
```
src_tss2_fapi_libtss2_fapi_la_CFLAGS  = $(AM_CFLAGS) -I$(srcdir)/src/tss2-fapi $(JSONC_CFLAGS) $(CURL_CFLAGS)
src_tss2_fapi_libtss2_fapi_la_LDFLAGS = $(AM_LDFLAGS) $(LIBCRYPTO_LIBS) $(JSONC_LIBS) $(CURL_LIBS) 
```

thank you

**Comment by tstruk** [comment]
> Should `$(JSONC_CFLAGS)` and `$(CURL_CFLAGS)` be added as shown below?
> 
> ```
> src_tss2_fapi_libtss2_fapi_la_CFLAGS  = $(AM_CFLAGS) -I$(srcdir)/src/tss2-fapi $(JSONC_CFLAGS) $(CURL_CFLAGS)
> src_tss2_fapi_libtss2_fapi_la_LDFLAGS = $(AM_LDFLAGS) $(LIBCRYPTO_LIBS) $(JSONC_LIBS) $(CURL_LIBS) 
> ```

Looks like they should. Could you send a PR with this change please. Thanks

**Comment by safayetahmedatge** [comment]
It's a fairly minor change. Would someone else be able to make the pull request?

I apologize if this is inconvenient, but this could involve "processes" around contributing code to an open-source project I would rather not get into. I was cautioned about this by colleagues after similar contributions in the past.

**Comment by tstruk** [comment]
I can make that change, no problem. Thanks for reporting.
