### ISSUE TITLE
src/tss2-esys/esys_iutil.c: iesus_gen_auths adding encryptNonce and decryptNonce for non-encrypted sessions at index 0

### ISSUE THREAD

**Issue by idesai** [tpm2-software/tpm2-tss#2037]
@JuergenReppSIT, What is the reason for [this](https://github.com/tpm2-software/tpm2-tss/blob/master/src/tss2-esys/esys_iutil.c#L1341:L1344) check?

Due to this, the authorization hmac session at index 0 is inadvertently including the encryptNonce and decryptNonce despite sessionAttributes indicating that the parameter encryption is turned off.

Issue also captured in [tpm2-tools](https://github.com/tpm2-software/tpm2-tools/issues/2377).

**Comment by idesai** [comment]
the check should instead be like:
(session_idx == decryptNonceIdx) ? decryptNonce : 0
(session_idx == encryptNonceIdx) ? encryptNonce : 0

**Comment by AndreasFuchsSIT** [comment]
IMHO, the code is correct.
It resembles the following statements from the TPM spec `19.6.5 HMAC Computation`:
```
in   the   HMAC   computation   for   the   first   authorization   session   of   a   command,  if  a  different  session  is  being  used  for  parameter  decryption,  then  the  nonceTPM for  that  session  is  included  in  the  HMAC  of  the  first  authorization  session
```

Jürgen suspecs that the tools pass 2 sessions instead of 1.

**Comment by JuergenReppSIT** [comment]
That's true. session1 determined from the parent object in:
https://github.com/tpm2-software/tpm2-tools/blob/acfaa4fab1f6efbecf98161f11c00e68f1387c20/lib/tpm2.c#L1300
session2 is the session determined by tpm2_util_aux_sessions_setup.

**Comment by AndreasFuchsSIT** [comment]
Ok, so for TPM2_Create, only the first session can be an auth/policy session. Session 2 may only be an audit-session.
So either the -S is for aux-audit-sessions or it needs to be handled differently inside the commands.

**Comment by idesai** [comment]
Here, in the case of TPM2_Create, of the 3 sessions allowed in a command,
1. The first is the hmac auth session for auth.
2. Second session can be for encrypt/ decrypt.
3. Third session is empty.

IMHO this is a valid configuration.

What I am pointing out is that, the decryptNonce and encryptNonce is added during the hmac calculation for the first session even though the first session has both encrypt and decrypt turned off in the session attributes.

**Comment by idesai** [comment]
@AndreasFuchsSIT @JuergenReppSIT there is still a condition that isn't handled in iesys_comput_hmac.
Look at 19.6.5 Note 7
```If the same session (not the first session) is used for decrypt and encrypt, its nonceTPM is only used once. If different sessions are used for decrypt and encrypt, both nonceTPMs are included.```

**Comment by idesai** [comment]
> @AndreasFuchsSIT @JuergenReppSIT there is still a condition that isn't handled in iesys_compute_hmac.
> Look at 19.6.5 Note 7
> `If the same session (not the first session) is used for decrypt and encrypt, its nonceTPM is only used once. If different sessions are used for decrypt and encrypt, both nonceTPMs are included.`

Compare this to [ComputeCommandHMAC](https://github.com/microsoft/ms-tpm-20-ref/blob/b94f9f92c579b723a16be72a69efbbf9c35ce44e/TPMCmd/tpm/src/main/SessionProcess.c#L851) from the TPM reference implementation.

**Comment by idesai** [comment]
please include this in 3.0.x and the latest 3.0.4-rc1?

**Comment by idesai** [comment]
> @tstruk please include this in 3.0.x and the latest 3.0.4-rc1?

@williamcroberts is this on 3.0.4-rc ?

**Comment by williamcroberts** [comment]
> > @tstruk please include this in 3.0.x and the latest 3.0.4-rc1?
> 
> @williamcroberts is this on 3.0.4-rc ?

Ill have to cut rc1, it's commit da74d44e8 which is two commits over rc0

**Comment by idesai** [comment]
It is on the branch 3.0.x and now that we are having 3.1 rc, may be it's a good idea to have a 3.X branch.
