### ISSUE TITLE
Unable to read size of stored data in TPM

### ISSUE THREAD

**Issue by PavanKumaryc** [tpm2-software/tpm2-tss#2038]
Hi,
I am facing issue while reading stored data from NV space of TPM.
I have defined 3 NV index areas of size 768 bytes(total 2304 bytes) each and I am storing data of size 1900 bytes in those 3 NV space(768+786+364).
I am able to read first and second NV space (full 768 bytes) successfully but unable to read third space as it throws error while i tried to read full 768 byte (Here i am reading full 768 because i am not saving size of stored data anywhere).
To solve this issue i tried reading PublicInfo using Esys_NV_readPublic() API but nvPublic->nvPublic.dataSize   always gives 768 instead of stored data size (364).

    TSS2_RC err; 
    ESYS_CONTEXT *ctx;
    TPM2B_MAX_NV_BUFFER *nvReadData;
    ESYS_TR nvHandle = ESYS_TR_NONE;
    TPM2B_NV_PUBLIC *nvPublic;
    TPM2B_NAME *nvName ;

    Esys_Initialize(&ctx, NULL, NULL);
    Esys_TR_FromTPMPublic (ctx, nv_index , ESYS_TR_NONE, ESYS_TR_NONE, ESYS_TR_NONE, &nvHandle);
    Esys_NV_ReadPublic       (ctx,nvHandle,ESYS_TR_NONE,ESYS_TR_NONE ,ESYS_TR_NONE, &nvPublic,&nvName);
    Esys_NV_Read                 (ctx, ESYS_TR_RH_OWNER, nvHandle, ESYS_TR_PASSWORD, ESYS_TR_NONE, ESYS_TR_NONE, 
                                             nvPublic->nvPublic.dataSize, 0, &nvReadData);

I went through tpm2_tools source code also because  tpm2_nvread -C o 2 will read only stored data(364bytes) irrespective of NV size but did not get any clue.
I am stuck in this issue, please suggest me how i can read size of stored data size.

Thank you so much in advance.

**Comment by williamcroberts** [comment]
> Hi,
> I am facing issue while reading stored data from NV space of TPM.
> I have defined 3 NV index areas of size 768 bytes(total 2304 bytes) each and I am storing data of size 1900 bytes in those 3 NV space(768+786+364).
> I am able to read first and second NV space (full 768 bytes) successfully but unable to read third space as it throws error while i tried to read full 768 byte (Here i am reading full 768 because i am not saving size of stored data anywhere).
> To solve this issue i tried reading PublicInfo using Esys_NV_readPublic() API but nvPublic->nvPublic.dataSize always gives 768 instead of stored data size (364).
> 
> ```
> TSS2_RC err; 
> ESYS_CONTEXT *ctx;
> TPM2B_MAX_NV_BUFFER *nvReadData;
> ESYS_TR nvHandle = ESYS_TR_NONE;
> TPM2B_NV_PUBLIC *nvPublic;
> TPM2B_NAME *nvName ;
> 
> Esys_Initialize(&ctx, NULL, NULL);
> Esys_TR_FromTPMPublic (ctx, nv_index , ESYS_TR_NONE, ESYS_TR_NONE, ESYS_TR_NONE, &nvHandle);
> Esys_NV_ReadPublic       (ctx,nvHandle,ESYS_TR_NONE,ESYS_TR_NONE ,ESYS_TR_NONE, &nvPublic,&nvName);
> Esys_NV_Read                 (ctx, ESYS_TR_RH_OWNER, nvHandle, ESYS_TR_PASSWORD, ESYS_TR_NONE, ESYS_TR_NONE, 
>                                          nvPublic->nvPublic.dataSize, 0, &nvReadData);
> ```
> 
> I went through tpm2_tools source code also because tpm2_nvread -C o 2 will read only stored data(364bytes) irrespective of NV size but did not get any clue.
> I am stuck in this issue, please suggest me how i can read size of stored data size.
> 
> Thank you so much in advance.

tpm2-tools uses Esys_NV_ReadPublic public. So if you're getting a different size then you expect, perhaps:
- The NV Index used for Esys_NV_ReadPublic is wrong
- The NV_DefineSpace isn't setting up the size properly, its using 768 instead of 364

The tpm2_nvdefine command has the -s paramter which sets the size field, it defaults to something like 2048

So if you write a string to it, it will look like it only reads string length in bytes. But it really reads all 2048 unless you specify differently. It's just the shell sees the '\0' and ends the output.

```bash
tpm2_nvdefine
echo hello | tpm2_nvwrite -Co -i- 0x1000000
tpm2_nvread 0x1000000 | xxd
00000000: 6865 6c6c 6f0a 0000 0000 0000 0000 0000  hello...........
<snip>
000007f0: 0000 0000 0000 0000 0000 0000 0000 0000  ................

# notics the size is 2048, it only cares about tpm2_nvdefine, it doesn't keep track of how much data you sent to it. So if you want
# 368 bytes, define it that way OR add logic to store a fixed width integer value, like a UINT16, to the first two bytes, and then # your data. This way you know how much to read.
tpm2_nvreadpublic 0x1000000
0x1000000:
  name: 000b287c9b1b06fab6e51bd26e98ea89460574e97a3d2ef995eb35f7e23db7e94f67
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: ownerwrite|authwrite|ownerread|authread|written
    value: 0x6000620
  size: 2048
```
