### ISSUE TITLE
interface type confusion for Esys_EncryptDecrypt

### ISSUE THREAD

**Issue by Superhepper** [tpm2-software/tpm2-tss#2056]
I apologize in advance for this might not be the correct place for this kind of question/bug.

I ran into something that made me rather confused when it came to the use of the interface type in the Esys_EncryptDecrypt2 api.
The code uses the following interface type
https://github.com/tpm2-software/tpm2-tss/blob/adfa451c1ec362ac5ce19a644baf48d7003cb3d8/src/tss2-esys/api/Esys_EncryptDecrypt2.c#L75

And according to *TCG TSS 2.0 Enhanced System API (ESAPI) Specification, Version 1.00, Revision 08* this is correct.

And when you look at the API at sys level it looks the same
https://github.com/tpm2-software/tpm2-tss/blob/adfa451c1ec362ac5ce19a644baf48d7003cb3d8/src/tss2-sys/api/Tss2_Sys_EncryptDecrypt2.c#L20

And according to *TCG TSS 2.0 System Level API (SAPI) Specification, Version 1.1, Revision 29* this is correct.

But when you look at *Trusted Platform Module Library Part 3: Commands, Family 2.0, Level 00 Revision 01.59, Section 15.3.2*
it says that the interface type for mode should be ```TPMI_ALG_CIPHER_MODE+```.

And the ```TPMI_ALG_SYM_MODE``` contains more algorithms then ```TPMI_ALG_CIPHER_MODE+```. 

So how can SAPI and ESAPI be allowed to use algorithms that is not supported by the TPM command?

**Comment by Superhepper** [comment]
I may have found why they have diverged.

**TCG Guide for TPM Library Specification Changes Revision 1.38 to 1.59, Version 1.4**
>5.3 TPMI_ALG_CIPHER_MODE – TPM2_EncryptDecrypt/2
>5.3.1 Description
>This change is necessary to enable the changes to the MAC commands described 
>in section 4.3 TPM2_MAC, TPM2_MAC_Start (of this document). 
>5.3.2 Old Behavior
>In Library specification revision 1.38, the interface type of the 
>mode parameter of TPM2_EncryptDecrypt() and TPM2_EncryptDecrypt2() was defined as 
>TPMI_ALG_SYM_MODE, which allowed selection of a symmetric encryption/decryption >mode.
>5.3.3 New Behavior
>In Library specification revision 1.59, the interface type of the mode
>parameter of TPM2_EncryptDecrypt() and TPM2_EncryptDecrypt2() has been changed to 
>TPMI_ALG_CIPHER_MODE. The new interface type TPMI_ALG_CIPHER_MODE equals
>the previous definition of TPMI_ALG_SYM_MODE in revision 1.38 and is 
>therefore backwards compatible. 
>Affected commands: TPM2_EncryptDecrypt(), TPM2_EncryptDecrypt2()
>5.3.4 Impact on Software
>Software using the TPM must change the interface type of the mode
>parameter in the same way as the reference code. As 
>TPMI_ALG_CIPHER_MODE is identical to the previous definition of >TPMI_ALG_SYM_MODE in revision 1.38, there is no impact on compatibility

So is this a case where the SAPI and ESAPI specifications have not been updated to follow the new TPM library specifications? And what happens if I use the new version of the TPMI_ALG_SYM_MODE as ESAPI says I could but using algorithms that are not supported?

**Comment by tstruk** [comment]
> So is this a case where the SAPI and ESAPI specifications have not been updated to follow the new TPM library specifications? And what happens if I use the new version of the TPMI_ALG_SYM_MODE as ESAPI says I could but using algorithms that are not supported?

Yes, SAPI and ESAPI specs need to be updated to be in sync with the TPM2.0 1.59 specification.
You can use the new type as they are the same.

**Comment by Superhepper** [comment]
Ok thank you very much. I will do that.
