### ISSUE TITLE
tpm2 commands failing with bad-address 

### ISSUE THREAD

**Issue by defaultshr** [tpm2-software/tpm2-tss#2060]
Facing following issues while running TPM commands on dell system. Same lockout clear operation when tried using go-tpm code works fine. 
TPM commands got into this situation when i was trying resetting dictionary lockout parameters using tpm2 commands and in parallel attempting TPM sign in loop to check if i hit any lockout situation. 

$ uname -a
Linux dell2-PowerEdge-R540 4.15.0-140-generic #144-Ubuntu SMP Fri Mar 19 14:12:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linu
-------------------------------
$ sudo tpm2_dictionarylockout -c
ERROR:tcti:src/util/io.c:108:write_all() failed to write to fd 3: Bad address 
ERROR:tcti:src/tss2-tcti/tcti-device.c:126:tcti_device_transmit() wrong number of bytes written. Expected 59, wrote 0. 
ERROR:esys:src/tss2-esys/api/Esys_StartAuthSession.c:283:Esys_StartAuthSession_Async() Finish (Execute Async) ErrorCode (0x000a000a) 
ERROR:esys:src/tss2-esys/api/Esys_StartAuthSession.c:113:Esys_StartAuthSession() Error in async function ErrorCode (0x000a000a) 
ERROR: Esys_StartAuthSession(0xA000A) - tcti:IO failure
ERROR: Invalid authorization
ERROR: Unable to run tpm2_dictionarylockout
---
Kernel logs at this execution (tail -f kern.log)

Apr  9 11:55:26 dell2-PowerEdge-R540 kernel: [365097.011342] tpm tpm0: tpm2_save_context: failed with a TPM error 0x0901
Apr  9 11:55:26 dell2-PowerEdge-R540 kernel: [365097.032919] tpm tpm0: A TPM error (139) occurred flushing context
Apr  9 11:55:26 dell2-PowerEdge-R540 kernel: [365097.032923] tpm tpm0: tpm2_commit_space: error -14
-----------------

tpm2-tss and tpm2-tools lib code details: 
**TPM-TSS commit head** 
commit 2d7233eedb83465866bae63761be79b0a28a511b (HEAD -> master, origin/master, origin/HEAD)
Author: Juergen Repp <juergen.repp@sit.fraunhofer.de>
Date:   Thu Sep 10 15:53:37 2020 +0200

**TPM2-Tools**
Pulled today only. 
https://github.com/tpm2-software/tpm2-tools/commit/1afcea9b5edca9e6cacacf4da09c99737131cbb0
Commits on Apr 9, 2021
PCR: Allow empty PCR selection by specifying keyword none. …

PeterHuewe authored and idesai committed 10 hours ago

**Comment by williamcroberts** [comment]
Wrong project, please report to tpm2-tools: https://github.com/tpm2-software/tpm2-tools
