### ISSUE TITLE
Branch 2.0.x fails on Ubuntu 20 groovy

### ISSUE THREAD

**Issue by kgold2** [tpm2-software/tpm2-tss#2066]
config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  If GNU make was not used, consider
    re-running the configure script with MAKE="gmake" (or whatever is
    necessary).  You can also try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).

I don't know why keylime is using this branch.  If it's no longer maintained, could you tell the keylime maintainers not to specify it.  Perhaps recommend a better version.  If it is still valid, there's a bug.

**Comment by AndreasFuchsSIT** [comment]
2.0.x is very outdated and not maintained anymore.
Please try 3.0.x or 2.4.x ?

Also could you point me to the place at keylime where this 2.0.x branch is referenced ?

**Comment by utkarsh2102** [comment]
Hello,

> Perhaps recommend a better version. If it is still valid, there's a bug.

There exists a [tpm2-tss](https://launchpad.net/ubuntu/+source/tpm2-tss) package in Ubuntu and in Groovy it's at v3.0.1-1. I believe you could simple `apt install` this (for eg: `apt install libtss2-dev`), no?

**Comment by kgold2** [comment]
> 2.0.x is very outdated and not maintained anymore.
> Please try 3.0.x or 2.4.x ?
> 
> Also could you point me to the place at keylime where this 2.0.x branch is referenced ?

https://github.com/keylime/keylime/blob/master/installer.sh

line 17

**Comment by williamcroberts** [comment]
I saw this on the mailing list as:
  - https://lists.01.org/hyperkitty/list/tpm2@lists.01.org/thread/Y6L242IK5RE3SQO6EVXOSZQ7L5A7TGYS/

solution should be there.

**Comment by williamcroberts** [comment]
> > 2.0.x is very outdated and not maintained anymore.
> > Please try 3.0.x or 2.4.x ?
> > Also could you point me to the place at keylime where this 2.0.x branch is referenced ?
> 
> https://github.com/keylime/keylime/blob/master/installer.sh
> 
> line 17

You can bump the installer versions AFAICT:
```diff
diff --git a/installer.sh b/installer.sh
index 64a0b9ca9143..5ee4782df833 100755
--- a/installer.sh
+++ b/installer.sh
@@ -14,8 +14,8 @@ TPM2SIM_SRC=http://sourceforge.net/projects/ibmswtpm2/files/ibmtpm1119.tar.gz/do
 KEYLIME_VER="master"
 TPM4720_VER="master"
 GOLANG_VER="1.13.1"
-TPM2TSS_VER="2.0.x"
-TPM2TOOLS_VER="3.X"
+TPM2TSS_VER="3.0.3"
+TPM2TOOLS_VER="4.2"
 
 # Minimum version requirements
 MIN_PYTHON_VERSION="3.6.7"
```

keylime has support for newer tools versions, up to 4.2 last time I looked.
