### ISSUE TITLE
2.4.0 JSON_C_CFLAGS: command not found, etc

### ISSUE THREAD

**Issue by kgold2** [tpm2-software/tpm2-tss#2071]
A normal build on Ubuntu groovy yields.  I don't know if this is important, but it seems like an error.

At the end, it says     tpm2-tss 2.4.6-rc0

checking for libcrypto... yes
./configure: line 13075: JSON_C_CFLAGS: command not found
./configure: line 13076: C: command not found
./configure: line 13077: JSON_C_LIBS: command not found
checking for json-c... yes
./configure: line 13176: CURL_CFLAGS: command not found
./configure: line 13177: CURL_LIBS: command not found
checking for libcurl... yes

**Comment by williamcroberts** [comment]
That looks like one to worry about.

**Comment by williamcroberts** [comment]
@kgold2 m4 quotes needed, here's the patch I have that fixes it for me:
```diff
diff --git a/configure.ac b/configure.ac
index 1cf604118e5e..520b18e69729 100644
--- a/configure.ac
+++ b/configure.ac
@@ -161,16 +161,16 @@ AC_SUBST([TSS2_ESYS_CFLAGS_CRYPTO])
 AC_SUBST([TSS2_ESYS_LDFLAGS_CRYPTO])
 
 AS_IF([test "x$enable_fapi" != xno -a "x$enable_esapi" = "xno"],
-    AC_MSG_ERROR([ESAPI has to be enabled to compile FAPI.]))
+    [AC_MSG_ERROR([ESAPI has to be enabled to compile FAPI.])])
 
 AS_IF([test "x$enable_fapi" != xno -a "x$with_crypto" != "xossl"],
-    AC_MSG_ERROR([FAPI has to be compiled with OpenSSL]))
+    [AC_MSG_ERROR([FAPI has to be compiled with OpenSSL])])
 
 AS_IF([test "x$enable_fapi" = xyes ],
-    PKG_CHECK_MODULES([JSON_C], [json-c]))
+    [PKG_CHECK_MODULES([JSON_C], [json-c])])
 
 AS_IF([test "x$enable_fapi" = xyes ],
-    PKG_CHECK_MODULES([CURL], [libcurl]))
+    [PKG_CHECK_MODULES([CURL], [libcurl])])
 
 AC_ARG_WITH([tctidefaultmodule],
             [AS_HELP_STRING([--with-tctidefaultmodule],
```

Can you confirm? Ill stage it for 2.4.6-rc1 and see if it applies to the other branches as well.

**Comment by kgold2** [comment]
When I checkout 2.4.x, I now get tpm2-tss 2.4.6-rc2 and I don't get the json error.  It doesn't have the [].  I don't know how to get rc0.

I haven't figured out the TSS branch and tag naming convention.  Perhaps put a description on the home page.

The mysteries of git and autotools.  It's possible that I got a new version of autotools that now works.

**Comment by williamcroberts** [comment]
> When I checkout 2.4.x, I now get tpm2-tss 2.4.6-rc2 and I don't get the json error. It doesn't have the []. I don't know how to get rc0.
> 
> I haven't figured out the TSS branch and tag naming convention. Perhaps put a description on the home page.

This covers the tagging explictly:
  - https://github.com/tpm2-software/tpm2-tss/blob/master/RELEASE.md

It follows semantic versioning, so version numbers are in the form A.B.C, where:
A --> major API breaking change
B --> added feature
C --> bug fix

-rcN is added for release candidates.

When you're tracking a branch, the HEAD of that branch will move. If you need a specific thing, you would check out the tag. Eventually a tag without the RC will be made that points to a specific commit that is a release on that branch.

> 
> The mysteries of git and autotools. It's possible that I got a new version of autotools that now works.

**Comment by AndreasFuchsSIT** [comment]
I'll assume this is fixed for the 3.x releases and 2.4 is going eol now.
