### ISSUE TITLE
Fapi nameAlg default value inconsistency breaks PolicySigned

### ISSUE THREAD

**Issue by joholl** [tpm2-software/tpm2-tss#2080]
The root problem: the default nameAlg for public keys is SHA1 in some cases and SHA256 in other cases.

This breaks PolicySigned:

1. Import a PolicySigned with a public signing key (PEM)
2. Create a key to-be-authorized with the PolicySigned
    1. Fapi calculates policyAuth of key to-be-authorized using  **SHA1 name** of signing key
3. Set signing callback
4. Use key to-be-authorized
   1. Fapi loads public signing key via LoadExternal (nameAlg is **SHA256**)  
   2. Fapi Sign Callback is called, signature is returned and verified successfully
   3. TPM extends policyDigest using **SHA256 name** of signing key
   4. policyDigest != policyAuth, TPM policy check fails

#### Default nameAlgs when calculating policyDigest for PolicySigned:
https://github.com/tpm2-software/tpm2-tss/blob/2bae50a3551cd8b0123ef609ea973678339df5ae/src/tss2-fapi/fapi_crypto.c#L95-L99
https://github.com/tpm2-software/tpm2-tss/blob/2bae50a3551cd8b0123ef609ea973678339df5ae/src/tss2-fapi/fapi_crypto.c#L126-L130

#### Default nameAlg for keys as part of policies:
I'm not sure where to find the default value for the nameAlg but it seems to be SHA256.

**Comment by JuergenReppSIT** [comment]
The default SHA1 should be overwritten in policy instantiation before the computation of the name:
https://github.com/tpm2-software/tpm2-tss/blob/05beb087939024c2f1b640c58147a0c5e4e94fbf/src/tss2-fapi/ifapi_policy_instantiate.c#L149-L151
hash_alg is taken from `PolicySigned.keyPEMhashAlg` (Default SHA256)
Do you have an example where the name is computed with SHA1 instead of the value from the policy?

**Comment by joholl** [comment]
You're right, I did not see that. As it turns out, the problem seems to be fixed in master.

When working on the python bindings, I cannot really debug the TSS and need to have a look at the logs. That's why I was testing against a packaged version (3.0.3) instead of master, my bad!

Thanks, regardless!
