### ISSUE TITLE
Fapi_Quote does not clean up after policy check fail

### ISSUE THREAD

**Issue by joholl** [tpm2-software/tpm2-tss#2084]
If quote fails due to a policy check fail (`Fapi_Quote.c:391`), it does not flush the key. As a result, a transient handle remains loaded. If this is done multiple times, the TPM runs out of key slots.

https://github.com/tpm2-software/tpm2-tss/blob/05beb087939024c2f1b640c58147a0c5e4e94fbf/src/tss2-fapi/api/Fapi_Quote.c#L381-L397

**Comment by williamcroberts** [comment]
Ahh, I remember now. We have checks for version in test, should we skip this based on TSS version + TCTI (is TCTI still relevant)?

**Comment by williamcroberts** [comment]
> Ahh, I remember now. We have checks for version in test, should we skip this based on TSS version + TCTI (is TCTI still relevant)?

I guess TCTI is not relevant....
