### ISSUE TITLE
TPM2_RS_PW, should it be TPM2_RH_PW?

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tss#2095]
I was looking through the RH constants, and came accross:
```C
#define TPM2_RS_PW          ((TPM2_RH) 0x40000009) /* S */
```

It appears this way in the spec, should we change this and leave the old one in place for backwards compat?

**Comment by williamcroberts** [comment]
@AndreasFuchsSIT

**Comment by AndreasFuchsSIT** [comment]
I say change it. Was a bug...

**Comment by williamcroberts** [comment]
@AndreasFuchsSIT it's in the spec document too

**Comment by AndreasFuchsSIT** [comment]
If it's in the annex of the spec, then it's only informative...
Is it in the main part ?
Still, bug in the spec, change it there too.

**Comment by williamcroberts** [comment]
> If it's in the annex of the spec, then it's only informative...
> Is it in the main part ?
> Still, bug in the spec, change it there too.

It's in Table 28 of https://trustedcomputinggroup.org/wp-content/uploads/TCG_TSS_Overview_Common_Structures_v0.9_r03_published.pdf.

Thats normative text right?

**Comment by AndreasFuchsSIT** [comment]
@williamcroberts Are you aware of cases where this would break software ?
Should we maybe keep the old one as well ?

**Comment by williamcroberts** [comment]
These following things have references:
```
tpm2-abrmd - tests
tpm2-pk11 - defunct project
tpm2-pytss - I can change this, no 1.0 release yet.
tpm2-software.github.io: tpm2-tss-policy-editor.schema.json:3170:
tpm2-tools - comment
tpm2-tss -  tests, and it's self so easy to fix.
```

**Comment by williamcroberts** [comment]
Oh I need backwards compat on the python code or else I need yet another version check.... which is fine I can do that.

**Comment by AndreasFuchsSIT** [comment]
Ok, Sounds like we'll add the new define now and deprecate the other some years down the road...

**Comment by williamcroberts** [comment]
> Ok, Sounds like we'll add the new define now and deprecate the other some years down the road...

Actually I'm working around it now since I never released, but I can't say the same for other projects...

**Comment by AndreasFuchsSIT** [comment]
Funny ideas on macro deprectation:
https://stackoverflow.com/questions/57478368/what-is-the-best-way-to-mark-macro-as-deprecated
