### ISSUE TITLE
Can this TSS2 support Windows ARM64

### ISSUE THREAD

**Issue by frostzou** [tpm2-software/tpm2-tss#2100]
Hi.

I am working on a project using this repo, and we are going to use it in some Window ARM architecture.

Can this library support Windows ARM64?

Thanks!

**Comment by williamcroberts** [comment]
It should as it builds on ARM64 and Windows. However, I don't think our CI tests that exact combination.

**Comment by frostzou** [comment]
Hi, 

Thanks for your reply!

Um, but what 'exact combination' means here? It means tests for some FAPIs to check whether it can run in ARM64 perfectly? or check whether all related files and dependency can run as expected.

**Comment by williamcroberts** [comment]
> Hi,
> 
> Thanks for your reply!
> 
> Um, but what 'exact combination' means here? It means tests for some FAPIs to check whether it can run in ARM64 perfectly? or check whether all related files and dependency can run as expected.

We run our full test suite on ARM64 and Linux, and we run our windows specific test suite on Windows x86_64.

**Comment by williamcroberts** [comment]
> @williamcroberts : Can you please share vcxproj file used to build on AM64 and Windows?

Its in the root of the tpm2-tss project as tpm2-tss.sln

**Comment by achal1012** [comment]
Thanks @williamcroberts I checked that it and individual .vcxproj files but they don't have ARM64 configuration for example:

`  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|ARM64'" Label="Configuration">
    <ConfigurationType>DynamicLibrary</ConfigurationType>
    <UseDebugLibraries>true</UseDebugLibraries>
    <PlatformToolset>v142</PlatformToolset>
  </PropertyGroup>`

This will help me understand which ToolSet is used for WIndows-ARM64 configuration.

**Comment by achal1012** [comment]
Sorry I forgot to post a draft PR here: https://github.com/tpm2-software/tpm2-tss/pull/2182/commits/87dc0c734c61e248ef936f7e4e756dc9e648f8df# 
This worked for me :)
