### ISSUE TITLE
Error during Esys_Initialize using IBM TPM Simulator

### ISSUE THREAD

**Issue by joe-cryptosecurellc** [tpm2-software/tpm2-tss#2103]
Hi - I'm using tpm2-tss, version 3.1, and the TPM Simulator v1661.tar

Esys_Intialize call returns the following messages:

ERROR:tcti:src/tss2-tcti/tcti-device.c:443:Tss2_Tcti_Device_Init() Failed to open specified TCTI device file /dev/tpmrm0: No such file or directory 
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-device.so.0 
ERROR:tcti:src/tss2-tcti/tcti-device.c:443:Tss2_Tcti_Device_Init() Failed to open specified TCTI device file /dev/tpm0: Permission denied 
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-device.so.0 
ERROR:tcti:src/tss2-tcti/tcti-swtpm.c:222:tcti_control_command() Control command failed with error: 1 
ERROR:tcti:src/tss2-tcti/tcti-swtpm.c:330:tcti_swtpm_set_locality() Failed to set locality: 0xa000a 
WARNING:tcti:src/tss2-tcti/tcti-swtpm.c:600:Tss2_Tcti_Swtpm_Init() Could not set locality via control channel: 0xa000a 
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-swtpm.so.0

tpm2_server returns the following messages:

Command IPv4 client accepted
TPM command server listening on port 2321
Platform IPv4 client accepted
Unrecognized platform interface command 00000005
Platform server listening on port 2322
Command IPv4 client accepted
Platform IPv4 client accepted

Is this a configuration issue - BTW, I also have the tcti_mssim.so installed.

Thanks.

**Comment by joe-cryptosecurellc** [comment]
I also tried to link the tcti-mssim.so.0.0.0 to tcti-device.so and .so.0, and I get the following errors:

WARNING:tcti:src/util/key-value-parse.c:50:parse_key_value() key / value string is invalid 
WARNING:tcti:src/util/io.c:171:socket_close() Failed to close SOCKET 0. errno 9: Bad file descriptor 
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-device.so.0 
WARNING:tcti:src/util/key-value-parse.c:50:parse_key_value() key / value string is invalid 
WARNING:tcti:src/util/io.c:171:socket_close() Failed to close SOCKET 0. errno 9: Bad file descriptor 
WARNING:tcti:src/util/io.c:171:socket_close() Failed to close SOCKET 0. errno 9: Bad file descriptor 
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-device.so.0 
ERROR:tcti:src/tss2-tcti/tcti-swtpm.c:222:tcti_control_command() Control command failed with error: 1 
ERROR:tcti:src/tss2-tcti/tcti-swtpm.c:330:tcti_swtpm_set_locality() Failed to set locality: 0xa000a 
WARNING:tcti:src/tss2-tcti/tcti-swtpm.c:600:Tss2_Tcti_Swtpm_Init() Could not set locality via control channel: 0xa000a 
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-swtpm.so.0 


Is there another way to get the tcti ldr/etc. to choose the mssim, or is this a legitimate issue. Thanks for your help

**Comment by JuergenReppSIT** [comment]
For using the IBM TPM Simulator you need to send a Startup command to the TPM. You can use 
` Esys_Startup(ctx, TPM2_SU_CLEAR);`
or compile a small standalone Program to execute the startup. To avoid error messages you can create a link to:
 /usr/local/lib/libtss2-tcti-default.so
```
#include <stdio.h>
#include <tss2/tss2_mu.h>
#include <tss2/tss2_esys.h>

int main() {

    TSS2_RC r;

    /* Initialize the ESAPI context */
    ESYS_CONTEXT *ctx;
    r = Esys_Initialize(&ctx, NULL, NULL);
    
    if (r != TSS2_RC_SUCCESS){
        printf("\nError: Esys_Initialize\n");
        exit(1);
    }

    r = Esys_Startup(ctx, TPM2_SU_CLEAR);
    if (r != TSS2_RC_SUCCESS){
        printf("\nError: Esys_Startup\n");
        exit(1);
    }

    printf("\n");
    exit(0);
}
//   gcc tpm_startup.c -L=/usr/local/lib/ -ltss2-esys -o tpm_startup
```

**Comment by AndreasFuchsSIT** [comment]
Unfortunately, swtpm and tpm_server (IBM tpm simulator) both use the same port, but different protocols.
When you call Esys_Initialize without a TCTI, we attempt to autoconnect and thus we fail.

You need to call Tss2_TctiLdr_Initialize("mssim:host=127.0.0.1,port=2321", &tcti); Esys_Initialize(&ectx, tcti, NULL);
Then it should correctly connect to the tpm_server.

**Comment by joe-cryptosecurellc** [comment]
Implemented all your suggestions, invoked a 'get caps' and it works perfectly!

I appreciate the help!

**Comment by joe-cryptosecurellc** [comment]
Hi - I am reopening this issue because the code that you helped me with to iniitalize the tctildr is not working when it is in a shared library (.so) It works well when run from an executable.

When I execute the line: TSS2_RC rc = Tss2_TctiLdr_Initialize(tpmServer, &m_tContext):, with 
const char tpmServer[] = "mssim:host=127.0.0.1, port=2321";

static TSS2_TCTI_CONTEXT* m_tContext = NULL;

I get the following error:

WARNING:tcti:src/util/io.c:171:socket_close() Failed to close SOCKET 0. errno 9: Bad file descriptor 
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: mssim 
ERROR:tcti:src/tss2-tcti/tctildr.c:428:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI 

my shared library is in /usr/lib, as well as the tss libraries, and the error happens with or without tpm_server running.

Thanks for your help

**Comment by pevik** [comment]
> Implemented all your suggestions, invoked a 'get caps' and it works perfectly!

Would you please share which commits fixed it? 

Adding them as `Closes: ...` would help to link fixes automatically.

**Comment by moritzbuhl** [comment]
The issue is over 5 years old by now, please open a new one.
