### ISSUE TITLE
tcti-cmd fails with non-TPM error

### ISSUE THREAD

**Issue by elliotmtx** [tpm2-software/tpm2-tss#2122]
I am using tpm2-cmd option and trying to run something like this "tpm2_getrandom --tcti="cmd:ssh localhost tpm2_send" --hex 32", but I get below error, I do not understand why it is throwing error, tcti-cmd getting initialized but after that I see this issue

`$ tpm2_getrandom --tcti="cmd:ssh localhost tpm2_send" --hex 32 
sdp@localhost's password: ERROR:tcti:src/tss2-tcti/tcti-cmd.c:511:tcti_cmd_receive() Read was not size of header, got 0 expected 10 
ERROR:esys:src/tss2-esys/api/Esys_GetRandom.c:281:Esys_GetRandom_Finish() Received a non-TPM Error ERROR:esys:src/tss2-esys/api/Esys_GetRandom.c:95:Esys_GetRandom() Esys Finish ErrorCode (0x000a0011) 
ERROR: Esys_GetRandom(0xA0011) - tcti:Response is malformed ERROR: Unable to run tpm2_getrandom`

**Comment by williamcroberts** [comment]
What version of tpm2-tools?

**Comment by williamcroberts** [comment]
Oh I see the problem:
`sdp@localhost's password`

You need to enable passwordless login by setting up keys. Follow something like: https://linuxize.com/post/how-to-setup-passwordless-ssh-login/

**Comment by elliotmtx** [comment]
It's still same after making it passwordless login, also on a different machine able to run "tpm2_getrandom --tcti="cmd:ssh localhost tpm2_send" --hex 32" without even setting passwordless ssh login.

Versions: I cloned tpm2-tss, tpm2-tools and tpm2-abrmd yesterday itself from master and installed.

**Comment by elliotmtx** [comment]
Here are few logs for the above command:

> debug:tcti:src/tss2-tcti/tctildr.c:159:tctildr_conf_parse() name_conf: "cmd:ssh localhost tpm2_send" 
debug:tcti:src/tss2-tcti/tctildr.c:177:tctildr_conf_parse() TCTI name: "cmd" 
debug:tcti:src/tss2-tcti/tctildr.c:182:tctildr_conf_parse() TCTI conf: "ssh localhost tpm2_send" 
debug:tcti:src/tss2-tcti/tctildr-dl.c:299:tctildr_get_tcti() name: "cmd", conf: "ssh localhost tpm2_send" 
trace:tcti:src/tss2-tcti/tctildr-dl.c:136:tcti_from_file() Attempting to load TCTI file: cmd 
debug:tcti:src/tss2-tcti/tctildr-dl.c:92:handle_from_name() Could not load TCTI file: "cmd": cmd: cannot open shared object file: No such file or directory 
trace:tcti:src/tss2-tcti/tctildr.c:109:tcti_from_info() Attempting to load TCTI info 
trace:tcti:src/tss2-tcti/tctildr.c:116:tcti_from_info() Loaded TCTI info named: tcti-cmd 
trace:tcti:src/tss2-tcti/tctildr.c:117:tcti_from_info() TCTI description: TCTI module for using a process to send and receive data. 
trace:tcti:src/tss2-tcti/tctildr.c:118:tcti_from_info() TCTI config_help: string used as command, passed to execl("/bin/sh", "sh", "-c", command, (char *) 0);. 
trace:tcti:src/tss2-tcti/tctildr.c:61:tcti_from_init() Initializing TCTI for config: ssh localhost tpm2_send 
debug:tcti:src/tss2-tcti/tcti-cmd.c:604:Tss2_Tcti_Cmd_Init() Initializing command TCTI with command: ssh localhost tpm2_send 
debug:tcti:src/tss2-tcti/tctildr.c:98:tcti_from_init() Initialized TCTI for config: ssh localhost tpm2_send 
info:tcti:src/tss2-tcti/tctildr.c:125:tcti_from_info() Initialized TCTI named: tcti-cmd 
debug:tcti:src/tss2-tcti/tctildr-dl.c:162:tcti_from_file() Initialized TCTI file: cmd 
debug:tcti:src/tss2-tcti/tcti-cmd.c:302:popen_w_pipes() Forked child pid: 154679 
trace:esys:src/tss2-esys/api/Esys_GetCapability.c:158:Esys_GetCapability_Async() context=0x5608259130e0, capability=6, property=100,propertyCount=7f 
trace:marshal:src/tss2-mu/base-types.c:179:Tss2_MU_TPM2_ST_Marshal() offset non-NULL, initial value: 0 
debug:marshal:src/tss2-mu/base-types.c:179:Tss2_MU_TPM2_ST_Marshal() Marshalling TPM2_ST from 0x7ffe8da0c4cc to buffer 0x560825914660 at index 0x0 
debug:marshal:src/tss2-mu/base-types.c:179:Tss2_MU_TPM2_ST_Marshal() offset parameter non-NULL, updated to 2 
trace:marshal:src/tss2-mu/base-types.c:173:Tss2_MU_UINT32_Marshal() offset non-NULL, initial value: 10 

..............................

> debug:marshal:src/tss2-mu/tpms-types.c:976:Tss2_MU_TPMS_TAGGED_PROPERTY_Unmarshal() Unmarshaling TPMS_TAGGED_PROPERTY from 0x560825931620 to buffer 0x560825914660 at index 0x17b 
trace:marshal:src/tss2-mu/base-types.c:174:Tss2_MU_UINT32_Unmarshal() offset non-NULL, initial value: 379 
debug:marshal:src/tss2-mu/base-types.c:174:Tss2_MU_UINT32_Unmarshal() Unmarshaling UINT32 from 0x560825914660 to buffer 0x560825931620 at index 0x17b 
debug:marshal:src/tss2-mu/base-types.c:174:Tss2_MU_UINT32_Unmarshal() offset parameter non-NULL, updated to 383 
trace:marshal:src/tss2-mu/base-types.c:174:Tss2_MU_UINT32_Unmarshal() offset non-NULL, initial value: 383 
debug:marshal:src/tss2-mu/base-types.c:174:Tss2_MU_UINT32_Unmarshal() Unmarshaling UINT32 from 0x560825914660 to buffer 0x560825931624 at index 0x17f 
debug:marshal:src/tss2-mu/base-types.c:174:Tss2_MU_UINT32_Unmarshal() offset parameter non-NULL, updated to 387 
debug:marshal:src/tss2-mu/tpml-types.c:171:Tss2_MU_TPML_TAGGED_TPM_PROPERTY_Unmarshal() offset parameter non-NULL, updated to 387 
trace:esys:src/tss2-esys/api/Esys_GetRandom.c:137:Esys_GetRandom_Async() context=0x5608259130e0, bytesRequested=0020 
trace:marshal:src/tss2-mu/base-types.c:179:Tss2_MU_TPM2_ST_Marshal() offset non-NULL, initial value: 0 
debug:marshal:src/tss2-mu/base-types.c:179:Tss2_MU_TPM2_ST_Marshal() Marshalling TPM2_ST from 0x7ffe8da0c5cc to buffer 0x560825914660 at index 0x0 
debug:marshal:src/tss2-mu/base-types.c:179:Tss2_MU_TPM2_ST_Marshal() offset parameter non-NULL, updated to 2 
trace:marshal:src/tss2-mu/base-types.c:171:Tss2_MU_UINT16_Marshal() offset non-NULL, initial value: 10 
debug:marshal:src/tss2-mu/base-types.c:171:Tss2_MU_UINT16_Marshal() Marshalling UINT16 from 0x7ffe8da0c62c to buffer 0x560825914660 at index 0xa 
debug:marshal:src/tss2-mu/base-types.c:171:Tss2_MU_UINT16_Marshal() offset parameter non-NULL, updated to 12 
trace:esys:src/tss2-esys/api/Esys_GetRandom.c:222:Esys_GetRandom_Finish() context=0x5608259130e0, randomBytes=0x7ffe8da0c8e0 
ERROR:tcti:src/tss2-tcti/tcti-cmd.c:511:tcti_cmd_receive() Read was not size of header, got 0 expected 10 
ERROR:esys:src/tss2-esys/api/Esys_GetRandom.c:281:Esys_GetRandom_Finish() Received a non-TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_GetRandom.c:95:Esys_GetRandom() Esys Finish ErrorCode (0x000a0011) 
ERROR: Esys_GetRandom(0xA0011) - tcti:Response is malformed
ERROR: Unable to run tpm2_getrandom
trace:tcti:src/tss2-tcti/tcti-cmd.c:174:reap_child() Reaped: 154679

**Comment by williamcroberts** [comment]
It seems your not getting a valid response, perhaps some misconfiguration, does this work:
```bash
tpm2 getrandom --tcti=cmd:tpm2_send --hex 4
```

**Comment by elliotmtx** [comment]
> It seems your not getting a valid response, perhaps some misconfiguration, does this work:
> 
> ```shell
> tpm2 getrandom --tcti=cmd:tpm2_send --hex 4
> ```

Nope, same error.

**Comment by williamcroberts** [comment]
> > It seems your not getting a valid response, perhaps some misconfiguration, does this work:
> > ```shell
> > tpm2 getrandom --tcti=cmd:tpm2_send --hex 4
> > ```
> 
> Nope, same error.

I'm assuming that `tpm2_getrandom --hex 4` works, Is that correct?
