### ISSUE TITLE
Missing dependency: json-c-devel

### ISSUE THREAD

**Issue by MikeSpreitzer** [tpm2-software/tpm2-tss#2126]
I tried building in Fedora 34.  The `configure` step complained about no `json-c` package.  The list at https://github.com/tpm2-software/tpm2-tss/blob/master/INSTALL.md#gnulinux does not mention that one.  In Fedora 34, the package `json-c-devel` makes `configure` happy (and the package `json-c` _does not_).

**Comment by williamcroberts** [comment]
> I tried building in Fedora 34. The `configure` step complained about no `json-c` package. The list at https://github.com/tpm2-software/tpm2-tss/blob/master/INSTALL.md#gnulinux does not mention that one. In Fedora 34, the package `json-c-devel` makes `configure` happy (and the package `json-c` _does not_).

Thats autoconf for you. if your building you need to satisfy what most distros package as devel versions. Every flavor of distro calls them something slightly different, ie fedora does -devel suffix but Debian does just -dev. Some prefix with lib, some dont. But if you build and install from source, you'll get the devel versions.

**Comment by MikeSpreitzer** [comment]
My point here was not so much the `-devel` or not, but the complete absence of `json-c` in the dependencies list at https://github.com/tpm2-software/tpm2-tss/blob/master/INSTALL.md#gnulinux

**Comment by williamcroberts** [comment]
Ahh interesting its in the Ubuntu command and not in the raw list
