### ISSUE TITLE
Latest release is still marked as the old one

### ISSUE THREAD

**Issue by utkarsh2102** [tpm2-software/tpm2-tss#2136]
Hi @williamcroberts,

It looks like the latest release, 3.1.0, is not the official latest release in the releases page but an older one, 2.4.6. This is weird and I am not sure what's up. If you go to https://github.com/tpm2-software/tpm2-tss/releases/latest, you'll see what I am talking about.

Also, this:
![image](https://user-images.githubusercontent.com/31288318/126650438-498d2a79-de6f-4fc6-a1f0-e6ca54d631e2.png)

I am not sure if this was an overlook or what but this breaks a lot of automated script to find a newer version using the GitHub API. Here's how we use it:
```
$ curl -s https://api.github.com/repos/{$BRANCH}/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")'
2.4.6
```

Here, $BRANCH is obviously `tpm2-software/tpm2-tss`. Can you take a look and maybe fix this? Thank you!

**Comment by williamcroberts** [comment]
Same comments that apply to https://github.com/tpm2-software/tpm2-tools/issues/2798

latest means latest date tag, not the release number.
