### ISSUE TITLE
Maybe a bug. can't find the key. create key in user dir, but when want to sign, it only find key  in system dir

### ISSUE THREAD

**Issue by lsxkugoug** [tpm2-software/tpm2-tss#2138]
There is a bug. 
This is the FAPI configure file:
 {
     "profile_name": "P_RSA2048SHA256",
     "profile_dir": "/opt/tpm_dev/etc/tpm2-tss/fapi-profiles/",
     "user_dir": "~/.local/share/tpm2-tss/user/keystore",
     "system_dir": "/opt/tpm_dev/var/lib/tpm2-tss/system/keystore",
     "tcti": "",
     "system_pcrs" : [],
     "log_dir" : "/opt/tpm_dev/var/run/tpm2-tss/eventlog/",
      "ek_cert_less": "yes"
}
I create a key, it is in user_dir.
But when I try to use the key, 
```
ERROR:fapi:src/tss2-fapi/ifapi_keystore.c:512:rel_path_to_abs_path() ErrorCode (0x00060020) Key P_RSA2048SHA256/HS/SRK/aster3SignKey not found.
ERROR:fapi:src/tss2-fapi/ifapi_keystore.c:553:ifapi_keystore_load_async() ErrorCode (0x00060020) Object P_RSA2048SHA256/HS/SRK/aster3SignKey not found.
ERROR:fapi:src/tss2-fapi/fapi_util.c:1655:ifapi_load_key_finish() ErrorCode (0x00060020) Could not open: P_RSA2048SHA256/HS/SRK/aster3SignKey
ERROR:fapi:src/tss2-fapi/fapi_util.c:1555:ifapi_load_keys_finish() Load keys ErrorCode (0x00060020)
ERROR:fapi:src/tss2-fapi/fapi_util.c:2541:ifapi_load_key() ErrorCode (0x00060020)  Load key.
ERROR:fapi:src/tss2-fapi/api/Fapi_Sign.c:282:Fapi_Sign_Finish() Fapi load key. ErrorCode (0x00060020)
ERROR:fapi:src/tss2-fapi/api/Fapi_Sign.c:127:Fapi_Sign() ErrorCode (0x00060020) Key_Sign
Fapi_Sign(0x60020) - fapi:The key was not found
```
I debug it, and find that it only finds the key in system_dir.

**Comment by AndreasFuchsSIT** [comment]
Could you run this again with `export TSS2_LOG=fapi+debug` ?
Note: This will contain some information about your platform, such as home paths.

**Comment by lsxkugoug** [comment]
It is strange, now there is no questopm. I don't know why.

**Comment by AndreasFuchsSIT** [comment]
fixed I assume ?
