### ISSUE TITLE
Tpm-tss ESAPI demos for Windows 10

### ISSUE THREAD

**Issue by Mohan787** [tpm2-software/tpm2-tss#2146]
Hi team,

We have validated using ESAPI(using TPM2_tool) in ubuntu with nvread/sign/decrypt/persistent data features. It is based below tools,
https://github.com/tpm2-software/tpm2-tss
https://github.com/tpm2-software/tpm2-abrmd
https://github.com/tpm2-software/tpm2-tools

We are checking the equalent ESAPI based applications to access the TPM2 in windows. We have compiled the tpm2-tss with VS2019. But only tpm2-tss has support for windows but other tools are not availble for windows. Could you please suggest us the windows demos to access the ESAPIs with use the above features.

We want to implement the TPM features(nvread/sign/decrypt/persistent data) for both windows and linux using ESAPI and would like to estimate the risk to use this. Please provide your suggestions if any.

Note: TSS-MSR applications are not based on ESAPI format.
https://github.com/Microsoft/TSS.MSR

Thanks,
Mohanraj K.

**Comment by danielwangksu** [comment]
Hi @AndreasFuchsSIT I'm looking for solution to use EAPI on Windows 10, and found your comments here. Could you give me some help about the Windows EAPI interface? Such as which library should I link with my code. Thank you very much for your help!

**Comment by Huihh** [comment]
Hi, @AndreasFuchsSIT, I build tpm2-tss on window10, but I want to use *.dlls to access to TPM, what should I do, please give me some advice, thank you
