### ISSUE TITLE
undefined reference to `Tss2_TctiLdr_Initialize'

### ISSUE THREAD

**Issue by hhashim2** [tpm2-software/tpm2-tss#2153]
Any use of the command transmission interface, even to run example code provided at the following link "https://www.mankier.com/3/Tss2_TctiLdr_Initialize" fails with the error in the heading.

This was an issue with the ESAPI as well and I fixed it with modifying my makefile by adding a flag with the following: `TPMFLAGS =-L=/usr/local/lib/ -ltss2-esys `

Any advice would be great!

**Comment by williamcroberts** [comment]
Well when you use a library you need to link the library (-l,-L options) as well as have the header files on the search path (-I). 

You can get the values for most systems using pkg-config:
```bash
pkg-config --libs tss2-tctildr 
-L/usr/local/lib -ltss2-tctildr
```

**Comment by hhashim2** [comment]
Yes. Realized this a bit too late! Problem is fixed. Thank you for your reply! I do have another issue currently with Esys_NV_DefineSpace_Finish(). Would love some help with that!

**Comment by williamcroberts** [comment]
> Yes. Realized this a bit too late! Problem is fixed. Thank you for your reply! I do have another issue currently with Esys_NV_DefineSpace_Finish(). Would love some help with that!

Whats the problem?

**Comment by hhashim2** [comment]
Esys_NV_DefineSpace() return a warning for TPM Error and an error with errorcode 0x000014c. The following is the output from the terminal:
`WARNING:esys:src/tss2-esys/api/Esys_NV_DefineSpace.c:344:Esys_NV_DefineSpace_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_NV_DefineSpace.c:122:Esys_NV_DefineSpace() Esys Finish ErrorCode (0x0000014c) `

**Comment by williamcroberts** [comment]
> 0x0000014c

It's already defined....

```bash
tpm2_rcdecode 0x0000014c
tpm:error(2.0): NV Index or persistent object already defined
```

**Comment by hhashim2** [comment]
Yes! I am a little confused on what's happening in the background since I am trying to re-implement this. With the actual tpm2-totp, this would be solved with a "tpm2-totp clean" which calls tpm2totp_deleteKey_nv. 

In my own code, I generate a key and then try and store that key using the same structure as in tpm2-totp but I keep ending up with 0x0000014c. Tried clearing the NV as well, but on Esys_NV_UndefineSpace, the errorcode 0x00000284 pops up.

**Comment by williamcroberts** [comment]
```bash
tpm2 rc_decode 0x00000284
tpm:handle(2):value is out of range or is not correct for the context
```

If you look at the spec (and understand the markup of the command table):
https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p59_Part3_Commands_pub.pdf

Parameter 2 is the NV Index, in the ESYS API this is an ESYS_TR so you need to convert the NV Index TPM2_HANDLE to the ESYS_TR, which can be dont with:
```C
TSS2_RC
Esys_TR_FromTPMPublic(
    ESYS_CONTEXT *esysContext,
    TPM2_HANDLE tpm_handle,
    ESYS_TR optionalSession1,
    ESYS_TR optionalSession2,
    ESYS_TR optionalSession3,
    ESYS_TR *object);
```

**Comment by hhashim2** [comment]
This is my instantiation of the TPMS_NV_PUBLIC
`	TPM2B_NV_PUBLIC publicInfo = { .size = 0,
        .nvPublic = {
            .nvIndex = TPM2_NV_INDEX_FIRST,
            .nameAlg = TPM2_ALG_SHA256,
            .attributes = (TPMA_NV_OWNERWRITE |
                           TPMA_NV_AUTHWRITE |
                           TPMA_NV_WRITE_STCLEAR |
                           TPMA_NV_READ_STCLEAR |
                           TPMA_NV_AUTHREAD |
                           TPMA_NV_OWNERREAD ),
            .authPolicy = { .size = 0, .buffer = {}, },
            .dataSize = keyBlob_size,
        } };`

This is the call to Esys_NV_Define_Space in my store key function:
already called Esys_Startup and Esys_Initialize before this
`rc = Esys_NV_DefineSpace(esysCon, ESYS_TR_RH_OWNER, ESYS_TR_PASSWORD, ESYS_TR_NONE,
	 					ESYS_TR_NONE, &emptyAuth, &publicInfo, &nvHandle);
	
	if(rc == TPM2_RC_NV_DEFINED){
		printf("nv definespace error\n");
		Esys_Finalize(&esysCon);
		return rc;
	}`

This is the invocation to the function storeKey:
`printf("%d\n", storeKey_NV(keyBlob, keyBlob_size, tcti_context));`

Still getting the 0x0000014c.

**Comment by williamcroberts** [comment]
Did you actually undefine it, what does something like:
```bash
tpm2_getcap handles-nv-index
```
return?

**Comment by williamcroberts** [comment]
I mean if you don't undefine the space, you'll keep getting the error.

**Comment by hhashim2** [comment]
Rightio! Figured out most of it. Thank you so much for your help and patience William!
