### ISSUE TITLE
How to get the aes_key generated by ESYS_CREATE( ) to encrypt/decrypt data.

### ISSUE THREAD

**Issue by ilariaguarini** [tpm2-software/tpm2-tss#2162]
Hello,
in my C program, I created an AES key to encrypt and decrypt data according to the example reported to this link:
https://github.com/tpm2-software/tpm2-tss/blob/master/test/integration/esys-encrypt-decrypt.int.c 

My question is the following:

How can I decipher the encrypted data after switching off/on the TPM device?
I have seen the Esys_Load() function, but it requires some structures (TPM2B_PUBLIC outPublic, TPM2B_PRIVATE outPrivate) that I lose when I restart my C program.

Hope for help.

**Comment by JuergenReppSIT** [comment]
The TPM2B blobs must be saved in the file system.
