### ISSUE TITLE
Fapi_Encrypt and Fapi_Decrypt time using RSA

### ISSUE THREAD

**Issue by dwaraka1982** [tpm2-software/tpm2-tss#2168]
We are doing some performance measurements using above API's with the tpm2 stack ported on a embedded device.

Algo - TPM2_ALG_SHA256
"keyBits": 2048

We are feeding the data as chunks in 128 Bytes block to the Encrypt function. 
For 1024 Bytes total data the algorithm takes around 1.1 sec for encryption and for 1MB it is taking around 20 Min. We understand that RSA is kind of time consuming one but wanted to know if the above time is expected ?

To improve performance can  we tune any parameters in the P_RSA.json file ?

**Comment by AndreasFuchsSIT** [comment]
You should go ahead and encrypt the data with an AES key externally and only send that key (i.e. 128 bits) to FAPI.
