### ISSUE TITLE
Multiple License Identifiers

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tss#2173]
```bash
git grep -r SPDX | cut -dS -f2- | cut -d: -f2- | sed 's/ //g' | sed s/'\*\/'//g | sort | uniq
BSD-2
BSD-2-Clause
BSD-3-Clause
PDXLicenseIdentifiers
/*SPDX-License-Identifier:BSD-2-Clause
```
We can ignore the bottom two, just some cruft from an imperfect command, but the:
1. The `BSD-2` should be `BSD-2-Clause`.
2. The ci scripts are BSD-3, so not two worried about that since they are not distributed and come from a BSD3 source (copy and paste).
3. I think this file should be BSD-2: src/tss2-fapi/ifapi_get_intl_cert.c:1:/* SPDX-License-Identifier: BSD-3-Clause */ 
  ```
   git shortlog -n -s src/tss2-fapi/ifapi_get_intl_cert.c
       9  Juergen Repp
       3  Andreas Fuchs
       2  Petr Gotthard
       2  Tadeusz Struk
  ```

I think we just need an Intel representative, a Fraunhofer representative and Petr to Ack on that change.
For Intel, I'll Ack this change.

**Comment by AndreasFuchsSIT** [comment]
Ack as well
