### ISSUE TITLE
FAPI does not compute authPolicy for primary keys

### ISSUE THREAD

**Issue by gaetanww** [tpm2-software/tpm2-tss#2175]
`ifapi_create_primary` [link](https://github.com/tpm2-software/tpm2-tss/blob/master/src/tss2-fapi/fapi_util.c#L4518) does not compute the policy hash.

Expected code similar to `ifapi_create` [link](
https://github.com/tpm2-software/tpm2-tss/blob/master/src/tss2-fapi/fapi_util.c#L3301)

This makes it impossible to create primary keys with non empty policy buffer using FAPI.

**Comment by JuergenReppSIT** [comment]
Because no access to the file system is needed the policy hash is already computed in the async part:
https://github.com/tpm2-software/tpm2-tss/blob/5902fbabe9dc5f24473756baec08377ebe52e765/src/tss2-fapi/fapi_util.c#L587

**Comment by JuergenReppSIT** [comment]
Oh yes, you're right. I will create a PR
