### ISSUE TITLE
stable release to support openssl 3

### ISSUE THREAD

**Issue by nullr0ute** [tpm2-software/tpm2-tss#2188]
tpm2_createprimary fails with the latest tagged release when built against openssl 3. It looks like there have been fixes land upstream post that so it would be useful to have stable release that supports openssl 3.

**Comment by AndreasFuchsSIT** [comment]
Will be fixed with 3.2 next week

**Comment by nullr0ute** [comment]
> Will be fixed with 3.2 next week

@AndreasFuchsSIT what's the status of this, over 3 weeks later and there's still no release?

**Comment by AndreasFuchsSIT** [comment]
Yes, there were some more nasty and weird bugs fixed in the PRs.
Hold on a few more day...
