### ISSUE TITLE
[Specification question]: Potential wrong type of field in TPMS_COMMAND_AUDIT_INFO?

### ISSUE THREAD

**Issue by Superhepper** [tpm2-software/tpm2-tss#2191]
First of all I apologize for asking a question here that is not related to the code but rather the specification, but I had trouble finding any other place to ask such question.

When I look at the specification:
*Trusted Platform Module Library, Part 2: Structures, Family “2.0”, Level 00 Revision 01.59, November 8, 2019, Section, 10.12.5 TPMS_COMMAND_AUDIT_INFO"

it says the ```digestAlg``` field is defined as this:
>| digestAlg | TPM_ALG_ID |  hash algorithm used for the command audit |

My question is why is the type of the ```digestAlg``` not of type ```TPMI_ALG_HASH``` when it is clear that is supposed to be a hash algorithm? The use of ```TPM_ALG_ID``` does not make it clear that is supposed to be hash algorithm.

**Comment by williamcroberts** [comment]
Probably just an oversight, it probably should be a TPMI_ALG_HASH, but they're both UINT16 so it shouldn't matter. We could probably ask the TPM WG and they can change it.

**Comment by Superhepper** [comment]
Nice, that would be great.

I needed to be sure before committing code to a tss-esapi Rust wrapper.

**Comment by williamcroberts** [comment]
I would just match the structure for now.

**Comment by williamcroberts** [comment]
From the TPM experts themselves:
```
A TPMI is an interface type and only has meaning for input to the TPM. A
TPMS_COMMAND_AUDIT_INFO is out only so it can't contain a TPMI.
```

**Comment by Superhepper** [comment]
Ok, but then why does the ```TPMS_SESSION_AUDIT_INFO<out>``` has a field ```exclusiveSession``` that is of type ```TPMI_YES_NO```?
