### ISSUE TITLE
stack usage is too large when tcti initialize

### ISSUE THREAD

**Issue by JerryDevis** [tpm2-software/tpm2-tss#2201]
Hi, teamer. When Tss2_TctiLdr_Initialize is executed, the tcti_from_file interface is called. In tcti_from_file, `PATH_MAX`(4KB) of stack space is malloced. Is there some problems for some resource-constrained embedded devices?

**Comment by williamcroberts** [comment]
> Hi, teamer. When Tss2_TctiLdr_Initialize is executed, the tcti_from_file interface is called. In tcti_from_file, `PATH_MAX`(4KB) of stack space is malloced. Is there some problems for some resource-constrained embedded devices?

Iv'e never heard of an issue on a Linux embedded device, no idea for Windows. But i'd take patches to make the memory consumption less greedy on the stack.

**Comment by JerryDevis** [comment]
> > Hi, teamer. When Tss2_TctiLdr_Initialize is executed, the tcti_from_file interface is called. In tcti_from_file, `PATH_MAX`(4KB) of stack space is malloced. Is there some problems for some resource-constrained embedded devices?
> 
> Iv'e never heard of an issue on a Linux embedded device, no idea for Windows. But i'd take patches to make the memory consumption less greedy on the stack.

Hi, @williamcroberts, the heap in the embedded device will usually be more than the stack, maybe it is better to use the heap memory. What do you think?

**Comment by williamcroberts** [comment]
> > > Hi, teamer. When Tss2_TctiLdr_Initialize is executed, the tcti_from_file interface is called. In tcti_from_file, `PATH_MAX`(4KB) of stack space is malloced. Is there some problems for some resource-constrained embedded devices?
> > 
> > 
> > Iv'e never heard of an issue on a Linux embedded device, no idea for Windows. But i'd take patches to make the memory consumption less greedy on the stack.
> 
> Hi, @williamcroberts, the heap in the embedded device will usually be more than the stack, maybe it is better to use the heap memory. What do you think?

In Linux it doesn't matter IIRC. The stack for userspace processes is dynamically updated on a fault to grow. So you end up with essentially the same thing. But i'd take patches to use the heap and also make it less greedy than just a 4k buffer as well. Compute the size needed and only allocate that.

**Comment by JerryDevis** [comment]
> > > > Hi, teamer. When Tss2_TctiLdr_Initialize is executed, the tcti_from_file interface is called. In tcti_from_file, `PATH_MAX`(4KB) of stack space is malloced. Is there some problems for some resource-constrained embedded devices?
> > > 
> > > 
> > > Iv'e never heard of an issue on a Linux embedded device, no idea for Windows. But i'd take patches to make the memory consumption less greedy on the stack.
> > 
> > 
> > Hi, @williamcroberts, the heap in the embedded device will usually be more than the stack, maybe it is better to use the heap memory. What do you think?
> 
> In Linux it doesn't matter IIRC. The stack for userspace processes is dynamically updated on a fault to grow. So you end up with essentially the same thing. But i'd take patches to use the heap and also make it less greedy than just a 4k buffer as well. Compute the size needed and only allocate that.
Hi @williamcroberts. I have used heap instead of stack and allocate it as needed. For details, see these two PRs([#2319 ](https://github.com/tpm2-software/tpm2-tss/pull/2319)and [#2321](https://github.com/tpm2-software/tpm2-tss/pull/2321)). Please help me review these two PRs. Thanks very much.

**Comment by AndreasFuchsTPM** [comment]
Solved since #2319 and #2321 are merged now
