### ISSUE TITLE
CI: Add tests using OpenSSL 3.0

### ISSUE THREAD

**Issue by JuergenReppSIT** [tpm2-software/tpm2-tss#2202]
The current version of TSS does support OSSL 3.0 which is now released. A new TSS release should also be tested with OSSL 3.0.
Also CURL uses OSSL. So the current version of  CURL should be compiled with OSSL 3.0 in the CI.

**Comment by williamcroberts** [comment]
It would be nice if we could build a container ready to go for this, or if something came with openssl 3.0 already. Someone mentioned openembedded to me, and I went and looked at that. OpenEmbedded seems to just be a build system for making linux distro's. It would be nice to be able to start with a base docker image off of dockerhub or wherever, that has OSSL3.0 as the default dependency.

**Comment by JuergenReppSIT** [comment]
We already run the tests with openssl 3.0 in a container based on ghcr.io/tpm2-software/ubuntu-20.04.
We did remove openssl and curl and installed openssl and curl from github.

**Comment by williamcroberts** [comment]
> We already run the tests with openssl 3.0 in a container based on ghcr.io/tpm2-software/ubuntu-20.04. We did remove openssl and curl and installed openssl and curl from github.

When we get into the other projects the dependency chains turn into hell. So it would be nice to solve this generically for all projects.

**Comment by JuergenReppSIT** [comment]
@williamcroberts Do you refer to the usage of the ubuntu image or the installing of openssl and curl from github with your comment?

Would you expect something like:
```
FILE: ubuntu-20.04-ossl3.docker.m4
....
include('apt_remove_ossl.m4')
include('add_ossl3.m4')

FILE: add_ossl3.m4

## OpenSSL 3
ENV OSSL_VERSION=3.0.0
RUN wget --no-verbose https://www.openssl.org/source/openssl-$OSSL_VERSION.tar.gz
RUN tar -zxf openssl-$OSSL_VERSION.tar.gz --one-top-level=/tmp/
WORKDIR /tmp/openssl-$OSSL_VERSION
RUN ./config \
	&& make -j \
	&& make install \
	&& ldconfig
# RUN rm -rfv /tmp/openssl-$OSSL_VERSION

ENV LD_LIBRARY_PATH=/usr/local/lib64
ENV PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig
RUN printenv > /env.txt

## CURL
ENV CURL_VERSION=7.80.0
RUN wget --no-verbose https://curl.se/download/curl-$CURL_VERSION.tar.gz
RUN tar -zxf curl-$CURL_VERSION.tar.gz --one-top-level=/tmp/
WORKDIR /tmp/curl-$CURL_VERSION
RUN autoreconf -fi \
	&& ./configure --with-openssl
 	&& make -j \
	&& make install \
	&& ldconfig
# RUN rm -rfv /tmp/$CURL_VERSION

FILE: apt_remove_ossl.m4

RUN apt-get remove -y libssl-dev libcurl4-openssl-dev
```

**Comment by williamcroberts** [comment]
Right now, the example you provide is the only way. Which means that if another project uses a dependency based on OSSL, we can't fetch it from the package manager as it's linked against the old version of OSSL. It can then turn into a dependency nightmare. I'd be much more palatable to find a distro we can base an image off of that already has OSSL3 in the package manager and the dependencies built out.

**Comment by AndreasFuchsSIT** [comment]
Only one I found is Alpine Linux 3.15
Sounds like a candidate

**Comment by williamcroberts** [comment]
That sucks. Even edge is 1.1.1l.

**Comment by williamcroberts** [comment]
Oh wait, you have install openssl3:
```bash
apk add openssl3
apk add openssl3
```

I wonder how they are handling openssh, or if thats dependent on version 1.X as well....

**Comment by williamcroberts** [comment]
Seems also candidates are:
- Debian Experimental
- EPEL8

**Comment by williamcroberts** [comment]
They don't in alpine, looks like theyre doing a side by side install now:
```bash
/ # ldd `which ssh`
	/lib/ld-musl-x86_64.so.1 (0x7ff897fca000)
	libcrypto.so.1.1 => /lib/libcrypto.so.1.1 (0x7ff897c8b000)
	libz.so.1 => /lib/libz.so.1 (0x7ff897c71000)
	libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7ff897fca000)
```

**Comment by AndreasFuchsSIT** [comment]
ok, so we'll add openssl3-dev apk to the docker I guess...

**Comment by AndreasFuchsSIT** [comment]
I'll defer this to 3.3 to get 3.2 out this week.
