### ISSUE TITLE
[Specification Question]: When is the TPMS_ALGORITHM_DESCRIPTION type ever used?

### ISSUE THREAD

**Issue by Superhepper** [tpm2-software/tpm2-tss#2228]
When I look into one of the return types of the TPM2_GetCapability command I came across something strange.

https://github.com/tpm2-software/tpm2-tss/blob/95b8a529af6671f464b67116766435960dfe7f03/include/tss2/tss2_tpm2_types.h#L1206

contains the union

https://github.com/tpm2-software/tpm2-tss/blob/95b8a529af6671f464b67116766435960dfe7f03/include/tss2/tss2_tpm2_types.h#L1190

The algorithm field in that union has the type
https://github.com/tpm2-software/tpm2-tss/blob/95b8a529af6671f464b67116766435960dfe7f03/include/tss2/tss2_tpm2_types.h#L1140

which is a list of
https://github.com/tpm2-software/tpm2-tss/blob/95b8a529af6671f464b67116766435960dfe7f03/include/tss2/tss2_tpm2_types.h#L1054

So far nothing strange.

Then in the specification
*Trusted Platform Module Library, Part 2: Structures, Family “2.0”, Level 00 Revision 01.59, November 8, 2019*
There is also the TPMS_ALGORITHM_DESCRIPTION  type of which the specification says the following:
>This structure is a return value for a TPM2_GetCapability() that reads the installed algorithms.

But it does not exist in any of structures that are returned in from the TPMS_CAPABILITY_DATA so when and how is this structure returned?

**Comment by williamcroberts** [comment]
what's interesting is that `TPMS_ALGORITHM_DESCRIPTION` matches the in use structure:
```
typedef struct TPMS_ALG_PROPERTY TPMS_ALG_PROPERTY;
struct TPMS_ALG_PROPERTY {
    TPM2_ALG_ID alg;               /* an algorithm identifier */
    TPMA_ALGORITHM algProperties;  /* the attributes of the algorithm */
};
```

and `TPMS_ALGORITHM_DESCRIPTION` is not referenced in the "commands" part of the spec that has a table for valid returns which shows only `TPML_ALG_PROPERTY` which contains a list of `TPMS_ALG_PROPERTY`.

I wonder if this is a typo in the spec. I don't see it in use in the simulator as well.

**Comment by Superhepper** [comment]
Yeah, I think some one has moved the type from one place to another in the specification and forgot to remove the original.

**Comment by williamcroberts** [comment]
This is dead, along with the MU bindings. In theory no one is using it, but we will mark them deprecated.

@AndreasFuchsSIT any input here?

**Comment by AndreasFuchsSIT** [comment]
Yep

**Comment by Superhepper** [comment]
Thank you for the answer then I do not have to bother with that type.

**Comment by williamcroberts** [comment]
Leave this open, im going to add a deprecated line to it.
