### ISSUE TITLE
the type of the value is not appropriate for the use

### ISSUE THREAD

**Issue by haersfather** [tpm2-software/tpm2-tss#2229]
after I installed tpm2-tss, tpm2-abrmd, tpm2-tools and so on. I typed "tss2_provision". And this happend. 
tss2_provision
Fapi_Provision(0x2CA) - tpm:parameter(2):the type of the value is not appropriate for the use

**Comment by AndreasFuchsSIT** [comment]
Could you give a little more information about your setup ?
Versions and what state the TPM was in before ?
And also the complete log output ?
