### ISSUE TITLE
Problem tss2_delete and tss2_createseal

### ISSUE THREAD

**Issue by redradit** [tpm2-software/tpm2-tss#2231]
pi@raspberrypi:~/tssSetup $ tss2_delete --path /HS

Fapi_Delete(0x6001D) - fapi:The provided path is bad

pi@raspberrypi:~/tssSetup $ tss2_list

/P_ECCP256SHA256/HN:/P_ECCP256SHA256/HE/EK:/P_ECCP256SHA256/HE:/P_ECCP256SHA256/LOCKOUT:/P_ECCP256SHA256/HS:/P_ECCP256SHA256/HS/SRK:/P_ECCP256SHA256/HS/SRK/mySealKey

How i can resolve?

**Comment by JuergenReppSIT** [comment]
The SRK key under /HS is used by FAPI to encrypt the session salt. /HS can only be deleted if all other hierarchies are deleted.
