### ISSUE TITLE
[Specification Question]: Are the different PCR select the same?

### ISSUE THREAD

**Issue by Superhepper** [tpm2-software/tpm2-tss#2237]
In the specification there are (from what I can tell) three different types of PCR select. 
1. ```TPMS_PCR_SELECT```
2. ```TPMS_PCR_SELECTION```
3. ```TPMS_TAGGED_PCR_SELECT```

All three of them have a ```sizeOfSelect``` field and a ```pcrSelect``` field and the description text for the fields is the same for all the three types. But only ```TPMS_PCR_SELECT``` is describing how the fields should be interpreted.

So I have two questions. 
Can I assume that these fields in ```TPMS_PCR_SELECTION``` and in ```TPMS_TAGGED_PCR_SELECT``` can be interpreted as described for ```TPMS_PCR_SELECT```? And if that is the case why are these structs not defined in the following way:
```c
typedef struct TPMS_PCR_SELECTION TPMS_PCR_SELECTION;
struct TPMS_PCR_SELECTION {
    TPMI_ALG_HASH hash;
    TPMS_PCR_SELECT pcrSelect;
};
```
and
```c
typedef struct TPMS_TAGGED_PCR_SELECT TPMS_TAGGED_PCR_SELECT;
struct TPMS_TAGGED_PCR_SELECT {
    TPM_PT_PCR tag;
    TPMS_PCR_SELECT pcrSelect;
};
```
? Or at least mentioned in the specification that they should be interpreted as described in ```TPMS_PCR_SELECT```?

**Comment by AndreasFuchsSIT** [comment]
I assume this has something to do with the added constraints in the TPM spec.
If I remember correctly, the TPMS_PCR_SELECT has a minimum buffer length of 3, whilst the other two do not.
This is only checked on TPM input buffers though.
It's some weirdness that I also don't understand. I assume a leftover from old times.
