### ISSUE TITLE
--key options for swtpm

### ISSUE THREAD

**Issue by dwaraka1982** [tpm2-software/tpm2-tss#2238]
We are using TPM2.0 by starting the "swtpm" using one of the below options

--key file=<keyfile>

--key pwdfile=<passphrase file>

Both these keys including the migration key is AES. Do we have any option to start the swtpm using a asymmetric key like RSA or only AES is supported for now ?

**Comment by AndreasFuchsSIT** [comment]
That's a Question for https://github.com/stefanberger/swtpm
