### ISSUE TITLE
FAPI crashes when creating key under the Edorsement Key.

### ISSUE THREAD

**Issue by Leonard-k** [tpm2-software/tpm2-tss#2253]
I want to create an AIK under the EK. I tried using tss2_createKey and the FAPI function`Fapi_CreateKey`. both work for creating a key under the SRK or in the Endorsement hirarchy but when i supply the path to the EK I get a segmentation fault:
```bash
$ tss2_provision
$ tss2_createkey -p /SRK/AK -t sign -a ""
$ tss2_createkey -p /EK/AK -t sign -a ""
Segmentation fault (core dumped)
````
My C code using FAPI has the same results therefore i post this here and not in tools.
I am using a docker image based on ubuntu 18.04  which builds tss from source. It uses the ibmswtpm version 1332 which does not come with an EK certificate therefore i disabled the EK certificate check in the fapi config. Is this a bug or am I missing something?

**Comment by JuergenReppSIT** [comment]
@Leonard-k No you are not missing anything. I can confirm the bug and will create PR to fix it.
