### ISSUE TITLE
Some memory leak in Fapi

### ISSUE THREAD

**Issue by JerryDevis** [tpm2-software/tpm2-tss#2265]
Hello, there are some memory leak in Fapi [#2265 ](https://github.com/tpm2-software/tpm2-tss/pull/2263)
1. In ifapi_get_certificates, when ifapi_keystore_load_async or ifapi_keystore_load_finish or ifapi_initialize_object failed, it leads to leak memory that is allocated for context->cmd.Provision.nvPublic.
https://github.com/tpm2-software/tpm2-tss/blob/f1bad6eef225609e1889ea9a57ef053dcb58c5d3/src/tss2-fapi/fapi_util.c#L4302-L4371
2. In keystore_search_obj, object may be leak when ifapi_keystore_load_finish failed.
https://github.com/tpm2-software/tpm2-tss/blob/f1bad6eef225609e1889ea9a57ef053dcb58c5d3/src/tss2-fapi/ifapi_keystore.c#L1174-L1209
3. In command->data may be leak when Fapi_GetEsysBlob_Finish failed. Because when it successed, *data = command->data .
https://github.com/tpm2-software/tpm2-tss/blob/f1bad6eef225609e1889ea9a57ef053dcb58c5d3/src/tss2-fapi/api/Fapi_GetEsysBlob.c#L358-L405
4. In test_fapi_key_create_policy_nv_sign, when Fapi_List_Finish failed, Fapi_List will failed and pathlist may be leaked.
https://github.com/tpm2-software/tpm2-tss/blob/f1bad6eef225609e1889ea9a57ef053dcb58c5d3/test/integration/fapi-key-create-policy-nv-sign.int.c#L128-L152

**Comment by JuergenReppSIT** [comment]
Some more leaks (PR #2269) were fixed
