### ISSUE TITLE
out-of-tree builds don't work

### ISSUE THREAD

**Issue by geoffthorpe** [tpm2-software/tpm2-tss#2271]
Hi all, I have been tweaking some automation and was a little surprised to see that the tpm2-tss source couldn't be configured and compiled from a read-only mount of the source code. I'm aware that bootstrap by its nature modifies the source tree, but I was expecting that the resulting source tree (post-bootstrap) would support "configure" and "make" from an out-of-tree build, with the source mounted read-only, but it's breaking almost right away. (First sign of trouble is "git.mk" trying to generate a ".gitignore" file in the source tree.)

Has there already been a conscious decision not to support this? If so, OK. Otherwise, please let me know if (and how) I can help.

**Comment by williamcroberts** [comment]
There was never a conscious decision made not to support this, it's just never popped up as an issue before. Looks like git.mk has the all target depend on `$(srcdir)/.gitignore`, so perhaps if thats a problem we can drop it, and just generate it with an explicit make gitignore.

**Comment by AndreasFuchsSIT** [comment]
Sounds good to me

**Comment by AndreasFuchsSIT** [comment]
How about skipping if fail, i.e.
```
diff --git a/git.mk b/git.mk
index 6874a32f..a87084bd 100644
--- a/git.mk
+++ b/git.mk
@@ -380,7 +380,7 @@ $(srcdir)/.gitignore: Makefile.am $(top_srcdir)/git.mk $(top_srcdir)/configure.a
        sed "s@^/`echo "$(srcdir)" | sed 's/\(.\)/[\1]/g'`/@/@" | \
        sed 's@/[.]/@/@g' | \
        LC_ALL=C sort | uniq > $@.tmp && \
-       mv $@.tmp $@;
+       mv -f $@.tmp $@ || echo "WARNING: Cannot create .gitignore file; skipping";
 
 all: $(srcdir)/.gitignore gitignore-recurse-maybe
 gitignore: $(srcdir)/.gitignore gitignore-recurse
```

**Comment by williamcroberts** [comment]
I like that idea. I'm not 100% sure if this is the only spot where RO mount of the tree messes us up, would have test it.

**Comment by AndreasFuchsSIT** [comment]
I can say that this works:
```
git clean -xdf
./bootstrap 
chmod -R -w .
chmod +w .
mkdir build
chmod -w .
cd build/
../configure --enable-unit --enable-integration
make -j check
```
LGTM

**Comment by AndreasFuchsSIT** [comment]
I'd merge this into 3.2.0-rc1 but not backport it if that's ok with @geoffthorpe ?

**Comment by geoffthorpe** [comment]
Hi all, I’ve been sporadic on email and hacking, sorry for the delay. I
should be able to retry this in the next day or two with the suggested
change and let you know.

FWIW it’s pretty easy to test this use case out, if you’re game. Basically;

docker -it —rm \
    -v source:/source:ro \
    -v output:/output:rw \
    someimage bash

Then inside the container you try to configure and build from within
/output, using /source (which is of course read-only). I can probably share
a more ready-to-run incantation for this when I get back to my workstation.

Cheers
Geoff

**Comment by geoffthorpe** [comment]
Yeah, that works. @AndreasFuchsSIT, I hadn't noticed your chmod-ing test, that validates it too. :-)
