### ISSUE TITLE
Changes in FAPI broke TSS2 tools

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tss#2274]
So this action builds and tests out fine with tpm2-tss version 3.1.0, but on master fails:
```
ERROR:fapi:src/tss2-fapi/api/Fapi_VerifyQuote.c:302:Fapi_VerifyQuote_Finish() ErrorCode (0x00060021) Invalid qualifying data for quote 
ERROR:fapi:src/tss2-fapi/api/Fapi_VerifyQuote.c:103:Fapi_VerifyQuote() ErrorCode (0x00060021) Key_VerifyQuote 
```
https://github.com/williamcroberts/tpm2-tools/runs/4777639746?check_suite_focus=true#step:4:146

And this one:
```
ERROR:fapi:src/tss2-fapi/api/Fapi_Delete.c:405:Fapi_Delete_Async() ErrorCode (0x00060034) FAPI not provisioned. 
ERROR:fapi:src/tss2-fapi/api/Fapi_Delete.c:313:Fapi_Delete() ErrorCode (0x00060034) Entity_Delete 
Fapi_Delete(0x60034) - fapi:Provisioning was not executed.
```
https://github.com/williamcroberts/tpm2-tools/runs/4777639746?check_suite_focus=true#step:4:72

**Comment by AndreasFuchsSIT** [comment]
I guess this PR is to blame: https://github.com/tpm2-software/tpm2-tss/pull/2256
@JuergenReppSIT You're much more familiar with this than me:
So test/integration/fapi/fapi-quote-verify will probably need other Qualifying data ?
And similarly test/integration/fapi/fapi-quote-verify_ecc (the ECC version of it).
The delete stuff sounds like a followup bug in the test or not ?

**Comment by JuergenReppSIT** [comment]
I created PR  #2913 related to this topic which is already merged.

**Comment by AndreasFuchsSIT** [comment]
So can we close this bug ?

**Comment by williamcroberts** [comment]
Yes builds seem to be working again.
