### ISSUE TITLE
Uninitialized value

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tss#2275]
Coverity reports that `object.objectType` can be uninitialized here
https://github.com/tpm2-software/tpm2-tss/blob/0d0573766bf17b6872824b7b35258358a6d1e961/src/tss2-fapi/ifapi_keystore.c#L1209

I guess we need to init it to something meaningful here
https://github.com/tpm2-software/tpm2-tss/blob/0d0573766bf17b6872824b7b35258358a6d1e961/src/tss2-fapi/ifapi_keystore.c#L1140

@JuergenReppSIT Is there an "invalid" objectType we can use or what would make sense here ?

**Comment by JuergenReppSIT** [comment]
@AndreasFuchsSIT Yes we can use IFAPI_OBJ_NONE. I will create the PRs.

**Comment by JuergenReppSIT** [comment]
was fixed with PR #2276.
