### ISSUE TITLE
Makefile build error - 2.0.x

### ISSUE THREAD

**Issue by AyushAmbastha** [tpm2-software/tpm2-tss#2305]
Hi, 
The `make` command fails with the error - `Makefile:14664: *** missing separator.  Stop.` This is after the Makefile is generated using the `configure` script.
Which is line #45 in Makefile.am - https://github.com/tpm2-software/tpm2-tss/blob/2.0.x/Makefile.am#L45

I think its an indentation error but wanted to be sure that there isn't an error from my side. 
Thanks!

**Comment by AndreasFuchsSIT** [comment]
I'm sorry, but the 2.0.x branch of versions is kind of old and end of life.
Please consider moving to a newer version, such as 3.2.0 that will be released today.
