### ISSUE TITLE
Release tarball for 3.2.0 does not contain lib/tss2-tcti-libtpms.map

### ISSUE THREAD

**Issue by diabonas** [tpm2-software/tpm2-tss#2313]
The freshly released [`tpm2-tss-3.2.0.tar.gz`](https://github.com/tpm2-software/tpm2-tss/releases/download/3.2.0/tpm2-tss-3.2.0.tar.gz) does not contain the file [`lib/tss2-tcti-libtpms.map`](https://github.com/tpm2-software/tpm2-tss/blob/master/lib/tss2-tcti-libtpms.map), leading to the following build failure on systems that have libtpms installed:
```
  CCLD     src/tss2-tcti/libtss2-tcti-libtpms.la
/usr/bin/ld: cannot open linker script file ./lib/tss2-tcti-libtpms.map: No such file or directory
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:11581: src/tss2-tcti/libtss2-tcti-libtpms.la] Error 1
```
The reason seems to be because the release tarball has been generated on a system without libtpms, as including that file into the tarball is [conditional on the auto-detected `ENABLE_TCTI_LIBTPMS`](https://github.com/tpm2-software/tpm2-tss/blob/e237e4d33cbf280292a480edd8ad061dcd3a37a2/Makefile.am#L361-L367). This seems like a suboptimal choice, especially since `tss2-tcti-libtpms.map` is just a static file that could be included unconditionally.

I noticed there are more of these conditional includes, e.g. for [`lib/tss2-tcti-device.map`](https://github.com/tpm2-software/tpm2-tss/blob/e237e4d33cbf280292a480edd8ad061dcd3a37a2/Makefile.am#L289-L295). However `tss2-tcti-libtpms.map` is the only file actually missing from the 3.2.0 release tarball as far as I can tell.

All of these conditional `EXTRA_DIST` includes should be reviewed and made unconditional, if possible. If they include auto-generated files that can only be created if the prerequisite condition is fulfilled, an alternative would be keeping the `EXTRA_DIST` conditional, but enforcing the respective condition to be fulfilled when generating a release tarball with `make dist(check)`.

**Comment by AndreasFuchsTPM** [comment]
Merged and will be part of 3.2.1 release.
