### ISSUE TITLE
Pluggable crypto backend?

### ISSUE THREAD

**Issue by ueno** [tpm2-software/tpm2-tss#2315]
In GnuTLS we have recently added a [feature](https://gitlab.com/gnutls/gnutls/-/merge_requests/1460) to load TPM2 key blob through tpm2-tss. It works great, but turned out that libtss2-esys.so.* brings in OpenSSL dependency, which causes issues in packaging. To mitigate this I wonder if tpm2-tss could provide a means to install a custom crypto backend for ESAPI, something like:

- A new API is added to set custom crypto backend, say `TSS2_RC Tss2_Crypto_Register(... function pointers ...);`
- If the function is not called, libtss2-esys.so.* dlopen's the existing crypto implementations (OpenSSL or mbed TLS), which are provided as a separate shared library (libtss2-esys-ossl.so.* and libtss2-esys-mbed.so.*)

**Comment by AndreasFuchsSIT** [comment]
We actually used to have libgcrypt as backend, but removed it since there were no users and no maintainers and we already had two backends with openssl and mbed-tls.
see https://github.com/tpm2-software/tpm2-tss/pull/1781
see also the discussion at https://github.com/tpm2-software/tpm2-tss/issues/1676
If you were interested in reintroducing this, I'd be totally open. But we'd need someone commited to working on issues with this backend.
Could you take over this task ?

**Comment by ueno** [comment]
I'm afraid reviving the libgcrypt backend doesn't help, as GnuTLS switched to Nettle some time ago.

**Comment by AndreasFuchsSIT** [comment]
Ok, so almost the same story... ;-)
I'm not opposed as long as someone looks into keeping it running...
But also I'd prefer this to be a comile-time options, not a dlopen one...

**Comment by williamcroberts** [comment]
> Ok, so almost the same story... ;-) I'm not opposed as long as someone looks into keeping it running... But also I'd prefer this to be a compile-time options, not a dlopen one...

So does Gentoo.

**Comment by ueno** [comment]
The current workaround is to [`dlopen`](https://gitlab.com/gnutls/gnutls/-/merge_requests/1544) libtss2* libs in GnuTLS. This is the same approach as we [take](https://gitlab.com/gnutls/gnutls/-/blob/15b43385c1f3a903e430fc79feabcb68b164df2b/lib/tpm.c#L120) for trousers but certainly not ideal.

From the perspective of a crypto library, it would be nice if a variant of libtss2-esys was provided, without any dependencies to particular crypto library That might be possible if libtss2-esys is spit into two parts: one only provides stub implementation of the [internal crypto API](https://tpm2-tss.readthedocs.io/en/latest/group__iesys__crypto.html) as `weak` symbols, and the other provides actual crypto implementation through OpenSSL, mbed TLS, etc.

**Comment by AndreasFuchsSIT** [comment]
I do fear a bit, that people will be running into problems with this. I know that experienced programmers have no problem with weak symbols but I'm afraid the issue tracker will blow up.

As for dlopening tpm2-tss, we've created some helpers that you can copy while we figure this stuff out: https://github.com/tpm2-software/tpm2-tss/tree/master/tss2-dlopen

**Comment by williamcroberts** [comment]
I have this PR to address this:
  - https://github.com/tpm2-software/tpm2-tss/pull/2365

**Comment by AndreasFuchsTPM** [comment]
Solved by #2365
