### ISSUE TITLE
finish 1.59 spec support

### ISSUE THREAD

**Issue by ProLoDs** [tpm2-software/tpm2-tss#2317]
Hi,

i want to calculate a CMAC with the TPM.
I have seen, that the `TPM2_ALG_CMAC` was added, but i have not found out howto use it. 
The `alg.md` only specifies the HMAC not the CMAC.

Thank you in advance.

EDIT: looks like it was added here : https://github.com/tpm2-software/tpm2-tools/commit/0d88935be88e9590a893b2532a0271a1cb1ed868.
But i can't use it with ` tpm2 create -Q -G cmac -C primary.ctx`. I just get unable to run command.
If i execute `tpm2_hmac -g cmac -c hmac.ctx --hex data.in` it just returns nothing. 

Im currently running: tag 5.1.1

**Comment by williamcroberts** [comment]
The bug is on a list of TODO's to support (1.59 of the spec). We should just create a generic ticket in the tss to finish 1.59 support. We're in an awkward state of support between 1.38 (I think that's the last one offhand) and 1.59.

**Comment by williamcroberts** [comment]
FYI The recent versions of all of our specs should have the 1.59 changes:
  - https://trustedcomputinggroup.org/resources/?workgroups=TPM%20Software%20Stack%20(TSS)&

**Comment by ProLoDs** [comment]
@williamcroberts  Thanks for the info. 
Is there a timeline or version connected to the spec 1.59?

**Comment by williamcroberts** [comment]
I was hoping to be done with it this summer, not sure what kind of time I have on it. Perhaps @JuergenReppSIT or @AndreasFuchsSIT want to get it into a specified timeline?

**Comment by ProLoDs** [comment]
Any News? @JuergenReppSIT , @AndreasFuchsTPM is there a rough timeline?

**Comment by williamcroberts** [comment]
@malikabhi05 the first thing to do will be to generate a todo list of each change to make sure we don't miss anything
- [ ] Add CMAC commands to tss2-sys
- [ ] Add CMAC commands to tss2-esys
- [ ] Update signatures for Encrypt/Encrypt2/Decrypt in tss2-sys
- [ ] Update signatures for Encrypt/Encrypt2/Decrypt in tss2-esys
- [ ] Etc Etc

**Comment by AndreasFuchsTPM** [comment]
I guess this is closed since merge of #2402 with the upcoming 4.0 release.
