### ISSUE TITLE
Configure command fails on macOS Catalina 10.15.7 . configure: error: addgroup or groupadd are needed

### ISSUE THREAD

**Issue by so-b1** [tpm2-software/tpm2-tss#2318]
Trying to build on macOS Catalina 10.15.7

Command:
`./configure && make && make install`

Error:
`configure: error: addgroup or groupadd are needed`

**Comment by williamcroberts** [comment]
Do you have addgroup or group add? You'll need to full fill those dependencies. I don't think anyone has built on mac since they don't have TPMs, so I am not sure if you'll bump into other issues.

**Comment by AndreasFuchsTPM** [comment]
I hope things are working now.
Closing the issue since no update for a long time.
