### ISSUE TITLE
Question - what's exact purpose of `tss:tss` user

### ISSUE THREAD

**Issue by ueco-jb** [tpm2-software/tpm2-tss#2322]
Hey,
so recently I noticed during my kernel update following log:
```bash
:: Running post-transaction hooks...
( 1/16) Creating system user accounts...
Creating group 'tss' with GID 974.
Creating user 'tss' (tss user for tpm2) with UID 974 and GID 974.
```
My investigation got me to this PR for example: https://github.com/tpm2-software/tpm2-tss/pull/1582
This line confuses me a bit:
> To create the tss system user and group, install a [sysusers.d](https://www.freedesktop.org/software/systemd/man/sysusers.d.html) configuration file.

I'm on Artix Linux with OpenRC (so no systemd). I have plenty of questions - what's purpose of that user:group, is it systemd dependent, how does it work around without it?
I'd be glad if you could either explain or point me to some sources to understand this process.

**Comment by williamcroberts** [comment]
So its for permissions on what can access the TPM directly (/dev/tpm0) or through the resource manager (/dev/tpmrm0 or tpm2-abrmd). It is not systemd dependent. You just need a udev rule to assign the right permissions. What's your actual issue?

See:
  - https://github.com/tpm2-software/tpm2-tss/blob/9288970a3e657cdee85d08d3813199ec864de3ad/dist/tpm-udev.rules

**Comment by williamcroberts** [comment]
So a user can access anything and a group member can access the tpm through a resource manager

**Comment by ueco-jb** [comment]
Thank you. I wanted to understand that mechanism better and clarify whether I didn't install incorrect soft for my configuration (so requiring systemd).

I just noticed that you have mailing list, so probably I should have post my question there. Sorry for disturbance in that case.

**Comment by williamcroberts** [comment]
Yeah the mailing list is preferred, but no worries, can I close this?
