### ISSUE TITLE
Procedure to add a new function to the Esys API?

### ISSUE THREAD

**Issue by LoupVaillant** [tpm2-software/tpm2-tss#2327]
I'm currently losing my hair over what should be a trivial issue: adding a publicly exported function, then use it.

Here's what I have done so far. First, I added a function to the Esys API. Here's the whole patch for reference:

```diff
diff --git a/include/tss2/tss2_esys.h b/include/tss2/tss2_esys.h
index b3fa9ca7..9b16cd92 100644
--- a/include/tss2/tss2_esys.h
+++ b/include/tss2/tss2_esys.h
@@ -3304,0 +3305,3 @@ Esys_GetSysContext(
+void
+Esys_PrintFooBar();
+
diff --git a/lib/tss2-esys.def b/lib/tss2-esys.def
index ffdadebf..5a9f644c 100644
--- a/lib/tss2-esys.def
+++ b/lib/tss2-esys.def
@@ -287,0 +288 @@ EXPORTS
+    Esys_PrintFooBar
diff --git a/src/tss2-esys/esys_context.c b/src/tss2-esys/esys_context.c
index f7ef55c2..fcf36961 100644
--- a/src/tss2-esys/esys_context.c
+++ b/src/tss2-esys/esys_context.c
@@ -240,0 +241,6 @@ Esys_GetSysContext(ESYS_CONTEXT *esys_context, TSS2_SYS_CONTEXT **sys_context)
+
+void
+Esys_PrintFooBar()
+{
+    LOG_DEBUG("Foo Bar");
+}
```

Note that I have also added my new function to the list of symbols in `lib/tss2-esys.def`. Anyway, I can install my patched library on my system (an Alpine Linux Docker container, I am root), with classic commands from the autotools:

```bash
$ autoreconf
$ ./configure --prefix=/usr
$ make
$ make install
```

I have a problem however:

```bash
$ nm /usr/lib/libtss2-esys.so | grep Esys_PrintFooBar
000000000005e760 t Esys_PrintFooBar
```

See the lowercase `t`? According to the manual, it means `Esys_PrintFooBar` is a _local_ symbol. To contrast with all other exported Esys functions, which are all global. I don't know what's the difference. But one thing's for sure: I cannot link to that new symbol. To test this, I have written a small C test program:

```C
#include <tss2/tss2_tctildr.h>
#include <tss2/tss2_esys.h>
int main(void)
{
    /* Normal stuff from the TCTI and Esys APIs */
    TSS2_TCTI_CONTEXT *tcti;
    ESYS_CONTEXT *esys;
    TSS2_ABI_VERSION abi_version = TSS2_ABI_VERSION_CURRENT;
    Tss2_TctiLdr_Initialize(0, &tcti);
    Esys_Initialize(&esys, tcti, &abi_version);

    /* New stuff freshly added to the Esys API */
    Esys_PrintFooBar();
    return 0;
}
```

Here's what I get when I try to compile i:

```bash
$ gcc -Wall -Wextra foobar.c -ltss2-esys -ltss2-tctildr
/usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/ccEAppjD.o: in function `main':
foobar.c:(.text+0x61): undefined reference to `Esys_PrintFooBar'
collect2: error: ld returned 1 exit status
```

Note that the other symbols, `Tss2_TctiLdr_Initialize` and `Esys_Initialize`, _do_ successfully link.

I told myself _maybe_ I could make the symbol global? So I tried `objcopy --globalize-symbol`, and it did change my lowercase `t` into an uppercase `T`, but I could still not link.

---

Right now I would like to get around #2326, perhaps even contribute an actual patch somewhere down the line. This means adding one or more function to the Esys API. Everything I have tried to far failed miserably. Hence my question: _what's the procedure to add a function to the Esys API?_

**Comment by williamcroberts** [comment]
update the `.map` file as well. In your case it's the `tss2-esys.map` file under lib.

**Comment by LoupVaillant** [comment]
Aaaahh, I see where the local/global distinction comes from now, thanks. As far as I can tell it works now.

Out of curiosity, are those `.def` and `.map` standard practice among projects that use the autotools, or are they specific to TPM2 software? I've search the autotools (mostly libtool) a lot these last two days, and I never saw any mention of those files. Is there any resource, either on this project or elsewhere on the web, that discusses `.def` and `.map` files and how they are used?

**Comment by williamcroberts** [comment]
They're linker scripts. `.map` is used for linux, `.def`, IIUC, is windows:
  - https://docs.microsoft.com/en-us/cpp/build/reference/module-definition-dot-def-files?view=msvc-170
  - https://interrupt.memfault.com/blog/get-the-most-out-of-the-linker-map-file
