### ISSUE TITLE
[Specification questions]: Expected response codes for RESMGR layer are missing.

### ISSUE THREAD

**Issue by Superhepper** [tpm2-software/tpm2-tss#2331]
I am looking at "TCG TSS 2.0 Overview and Common, Structures Specification, Version 1.0, Revision 10, September 23, 2021" in order to figure out how to interpret the return code TSS2_RC and I have two questions.

1. Is there any difference between "Response Code" and "Return Code" because it seems as two different terms are used for the same thing.

2. There is no response codes defined for the TSS2_RESMGR_RC_LAYER layer. Can I then assume that all errors defined in "3.5 tss2_common.h Base Return Codes" can be returned from this layer?

**Comment by williamcroberts** [comment]
> I am looking at "TCG TSS 2.0 Overview and Common, Structures Specification, Version 1.0, Revision 10, September 23, 2021" in order to figure out how to interpret the return code TSS2_RC and I have two questions.
> 
> 1. Is there any difference between "Response Code" and "Return Code" because it seems as two different terms are used for the same thing.

I don't know if they are used correctly, but the TPM or the Resource Manager respond (Response Code) and the library layers return (Return Code), but in general they are the same thing.

> 2. There is no response codes defined for the TSS2_RESMGR_RC_LAYER layer. Can I then assume that all errors defined in "3.5 tss2_common.h Base Return Codes" can be returned from this layer?

What it can return is defined in Sections 3.1 and 3.2 of:
  - https://trustedcomputinggroup.org/resource/tss-tab-and-resource-manager/

**Comment by Superhepper** [comment]
Thank you for the answer!

"TSS2_RESMGR_RC_LAYER is used to return TAB/RM specific errors. The least significant two bytes
are interpreted following the scheme for base error codes in TSS 2.0 Overview and Common
Structures Specification ." 

So I guess its all of the base return codes?

**Comment by williamcroberts** [comment]
I think all the base RC's are valid, but it may not actually return them all. It can also return layer 0 (TPM codes) as well when the TPM returns an error.

**Comment by Superhepper** [comment]
Thanks for this answer I will close this.
