### ISSUE TITLE
Cannot create policy file in /usr/local/var/lib/tpm2-tss/system/keystore/policy

### ISSUE THREAD

**Issue by mslearner** [tpm2-software/tpm2-tss#2343]
I am running a basic HelloWorld program for creating a FAPI based key using TPM. When I do FAPI_Initialize(...), I get the following errors. 

WARNING:fapi:../src/tss2-fapi/ifapi_io.c:339:ifapi_io_check_create_dir() Directory /usr/local/var/lib/tpm2-tss/system/keystore/policy does not exist, creating 
ERROR:fapi:../src/tss2-fapi/ifapi_helpers.c:1053:create_dirs() mkdir not possible: -1 /usr/local/var/lib/tpm2-tss/system/keystore/policy 
ERROR:fapi:../src/tss2-fapi/ifapi_helpers.c:1080:ifapi_create_dirs() ErrorCode (0x0006000b) Create directories for /usr/local/var/lib/tpm2-tss/system/keystore/policy 
ERROR:fapi:../src/tss2-fapi/ifapi_io.c:342:ifapi_io_check_create_dir() ErrorCode (0x0006000b) Directory /usr/local/var/lib/tpm2-tss/system/keystore/policy can't be created. 
ERROR:fapi:../src/tss2-fapi/ifapi_policy_store.c:115:ifapi_policy_store_initialize() ErrorCode (0x0006000b) Policy directory /usr/local/var/lib/tpm2-tss/system/keystore/policy can't be created. 
ERROR:fapi:../src/tss2-fapi/api/Fapi_Initialize.c:215:Fapi_Initialize_Finish() ErrorCode (0x0006000b) Keystore could not be initialized.

---------------
Here is the program ---  
`#include "basic_fapi_program.h"
#include <stdio.h>
#include <tss2/tss2_fapi.h>
int main() {
  printf("Hello World\n");
  TSS2_RC r = 0;
  FAPI_CONTEXT *fapi_context;
  size_t signatureSize = 0;
  uint8_t *signature;
  char *publicKey;
  size_t digestSize = 32;
  uint8_t digest[32] = {0x67, 0x68, 0x69, 0x70, 0x71, 0x72, 0x73, 0x3e};
  r = Fapi_Initialize(&fapi_context, NULL);
  if (r != TSS2_RC_SUCCESS)
    goto error;

  Fapi_Finalize(&fapi_context);

  return 0;

error:

  Fapi_Finalize(&fapi_context);
  return 1;
}`

------------------------------

Here are the permissions in the keystore directory

![image](https://user-images.githubusercontent.com/19580776/163305040-7bb2bd35-fe9e-4a1b-9dd2-4e7733e57c88.png)

**Comment by williamcroberts** [comment]
Is your user account part of the tss group?

For example on my dev box:
```bash
$ groups
wcrobert adm cdrom sudo dip plugdev tss lpadmin lxd sambashare docker
```

**Comment by AndreasFuchsTPM** [comment]
I hope things are working now.
Closing the issue since no update for a long time.
