### ISSUE TITLE
HowTo: Import AES key with Esys

### ISSUE THREAD

**Issue by ProLoDs** [tpm2-software/tpm2-tss#2355]
Hi,
is there a way to import a symmetric key into the TPM using the ESYS interface?
Apparently the tpm2_tool support that usecase with tpm2_import.
I read the Esys_Import function, but could not figure out how to use it. All the Integration tests seam to import a key that was already inside a tpm. 

I would appreciate a hint :)

**Comment by williamcroberts** [comment]
importing is pretty hard, you need to wrap the raw key using the duplication process described in https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p59_Part1_Architecture_pub.pdf Section 23.3 on Duplication. See figures 19, 20, 21 and 22 for the different possibilities.

If you can use python, we have that wrap function implemented:
  - https://github.com/tpm2-software/tpm2-pytss/blob/master/tpm2_pytss/utils.py#L74

Makes life much easier and then the tests showcase it through the import call:
  - https://github.com/tpm2-software/tpm2-pytss/blob/master/test/test_utils.py#L180

**Comment by ProLoDs** [comment]
Thanks a lot for the Hint, in the end we used the implementation of the tpm2_tools. 
As a primary we want to use a ECC Key, unfortunately we cant create one with:
```c    
TPM2B_PUBLIC inPublicECC = {
        .size = 0,
        .publicArea = {
            .type = TPM2_ALG_ECC,
            .nameAlg = TPM2_ALG_SHA256,
            .objectAttributes = (TPMA_OBJECT_USERWITHAUTH |
                                 TPMA_OBJECT_RESTRICTED |
                                 TPMA_OBJECT_SIGN_ENCRYPT |
                                 TPMA_OBJECT_FIXEDTPM |
                                 TPMA_OBJECT_FIXEDPARENT |
                                 TPMA_OBJECT_SENSITIVEDATAORIGIN),
            .authPolicy = {
                .size = 0,
            },
            .parameters = {.eccDetail = {.symmetric = {
                                             .algorithm = TPM2_ALG_AES,
                                             .keyBits = {.aes = 128},
                                             .mode = {.aes = TPM2_ALG_CFB},
                                         },
                                         .scheme = {.scheme = TPM2_ALG_ECDSA, .details = {.ecdsa = {.hashAlg = TPM2_ALG_SHA256}}},
                                         .curveID = TPM2_ECC_NIST_P256,
                                         .kdf = {.scheme = TPM2_ALG_NULL, .details = {}}}},
            .unique = {.ecc = {.x = {.size = 0, .buffer = {}}, .y = {.size = 0, .buffer = {}}}},
        }};
```
With a RSA key it works just fine. All integration tests use as `parameters.eccDetail.symmetric.algorithm` the `TPM2_ALG_NULL`. But we can't use the NULL algorithm for the inner wrapping. RSA is not an option, because the TPM only supports 2048 bit keys. 

Thanks a lot!
