### ISSUE TITLE
some errors when make check :"Makefile:11055：src/tss2-esys/libtss2-esys.la"

### ISSUE THREAD

**Issue by Chanz6666** [tpm2-software/tpm2-tss#2376]
log here
CCLD     src/tss2-esys/libtss2-esys.la
/usr/bin/ld: src/tss2-tcti/.libs/tss2_esys_libtss2_esys_la-tctildr-dl.o: in function `info_from_handle':
/home/user_8e4db6/2new_tss/tpm2-tss/src/tss2-tcti/tctildr-dl.c:69: undefined reference to `dlsym'
/usr/bin/ld: /home/user_8e4db6/2new_tss/tpm2-tss/src/tss2-tcti/tctildr-dl.c:71: undefined reference to `dlerror'
/usr/bin/ld: src/tss2-tcti/.libs/tss2_esys_libtss2_esys_la-tctildr-dl.o: in function `handle_from_name':
/home/user_8e4db6/2new_tss/tpm2-tss/src/tss2-tcti/tctildr-dl.c:89: undefined reference to `dlopen'
/usr/bin/ld: /home/user_8e4db6/2new_tss/tpm2-tss/src/tss2-tcti/tctildr-dl.c:93: undefined reference to `dlerror'
/usr/bin/ld: /home/user_8e4db6/2new_tss/tpm2-tss/src/tss2-tcti/tctildr-dl.c:115: undefined reference to `dlopen'
/usr/bin/ld: /home/user_8e4db6/2new_tss/tpm2-tss/src/tss2-tcti/tctildr-dl.c:120: undefined reference to `dlerror'
/usr/bin/ld: /home/user_8e4db6/2new_tss/tpm2-tss/src/tss2-tcti/tctildr-dl.c:132: undefined reference to `dlopen'
/usr/bin/ld: /home/user_8e4db6/2new_tss/tpm2-tss/src/tss2-tcti/tctildr-dl.c:134: undefined reference to `dlerror'
/usr/bin/ld: src/tss2-tcti/.libs/tss2_esys_libtss2_esys_la-tctildr-dl.o: in function `tcti_from_file':
/home/user_8e4db6/2new_tss/tpm2-tss/src/tss2-tcti/tctildr-dl.c:161: undefined reference to `dlsym'
/usr/bin/ld: /home/user_8e4db6/2new_tss/tpm2-tss/src/tss2-tcti/tctildr-dl.c:164: undefined reference to `dlclose'
/usr/bin/ld: /home/user_8e4db6/2new_tss/tpm2-tss/src/tss2-tcti/tctildr-dl.c:171: undefined reference to `dlclose'
/usr/bin/ld: src/tss2-tcti/.libs/tss2_esys_libtss2_esys_la-tctildr-dl.o: in function `tctildr_finalize_data':
/home/user_8e4db6/2new_tss/tpm2-tss/src/tss2-tcti/tctildr-dl.c:332: undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
make: *** [Makefile:11055：src/tss2-esys/libtss2-esys.la] error 1

Since an error about gdbus-coden path missing happened in the first time , so this was the second time I install tpm2-tss. Is it related to each other?Maybe?.
I have also tried modify LD_LIBRARY_PATH, but it still didn't work. Please help!

**Comment by JuergenReppSIT** [comment]
@Chanz6666 What happens if you execute:
`make check LDFLAGS+='-ldl'`

**Comment by AndreasFuchsTPM** [comment]
I hope everything is working now.
I close this now since no update for a long time.

**Comment by hashmi240400** [comment]
make  all-am
make[1]: Entering directory '/home/cdac/Desktop/new2/tpm2-tss'
  CCLD     src/tss2-esys/libtss2-esys.la
/usr/bin/ld: src/tss2-esys/.libs/libtss2_esys_la-esys_crypto_ossl.o: in function `iesys_cryptossl_context_new':
esys_crypto_ossl.c:(.text+0x2e): undefined reference to `OSSL_LIB_CTX_new'
/usr/bin/ld: src/tss2-esys/.libs/libtss2_esys_la-esys_crypto_ossl.o: in function `iesys_cryptossl_context_set_hash_md':
esys_crypto_ossl.c:(.text+0xde): undefined reference to `EVP_MD_fetch'
/usr/bin/ld: src/tss2-esys/.libs/libtss2_esys_la-esys_crypto_ossl.o: in function `iesys_cryptossl_context_free.part.0':
esys_crypto_ossl.c:(.text+0x1e6): undefined reference to `EVP_MD_free'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x1ef): undefined reference to `OSSL_LIB_CTX_free'
/usr/bin/ld: src/tss2-esys/.libs/libtss2_esys_la-esys_crypto_ossl.o: in function `iesys_cryptossl_hmac_update':
esys_crypto_ossl.c:(.text+0xf6d): undefined reference to `EVP_DigestSignUpdate'
/usr/bin/ld: src/tss2-esys/.libs/libtss2_esys_la-esys_crypto_ossl.o: in function `iesys_cryptossl_random2b':
esys_crypto_ossl.c:(.text+0x1483): undefined reference to `OSSL_LIB_CTX_new'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x14a8): undefined reference to `RAND_bytes_ex'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x14b2): undefined reference to `OSSL_LIB_CTX_free'
/usr/bin/ld: src/tss2-esys/.libs/libtss2_esys_la-esys_crypto_ossl.o: in function `iesys_cryptossl_pk_encrypt':
esys_crypto_ossl.c:(.text+0x15bf): undefined reference to `OSSL_LIB_CTX_new'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x1600): undefined reference to `EVP_MD_fetch'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x16ac): undefined reference to `EVP_MD_free'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x16b4): undefined reference to `OSSL_LIB_CTX_free'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x1763): undefined reference to `OSSL_PARAM_BLD_new'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x1781): undefined reference to `OSSL_PARAM_BLD_push_BN'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x179a): undefined reference to `OSSL_PARAM_BLD_push_uint32'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x17aa): undefined reference to `OSSL_PARAM_BLD_to_param'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x17c7): undefined reference to `EVP_PKEY_CTX_new_from_name'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x17dd): undefined reference to `EVP_PKEY_fromdata_init'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x17ff): undefined reference to `EVP_PKEY_fromdata'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x1964): undefined reference to `OSSL_PARAM_free'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x1975): undefined reference to `OSSL_PARAM_BLD_free'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x1aba): undefined reference to `OSSL_LIB_CTX_free'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x1b2c): undefined reference to `EVP_PKEY_CTX_set_rsa_padding'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x1bac): undefined reference to `EVP_PKEY_CTX_set0_rsa_oaep_label'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x1c3a): undefined reference to `EVP_PKEY_CTX_set_rsa_oaep_md'
/usr/bin/ld: src/tss2-esys/.libs/libtss2_esys_la-esys_crypto_ossl.o: in function `iesys_cryptossl_get_ecdh_point':
esys_crypto_ossl.c:(.text+0x1fa2): undefined reference to `EVP_PKEY_CTX_set_ec_paramgen_curve_nid'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x1fd5): undefined reference to `EVP_PKEY_get_bn_param'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x1fef): undefined reference to `EVP_PKEY_get_bn_param'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x225a): undefined reference to `EVP_PKEY_get_bn_param'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:12414: src/tss2-esys/libtss2-esys.la] Error 1
make[1]: Leaving directory '/home/cdac/Desktop/new2/tpm2-tss'
make: *** [Makefile:11777: all] Error 2
root@ZTNA:/home/cdac/Desktop/new2/tpm2-tss# make check LDFLAGS+='-ldl'
  CCLD     src/tss2-esys/libtss2-esys.la
/usr/bin/ld: src/tss2-esys/.libs/libtss2_esys_la-esys_crypto_ossl.o: in function `iesys_cryptossl_context_new':
esys_crypto_ossl.c:(.text+0x2e): undefined reference to `OSSL_LIB_CTX_new'
/usr/bin/ld: src/tss2-esys/.libs/libtss2_esys_la-esys_crypto_ossl.o: in function `iesys_cryptossl_context_set_hash_md':
esys_crypto_ossl.c:(.text+0xde): undefined reference to `EVP_MD_fetch'
/usr/bin/ld: src/tss2-esys/.libs/libtss2_esys_la-esys_crypto_ossl.o: in function `iesys_cryptossl_context_free.part.0':
esys_crypto_ossl.c:(.text+0x1e6): undefined reference to `EVP_MD_free'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x1ef): undefined reference to `OSSL_LIB_CTX_free'
/usr/bin/ld: src/tss2-esys/.libs/libtss2_esys_la-esys_crypto_ossl.o: in function `iesys_cryptossl_hmac_update':
esys_crypto_ossl.c:(.text+0xf6d): undefined reference to `EVP_DigestSignUpdate'
/usr/bin/ld: src/tss2-esys/.libs/libtss2_esys_la-esys_crypto_ossl.o: in function `iesys_cryptossl_random2b':
esys_crypto_ossl.c:(.text+0x1483): undefined reference to `OSSL_LIB_CTX_new'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x14a8): undefined reference to `RAND_bytes_ex'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x14b2): undefined reference to `OSSL_LIB_CTX_free'
/usr/bin/ld: src/tss2-esys/.libs/libtss2_esys_la-esys_crypto_ossl.o: in function `iesys_cryptossl_pk_encrypt':
esys_crypto_ossl.c:(.text+0x15bf): undefined reference to `OSSL_LIB_CTX_new'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x1600): undefined reference to `EVP_MD_fetch'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x16ac): undefined reference to `EVP_MD_free'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x16b4): undefined reference to `OSSL_LIB_CTX_free'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x1763): undefined reference to `OSSL_PARAM_BLD_new'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x1781): undefined reference to `OSSL_PARAM_BLD_push_BN'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x179a): undefined reference to `OSSL_PARAM_BLD_push_uint32'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x17aa): undefined reference to `OSSL_PARAM_BLD_to_param'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x17c7): undefined reference to `EVP_PKEY_CTX_new_from_name'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x17dd): undefined reference to `EVP_PKEY_fromdata_init'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x17ff): undefined reference to `EVP_PKEY_fromdata'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x1964): undefined reference to `OSSL_PARAM_free'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x1975): undefined reference to `OSSL_PARAM_BLD_free'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x1aba): undefined reference to `OSSL_LIB_CTX_free'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x1b2c): undefined reference to `EVP_PKEY_CTX_set_rsa_padding'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x1bac): undefined reference to `EVP_PKEY_CTX_set0_rsa_oaep_label'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x1c3a): undefined reference to `EVP_PKEY_CTX_set_rsa_oaep_md'
/usr/bin/ld: src/tss2-esys/.libs/libtss2_esys_la-esys_crypto_ossl.o: in function `iesys_cryptossl_get_ecdh_point':
esys_crypto_ossl.c:(.text+0x1fa2): undefined reference to `EVP_PKEY_CTX_set_ec_paramgen_curve_nid'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x1fd5): undefined reference to `EVP_PKEY_get_bn_param'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x1fef): undefined reference to `EVP_PKEY_get_bn_param'
/usr/bin/ld: esys_crypto_ossl.c:(.text+0x225a): undefined reference to `EVP_PKEY_get_bn_param'
collect2: error: ld returned 1 exit status
make: *** [Makefile:12414: src/tss2-esys/libtss2-esys.la] Error 1

Tried everything but unable to resolve this issue.Please look into the issue.

**Comment by PunyHunter** [comment]
similar error & execute "make check LDFLAGS+='-ldl' "
 esys_crypto_ossl.c:(.text+0x3338): undefined reference to `EVP_aes_256_cfb128'
/opt/hcc_arm64le/bin/../lib64/gcc/aarch64-target-linux-gnu/7.3.0/../../../../aarch64-target-linux-gnu/bin/ld: esys_crypto_ossl.c:(.text+0x3340): undefined reference to `EVP_CIPHER_CTX_new'
/opt/hcc_arm64le/bin/../lib64/gcc/aarch64-target-linux-gnu/7.3.0/../../../../aarch64-target-linux-gnu/bin/ld: esys_crypto_ossl.c:(.text+0x3444): undefined reference to `EVP_aes_128_cfb128'
/opt/hcc_arm64le/bin/../lib64/gcc/aarch64-target-linux-gnu/7.3.0/../../../../aarch64-target-linux-gnu/bin/ld: esys_crypto_ossl.c:(.text+0x344c): undefined reference to `EVP_CIPHER_CTX_new'
/opt/hcc_arm64le/bin/../lib64/gcc/aarch64-target-linux-gnu/7.3.0/../../../../aarch64-target-linux-gnu/bin/ld: esys_crypto_ossl.c:(.text+0x34c8): undefined reference to `EVP_DecryptInit'
/opt/hcc_arm64le/bin/../lib64/gcc/aarch64-target-linux-gnu/7.3.0/../../../../aarch64-target-linux-gnu/bin/ld: esys_crypto_ossl.c:(.text+0x3520): undefined reference to `EVP_CIPHER_CTX_free'
/opt/hcc_arm64le/bin/../lib64/gcc/aarch64-target-linux-gnu/7.3.0/../../../../aarch64-target-linux-gnu/bin/ld: esys_crypto_ossl.c:(.text+0x361c): undefined reference to `EVP_aes_192_cfb128'
/opt/hcc_arm64le/bin/../lib64/gcc/aarch64-target-linux-gnu/7.3.0/../../../../aarch64-target-linux-gnu/bin/ld: esys_crypto_ossl.c:(.text+0x3640): undefined reference to `EVP_DecryptUpdate'
/opt/hcc_arm64le/bin/../lib64/gcc/aarch64-target-linux-gnu/7.3.0/../../../../aarch64-target-linux-gnu/bin/ld: esys_crypto_ossl.c:(.text+0x368c): undefined reference to `EVP_DecryptFinal'
collect2: error: ld returned 1 exit status
Makefile:10907: recipe for target 'src/tss2-esys/libtss2-esys.la' failed
make: *** [src/tss2-esys/libtss2-esys.la] Error 1
