### ISSUE TITLE
Replace tpmclient ABI version tests with unit tests

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#239]
The AbiVersionTest function in tpmclient: https://github.com/01org/TPM2.0-TSS/blob/master/test/tpmclient/tpmclient.cpp#L6941 is another prime candidate for unit-test-ification. These tests effectively make sure that the Tss2_Sys_Initialize function returns the expected error codes for bad parameters. They're really already unit tests, they just roll up into all the other tests in this 8KLOC program. Breaking these out into a set of unit tests specific to the Tss2_Sys_Initialize function would make the world a better place.

**Comment by flihp** [comment]
This should include the SysInitializeTests as well.

**Comment by AndreasFuchsSIT** [comment]
Closed as of #481 if I'm not mistaken...
