### ISSUE TITLE
test fail under musl: /test/unit/fapi-io.c:41:6: error: storage size of 'mock_stream' isn't known

### ISSUE THREAD

**Issue by salahcoronya** [tpm2-software/tpm2-tss#2419]
The tests for fapi.io.c won't compile because FILE is an incomplete type under musl:

/var/tmp/portage/app-crypt/tpm2-tss-3.2.0-r3/work/tpm2-tss-3.2.0/test/unit/fapi-io.c:41:6: error: storage size of 'mock_stream' isn't known
   41 | FILE mock_stream; /**< stream will be used to activate wrapper.*/
      |      ^~~~~~~~~~~

**Comment by williamcroberts** [comment]
I'm surprised that ever worked, FILE should always be assumed to be opaque and pointers can be made. Patch incoming.
