### ISSUE TITLE
TSS2_BASE_RC_BAD_TEMPLATE error when running Tss2_Sys_Startup

### ISSUE THREAD

**Issue by marincovic** [tpm2-software/tpm2-tss#2421]
Hello team,

I am trying to run the Tss2_Sys_Startup command in Windows but my TSS2_RC is 40:0x400. I have tried to figure what might be a problem but I can not find any information.
By 
Could you please provide the reason why this error code is given

Thank you in advance!
Best regards!

**Comment by williamcroberts** [comment]
> Hello team,
> 
> I am trying to run the Tss2_Sys_Startup command in Windows but my TSS2_RC is 40:0x400. 

This looks like you ran it through `tpm2_rc_decode` and it didn't come back with anything. Is that correct?

> I have tried to figure what might be a problem but I can not find any information. By Could you please provide the reason why this error code is given
> 
> Thank you in advance! Best regards!

I think startup is blocked by the TBS. Here's some information where perhaps you can figure that out:
https://learn.microsoft.com/en-us/windows/win32/tbs/command-blocking

**Comment by marincovic** [comment]
> > Hello team,
> > I am trying to run the Tss2_Sys_Startup command in Windows but my TSS2_RC is 40:0x400.
> 
> This looks like you ran it through `tpm2_rc_decode` and it didn't come back with anything. Is that correct?

Yes. I did a bit of a deep dive, followed the code to the exact point it "fails". The issue occurs in Tss2_Sys_Execute.c when doing
Tss2_MU_UINT32_Unmarshal(ctx->cmdBuffer,
                                    ctx->maxCmdSize,
                                    &ctx->nextData,
                                    &ctx->rsp_header.responseCode); 
in line 133 (last unmarshal of Tss2_Sys_ExecuteFinish) it looks like the response code in rsp_header.responseCode changes to the value **2150106112**. The issue happens when the command buffer is se to **0x000001ca31a0b0d0** (value as decimal **128**). 
> > I have tried to figure what might be a problem but I can not find any information. By Could you please provide the reason why this error code is given
> > Thank you in advance! Best regards!
> 
> I think startup is blocked by the TBS. Here's some information where perhaps you can figure that out: https://learn.microsoft.com/en-us/windows/win32/tbs/command-blocking
I was unable to remove the blocked command list but I was able to set the **IgnoreDefaultList** and **IgnoreLocalList** to enabled. This did not change the rsp_header.responseCode value.

**Comment by williamcroberts** [comment]
> > > Hello team,
> > > I am trying to run the Tss2_Sys_Startup command in Windows but my TSS2_RC is 40:0x400.
> > 
> > 
> > This looks like you ran it through `tpm2_rc_decode` and it didn't come back with anything. Is that correct?
> 
> Yes. I did a bit of a deep dive, followed the code to the exact point it "fails". The issue occurs in Tss2_Sys_Execute.c when doing Tss2_MU_UINT32_Unmarshal(ctx->cmdBuffer, ctx->maxCmdSize, &ctx->nextData, &ctx->rsp_header.responseCode); in line 133 (last unmarshal of Tss2_Sys_ExecuteFinish) it looks like the response code in rsp_header.responseCode changes to the value **2150106112**. The issue happens when the command buffer is se to **0x000001ca31a0b0d0** (value as decimal **128**).
> 
> > > I have tried to figure what might be a problem but I can not find any information. By Could you please provide the reason why this error code is given
> > > Thank you in advance! Best regards!
> > 
> > 
> > I think startup is blocked by the TBS. Here's some information where perhaps you can figure that out: https://learn.microsoft.com/en-us/windows/win32/tbs/command-blocking
> 
> I was unable to remove the blocked command list but I was able to set the **IgnoreDefaultList** and **IgnoreLocalList** to enabled. This did not change the rsp_header.responseCode value. While googling the return code it looks like that the command is still blocked. Do you have any recommendations?

I do not, I almost never touch windows.

**Comment by marincovic** [comment]
Hello,
I have found the issue. It looks like that windows started the TPM and when startup command was given it threw an error.
Get clock passed without a problem.

Thank you for your support,
BR

**Comment by williamcroberts** [comment]
> Hello, I have found the issue. It looks like that windows started the TPM and when startup command was given it threw an error. Get clock passed without a problem.
> 
> Thank you for your support, BR

That makes sense, if your running with an RM an RM almost always issues the startup command. Windows must catch that and throw an error.
