### ISSUE TITLE
tss2_provision raises an error

### ISSUE THREAD

**Issue by fansari** [tpm2-software/tpm2-tss#2424]
I have installed tpm2-tss-3.2.0-3.fc36.x86_64.

Now when I run "tss2_provision" it gives this error:

Fapi_Provision(0x6000B) - fapi:A parameter has a bad value

What can be wrong?

This is /etc/tpm2-tss/fapi-config.json:

```
{
     "profile_name": "P_ECCP256SHA256",
     "profile_dir": "/etc/tpm2-tss/fapi-profiles/",
     "user_dir": "~/.local/share/tpm2-tss/user/keystore",
     "system_dir": "/var/lib/tpm2-tss/system/keystore",
     "tcti": "",
     "system_pcrs" : [],
     "log_dir" : "/run/tpm2-tss/eventlog/"
}
```
Here the output of "tss2_getinfo -o -":
[tss2_getinfo.log](https://github.com/tpm2-software/tpm2-tss/files/9657839/tss2_getinfo.log)

**Comment by fansari** [comment]
[tss2_getinfo.log](https://github.com/tpm2-software/tpm2-tss/files/9657811/tss2_getinfo.log)

**Comment by JuergenReppSIT** [comment]
@fansari Are any other error messages displayed?
Could you please execute the provisioning as follows:
`TSS2_LOG=fapi+debug tss2_provision`

**Comment by fansari** [comment]
Please find here the logfile.
[tss2_provision_debug.log](https://github.com/tpm2-software/tpm2-tss/files/9664331/tss2_provision_debug.log)

**Comment by JuergenReppSIT** [comment]
@fanfari The persistent handle for the SRK which is defined in the profile P_ECCP256SHA256 already exists:
```ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:999:Fapi_Provision_Finish() ErrorCode (0x0006000b) SRK persistent handle already defined```
If the default profile is used it should be 0x81000001.
The TSS logging seems to be deactivated for the tools. So if the reason for an error is not obvious you could use:
`TSS2_LOG=all+error <tool command>`
to get more error related information.

**Comment by fansari** [comment]
When I run this command it displays:

```
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:999:Fapi_Provision_Finish() ErrorCode (0x0006000b) SRK persistent handle already defined
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:168:Fapi_Provision() ErrorCode (0x0006000b) Provision
Fapi_Provision(0x6000B) - fapi:A parameter has a bad value
```
This is what you told me. But now the question is: how do I fix this?

**Comment by fansari** [comment]
Yes it works now. Next step is to find out how to make this tss2_getrandom run as normal user.

I will try with tmpfiles.d as described here.

https://github.com/tpm2-software/tpm2-tss/blob/master/dist/tmpfiles.d/tpm2-tss-fapi.conf.in
