### ISSUE TITLE
bitbake get empty VERSION

### ISSUE THREAD

**Issue by BryanYangZL** [tpm2-software/tpm2-tss#2442]
https://github.com/flihp/meta-measured/tree/master/recipes-tpm/tpm2-tss
the tools will download 3.2.0 package into bitbake environment. It is not git repository, so `git describe --tags --always --dirty > VERSION`  in configure.ac will get a empty VERSION. It generate /lib/tss2-*.pc with empty version. cause pkg-config get a empty version.

**Comment by williamcroberts** [comment]
configure.ac is only invoked if you reconfigure the project with autoreconf, if you just use the generated configure script to configure project options that won't be invoked. However, the autreconf case was fixed in:
- master: 3e910b30bd926 --> target release of 4.0
- 3.2.x: 2eac8dfdd5376  --> target release of 3.2.1
-

**Comment by BryanYangZL** [comment]
we can't get correct VERSION file. becuase bootrap will create empty VERSION file in donwload tar.gz.

**Comment by williamcroberts** [comment]
> we can't get correct VERSION file. becuase bootrap will create empty VERSION file in donwload tar.gz.

How are you ascertaining the release tar.gz? You can't use github's archive feature you must download them from the releases section to get the dist tarball https://github.com/tpm2-software/tpm2-tss/releases. The release tarballs don't even contain a bootstrap script 
```bash
tar -tvf ~/Downloads/tpm2-tss-3.2.0.tar.gz | grep -i bootstrap
```
You unpack those and can run configure, the issue only arises if you need to run autoreconf, which is what happens in bootsrap.

**Comment by williamcroberts** [comment]
> Thank you. We can't download 3.2.x from https://github.com/tpm2-software/tpm2-tss/releases now. so when will 3.2.x release?

Can't you download 3.2.0 release tarball and just not run bootstrap or autoreconf? If you just run ./configure <options> it should work just fine?

https://github.com/tpm2-software/tpm2-tss/releases/download/3.2.0/tpm2-tss-3.2.0.tar.gz

**Comment by BryanYangZL** [comment]
Just run ./configure it should work fine.
