### ISSUE TITLE
FAPI Feature Request: Enable PolicySigned with a KEYEDHASH object. 

### ISSUE THREAD

**Issue by cplappert** [tpm2-software/tpm2-tss#2445]
My use case are interactions with resource-constrained devices (e.g., MCUs in an IoT network) that cannot afford to use public key cryptography. 

Implementation idea:
Because the KEYEDHASH has no public key, the prototype TSS2_RC (*Fapi_CB_Sign) should allow object name (e.g., path as hint) as parameter publicKey instead of the public PEM key. The verification of the returned HMAC should work without problems with TPM2_VerfifySignature with the symmetric key stored in the keystore.

**Comment by williamcroberts** [comment]
> Implementation idea: Because the KEYEDHASH has no public key, the prototype TSS2_RC (*Fapi_CB_Sign) should allow object name (e.g., path as hint) as parameter publicKey instead of the public PEM key. The verification of the returned HMAC should work without problems with TPM2_VerfifySignature with the symmetric key stored in the keystore.

Just to clarify, that means the symmetric key would be on disk (the keystore) in one environment and the key within the tpm in another environment?

**Comment by cplappert** [comment]
Yes. Two devices A and B are connected via network. Device A has a TPM and device B has no TPM (but some kind of other secure environment). Both devices share a common secret, the symmetric key (SK). An application key (AK) is secured via TPM policy with PolicySigned. To use AK, the PolicySigned-policy initiates a challenge-response scheme with device B. B uses SK to answer the challenge and the TPM verifies the response with SK. On success, the TPM unlocks AK.
