### ISSUE TITLE
SAPI/ESYS_GetCapability / TPMU_CAPABILITY unmarshalling for TPM2_CAP_VENDOR_PROPERTY harded to TPML_INTEL_PTT_PROPERTY

### ISSUE THREAD

**Issue by AndreasFuchsTPM** [tpm2-software/tpm2-tss#2449]
As I just learned, whenever TPM2_GetCapability is called for TPM2_CAP_VENDOR_PROPERTY the response is hardcoded to decode a TPML_INTEL_PTT_PROPERTY in the response.
If there was a second vendor who wanted to have their vendor-specific capabilities managed by tpm2-tss, that's currently not possible.

These are the relevant code paths:
https://github.com/tpm2-software/tpm2-tss/blob/9288970a3e657cdee85d08d3813199ec864de3ad/src/tss2-sys/api/Tss2_Sys_GetCapability.c#L78-L81
https://github.com/tpm2-software/tpm2-tss/blob/95b8a529af6671f464b67116766435960dfe7f03/src/tss2-mu/tpmu-types.c#L470-L482
https://github.com/tpm2-software/tpm2-tss/blob/8e64f13a1ecb95fead3b1b6d260d9a2d83008b2e/include/tss2/tss2_tpm2_types.h#L1222-L1237

The problem is now that I don't know how we could change the API in order to support vendor-specific capabilities for multiple vendors.

The only idea I currently have is to have change the member of TPMU_CAPABILITIES to something like TPMT_PROPERTIES_VENDOR which in turn would have the UINT32 Vendor String as selector and another union for the different vendors.
For Esys, ESYS could go ahead and query the Vendor string. For SAPI this would be less good, because we cannot make two requests to this.
Maybe a third entry to the TPMT_PROPERTIES_VENDOR could be a TPM2B with the plain bytes if the selector is empty and SAPI would only fill this in whereas ESYS could then further decode to each of the vendor string.

**Comment by williamcroberts** [comment]
Why wouldn't anything vendor specific just return something like TPM2B_MAX_BUFFER and then the caller decides how to unmarshal it?

**Comment by AndreasFuchsTPM** [comment]
I guess this would move things from libtss2-esys to the tpm2 tools and/or pytss and others, right ?

Even then, I'd have to add some #defines to the types header for use in the "property" parameter, but that would be ok I guess.

However, esys seems a bit nicer from my point of view, since it would deduplicate the parsing of the returned buffer rather than having tools and pytss to do it.
Also note that currently the ptt capabilities are also returned by the Fapi-GetInfo function.

P.S. In either case its an API/ABI change, that's why we need to add it to 4.0

**Comment by williamcroberts** [comment]
> I guess this would move things from libtss2-esys to the tpm2 tools and/or pytss and others, right ?
Yep

> P.S. In either case its an API/ABI change, that's why we need to add it to 4.0
Yeah i'd like to get as many breaking things into this major release.

**Comment by AndreasFuchsTPM** [comment]
So the proposal on the table is to just use TPM2B_MAX_BUFFER inside the union and to remove the type TPML_INTEL_PTT_PROPERTY from headers, sapi, esys and fapi_getinfo ?
If that's ok, I'll start drafting a PR

**Comment by williamcroberts** [comment]
> So the proposal on the table is to just use TPM2B_MAX_BUFFER inside the union 
Just this, general commands should be vendor agnostic.

> and to remove the type TPML_INTEL_PTT_PROPERTY from headers, sapi, esys and fapi_getinfo ?
If that's ok, I'll start drafting a PR

We've discussed adding a vendor extension for commands, so I would move types and defines to whatever convention were going to follow for vendors and we can even implement the intel getcap call as the first vendor extension. This should lay the groundwork for whomever needs to add their stuff :-p

**Comment by AndreasFuchsTPM** [comment]
> We've discussed adding a vendor extension for commands, so I would move types and defines to whatever convention were going to follow for vendors and we can even implement the intel getcap call as the first vendor extension. This should lay the groundwork for whomever needs to add their stuff :-p

Do I understand this correctly that we will have `Esys_GetCapability()` with just a TPM2B and then we would have a `Esys_INTL_GetCapabilityVendor()` to return e.g. the PTT stuff and a `Esys_IFX_GetCapabilityVendor()` to return IFX's stuff ?

**Comment by williamcroberts** [comment]
> > We've discussed adding a vendor extension for commands, so I would move types and defines to whatever convention were going to follow for vendors and we can even implement the intel getcap call as the first vendor extension. This should lay the groundwork for whomever needs to add their stuff :-p
> 
> Do I understand this correctly that we will have `Esys_GetCapability()` with just a TPM2B and then we would have a `Esys_INTL_GetCapabilityVendor()` to return e.g. the PTT stuff and a `Esys_IFX_GetCapabilityVendor()` to return IFX's stuff ?

The TPMU_CAPABILITIES union should have a vendor data field that would be a generic TPM2B. Then the vendor versions like Esys_IFX_GetCapabilityVendor and Esys_INTL_GetCapabilityVendor could have their own specific structures and marshal from that TPM2B into the appropriate field.

**Comment by williamcroberts** [comment]
@AndreasFuchsTPM what's your status on this? As of right now, this is our final 4.0 ticket. I was hoping to start the 4.0 release process next week.
