### ISSUE TITLE
CEL events for PCR 0 is included when Fapi_PcrRead is called for other PCR

### ISSUE THREAD

**Issue by whooo** [tpm2-software/tpm2-tss#2454]
In some tpm2-pytss tests we call Fapi_PcrRead with a PCR > 0, but with latest master all CEL events for PCR 0 are included in the response

**Comment by whooo** [comment]
I should mention that this affects Fapi_Quote as well

**Comment by williamcroberts** [comment]
@JuergenReppSIT I have no idea what to do with this, could you help out?

**Comment by JuergenReppSIT** [comment]
Only events which do not change PCR 0  (e.g. CEL management events) are included if PCR 0 is not in the PCR list. They are related to the firmware events.
@AndreasFuchsTPM If the PCR selection produces a list without firmware events, should we omit these events?

**Comment by whooo** [comment]
I see the EV_NO_ACTION firmware log header as well unless I disable the firmware log parsing

**Comment by JuergenReppSIT** [comment]
yes that's the SPECID event which also is not extended to PCR0.
@AndreasFuchsTPM @whooo @williamcroberts or should we omit all these events if PCR0 is not selected?

**Comment by williamcroberts** [comment]
> @AndreasFuchsTPM @whooo @williamcroberts or should we omit all these events if PCR0 is not selected?

I am not familiar enough with that API to have any reasonable answer, im assuming we're talking about the log file that comes in through the `char **pcrLog` argument?

**Comment by whooo** [comment]
I don't think the SpecID and firmware end events should be included, unless PCR 0 is requested as they are only used when looking at at firmware events.
Perhaps the CEL version event should only be included if the response contains other CEL events? If an application extends for example PCR 23 with it's own data and then requests the events for that does the version event make sense?
