### ISSUE TITLE
EvicControl returns persistent handle on 0x40 when TPMI_DH_PERSISTENT = TPM2_PERSISTENT_FIRST

### ISSUE THREAD

**Issue by marincovic** [tpm2-software/tpm2-tss#2476]
Hello team,

I have a issue when running the Esys_EvictControl on primary key and on a Created RSA key.
When I give the following function:
```
returnCode = Esys_EvictControl(SystemContext,
		ESYS_TR_RH_OWNER,
		SRK,
		HMACSession,
		ESYS_TR_NONE,
		ESYS_TR_NONE,
		persistantHandel,
		SRK_PersistantHandle);
```

where 

`	TPMI_DH_PERSISTENT persistantHandel = TPM2_PERSISTENT_FIRST + this->PV_CapabilatyData->data.handles.count;
`

my SRK_PersistantHandle = 1073746251 even thou I am working on OWNER.
Also When I get the Capability I can see that there is a new handle in the owner but whenever I use it it says
`The error code is: 458776. The decoded value is: esapi:The ESYS_TR resource object is bad`

BR//
Marin

**Comment by JuergenReppSIT** [comment]
Does this error occur in the current Esys SystemContext?
If not you have to use the following call to get a new Esys handle:
```
 r = Esys_TR_FromTPMPublic(ectx, persitantHandel,
                              ESYS_TR_NONE, ESYS_TR_NONE, ESYS_TR_NONE,
                              &esys_handle);
```

**Comment by marincovic** [comment]
Hello,

I figured it out. When I was saving the handle I was just saving the value I did not Serialize/Deserialize it.
Once I started doing that I was able to use the handle without a problem.

BR//
Marin
