### ISSUE TITLE
Off-topic: Maximum number of write cycles for nvwrite for SLB9670?

### ISSUE THREAD

**Issue by capiman** [tpm2-software/tpm2-tss#2480]
Does someone know if the number of write cycles in anywhere mentioned in a document for the Infineon SLB9670?
I assume it is similar to an EEPROM/Flash and not infinite?
Or if not mentioned, has someone experience exhausting it? What is then happening? Is it just getting unreliable?
Or is there perhaps even a check/status bit when the maximum write cycles are reached and which I can read back?
Or does someone know a better place to ask or look?

**Comment by AndreasFuchsTPM** [comment]
The operating and effective lifetime can be seen in the datasheet on the website for the given usage profile.
Note that it is not just reads and writes, but also temperature, uptime and other factors that influence lifetime. Therefore, you cannot just get number of read/writes for TPMs.

If you have more detailed inquiries, try to contact sales or support directly.
Hope this helps.

**Comment by capiman** [comment]
Many thanks for your helpful answer!

I also got an answer from Infineon, which I want to share:

https://community.infineon.com/t5/OPTIGA-TPM/Maximum-number-of-write-cycle-to-NVRAM-of-SLB9670/m-p/381537/emcs_t/S2h8ZW1haWx8dG9waWNfc3Vic2NyaXB0aW9ufExBSEpPQUhFNlU2WUJFfDM4MTUzN3xTVUJTQ1JJUFRJT05TfGhL#M185
