### ISSUE TITLE
Inform downstreams of .so version update on 4.0 release

### ISSUE THREAD

**Issue by AndreasFuchsTPM** [tpm2-software/tpm2-tss#2483]
This is a collection thread for informing users of the .so version changes.
This affects everyone who dlopens our libraries, such as systemd.

**Comment by poettering** [comment]
Any chance you could list the expected API changes? (i.e. just prototype before/after would suffice for me)

**Comment by AndreasFuchsTPM** [comment]
The change is:
```diff
include/tss2/tss2-tpm2-types.h

/* Definition of a non-TPM standard buffer object for use in a TPMU_CAPABILITIES
   for vendor specific capabilities */

typedef struct TPM2B_MAX_CAP_BUFFER TPM2B_MAX_CAP_BUFFER;
struct TPM2B_MAX_CAP_BUFFER {
    UINT16 size;
    BYTE buffer[TPM2_MAX_CAP_BUFFER];
};

/* Definition of TPMU_CAPABILITIES Union <OUT> */
typedef union TPMU_CAPABILITIES TPMU_CAPABILITIES;
union TPMU_CAPABILITIES {
@@ -1223,7 +1232,7 @@ union TPMU_CAPABILITIES {
    TPML_ECC_CURVE eccCurves;
    TPML_TAGGED_POLICY authPolicies;
    TPML_ACT_DATA actData;
    TPML_INTEL_PTT_PROPERTY intelPttProperty;
    TPM2B_MAX_CAP_BUFFER vendor;
};
```

This influences:
```
Tss2_Sys_GetCapability{,_Complete}()
Esys_GetCapability{,_Finish}()
Tss2_MU_TPMU_CAPABILITY_{Marshal,Unmarshal}()
Tss2_MU_TPMS_CAPABILITY_{Marshal,Unmarshal}()

All only for capability == TPM2_CAP_VENDOR;
```

Regarding FAPI (does not concern systemd):
The change is in `Fapi_Quote()` and `Fapi_PcrRead` regarding the `eventLog` return parameter

**Comment by williamcroberts** [comment]
> This is a collection thread for informing users of the .so version changes. This affects everyone who dlopens our libraries, such as systemd.

Do we need to bump the so version, I don't think their is an ABI break. The union is not getting smaller, I guess old callers on linked to a new library, are the intel ptt properties still sane?

> Any chance you could list the expected API changes? (i.e. just prototype before/after would suffice for me)
@poettering see: https://github.com/tpm2-software/tpm2-tss/pull/2478

The TPMU_CAPABILITIES union changes. It was coded that all vendor properties are PTT properties. Systemd doesn't use intelPttProperty field, so I don't see any worries on systemd.

**Comment by poettering** [comment]
but what exactly do you change on that union? if you just add another union field or fields at the end of the fields it shouldn't matter?

**Comment by williamcroberts** [comment]
> but what exactly do you change on that union? if you just add another union field or fields at the end of the fields it shouldn't matter?

Remove one and add a bigger one, the field intelPttProperty goes away and a new one is added.

**Comment by AndreasFuchsTPM** [comment]
So I guess I have a wrong understanding of ABI-breaks then...
I was assuming that sematic changes would also lead to .so major changes...

If this is not the case, then I guess I can revert all the .so major bumps from the PR and we are fine ?

Question: Do we need the TPMU_CAPABILITIES keep the same sizeof() as before ? If so, I could make the TPM2B_MAX_CAP_BUFFER smaller for this...

**Comment by williamcroberts** [comment]
> Question: Do we need the TPMU_CAPABILITIES keep the same sizeof() as before ? If so, I could make the TPM2B_MAX_CAP_BUFFER smaller for this...

No bigger is OK

**Comment by AndreasFuchsTPM** [comment]
> The question is, do we mess with ABI version for code that can't possible exist? My vote is no.

I'd be happy with this

**Comment by JuergenReppSIT** [comment]
> The question is, do we mess with ABI version for code that can't possible exist? My vote is no.

My vote is also no.

**Comment by williamcroberts** [comment]
@AndreasFuchsTPM I think we also just remove these c7d99a3b8132bb366ddd040657d160381fb330cc, might as well get rid of the unused structures and MU routines for 4.0

**Comment by williamcroberts** [comment]
Looking at https://www.gnu.org/software/libtool/manual/libtool.html#Updating-version-info it looks like we should bump c and r values, see below. But it looks like we need to be more conscious of changing soname on releases.

Here are a set of rules to help you update your library version information:

Start with version information of ‘0:0:0’ for each libtool library.
Update the version information only immediately before a public release of your software. More frequent updates are unnecessary, and only guarantee that the current interface number gets larger faster.
**If the library source code has changed at all since the last update, then increment revision (‘c:r:a’ becomes ‘c:r+1:a’).**
**If any interfaces have been added, removed, or changed since the last update, increment current, and set revision to 0.**
If any interfaces have been added since the last public release, then increment age.
**If any interfaces have been removed or changed since the last public release, then set age to 0.**

**Comment by williamcroberts** [comment]
Ahh this is more clear:
```
The following explanation may help to understand the above rules a bit better: consider that there are three possible kinds of reactions from users of your library to changes in a shared library:

Programs using the previous version may use the new version as drop-in replacement, and programs using the new version can also work with the previous one. In other words, no recompiling nor relinking is needed. In this case, bump revision only, don’t touch current nor age.
Programs using the previous version may use the new version as drop-in replacement, but programs using the new version may use APIs not present in the previous one. In other words, a program linking against the new version may fail with “unresolved symbols” if linking against the old version at runtime: set revision to 0, bump current and age.
Programs may need to be changed, recompiled, and relinked in order to use the new version. Bump current, set revision and age to 0.
```

But since we're dropping broken functionality, I think I agree with @poettering and just do a revision bump on all sonames.

**Comment by williamcroberts** [comment]
So #2488 is my PR to handle all of this based of @AndreasFuchsTPM earlier work. The big parts are:
- bump sys, esapi and mu revision number (middle number) on soname
- Drop intel specific vendor field
- Add vendor agnostic field
- Add MU routines for new type
- Update mu routine for TPMU_CAPABILITIES for vendor field.
- fapi ignores vendor properties
- fix the magic my macros to handle 12 fields.

**Comment by williamcroberts** [comment]
The final verdict is:

| library   | release soname | new soname |
|-----------|----------------|------------|
| tss2-mu   | 0.0.0          | 0.1.0      |
| tss2-sys  | 1.0.0          | 1.1.0      |
| tss2-esys | 0.0.0          | 0.1.0      |

All other libraries stay on the same so version.
