### ISSUE TITLE
Symmetric private key generation using ESAPI APIs 

### ISSUE THREAD

**Issue by shekharpaty** [tpm2-software/tpm2-tss#2494]
GE Team,
I was going through the ESAPI APIs , I have hosted the TPM simulator on my Ubuntu 22 desktop and trying to generate the symmetric private key from one C program and use the same key for encryption and decryption simple text.

So far I went through this example [https://github.com/tpm2-software/tpm2-tss/blob/master/test/integration/esys-rsa-encrypt-decrypt.int.c]

And I did small compilation  using -ltss2-esys the code and environment looks fine.

If the one private key I am able to generate from ESAPI , where the key will be stored? I mean which path?

 /* Alternative for simulator */
    // char *name = "mssim:host=127.0.0.1,port=2321";  ?   where I can view the key I have simulator , no Hardware TPM usage as if now.

**Comment by williamcroberts** [comment]
If you create a key using the Esys_CreatePrimary or Esys_Create APIs it is not stored at a path. Esys_CreatePrimary has no way to store a key. Given the same inputs, you get the same key context back, ESYS_TR each time. For Esys_Create. their are two keyblobs TPM2B_PUBLIC and a TPM2B_PRIVATE that you may use in Esys_Load to load that key into the TPM and you can save those key blobs wherever you like.

I would **strongly urge** you, to use the Feature API aka FAPI. This handles key storage of those blobs, automatic encrypted sessions and a host of other features to prevent "gotchya" scenarios. ESAPI is a great API, but it should only be used in situations requiring absolute full control of the TPM.

**Comment by shekharpaty** [comment]
Thankyou, I went through quick usage  of FAPI  [(and](https://github.com/tpm2-software/tpm2-tss/blob/29c46f0d27942146a909f7f12c0f8f65c45bec93/test/integration/fapi-data-crypt.int.c) see we need to load json policy based settings, and I see there are two default  policies in ( /etc/tpm2-tss/fapi-profiles) I can change them according to my requirement yes! please can I get to know is it possible using FAPI to generate symmetric key , one C program for symmetric key generation and another C program for encrypting the plain text using same symmetric private key and for decryption also the same key using the out Cipher from Fapi_Encrypt. I am learning the security concepts and using CNG Ncrypt.h I can do the previous operations successfully, with TPM i am curious to explore.

**Comment by williamcroberts** [comment]
> Thankyou, I went through quick usage of FAPI [(Sample code of FAPI here and I see](https://github.com/tpm2-software/tpm2-tss/blob/29c46f0d27942146a909f7f12c0f8f65c45bec93/test/integration/fapi-data-crypt.int.c) we need to load json policy based settings, and I see there are two default policies in ( /etc/tpm2-tss/fapi-profiles) 

See "man fapi-profile"

Those are profiles, which describe at a high level how you want to use and configure your TPM. I would just use the default that FAPI installs. If you need to tweak it go ahead, but start with something that is known to work. On you system, make sure command line tool (part of tpm2-tools) tss2_initialize OR the C variant Fapi_Initialize() works.

Policies are different, When you see policy it means using a policy to authorize the use of an object. The TPM provides two ways of authenticating to an object, policy and password.

> I can change them according to my requirement yes!

Yes, again i'd start with a known good config and tweak from there.

> please can I get to know is it possible using FAPI to generate symmetric key ,
No, theirs no point for two reasons:
1. The TPM is slow and isn't good for bulk encryption using something like AES
2. Most TPMs don't support the Encrypt/Decrypt interface to use an AES key directly

The way you do this is to generate an AES key and use Fapi_CreateSeal() to seal that key to that TPM and then you use
Fapi_Unseal to retrieve it. Fapi will ensure that an encrypted tunnel is established with the TPM so no one can see your key in flight. You can use any mechanism you want to generate the key, you could even use Fapi_GetRandom as an entropy source for generating your AES key.

> one C program for symmetric key generation and another C program for encrypting the plain text using same symmetric private key and for decryption also the same key using the out Cipher from Fapi_Encrypt. I am learning the security concepts and using CNG Ncrypt.h I can do the previous operations successfully, with TPM i am curious to explore.

Once you unseal the AES key from the TPM, you can use them in any software library you would like to perform the encryption and decryption.

**Comment by shekharpaty** [comment]
Sure let me just start with FAPI programs, it fits, will soon post the updated results and make sure we will close this thread ASAP.

**Comment by JuergenReppSIT** [comment]
@shekharpaty I could reproduce your commands without errors with tpm2_tss Version 3.2.0.  
Which version are you using?  and is 0x81000001 the output of the command:
`tss2_gettpm2object -p /SRK -c-`
This command should display the TPM handle of the SRK which is used as tpmKey for StartAuthSession.

**Comment by shekharpaty** [comment]
@JuergenReppSIT  please find the version 3.2.0-151-g10a5e226

**Comment by JuergenReppSIT** [comment]
@shekharpaty Can you create and use a session with the tpm2 tools using the SRK as tpmKey?
`tpm2_startauthsession --hmac-session -c 0x81000001 -S /tmp/session.ctx`
`tpm2_create -S /tmp/session.ctx -C 0x81000001 -o /tmp/test-key.ctx`
If that works could you please attach the SRK file from the object store:
`P_ECCP256SHA256/HS/SRK/object.json`
in the directory you get with:
`tss2_getinfo -o-| grep system_di`r

**Comment by shekharpaty** [comment]
Something would have been changed, I am valdating it.

amp@amp-virtual-machine:~/FAPI_CODE$ tpm2_startauthsession --hmac-session -c 0x81000001 -S /tmp/session.ctx
ERROR:esys:src/tss2-esys/api/Esys_ReadPublic.c:324:Esys_ReadPublic_Finish() Received a non-TPM Error 
ERROR:esys:src/tss2-esys/esys_tr.c:278:Esys_TR_FromTPMPublic_Finish() Error ReadPublic ErrorCode (0x000a000a) 
ERROR:esys:src/tss2-esys/esys_tr.c:398:Esys_TR_FromTPMPublic() Error TR FromTPMPublic ErrorCode (0x000a000a) 
ERROR: Esys_TR_FromTPMPublic(0xA000A) - tcti:IO failure
ERROR: Unable to run tpm2_startauthsession

**Comment by shekharpaty** [comment]
I see the metadata is created in HS/SRK folder , these are my operations,
echo 'hello world' > secrets.txt
-->openssl rand 128 > symmetric_keyfile.key
-->openssl enc -in secrets.txt -out secrets.txt.enc -e -aes256 -k symmetric_keyfile.key
-->tss2_createseal --path=HS/SRK/sealed_key --authValue="" --type="noDa" --data="symmetric_keyfile.key"

I have the query here please help me to understand the  concept of sealing and unsealing.
I have symmetric_keyfile.key , with this key I can decrypt the secrets.txt.enc using openssl , so what is advantage of using the tss2_createseal? still symmetric_keyfile.key is there for me to use , how to hide this or store in TPM?
How unsealing hides the key? what is the end use? am i using the sealing and unsealing properly to keep my key secured.

**Comment by shekharpaty** [comment]
Thankyou Team, I am able to find the use case for the tss2_unseal and I have deleted the key in my local folder and using the tss2_unseal I retrieved back the key and decrypted my text using openssl.

Next goal is to programmatically prove the use case of symmetric key generation using Openssl and seal it using the FAPI API and then unseal the key and decrypt the data again using FAPI api.
