### ISSUE TITLE
Add AC Range into iesys_handle_to_tpm_handle and ensure builder macro exists

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tss#2495]
- [x] Add the AC range to iesys_handle_to_tpm_handle and ensure a test is there for it, Theirs an ESYS routine called Esys_TR_GetTpmHandle that should do it.
- [x] Make sure the macro ESYS_TR_RH_AC exists and make a note if we need to add it to spec, use in the test. Follow ACT tests for examples.
- [x] Call Esys_TR_GetName to make sure a name is returned. The name should be the handle number as a string. Ie ESYS_TR.OWNER maps to 0x40001, so it returns a TPM2B_DIGEST of size 4 with bytes `0x04, 0x00, 0x00, 0x01`.
- [x] Check that the ACT handles, do the same test for GetName that is being done for `_AC_` handles for `_ACT_` handles.

**Comment by malikabhi05** [comment]
#2496
