### ISSUE TITLE
Error code 2150106112 when trying to send a Esys_EncryptDecrypt2

### ISSUE THREAD

**Issue by marincovic** [tpm2-software/tpm2-tss#2499]
Hello,

When I use Esys_EncryptDecrypt2 or Esys_EncryptDecrypt I get the error 2150106112 which from my understanding means that this command is blocked from TBS. I have tested almost all commands and this is the only one that is being blocked.
I removed all registry information in regards to the restrictions. So I have no idea what is stopping me from encrypting information.

BR//
Marin Covic

**Comment by williamcroberts** [comment]
Yeah that looks like Windows blocking you. I don't really use Windows so I don't have much advice other than tweaking the registry settings.
```
tpm2 rc_decode 2150106112
40:0x400
```
