### ISSUE TITLE
ESAPI: extra nonceTPM parameter

### ISSUE THREAD

**Issue by IKhanov** [tpm2-software/tpm2-tss#2515]
According to the latest version of [ESAPI specification](https://trustedcomputinggroup.org/wp-content/uploads/TSS_ESAPI_v1p0_r14_pub10012021.pdf) there's no `nonceTPM` parameter for `Esys_*` commands except `Esys_TRSess_GetNonceTPM`:

1. For `Esys_PolicySigned`
```
TSS2_RC
Esys_PolicySigned(
    ESYS_CONTEXT *esysContext,
    ESYS_TR authObject,
    ESYS_TR policySession,
    ESYS_TR shandle1,
    ESYS_TR shandle2,
    ESYS_TR shandle3,
    const TPM2B_NONCE *nonceTPM,
    const TPM2B_DIGEST *cpHashA,
    const TPM2B_NONCE *policyRef,
    INT32 expiration,
    const TPMT_SIGNATURE *auth,
    TPM2B_TIMEOUT **timeout,
    TPMT_TK_AUTH **policyTicket)
{
...
```

2. For `Esys_PolicySecret`:
```
TSS2_RC
Esys_PolicySecret(
    ESYS_CONTEXT *esysContext,
    ESYS_TR authHandle,
    ESYS_TR policySession,
    ESYS_TR shandle1,
    ESYS_TR shandle2,
    ESYS_TR shandle3,
    const TPM2B_NONCE *nonceTPM,
    const TPM2B_DIGEST *cpHashA,
    const TPM2B_NONCE *policyRef,
    INT32 expiration,
    TPM2B_TIMEOUT **timeout,
    TPMT_TK_AUTH **policyTicket)
{
...
```

`const TPM2B_NONCE *nonceTPM` should not be there. Please, correct me if I'm wrong.

**Comment by AndreasFuchsTPM** [comment]
I'm thinking right now, if we added the nonceTPM for a good reason here to be honest.

I think the idea is to get the nonceTPM from the session, then do you calculation and then add it here in the call.
Maybe @JuergenReppSIT still remembers.

Also @idesai I think you asked for ESYS_TR_GetTPMNone in the first place for his use case ? Do you know ?

**Comment by AndreasFuchsTPM** [comment]
@IKhanov Also please note, that in the ESAPI spec, Sections 9 and 10 are normative. Section 11 is only informative.
If I see things correctly here, then Section 9+10 contradict Section 11 here.

And tpm2-tss complies with Section 9+10.

I know that this is somewhat counter-intuitive, but from a compliance perspective, tpm2-tss would be correct here.

**Comment by williamcroberts** [comment]
> I'm thinking right now, if we added the nonceTPM for a good reason here to be honest.

That I don't know, my guess is it was just a copy + paste error from SAPI function signature. But I've also convinced myself of two arguments below:

The case for keeping the nonceTPM parameter is that
1. ESAPI provides quasi "full control". 
2. Section 23.2 describes uses of using NULL versus a set nonceTPM https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p59_Part3_Commands_pub.pdf

The case for removing it is:
1. this is 4.0 id rather not have a 5.0. 
4. simplifying the interface is always a win.
5. Auditing users of the function shows most passing NULL or the current tpm

> Also @idesai I think you asked for ESYS_TR_GetTPMNone in the first place for his use case ? Do you know ?

It's called and immediately passed to PolicySecret unmodified.

> @IKhanov Also please note, that in the ESAPI spec, Sections 9 and 10 are normative. Section 11 is only informative. If I see things correctly here, then Section 9+10 contradict Section 11 here.
> 
> And tpm2-tss complies with Section 9+10.

Theirs nothing in sections 9 and 10 specifically covering or I guess not covering to your point, the PolicySigned and PolicySecret interfaces.

> 
> I know that this is somewhat counter-intuitive, but from a compliance perspective, tpm2-tss would be correct here.

Yes since the signature isn't specifically covered.

On another note, SAPI allows for NULL which sets a flag decryptNull which is never used AFAICT and just serializes a 0 for the size parameter in the TPM2B_NONCE parameter.

**Comment by IKhanov** [comment]
> ... from a compliance perspective, tpm2-tss would be correct here.

Yes, indeed, but I guess it brings some mess here. It's not clear why that parameter is needed (at least by reading its code and comparing it to the spec), because `Esys_StartAuthSession` does not include `nonceTPM` output parameter (see #1021), so it's needed to call `Esys_GetTPMNonce` to receive it and pass to the function (what for).

From ESAPI spec for `Esys_StartAuthSession`:
> - store the response parameter tpmNonce in the ESys_TR ‘sessionHandle’

So, `Esys_PolicySecret` or `Esys_PolicySigned` can do automatically what section 23.2 describes of the Part 3 spec as @williamcroberts mentioned above.

>ESAPI provides quasi "full control".

Providing quasi "full control" is a SAPI's job. tss2-esys does what that section describes - it passes `policySession->nonceTPM` to the SAPI level  and then SAPI should do its work, doesn't it?

**Comment by williamcroberts** [comment]
>> ESAPI provides quasi "full control".

> Providing quasi "full control" is a SAPI's job. tss2-esys does what that section describes - it passes policySession->nonceTPM to the SAPI level and then SAPI should do its work, doesn't it?

Yes and no. So the nonceTPM parameter exists in TPM2_PolicySigned so the (per the [command spec](https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p59_Part3_Commands_pub.pdf), "the nonceTPM 
parameter from the TPM2_StartAuthSession() response. If the authorization is not limited to this session, the size of this value is zero."

By quasi full control, ESAPI shouldn't prevent a TPM feature. Contrast this to design decisions in FAPI where for the simplicity of the API certain features were ignored.

**Comment by williamcroberts** [comment]
> Anyway, Why can't ESAPI distinguish those cases, especially by verifying `shandle{1,2,3}` and check if we have password/policy/hmac/other authorizations or so? Looks like ESAPI has enough information to hide `nonceTPM`.

Because weather or not to add nonceTPM determines the authorization scope and only the policy author knows the scope. Also, it doesn't have the 3 session handles like typical commands, not like that would help anyways .

**Comment by williamcroberts** [comment]
> > Because weather or not to add nonceTPM determines the authorization scope and only the policy author knows the scope. Also, it doesn't have the 3 session handles like typical commands, not like that would help anyways .
> 
> Ok, I got it, thanks! What about the spec itself? I understand that headers are just informative/recommendations, but according to your comments it seems that the spec has a kinda mistake (not including `nonceTPM`), because ESAPI cannot predict or does automatically manipulations of `nonceTPM` for those functions?

Correct.

> 
> > I would be against a merge and a quick update to the TCG specs (removal of headers).
> 
> Will you plan to update the spec?

Yes. We also plan on removing all the C code from the specs, that is in the spec do to legacy reasons. I'm going to close this issue, but if you have any more questions or comments, just post them.
