### ISSUE TITLE
`--disable-fapi` not working properly in v4.0.0 breaking Windows MinGW-w64 builds

### ISSUE THREAD

**Issue by brechtsanders** [tpm2-software/tpm2-tss#2528]
When building version 4.0.0 on Windows for Windows using MinGW-w64 GCC build fails because of issues in fapi sources, even though `--disable-fapi` was specified.

I was able to build version 3.2.1 just fine before.

**Comment by JuergenReppSIT** [comment]
> When building version 4.0.0 on Windows for Windows using MinGW-w64 GCC build fails because of issues in fapi sources, even though `--disable-fapi` was specified.

Could you please try configure with `--disable-fapi --disable-policy`. With 4.0  a policy library that exposes the internal FAPI policy engine was introduced.

**Comment by brechtsanders** [comment]
Yes, that works right away, thanks!

Is FAPI something that will be supported on Windows too, or is it not needed there?

**Comment by williamcroberts** [comment]
> Yes, that works right away, thanks!
> 
> Is FAPI something that will be supported on Windows too, or is it not needed there?

I think it would just be a matter of fixing up any platform specific code.
