### ISSUE TITLE
TPM FAPI sealing data inside /dev

### ISSUE THREAD

**Issue by shekharpaty** [tpm2-software/tpm2-tss#2532]
I am using TPM simulator in my local VM to test FAPI API and able to seal the important data inside directory ` ~/.local/share/tpm2-tss/user/keystore ` as per the path mentioned in config file ` /etc/fapi-config.json`
`"profile_dir": "/usr/local/etc/tpm2-tss/fapi-profiles/",`
`"user_dir": "~/.local/share/tpm2-tss/user/keystore",`
`"tcti": "",`
`"ek_cert_less" : "yes"`

after some trial runs I will play with hardware TPM where /dev/tpm0 will be available, I have query regarding /dev/tpm0 do we need to change the "user_dir": "~/.local/share/tpm2-tss/user/keystore" to "user_dir": "/dev/tpm0" in /etc/fapi-config.json to store the sealed json metadata or how we will use FAPI API w.r.t /dev/tpm0 how this directory will be used?

Note: want to understand how we use FAPI framework with /dev/tpm0, I am not getting  what is the purpose of this  "tcti"="device:/dev/tpm0", does my sealed object.json is securely stored , how to ensure hardware tpm is taking care of object.json

**Comment by JuergenReppSIT** [comment]
The objects stored in user_dir are encrypted keys or sealed objects corresponding to the a certain device. E.g. your TPM simulator or your physical device. 
So every user_dir can only be used for one device. If you will use both devices you could crate two FAPI config files with different system_dir and user_dir. You can switch between the config files via the environment variable 
TSS2_FAPICONF.
You can't set user_dir to /dev/tpm0. user_dir should be the directory where your keys or sealed objects will be stored.

**Comment by shekharpaty** [comment]
@JuergenReppSIT  Thankyou, so how do we know FAPI API is talking to /dev/tpm0 or TPM hardware, is there any relationship is there between them, because we see the object.json in user_dir , "tcti"="device:/dev/tpm0" what is the purpose of this key:value?
how TPM hardware is controlling this directory ~/.local/share/tpm2-tss/user/keystore, I searched in google but not getting a clear picture on the FAPI and TPM hardware relationship.

**Comment by JuergenReppSIT** [comment]
@shekharpaty tcti in the FAPI config defines the used device. So the combination of tcti and system_dir/user_dir defines the relation between the TPM and the current used FAPI keystore (env TSS2_FAPICONF). 
If tcti is not defined it will be tried to find an appropriate device in the order: 
default (if link exits), tabrmd, device /dev/tpmrm0, device /dev/tpm0, swtpm,. mssim.
E.g. `device:/dev/tpm0` or  `swtpm:host=localhost,port=2321`

**Comment by williamcroberts** [comment]
> Does Fapi_Provision() API provide underlying connections to TPM hardware?

Yes is this is done with TCTI's which can be changed as needed. Ie device drivere (/dev/tpmrm0) vs the simulator vs spi, etc.

> All communication with the TPM is performed in salted HMAC sessions and parameter encryption is enabled
> wherever applicable. ( Q---Please can you clarify this sentence)

Not all commands support parameter and/or response encryption, so it can only be enabled for applicable commands. Theirs also a point where you need to create the EK using TPM2_CreatePrimary command. That cannot be done in an encrypted session as their is no key yet, however, that key is then verified using the EK Certificate (so an attacker could not monkey with it). IIRC (I could be wrong here) is used to bootstrap the communications until the SRK is created. Once the SRK is created, it uses that key. Note that the EK verification is hardcoded to the tss2-fapi shared object (stored in the library), so swapping out the library would be an attack to trust an invalid EK. Also, if my rant on the SRK is true, somewhere in that store contains the SRK name for verification, changing that could allow an attacker to change the key used for encrypted comms to one they control the private key for.

> The host platform’s TPM is the default TPM for all FAPI interactions and the key and policy store are stored
> on the local filesystem. ( Q--- if key and policy are stored in local filesystem is it exposed to hacker, how TPM will protect the object.json saved inside user_dir? )

The two important things are the key public and key private blobs that are returned from the TPM during a TPM2_Create call, (if your using tpm2-tools it's the -u and -r outputs of tpm2_create that are passed to tpm2_load). These blobs are protected by the TPM, so an attacker could delete them, inject new ones, but not modify. Their is metadata in the store, but that won't affect the ability of the attacker to steal a key and use it elsewhere (depends on attributes and authPolicy/Value).

**Comment by williamcroberts** [comment]
> Does Fapi_CreateKey utilizes tpm2_create ,

Yes, essentially. it using the TPM command directly through the API and not a subprocess to tpm2_create tool.

> can we validate our key stored in "HS/SRK/myRsaCryptKey" has any relative BLob or any supporting reference stored or protected inside TPM hardware?

FAPI ensures all of this through the encrypted sessions so you don't have to. Without changing your trusted EK during provisioning by swapping out the shared library or SRK by modifying the store, their is no way that FAPI won't create a key within the expected TPM becuase of the verified encrypted sessions, which provide integrity as well.

If you wanted to, you could use a combination of Fapi_GetEsysBlob and/or Fapi_GetTpmBlobs and than use the ESAPI API to call Certify or something on them.

> or initially when I perform tss2_provison it will read the fapi-config and create "HS/SRK/" folder structure and it will take care of TPM authentication.

On tss2_provision, or via the API call, FAPI will set up that tree structure based on the config.

**Comment by shekharpaty** [comment]
@williamcroberts @JuergenReppSIT  Thanks for clarifying the things I am closing the topic.
