### ISSUE TITLE
FAPI encrypt and decrypt usecase

### ISSUE THREAD

**Issue by shekharpaty** [tpm2-software/tpm2-tss#2534]
I am performing encrypt and decrypt operations using FAPI.
I am referring to this thread [https://github.com/tpm2-software/tpm2-tss/blob/29c46f0d27942146a909f7f12c0f8f65c45bec93/test/integration/fapi-data-crypt.int.c](url)

 *  - Fapi_Provision()
 *  - Fapi_Import()
 *  - Fapi_CreateKey()
 *  - Fapi_SetSignCB() (Q--can we skip the openssl API usage?) can drop the  Fapi_SetSignCB().
 *  - Fapi_Encrypt()
 *  - Fapi_Decrypt()
 *  - Fapi_Free()

**Comment by JuergenReppSIT** [comment]
> * Fapi_SetSignCB() (Q--can we skip the openssl API usage?) can drop the  Fapi_SetSignCB().

If you you do not use PolicySigned, which is used for the key `HS/SRK/myRsaCryptKey` in the integration test, `Fapi_SetSignCB` is not needed.

**Comment by shekharpaty** [comment]
@JuergenReppSIT Thankyou,
I have tried further and created two files FAPI_Enc.C and FAPI_decr.C
Encryption and key creation was sucessful, but while decrypting it throws me below error.
 > WARNING:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:305:Esys_RSA_Decrypt_Finish() Received TPM Error 
ERROR:fapi:src/tss2-fapi/api/Fapi_Decrypt.c:329:Fapi_Decrypt_Finish() ErrorCode (0x00000095) RSA decryption. 
ERROR:fapi:src/tss2-fapi/api/Fapi_Decrypt.c:121:Fapi_Decrypt() ErrorCode (0x00000095) Data_Decrypt 
decrypt text

Please find my code for refernce:
FAPI_Enc.C -->works fine.
int main()
{
//Declrations   
				`TSS2_RC r = 0;
				FAPI_CONTEXT *fapi_context;
				uint8_t  *plainText=(uint8_t  *)"The";
				uint8_t *cipherText = NULL;
				size_t cipherTextSize;
				r = Fapi_Initialize(&fapi_context, NULL);
				if (r != TSS2_RC_SUCCESS) {
					printf("Error: Fapi_Initialize\n");
				}`
//Provision will come here, no need to worry env setup will take care w.r.t proile user, tss2_provison() will do the job
//Create Key    
				`r = Fapi_CreateKey(fapi_context, "HS/SRK/g3",
					"decrypt, noDa", "", NULL);
				if (r != TSS2_RC_SUCCESS) {
					printf("Error: Fapi_CreateKey\n");
				}
				else{
					printf("Encryption key created successfully!\n");
				}`
//Encrypt
				`std::fstream outfile;
				outfile.open("cipher3.txt", ios::out);
				r = Fapi_Encrypt(fapi_context, "HS/SRK/g3", &plainText[0],
								 3, &cipherText, &cipherTextSize);
				outfile<<cipherText;
				cout<<cipherText<<endl;
				if (r != TSS2_RC_SUCCESS) {
					printf("Error: Encrypt failed\n");
				}
				printf((const char*)plainText);
				outfile.close();
				Fapi_Finalize(&fapi_context);
				return 1;`
}`

Now FAPI_decr.C, I am getting error while executing this.
int main()
{
//Declrations   
				`TSS2_RC r = 0;
				FAPI_CONTEXT *fapi_context;
				r = Fapi_Initialize(&fapi_context, NULL);
				if (r != TSS2_RC_SUCCESS) {
					printf("Error: Fapi_Initialize\n");
				}`
    //Decrypt---------------------------
				`uint8_t *plainText2 = NULL;
				uint8_t *cipher=nullptr;
				size_t plainText2_size = 0;
				char *buffer=nullptr;
				FILE *fp;
				fstream cipherread; string store;
				cipherread.open("cipher3.txt");
				if (cipherread) {
							ostringstream buf;
							buf << cipherread.rdbuf();
							store = buf.str();
						 }
				cipher = new unsigned char[256];
				size_t lSize=store.length() + 1;
				strcpy((char *)cipher, store.c_str());
				r = Fapi_Decrypt(fapi_context, "HS/SRK/g3", (uint8_t const *)&cipher[0], lSize,
								 &plainText2, &plainText2_size);
				printf("decrypt text\n");
				printf((const char*)plainText2);
				return 0;`
}

**Comment by JuergenReppSIT** [comment]
@shekharpaty I think the value of lSize is wrong (should be 256) and you should not declare the binary cipher as a string.

**Comment by shekharpaty** [comment]
Please guide me on checking the error codes, any reference I can understand from error codes.
 
I will be trying to avoid the string, but meanwhile I gave one more try with the changed code, still it failed.
`int main()
{
//Declrations   
				TSS2_RC r = 0;
				FAPI_CONTEXT *fapi_context;
				r = Fapi_Initialize(&fapi_context, NULL);
				if (r != TSS2_RC_SUCCESS) {
					printf("Error: Fapi_Initialize\n");
				}
    //Decrypt---------------------------
				uint8_t *plainText2 = NULL;
				size_t plainText2_size = 0;
				uint8_t *cipherText = NULL;
				size_t cipherTextSize;
				fstream cipherread;
				string store;
				cipherread.open("cipher3.txt");
				if (cipherread) {
							ostringstream buf;
							buf << cipherread.rdbuf();
							store = buf.str();
						        }

				cout<<store<<endl;
				cipherTextSize=store.length()+1;
				cipherText = (uint8_t*)store.c_str();
				//strcpy((char *)cipher, store.c_str());
				cout<<"-------->\n"<<cipherText<<"\nsize--->"<<cipherTextSize<<endl;
				r = Fapi_Decrypt(fapi_context, "HS/SRK/g10", cipherText, cipherTextSize,
								 &plainText2, &plainText2_size);
				printf("decrypt text\n");
				printf((const char*)plainText2);
				return 0;
}
`
Encrypt Cpp code cipher output:
![image](https://user-images.githubusercontent.com/9739252/211039097-d0f83a32-9bd9-4ef6-9659-abeb347500fd.png)
Decrypt Cpp  code cipher output, i printed twice the cipher to verify, so almost  it looks similar from encrypt output:
![image](https://user-images.githubusercontent.com/9739252/211039268-42f45f0b-0cf2-466b-bfb9-8f7eef391b83.png)

Surprisingly when i did Vim cipher3.txt i see something other out, ubuntu is convetring at bottom of snippet please see.
![image](https://user-images.githubusercontent.com/9739252/211039583-987d3dad-c6d0-4cc7-a71c-76f25729c620.png)

**Comment by JuergenReppSIT** [comment]
@shekharpaty The error is:
```
tpm2_rc_decode 0x95
tpm:handle(unk):structure is the wrong size
```
The size of the cipher file should be 256. I'm not familiar with c++. But you did not treat this file as a binary file.
The flag `ios::binary` should be added to open the cipher file.

**Comment by shekharpaty** [comment]
@JuergenReppSIT 

- I have chnaged in two places while writing to file in Encrypt.Cpp --> outfile.open("cipher3.txt", ios::binary | ios::out);

- while reading in Decrypt.Cpp----->cipherread.open("cipher3.txt", ios::binary | ios::in );
       size_t cipherTextSize=256;
         r = Fapi_Decrypt(fapi_context, "HS/SRK/g11", cipherText, cipherTextSize,
                     &plainText2, &plainText2_size);
But still same error:

> amp@amp-virtual-machine:~/poc2$ ./decr 
> 7�coO���D�G�Ż�^�J�e���Ӕ��)�yc�Ua뻯L'�4f ESYp^?=�H��Gc
> -------->
> 7�coO���D�G�Ż�^�J�e���Ӕ��)�yc�Ua뻯L'�4f ESYp^?=�H��Gc
> size--->117
> WARNING:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:305:Esys_RSA_Decrypt_Finish() Received TPM Error 
> ERROR:fapi:src/tss2-fapi/api/Fapi_Decrypt.c:329:Fapi_Decrypt_Finish() ErrorCode (0x00000095) RSA decryption. 
> ERROR:fapi:src/tss2-fapi/api/Fapi_Decrypt.c:121:Fapi_Decrypt() ErrorCode (0x00000095) Data_Decrypt 
> decrypt text

**Comment by JuergenReppSIT** [comment]
@shekharpaty I have rewritten your example code and replaced the c++ part with c functions and it works. So you
should check what's the difference. But that's not TSS related ;-)
```
#include <stdio.h>
#include <tss2/tss2_fapi.h>

// gcc fapi-decrypt.c -L=/usr/local/lib/ -ltss2-fapi -o fapi-test -g

int main()
{
    //Declarations
    TSS2_RC r = 0;
    FAPI_CONTEXT *fapi_context;
    uint8_t  *plainText=(uint8_t  *)"The";
    uint8_t *cipher     = NULL;
    size_t cipherSize;
    r = Fapi_Initialize(&fapi_context, NULL);
    if (r != TSS2_RC_SUCCESS) {
        printf("Error: Fapi_Initialize\n");
    }
    //Provision will come here, no need to worry env setup will take care w.r.t proile user, tss2_provison() will do the job
    //Create Key
    r = Fapi_CreateKey(fapi_context, "HS/SRK/g3", "decrypt, noDa", "", NULL);
    if (r != TSS2_RC_SUCCESS) {
        printf("Error: Fapi_CreateKey\n");
    } else {
        printf("Encryption key created successfully!\n");
    }
    //Encrypt
    
    r = Fapi_Encrypt(fapi_context, "HS/SRK/g3", &plainText[0], 4, &cipher, &cipherSize);
    if (r != TSS2_RC_SUCCESS) {
        printf("Error: Encrypt failed\n");
    }
    fprintf(stdout, "\nplainText %s", plainText);

    FILE *file;
    file = fopen("cipher3.bin","wb"); 
    fwrite(cipher, cipherSize, 1 , file);
    fclose(file);

    //Decrypt
    uint8_t *plainText2 = NULL;
    uint8_t cipher2[256];
    size_t plainText2_size = 0;
    size_t cipher2_size = 0;

    file = fopen("cipher3.bin","rb"); 
    cipher2_size = fread(&cipher2[0], 1, sizeof(cipher2), file);
                         
    r = Fapi_Decrypt(fapi_context, "HS/SRK/g3", &cipher2[0],
                     cipher2_size, &plainText2, &plainText2_size);
    if (r != TSS2_RC_SUCCESS) {
        printf("Error: Dencrypt failed\n");
    }
    fprintf(stdout, "\ndecrypt text %s\n", plainText2);
    return 0;
}
  ```

**Comment by shekharpaty** [comment]
@JuergenReppSIT Thankyou , I have created two c files and reused your code, it works as per expected.

**Note:** Anyone who wants to split the code for encryption and decryption , make sure in decryption please use   Fapi_Initialize(&fapi_context, NULL); it wont specifically tell you have not used fapi_initialize().
Rather I got these errors when i didn't included the  fapi_initialize() in decryption code  c  code file, please let me  know if we can add the proper error messages in fapi code base, how to contribute to fapi code base? 
![image](https://user-images.githubusercontent.com/9739252/211145305-41253d17-f75a-4819-a8ba-705941b10513.png)
