### ISSUE TITLE
Unable to make TPM work on Raspberry Pi 3b+

### ISSUE THREAD

**Issue by LSuessmuth** [tpm2-software/tpm2-tss#2536]
Built tss, abrmd and tools accordingly (I retried it multiple times assuming the mistake on my end). When I try to run:

`tpm2_getcap`

with or without arguments I get:

`tpm2_getcap: symbol lookup error: /usr/local/lib/libtss2-esys.so.0: undefined symbol: Tss2_Sys_MAC_Start_Complete`

, the command seems to look for a symbol in the given file path, which exists, but somehow doesnt contain the symbol its looking for.

I would greatly appreciate any help on how to fix this or how to build tss, abrmd and tools alternatively so that this error doesnt occur.

**Comment by williamcroberts** [comment]
> Built tss, abrmd and tools accordingly (I retried it multiple times assuming the mistake on my end). When I try to run:
> 
> `tpm2_getcap`
> 
> with or without arguments I get:
> 
> `tpm2_getcap: symbol lookup error: /usr/local/lib/libtss2-esys.so.0: undefined symbol: Tss2_Sys_MAC_Start_Complete`
> 
> , the command seems to look for a symbol in the given file path, which exists, but somehow doesnt contain the symbol its looking for.
> 
> I would greatly appreciate any help on how to fix this or how to build tss, abrmd and tools alternatively so that this error doesnt occur.

This happens when you have two tss2-esys installed. In this case your building against one set of headers that define `Tss2_Sys_MAC_Start_Complete` and linking against an older version. Start by poking around your filesystem and clean everything up and reinstall. Check that you don't have any tss2 packages installed from the package manager as well.

**Comment by LSuessmuth** [comment]
Thanks for the answer. Just checked for anything that resembels tss2-esys. Nothing came up except for the one that was installed by the build processes. I will try to rebuild it again from scratch and then get back to you to see if I get a different output. But apt says there is no such thing installed and I wouldnt know where else to look for it other than the librarys which came up with nothing either.

**Comment by LSuessmuth** [comment]
Ok for some reason or other, building everything new didnt yield the same result. 

from:
`sudo tpm2_getcap`

I am now greeted with:
`** (process:7124): CRITICAL **: 19:46:41.644: failed to allocate dbus proxy object: Error calling StartServiceByName for com.intel.tss2.Tabrmd: Timeout was reached
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:169:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-tabrmd.so.0 
ERROR: missing capability string, see --help
Usage: tpm2_getcap [<options>] <arguments>
Where <options> are:
    [ -l | --list] [ --ignore-moredata]`

so the tpm2_getcap command executes but gives a critical error.

**Comment by LSuessmuth** [comment]
> 

So for some reason I am now greeted with 

`** (process:7124): CRITICAL **: 19:46:41.644: failed to allocate dbus proxy object: Error calling StartServiceByName for com.intel.tss2.Tabrmd: Timeout was reached
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:169:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-tabrmd.so.0 
ERROR: missing capability string, see --help
Usage: tpm2_getcap [<options>] <arguments>
Where <options> are:
    [ -l | --list] [ --ignore-moredata]
`
So the command executes now if I use 
`tpm2_getcap`
But there is a critical error. Do you have any suggestion on how to go on from here ? I will try my best to fix it in the meantime.

**Comment by williamcroberts** [comment]
> > This happens when you have two tss2-esys installed. In this case your building against one set of headers that define 'Tss2_Sys_MAC_Start_Complete' and linking against an older version. Start by poking around your filesystem and clean everything up and reinstall. Check that you don't have any tss2 packages installed from the package manager as well.
> 
> So for some reason I am now greeted with
> 
> `** (process:7124): CRITICAL **: 19:46:41.644: failed to allocate dbus proxy object: Error calling StartServiceByName for com.intel.tss2.Tabrmd: Timeout was reached ERROR:tcti:src/tss2-tcti/tctildr-dl.c:169:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-tabrmd.so.0 ERROR: missing capability string, see --help Usage: tpm2_getcap [<options>] <arguments> Where <options> are: [ -l | --list] [ --ignore-moredata] ` So the command executes now if I use `tpm2_getcap` But there is a critical error. Do you have any suggestion on how to go on from here ? I will try my best to fix it in the meantime.

First one, is service tpm2-abrmd running? 
The second one run `tpm2_getcap properties-fixed` or something to test that it all works.

**Comment by williamcroberts** [comment]
by any chance did you install an older version of tpm2-tss from make install and then update master and install again? Our soname bumped, so you might have some older soname versions kicking around too.

**Comment by LSuessmuth** [comment]
> First one, is service tpm2-abrmd running? The second one run `tpm2_getcap properties-fixed` or something to test that it all works.

It gave me this:
`TPM2_PT_FAMILY_INDICATOR:
  raw: 0x322E3000
  value: "2.0"
TPM2_PT_LEVEL:
  raw: 0
TPM2_PT_REVISION:
  raw: 0x74
  value: 1.16
TPM2_PT_DAY_OF_YEAR:
  raw: 0xD1
TPM2_PT_YEAR:
  raw: 0x7DF
TPM2_PT_MANUFACTURER:
  raw: 0x49465800
  value: "IFX"
TPM2_PT_VENDOR_STRING_1:
  raw: 0x534C4239
  value: "SLB9"
TPM2_PT_VENDOR_STRING_2:
  raw: 0x36373000
  value: "670"
TPM2_PT_VENDOR_STRING_3:
  raw: 0x0
  value: ""
TPM2_PT_VENDOR_STRING_4:
  raw: 0x0
  value: ""
TPM2_PT_VENDOR_TPM_TYPE:
  raw: 0x0
TPM2_PT_FIRMWARE_VERSION_1:
  raw: 0x70028
TPM2_PT_FIRMWARE_VERSION_2:
  raw: 0x83200
TPM2_PT_INPUT_BUFFER:
  raw: 0x400
TPM2_PT_HR_TRANSIENT_MIN:
  raw: 0x3
TPM2_PT_HR_PERSISTENT_MIN:
  raw: 0x7
TPM2_PT_HR_LOADED_MIN:
  raw: 0x3
TPM2_PT_ACTIVE_SESSIONS_MAX:
  raw: 0x40
TPM2_PT_PCR_COUNT:
  raw: 0x18
TPM2_PT_PCR_SELECT_MIN:
  raw: 0x3
TPM2_PT_CONTEXT_GAP_MAX:
  raw: 0xFFFF
TPM2_PT_NV_COUNTERS_MAX:
  raw: 0x8
TPM2_PT_NV_INDEX_MAX:
  raw: 0x680
TPM2_PT_MEMORY:
  raw: 0x6
TPM2_PT_CLOCK_UPDATE:
  raw: 0x80000
TPM2_PT_CONTEXT_HASH:
  raw: 0xB
TPM2_PT_CONTEXT_SYM:
  raw: 0x6
TPM2_PT_CONTEXT_SYM_SIZE:
  raw: 0x80
TPM2_PT_ORDERLY_COUNT:
  raw: 0xFF
TPM2_PT_MAX_COMMAND_SIZE:
  raw: 0x500
TPM2_PT_MAX_RESPONSE_SIZE:
  raw: 0x500
TPM2_PT_MAX_DIGEST:
  raw: 0x20
TPM2_PT_MAX_OBJECT_CONTEXT:
  raw: 0x396
TPM2_PT_MAX_SESSION_CONTEXT:
  raw: 0xEB
TPM2_PT_PS_FAMILY_INDICATOR:
  raw: 0x1
TPM2_PT_PS_LEVEL:
  raw: 0x0
TPM2_PT_PS_REVISION:
  raw: 0x100
TPM2_PT_PS_DAY_OF_YEAR:
  raw: 0x0
TPM2_PT_PS_YEAR:
  raw: 0x0
TPM2_PT_SPLIT_MAX:
  raw: 0x80
TPM2_PT_TOTAL_COMMANDS:
  raw: 0x59
TPM2_PT_LIBRARY_COMMANDS:
  raw: 0x58
TPM2_PT_VENDOR_COMMANDS:
  raw: 0x1
TPM2_PT_NV_BUFFER_MAX:
  raw: 0x300`

But the same Critical Error occured again.

**Comment by LSuessmuth** [comment]
> by any chance did you install an older version of tpm2-tss from make install and then update master and install again? Our soname bumped, so you might have some older soname versions kicking around too.

I scratched the SD card and built everything from scratch as intended, there should be no old versions of anything relating to this repository installed. I still get the same Critical Error. I wouldnt know why tpm2-abrmd shouldnt be running. Could you explain to me how I would get it running if its not ?

**Comment by LSuessmuth** [comment]
> > by any chance did you install an older version of tpm2-tss from make install and then update master and install again? Our soname bumped, so you might have some older soname versions kicking around too.
> 
> I scratched the SD card and built everything from scratch as intended, there should be no old versions of anything relating to this repository installed. I still get the same Critical Error. I wouldnt know why tpm2-abrmd shouldnt be running. Could you explain to me how I would get it running if its not ?
> 
> EDIT: Just checked it in systemctl. Status is disabled. Do I just enable it ?

So Ive no Idea on how to get it running. The message given to me by systemctl is:

`Failed to acquire DBus name com.intel.tss2.Tabrmd. UID 995 must be allowed to "own" this name. Check DBus config and check that this is running as user tss or root.`

Any Idea on how I can give ownership of the service to tss ?

**Comment by williamcroberts** [comment]
> > > by any chance did you install an older version of tpm2-tss from make install and then update master and install again? Our soname bumped, so you might have some older soname versions kicking around too.
> > 
> > 
> > I scratched the SD card and built everything from scratch as intended, there should be no old versions of anything relating to this repository installed. I still get the same Critical Error. I wouldnt know why tpm2-abrmd shouldnt be running. Could you explain to me how I would get it running if its not ?
> > EDIT: Just checked it in systemctl. Status is disabled. Do I just enable it ?
> 
> So Ive no Idea on how to get it running. The message given to me by systemctl is:
> 
> `Failed to acquire DBus name com.intel.tss2.Tabrmd. UID 995 must be allowed to "own" this name. Check DBus config and check that this is running as user tss or root.`
> 
> Any Idea on how I can give ownership of the service to tss ?

It's in the tpm2-abrmd.conf file that gets installed. On my system, Ubuntu 20.04 it needs to be installed in `/etc/dbus-1/system.d/tpm2-abrmd.conf`. This can be set at the time of running `./configure` via the configure option `--with-dbuspolicydir`. You can manually copy that file into the directory too, no need for another make install. Then you need to restart dbus and the service.

Also is UID 955 tss? If it is, then your good. Example of looking it up with id, you'll need to change the uid number as tss is 106 on my system:
```bash
id -nu 106
tss
```

**Comment by LSuessmuth** [comment]
> 



> > > > by any chance did you install an older version of tpm2-tss from make install and then update master and install again? Our soname bumped, so you might have some older soname versions kicking around too.
> > > 
> > > 
> > > I scratched the SD card and built everything from scratch as intended, there should be no old versions of anything relating to this repository installed. I still get the same Critical Error. I wouldnt know why tpm2-abrmd shouldnt be running. Could you explain to me how I would get it running if its not ?
> > > EDIT: Just checked it in systemctl. Status is disabled. Do I just enable it ?
> > 
> > 
> > So Ive no Idea on how to get it running. The message given to me by systemctl is:
> > `Failed to acquire DBus name com.intel.tss2.Tabrmd. UID 995 must be allowed to "own" this name. Check DBus config and check that this is running as user tss or root.`
> > Any Idea on how I can give ownership of the service to tss ?
> 
> It's in the tpm2-abrmd.conf file that gets installed. On my system, Ubuntu 20.04 it needs to be installed in `/etc/dbus-1/system.d/tpm2-abrmd.conf`. This can be set at the time of running `./configure` via the configure option `--with-dbuspolicydir`. You can manually copy that file into the directory too, no need for another make install. Then you need to restart dbus and the service.
> 
> Also is UID 955 tss? If it is, then your good. Example of looking it up with id, you'll need to change the uid number as tss is 106 on my system:
> 
> ```shell
> id -nu 106
> tss
> ```
 As you may have noticed im not that advanced of a linux user yet. So forgive me for the next one. I typed in 
`id -nu 955`
For which I got the message (its in german) that the user 955 does not exist. However when I type in
`id tss`
I get 
`uid=995(tss) gid=995(tss) Gruppen=995(tss)`
as an answer. Which does not make sense in my head. Can you explain to me what went wrong here. Also what should the config file in `etc/dbus-1/system.d/tpm2-abrmd.conf` contain exactly ? So far your support has been genius, Im sure we are very close to resolving my issue.

**Comment by williamcroberts** [comment]
> > 
> 
> > > > > by any chance did you install an older version of tpm2-tss from make install and then update master and install again? Our soname bumped, so you might have some older soname versions kicking around too.
> > > > 
> > > > 
> > > > I scratched the SD card and built everything from scratch as intended, there should be no old versions of anything relating to this repository installed. I still get the same Critical Error. I wouldnt know why tpm2-abrmd shouldnt be running. Could you explain to me how I would get it running if its not ?
> > > > EDIT: Just checked it in systemctl. Status is disabled. Do I just enable it ?
> > > 
> > > 
> > > So Ive no Idea on how to get it running. The message given to me by systemctl is:
> > > `Failed to acquire DBus name com.intel.tss2.Tabrmd. UID 995 must be allowed to "own" this name. Check DBus config and check that this is running as user tss or root.`
> > > Any Idea on how I can give ownership of the service to tss ?
> > 
> > 
> > It's in the tpm2-abrmd.conf file that gets installed. On my system, Ubuntu 20.04 it needs to be installed in `/etc/dbus-1/system.d/tpm2-abrmd.conf`. This can be set at the time of running `./configure` via the configure option `--with-dbuspolicydir`. You can manually copy that file into the directory too, no need for another make install. Then you need to restart dbus and the service.
> > Also is UID 955 tss? If it is, then your good. Example of looking it up with id, you'll need to change the uid number as tss is 106 on my system:
> > ```shell
> > id -nu 106
> > tss
> > ```
> 
> As you may have noticed im not that advanced of a linux user yet. So forgive me for the next one. I typed in `id -nu 955` For which I got the message (its in german) that the user 955 does not exist. However when I type in `id tss` I get `uid=995(tss) gid=995(tss) Gruppen=995(tss)` as an answer. Which does not make sense in my head. Can you explain to me what went wrong here. 

My guess is some difference in systems on how the id command itself works. But since `id 955` gave you the details right, I wouldn't worry about it right now.

Also what should the config file in `etc/dbus-1/system.d/tpm2-abrmd.conf` contain exactly ? 

That file tells dbus whom can access that communication "bus" (it's really just a pair of sockets). That file is in the project as `dist/tpm2-abrmd.conf` and make install sends it to the appropriate folder where dbus can find it. That folder location is linux distrobution specific based on how they configure dbus. So Ubuntu and Fedora probably won't use the same directory path, which is why I can't tell you exactly where it should be without know what your specific distro, what's your distro?

> So far your support has been genius, Im sure we are very close to resolving my issue.
> 
> EDIT: Just noticed the typo. 995 is indeed the tss user. Now I just need to know what to put into the tpm2-abrmd.conf file and my issue should be resolved right ? 

We need to know where your dbus configure file location should be, it's distro specific. You can just copy the file `dist/tpm2-abrmd.conf` into the proper folder.

> Or just rebuild with dbus-policydir if all else fails.
That just tells make install where to put it.

**Comment by LSuessmuth** [comment]
> > > 
> > 
> > 
> > > > > > by any chance did you install an older version of tpm2-tss from make install and then update master and install again? Our soname bumped, so you might have some older soname versions kicking around too.
> > > > > 
> > > > > 
> > > > > I scratched the SD card and built everything from scratch as intended, there should be no old versions of anything relating to this repository installed. I still get the same Critical Error. I wouldnt know why tpm2-abrmd shouldnt be running. Could you explain to me how I would get it running if its not ?
> > > > > EDIT: Just checked it in systemctl. Status is disabled. Do I just enable it ?
> > > > 
> > > > 
> > > > So Ive no Idea on how to get it running. The message given to me by systemctl is:
> > > > `Failed to acquire DBus name com.intel.tss2.Tabrmd. UID 995 must be allowed to "own" this name. Check DBus config and check that this is running as user tss or root.`
> > > > Any Idea on how I can give ownership of the service to tss ?
> > > 
> > > 
> > > It's in the tpm2-abrmd.conf file that gets installed. On my system, Ubuntu 20.04 it needs to be installed in `/etc/dbus-1/system.d/tpm2-abrmd.conf`. This can be set at the time of running `./configure` via the configure option `--with-dbuspolicydir`. You can manually copy that file into the directory too, no need for another make install. Then you need to restart dbus and the service.
> > > Also is UID 955 tss? If it is, then your good. Example of looking it up with id, you'll need to change the uid number as tss is 106 on my system:
> > > ```shell
> > > id -nu 106
> > > tss
> > > ```
> > 
> > 
> > As you may have noticed im not that advanced of a linux user yet. So forgive me for the next one. I typed in `id -nu 955` For which I got the message (its in german) that the user 955 does not exist. However when I type in `id tss` I get `uid=995(tss) gid=995(tss) Gruppen=995(tss)` as an answer. Which does not make sense in my head. Can you explain to me what went wrong here.
> 
> My guess is some difference in systems on how the id command itself works. But since `id 955` gave you the details right, I wouldn't worry about it right now.
> 
> Also what should the config file in `etc/dbus-1/system.d/tpm2-abrmd.conf` contain exactly ?
> 
> That file tells dbus whom can access that communication "bus" (it's really just a pair of sockets). That file is in the project as `dist/tpm2-abrmd.conf` and make install sends it to the appropriate folder where dbus can find it. That folder location is linux distrobution specific based on how they configure dbus. So Ubuntu and Fedora probably won't use the same directory path, which is why I can't tell you exactly where it should be without know what your specific distro, what's your distro?
> 
> > So far your support has been genius, Im sure we are very close to resolving my issue.
> > EDIT: Just noticed the typo. 995 is indeed the tss user. Now I just need to know what to put into the tpm2-abrmd.conf file and my issue should be resolved right ?
> 
> We need to know where your dbus configure file location should be, it's distro specific. You can just copy the file `dist/tpm2-abrmd.conf` into the proper folder.
> 
> > Or just rebuild with dbus-policydir if all else fails.
> > That just tells make install where to put it.

My Operating system is the default Raspberry Pi OS, so it should be configured the same as any debian.

**Comment by LSuessmuth** [comment]
Well turns out it was just the missing dbus policy directory.
