### ISSUE TITLE
How to save the AIK?

### ISSUE THREAD

**Issue by SAO-kirito-asuna** [tpm2-software/tpm2-tss#2538]
windows  esapi
I want to get the AIK that I created,so I try to save the handle of AIK.I call the Esys_EvictControl and get the persistent handle.However it return the error what is "Esys handle does not exist" when I call the Esys_ReadPublic by the persistent handle.
How to save the handle of AIK?

**Comment by SAO-kirito-asuna** [comment]
`    Esys_EvictControl(esysContext, ESYS_TR_RH_OWNER, loadedKeyHandle, ESYS_TR_PASSWORD, ESYS_TR_NONE, ESYS_TR_NONE, permanentHandle, &persistent_handle1);`
The value of permanentHandle can only be used once,otherwise it will fail.However the value of persistent_handle1 is always the same value(1073746251),and this value is invalid when I call the Esys_ReadPublic  in a new program.I am really confused.

**Comment by williamcroberts** [comment]
> 

Use ESYS_TR_Serialize to create a blob for later, in the new program call ESYS_TR_Deserialize to convert the blob back to an ESYS_TR handle.

**Comment by SAO-kirito-asuna** [comment]
Thanks very much.It works.There is an new question.Now I generate a random data by calling Esys_GetRandom.How to use the AIK handle to sign the random data?

**Comment by SAO-kirito-asuna** [comment]
`    
    ESYS_TR primaryHandle;
    TPM2B_PUBLIC* primaryPublic;
    TPM2B_CREATION_DATA* primaryCreationData;
    TPM2B_DIGEST* primaryCreationHash;
    TPMT_TK_CREATION* primaryCreationTicket;
    CreateEK(esysContext, primaryHandle, &primaryPublic, &primaryCreationData, &primaryCreationHash, &primaryCreationTicket);
    cout << "EK handle:" << primaryHandle << endl;
    cout << "EK public key:" << endl;
    for (int i = 0; i < primaryPublic->publicArea.unique.rsa.size; i++) {
        fprintf(stderr, "%02x", primaryPublic->publicArea.unique.rsa.buffer[i]);
    }
    cout << endl;

    TPMI_DH_PERSISTENT persistentHandle = TPM2_PERSISTENT_FIRST + 40;
    ESYS_TR newObjectHandle;
    Esys_EvictControl(esysContext, ESYS_TR_RH_OWNER, primaryHandle, ESYS_TR_PASSWORD, ESYS_TR_NONE, ESYS_TR_NONE, persistentHandle, &newObjectHandle);
`
Esys_EvictControl return error `WARNING:esys:api\Esys_EvictControl.c:330:Esys_EvictControl_Finish() Received TPM Error
ERROR:esys:api\Esys_EvictControl.c:114:Esys_EvictControl() Esys Finish ErrorCode (0x0000014b)`.
Esys_EvictControl worked well before.I used the different value of persistentHandle,however it don't work.

**Comment by SAO-kirito-asuna** [comment]
I call Esys_SequenceComplete to get the validation and it used by Esys_Sign.However,Esys_Sign return errcode 0x000000a0 which means 'invalid ticket'.I didn't figure out how to solve the probloem.I will really grateful for your help.

**Comment by williamcroberts** [comment]
> I call Esys_SequenceComplete to get the validation and it used by Esys_Sign.However,Esys_Sign return errcode 0x000000a0 which means 'invalid ticket'.I didn't figure out how to solve the probloem.I will really grateful for your help.

So you performed an Esys_HashSequenceStart, Esys_SequenceUpdate with the contents to hash and then Esys_SequenceComplete to get the digest and the ticket? You should just be able to pass that to Esys_Sign IIUC.

**Comment by williamcroberts** [comment]
> `ERROR:esys:api\Esys_EvictControl.c:114:Esys_EvictControl() Esys Finish ErrorCode (0x0000014b)`.
> Esys_EvictControl worked well before.I used the different value of persistentHandle,however it don't work.

looks like out of space:
```
tpm2 rc_decode 0x14b
tpm:error(2.0): Insufficient space for NV Allocation
```

**Comment by SAO-kirito-asuna** [comment]
I sorted it out.Thank you very much for your help.

**Comment by SAO-kirito-asuna** [comment]
It's okey to use EK to sign,but it return error when I try to sign with ak.
`WARNING:esys:api\Esys_Sign.c:311:Esys_Sign_Finish() Received TPM Error
ERROR:esys:api\Esys_Sign.c:105:Esys_Sign() Esys Finish ErrorCode (0x0000008e)`

The template of EK:
`        TPM2B_PUBLIC inPublicRSA = {
            .size = 0,
            .publicArea = {
                .type = TPM2_ALG_RSA,
                .nameAlg = TPM2_ALG_SHA256,
                .objectAttributes = (TPMA_OBJECT_USERWITHAUTH |
                                     TPMA_OBJECT_RESTRICTED |
                                     TPMA_OBJECT_DECRYPT |
                                     TPMA_OBJECT_FIXEDTPM |
                                     TPMA_OBJECT_FIXEDPARENT |
                                     TPMA_OBJECT_SENSITIVEDATAORIGIN),
                .authPolicy = {
                     .size = 0,
                 },
                .parameters.rsaDetail = {
                     .symmetric = {
                         .algorithm = TPM2_ALG_AES,
                         .keyBits.aes = 128,
                         .mode.aes = TPM2_ALG_CFB},
                     .scheme = {
                          .scheme = TPM2_ALG_NULL
                      },
                     .keyBits = 2048,
                     .exponent = 0,
                 },
                .unique.rsa = {
                     .size = 0,
                     .buffer = {}
                     ,
                 }
            }
        };`
The template of AK:
`        TPM2B_PUBLIC inPublicRSA = {
            .size = 0,
            .publicArea = {
                .type = TPM2_ALG_RSA,
                .nameAlg = TPM2_ALG_SHA256,
                .objectAttributes = (TPMA_OBJECT_USERWITHAUTH |
                                     TPMA_OBJECT_RESTRICTED |
                                     TPMA_OBJECT_SIGN_ENCRYPT |
                                     TPMA_OBJECT_FIXEDTPM |
                                     TPMA_OBJECT_FIXEDPARENT |
                                     TPMA_OBJECT_SENSITIVEDATAORIGIN),
                .authPolicy = {
                     .size = 0,
                 },
                .parameters.rsaDetail = {
                     .symmetric = {
                         .algorithm = TPM2_ALG_NULL,
                         .keyBits.aes = 128,
                         .mode.aes = TPM2_ALG_CFB
                     },
                     .scheme = {
                              .scheme = TPM2_ALG_RSAPSS,
                              .details = { .rsapss = {.hashAlg = TPM2_ALG_SHA256 }
                          }
                      },
                     .keyBits = 2048,
                     .exponent = 0,
                 },
                .unique.rsa = {
                     .size = 0,
                     .buffer = {}
                     ,
                 }
            }
        };`
The hierarchy is ESYS_TR_RH_ENDORSEMENT.

**Comment by SAO-kirito-asuna** [comment]
Even if I use the unrestricted aik to sign the digest,it still return error 0x0000008e which is the authorization HMAC check failed and DA counter incremented.

**Comment by SAO-kirito-asuna** [comment]
I figure it out.I need to perform Esys_TR_SetAuth before performing Esys_Sign.
