### ISSUE TITLE
Limited FAPI installation

### ISSUE THREAD

**Issue by shekharpaty** [tpm2-software/tpm2-tss#2539]
Please can i get the limited installation commands or packages  for FAPI, we have space constraint.

The goal to achieve from  FAPI is encryption and decrypting using Fapi_CreateKey(). on standalone system.

We have TPM hardware also.

But on ubuntu I ran few code and printed out the dependences here they are.

On real system we cannot have these may "so"

`>> amp@amp-virtual-machine:~/poc4$ objdump -p fapi-encr  | grep NEEDED
  NEEDED               libtss2-fapi.so.1
  NEEDED               libstdc++.so.6
  NEEDED               libc.so.6
amp@amp-virtual-machine:~/poc4$ objdump  -p /usr/local/lib/libtss2-fapi.so | grep NEEDED
  NEEDED               libcrypto.so.1.1
  NEEDED               libjson-c.so.5
  NEEDED               libcurl-gnutls.so.4  <why?>
  NEEDED               libuuid.so.1 <why?>
  NEEDED               libtss2-mu.so.0
  NEEDED               libtss2-esys.so.0
  NEEDED               libtss2-tctildr.so.0
  NEEDED               libc.so.6
`

This may too much info:
`amp@amp-virtual-machine:~/poc4$ ldd fapi-encr 
	linux-vdso.so.1 (0x00007ffc4edfd000)
	libtss2-fapi.so.1 => /usr/local/lib/libtss2-fapi.so.1 (0x00007f3861fa0000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f3861d76000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3861b4e000)
	libcrypto.so.1.1 => /usr/local/lib/libcrypto.so.1.1 (0x00007f386185f000)
	libjson-c.so.5 => /lib/x86_64-linux-gnu/libjson-c.so.5 (0x00007f386184c000)
	libcurl-gnutls.so.4 => /lib/x86_64-linux-gnu/libcurl-gnutls.so.4 (0x00007f38617a9000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f38617a0000)
	libtss2-mu.so.0 => /usr/local/lib/libtss2-mu.so.0 (0x00007f3861752000)
	libtss2-esys.so.0 => /usr/local/lib/libtss2-esys.so.0 (0x00007f3861686000)
	libtss2-tctildr.so.0 => /usr/local/lib/libtss2-tctildr.so.0 (0x00007f386167b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3861594000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f38620e1000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3861572000)
	libnghttp2.so.14 => /lib/x86_64-linux-gnu/libnghttp2.so.14 (0x00007f3861548000)
	libidn2.so.0 => /lib/x86_64-linux-gnu/libidn2.so.0 (0x00007f3861527000)
	librtmp.so.1 => /lib/x86_64-linux-gnu/librtmp.so.1 (0x00007f3861508000)
	libssh.so.4 => /lib/x86_64-linux-gnu/libssh.so.4 (0x00007f386149b000)
	libpsl.so.5 => /lib/x86_64-linux-gnu/libpsl.so.5 (0x00007f3861487000)
	libnettle.so.8 => /lib/x86_64-linux-gnu/libnettle.so.8 (0x00007f386143f000)
	libgnutls.so.30 => /lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f3861254000)
	libgssapi_krb5.so.2 => /lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f3861200000)
	libldap-2.5.so.0 => /lib/x86_64-linux-gnu/libldap-2.5.so.0 (0x00007f38611a1000)
	liblber-2.5.so.0 => /lib/x86_64-linux-gnu/liblber-2.5.so.0 (0x00007f3861190000)
	libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007f38610c1000)
	libbrotlidec.so.1 => /lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007f38610b1000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f3861095000)
	libtss2-sys.so.1 => /usr/local/lib/libtss2-sys.so.1 (0x00007f3861064000)
	libunistring.so.2 => /lib/x86_64-linux-gnu/libunistring.so.2 (0x00007f3860eba000)
	libhogweed.so.6 => /lib/x86_64-linux-gnu/libhogweed.so.6 (0x00007f3860e72000)
	libgmp.so.10 => /lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f3860dee000)
	libcrypto.so.3 => /lib/x86_64-linux-gnu/libcrypto.so.3 (0x00007f38609ac000)
	libp11-kit.so.0 => /lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f3860871000)
	libtasn1.so.6 => /lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f3860859000)
	libkrb5.so.3 => /lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f386078e000)
	libk5crypto.so.3 => /lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f386075d000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f3860757000)
	libkrb5support.so.0 => /lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f3860749000)
	libsasl2.so.2 => /lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f386072e000)
	libbrotlicommon.so.1 => /lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007f386070b000)
	libffi.so.8 => /lib/x86_64-linux-gnu/libffi.so.8 (0x00007f38606fc000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f38606f5000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f38606e1000)`
`amp@amp-virtual-machine:~/poc4$ file fapi-encr 
fapi-encr: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=6bed0244e05a0d6f5595e32c714c0d159339ee9d, for GNU/Linux 3.2.0, with debug_info, not stripped
amp@amp-virtual-machine:~/poc4$ `

**Comment by williamcroberts** [comment]
>> amp@amp-virtual-machine:~/poc4$ objdump  -p /usr/local/lib/libtss2-fapi.so | grep NEEDED NEEDED                              libcurl-gnutls.so.4  <why?> curl may be needed to download some EK Certificates. Some manufacturers host them on remote sites.
libuuid.so.1 <why?> - This is for JSON Event Log formats

This set of deps is for building everything, so it's likely very heavy:
```bash
$ sudo apt -y update
$ sudo apt -y install \
  autoconf-archive \
  libcmocka0 \
  libcmocka-dev \
  procps \
  iproute2 \
  build-essential \
  git \
  pkg-config \
  gcc \
  libtool \
  automake \
  libssl-dev \
  uthash-dev \
  autoconf \
  doxygen \
  libjson-c-dev \
  libini-config-dev \
  libcurl4-openssl-dev \
  uuid-dev \
  libltdl-dev
```
You could start with that and start dropping things until it doesn't compile/run. I don't know if your compiling on one system and deploying on another. You could even built it all as static libraries too.

**Comment by shekharpaty** [comment]
Thankyou.

https://github.com/tpm2-software (from this link i see these many components)

we have TPM 1.0 installed in our device. (/dev/tpm1.0)
The goal to achieve from FAPI is encryption and decrypting using Fapi_CreateKey(). on standalone system.

tpm2-tss  --> for FAPI its Important
tpm2-tools  --> <do we need this?><tss2_provison> i can use FAPI_API fapi_provision() , apart from this do you see we need it any thing else.
tpm2-abrmd --> <do we need this?>  
tpm2-pkcs11 --> < we may not need this>
tpm2-tss-engine --> < we may not need this>
tpm2-totp --> < we may not need this>

**Comment by williamcroberts** [comment]
> Thankyou.
> 
> https://github.com/tpm2-software (from this link i see these many components)
> 
> we have TPM 1.0 installed in our device. (/dev/tpm1.0) The goal to achieve from FAPI is encryption and decrypting using Fapi_CreateKey(). on standalone system.
> 
We only suppor TPM 2.0 devices, not the older 1.X devices. You need a different software stack for that TPM.

tpm2-tss is the core libraries everything is built on, its the root of the dependencies.
tpm2-tools you need this if you want the command line tools
tpm2-abrmd is the resource manager, you MAY need this. You can use /dev/tpmrm0 or the tpm directly /dev/tpm0 depending on what you're trying to do. Generally speaking you need an resource manager almost all of the time.
tpm2-pkcs11 You need this if you want to use a TPM through a PKCS11 interface
tpm2-tss-engine: you need this if you want to use the TPM through OpenSSL for versions less tham 3.0
tss2-openssl: Same as tpm2-tss-engine but for openssl 3.0 and greater
tpm2-totp: you probably don't need this. This allows a TPM to prove authenticity to a user using an authenticator app. Ie you booted the expected TPM on your system and want to verify it.
