### ISSUE TITLE
FAPI RSA encryption size limit

### ISSUE THREAD

**Issue by shekharpaty** [tpm2-software/tpm2-tss#2542]
Hello Team,
I am trying to encrypt data which is at least 512 bytes , I have initially done the testing with just 8 bytes of data it worked.
This is error message I am getting.

> amp@amp-virtual-machine:~/poc4$ ./fapi-encr 
Encryption key created successfully!
WARNING:esys:src/tss2-esys/api/Esys_RSA_Encrypt.c:302:Esys_RSA_Encrypt_Finish() Received TPM Error 
ERROR:fapi:src/tss2-fapi/api/Fapi_Encrypt.c:345:Fapi_Encrypt_Finish() The data to be encrypted might be too large. Common values are 256 bytes for no OAEP or 190 with OAEP. 
ERROR:fapi:src/tss2-fapi/api/Fapi_Encrypt.c:348:Fapi_Encrypt_Finish() ErrorCode (0x00000084) RSA encryption. 
ERROR:fapi:src/tss2-fapi/api/Fapi_Encrypt.c:126:Fapi_Encrypt() ErrorCode (0x00000084) Data_Encrypt 
Error: Encrypt failed

I am using default RSA fapi_profile, any tweaking is required to config profile to encrypt more than 256 bytes data?

uint8_t *plainText=(uint8_t  *)Data as if now I am playing with 256 bytes, but may need 512 bytes.
E8B6C00C9ADC5E75BB656ECD429CB1643A25B111FCD22C6622D53E0722439993E8B6C00C9ADC5E75BB656ECD429CB1643A25B111FCD22C6622D53E0722439993E8B6C00C9ADC5E75BB656ECD429CB1643A25B111FCD22C6622D53E0722439993E8B6C00C9ADC5E75BB656ECD429CB1643A25B111FCD22C6622D53E0722439993

r = Fapi_Encrypt(fapi_context, "HS/SRK/f", (uint8_t  *)plainText, 256, &cipher, &cipherSize);

Please let me know for any changes.

**Comment by williamcroberts** [comment]
With RSA, not sure about ECC, the message must be smaller than the key, an RSA 2048 key is 256 bytes so a message of length 512 won't work. What you should do is encrypt AES 256 symmetric key of 16 bytes and then you can encrypt or decrypt that with the RSA key to recover the AES key and use the AES key for encrypt/decrypt using software like openssl. Even more simply, is you seal that AES key, using FAPI_CreateSeal and and then unseal the key from the TPM and use that via software like openssl.

**Comment by shekharpaty** [comment]
> The data to be encrypted might be too large. Common values are 256 bytes for no OAEP or 190 with OAEP.
for this error I have changed the P_RSA2048SHA256.json.
 
from 
rsa_decrypt_scheme": {
        "scheme":"TPM2_ALG_OAEP",
        "details":{
            "hashAlg":"TPM2_ALG_SHA256"
        }

to

rsa_decrypt_scheme": {
        "scheme":"TPM2_ALG_NULL",
        "details":{
            "hashAlg":"TPM2_ALG_SHA256"
        }
and I am sticking to 256 bytes now, but still I am getting error`ERROR:fapi:src/tss2-fapi/api/Fapi_Encrypt.c:345:Fapi_Encrypt_Finish() The data to be encrypted might be too large. Common values are 256 bytes for no OAEP or 190 with OAEP.`
How to make OAEP disable? how to change the profile at least to encrypt 256 bytes.

**Comment by JuergenReppSIT** [comment]
With TPM2_ALG_NULL the encryption of 256 bytes should work. If jq is installed you could check the used profile:
```
profile_dir=$(tss2_getinfo -o -|jq -r ".fapi_config.profile_dir")
grep decrypt_scheme -A 3 $profile_dir/P_RSA2048SHA256.json

   "rsa_decrypt_scheme": {
        "scheme":"TPM2_ALG_NULL",
        "details":{
            "hashAlg":"TPM2_ALG_SHA256"
```

**Comment by shekharpaty** [comment]
Thankyou it worked,
