### ISSUE TITLE
FAPI: Retrieving key by persistent handle id

### ISSUE THREAD

**Issue by rkgfk** [tpm2-software/tpm2-tss#2544]
Hi everybody,

I started using the FAPI to interact with the TPM2. Up until now I only used the tpm2-tools collection or the PKCS#11 Interface.
In wonder if it is possible to use keys that are stored in the TPM2 as persistent handles with the FAPI routines. I.e. the Fapi_Decrypt routine. One should give a keyPath as parameter. But I only managed to use keys that were created by the Fapi_Create routine.
Am I missing something or is it just not possible?

**Comment by JuergenReppSIT** [comment]
yes it's just not possible. Fapi_Encrypt/Decrypt can only be used with keys created by FAPI. Only for the SRK it's checked whether an existing persistent key matches the  SRK paramters defined in the FAPI profile. If they match this key will be used as SRK. By using the tpm2-tool command `tss2_gettpm2object` keys create by FAPI can be used with the tpm2-tools.

**Comment by rkgfk** [comment]
I see. I was just wondering because a key is created by Fapi_Create as a persistent key shows up using `tpm2_getcap handles-persistent`. The persistent keys are also listed in Fapi_GetInfo().
But I got it now. It's just some kind of inconsistent to my thinking.
Thank you
