### ISSUE TITLE
tpm-tss configure issue AX_NORMALIZE_PATH(with_device)  on  GNU/Linux

### ISSUE THREAD

**Issue by shekharpaty** [tpm2-software/tpm2-tss#2548]
Hi Team,
I am trying to run `./configure --disable-tcti-mssim --disable-tcti-swtpm --disable-tcti-pcap --disable-tcti-libtpms --disable-tcti-cmd --disable-tcti-spi-helper --disable-valgrind-memcheck --disable-valgrind-helgrind  --disable-valgrind-drd  --disable-valgrind-sgcheck --disable-log-file --disable-defaultflags  --disable-weakcrypto --disable-doxygen-doc --disable-doxygen-man --disable-doxygen-rtf --disable-doxygen-html
`
But I am getting error.
`
./configure: line 16491: syntax error near unexpected token with_device'
./configure: line 16491:                     AX_NORMALIZE_PATH(with_device)'
`
configure snippet.
>
if test "${with_device+set}" = set; then :
  withval=$with_device;
  if test \( -w "$with_device" \)  -a \( -r "$with_device" \); then :
  { $as_echo "$as_me:${as_lineno-$LINENO}: result: success" >&5
$as_echo "success" >&6; }
                    AX_NORMALIZE_PATH(with_device)
                    with_device_set=yes
else
  as_fn_error $? "TPM device provided does not exist or is not writable" "$LINENO" 5
fi
else
  with_device_set=no
fi

Please let me know I am compiling it on Linux.

**Comment by williamcroberts** [comment]
Do you have autoconf archive installed?

**Comment by shekharpaty** [comment]
I havent installed the autoconf archive

**Comment by shekharpaty** [comment]
I will be installing autoconf archive and retest the configure

**Comment by shekharpaty** [comment]
will move the issue to the tpm2-abmrd. closing this thankyou.
