### ISSUE TITLE
FAPI json parser issue 

### ISSUE THREAD

**Issue by shekharpaty** [tpm2-software/tpm2-tss#2555]
hello Team,

I have built all the tpm2-tss libraries as static  and built a static binary which consists  only two FAPI API.
I have copied binary manually to our system and created  FAPI related directory structures  manually and copied fapi-profile.json also.
and the set env variable export TSS2_FAPICONF=/etc/tpm2-tss/fapi-config.json.

and I have set "tcti"="device:/dev/tpm0" in fapi-profile , we have hardware tpm.
1) Fapi_Initialize()
2)Fapi_Provision()

when I run binary i see this issue. 
ERROR:fapi:src/tss2-fapi/ifapi_config.c:198:ifapi_config_initialize_finish() Could not parse JSON objects  
ERROR:fapi:src/tss2-fapi/api/Fapi_Initialize.c:195:Fapi_Initialize_Finish() Could not finish initialization ErrorCode (0x00060001) 

Please let me know how to fix the issue.

Thanks team.

**Comment by JuergenReppSIT** [comment]
If you open the file in firefox: `file:/etc/tpm2-tss/fapi-config.json` you will see what's the problem.
you should use: 
`"tcti":"device:/dev/tpm0"`
or better:
`"tcti":"device:/dev/tpmrm0"`

**Comment by shekharpaty** [comment]
@jhachenbergerSIT   Thankyou that was the syntax issue, fixed it by json validator cool.

I am building static library like this

> gcc -o fap_cp Fapi_encr.c   /usr/local/lib/libtss2-fapi.a /usr/local/lib/libtss2-esys.a  /usr/lib/x86_64-linux-gnu/libjson-c.a /usr/local/lib/libtss2-mu.a /usr/lib/x86_64-linux-gnu/libcrypto.a /usr/local/lib/libtss2-sys.a /usr/local/lib/libtss2-tctildr.a /usr/local/lib/libtss2-tcti-device.a  -static

But still see the loading issue of tcti any hints? 

ERROR:tcti:src/tss2-tcti/tctildr.c:416:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI 
ERROR:fapi:src/tss2-fapi/api/Fapi_Initialize.c:227:Fapi_Initialize_Finish() Initializing TCTI. ErrorCode (0x000a0015)

**Comment by JuergenReppSIT** [comment]
@shekharpaty Could you please produce a Trace:
TSS2_LOG=tcti+trace ./fap_cp > trace.txt 2>&1

**Comment by shekharpaty** [comment]
@JuergenReppSIT  i see the initial environment issues w.r.t loading shared objects are resolved, now I am seeing the TPM hardware issues.

> chandru/extra_libs # /lib/ld-linux-x86-64.so.2 ./dumm 
ERROR:fapi:src/tss2-fapi/api/Fapi_GetInfo.c:89:Fapi_GetInfo() info is NULL: BAD_REFERENCE 
device Info

ERROR:esys_crypto:src/tss2-esys/esys_crypto_ossl.c:328:iesys_cryptossl_hmac_start() ErrorCode (0x00070001) EVP_PKEY_new_mac_key 
ERROR:esys_crypto:src/tss2-esys/esys_crypto.c:185:iesys_crypto_authHmac() Error ErrorCode (0x00070001) 
ERROR:esys:src/tss2-esys/esys_iutil.c:1241:iesys_compute_hmac() HMAC error ErrorCode (0x00070001) 
ERROR:esys:src/tss2-esys/esys_iutil.c:1351:iesys_gen_auths() Error while computing hmacs ErrorCode (0x00070001) 
ERROR:esys:src/tss2-esys/api/Esys_DictionaryAttackParameters.c:212:Esys_DictionaryAttackParameters_Async() Error in computation of auth values ErrorCode (0x00070001) 
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:907:Fapi_Provision_Finish() Error Esys_DictionaryAttackParameters ErrorCode (0x00070001) 
WARNING:fapi:src/tss2-fapi/ifapi_io.c:428:ifapi_io_remove_directories() Removing: /etc/local/var/lib/tpm2-tss/system/keystore/P_RSA2048SHA256/HE/EK/object.json 
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:168:Fapi_Provision() ErrorCode (0x00070001) Provision 
Error: Fapi_Provision

any hints? please let me know

**Comment by shekharpaty** [comment]
closing this issue the build  "https://launchpad.net/ubuntu/+source/tpm2-tss/3.2.0-0ubuntu1"  fixes the above issue.
