### ISSUE TITLE
Issues when creating new key with OEAP padding

### ISSUE THREAD

**Issue by marincovic** [tpm2-software/tpm2-tss#2556]
Hello team,

I am trying to create a RSA key but I am trying to set the padding to the TPM2_ALG_OAEP
For some reason when I set the schema to TPM2_ALG_OAEP I get the error:
```
2023-02-02 14:42:47.730 ( 603.211s) [                ]                 cTPM.h:25     ERR| Error in creation AppEncKey key pair. The error code is: 131. The decoded value is: tpm:handle(unk):hash algorithm not supported or not appropriate
```

the following is my public area:
```
TPMT_PUBLIC VDefaultAppEncKeyemplateRSA2048 = {
			.type = TPM2_ALG_RSA,
			.nameAlg = TPM2_ALG_SHA256,
			.objectAttributes = (TPMA_OBJECT_USERWITHAUTH |
								 TPMA_OBJECT_DECRYPT |
								 TPMA_OBJECT_FIXEDTPM |
								 TPMA_OBJECT_FIXEDPARENT |
								 TPMA_OBJECT_SENSITIVEDATAORIGIN),
			.authPolicy = {
				 .size = 0,
			 },
			.parameters.rsaDetail = {
				 .symmetric = { TPM2_ALG_NULL},
				 .scheme = {
					  .scheme = TPM2_ALG_OAEP,
				  },
				 .keyBits = 2048,
				 .exponent = 0,
			 },
			.unique.rsa = {
				 .size = 0,
				 .buffer = {},
			 },
	};
```

Thank you for your help!
BR//
Marin Covic

**Comment by marincovic** [comment]
Hello,

My mistake I am using TPM2_ALG_OAEP.

BR//
Marin

**Comment by JuergenReppSIT** [comment]
@marincovic  in the integration test esys-rsa-encrypt-decrypt.int.c also OAEP is used and it works.
Could you produce a trace with:
export  TSS2_LOG=all+trace

**Comment by marincovic** [comment]
Hello I found out what the issue was. 
OpenSSL by default uses SHA1 as hash algorithm and my template uses SHA256

Thank you for your support,
BR//
Marin
