### ISSUE TITLE
How to fix --TSS2_BASE_RC_NO_CERT-- error   and make Tss2_RC_Decode(...) work

### ISSUE THREAD

**Issue by JordanLBogdanov** [tpm2-software/tpm2-tss#2578]
Hi there.

I am developing a program using **FAPI** library and **Infineon TPM SLB 9665** chip. Working under **Ubuntu 22.04.2 LTS**.

My goal is to make the program **encrypt** and **decrypt** a sensitive piece of data for the company I work in.
I've been wrestling with running some code sample for a while.

There are 2 main **problems** that I have encountered.

**1.** I can't make the **Tss2_RC_Decode**(...) function work.  We are using **CMake** to build our project and I have linked **-ltss2-rc** to the project and included the **tss2_rc.h** and every time the function is executed to get a proper debug message, it makes the program crash.

The second problem is more important though.

**2.** I am running into difficulties while trying to run the bottom sample code.
There are several function from the **FAPI** library, that are executed.
**Fapi_Initialize**(...)      -- executes **-fine-** and return **TSS2_RC_SUCCESS**
**Fapi_Provision**(...)    -- throws **TSS2_BASE_RC_NO_CERT** error
**Fapi_CreateKey**(...)  -- throws **TSS2_BASE_RC_NOT_PROVISIONED** error
**Fapi_Sign**(...)             -- throws **TSS2_BASE_RC_NOT_PROVISIONED** error
**Fapi_Finalize**(...)        -- seems to execute fine. Before its execution, the context ptr is pointing to some memory, and after execution it is nullified.

Just out of curiosity I tried to execute:
**Fapi_GetRandom**(...)
**Fapi_CreateNv**(...)
**Fapi_NvRead**(...)
**Fapi_NvWrite**(...)
----- all of the throws the **TSS2_BASE_RC_NOT_PROVISIONED** error.

The **TSS2_BASE_RC_NO_CERT** says the FAPI needs **EK certificate**.

--------- The **BIG** question is where to get an **EK certificate** and how to feed it to the **FAPI** so that it stops throwing **TSS2_BASE_RC_NO_CERT** while I try to provision it?

From what I understand I need to use the CAs found here: **https://www.infineon.com/cms/en/product/promopages/optiga_tpm_certificates/#SLB9665xx2.0**
to generate myself a certificate with the TPM's public key and feed it to the FAPI.
Am I correct so far?

P.S.
The encrypted data is expected to be a small piece (we are talking of 30-40 characters), so there will be no need to involve a  **Symmetric** key. 

------------------------------------------------------------------------------ CODE SAMPLE  ------------------------------------------------------------------------------ 

```
#include <iostream>
#include <cstdint>

#include "tss2/tss2_fapi.h"
#include "tss2/tss2_rc.h"

#include "utils/Log.h"


uint32_t testEncrDecr()
{
    TSS2_RC r = 0;
    size_t signatureSize = 0;
    uint8_t *signature;
    char *publicKey;


    const size_t DIGEST_SIZE = 12;
    uint8_t digest[DIGEST_SIZE] = {72/*H*/,  101/*e*/, 108/*l*/, 108/*l*/,
                                   111/*o*/, 32/* */,  87/*W*/,  111/*o*/,
                                   114/*r*/, 108/*l*/, 100/*d*/, 33/*!*/};


    struct FAPI_CONTEXT *fapi_context;

    char const * uri = nullptr;

    
    // LEGEND: [TRCD] - at this point, if I call Tss2_RC_Decode(r) the program crashes


    r = Fapi_Initialize(&fapi_context, uri);

    if (TSS2_RC_SUCCESS != r)
    {
        LOGR("An error -- %d -- occurred while initializing the FAPI, exiting...", r)
        // [TRCD]
        goto error;
    }



    // provision the FAPI
    r = Fapi_Provision(fapi_context, NULL, NULL, NULL);

    if (TSS2_RC_SUCCESS != r)
    {
        LOGR("An error -- %d -- occurred while provisioning the FAPI, exiting...", r)
        // [TRCD]
        goto error;
    }



    r = Fapi_CreateKey(fapi_context,
                       "HS/SRK/mySigningKey",
                       "noDa, sign",
                       "",
                       "");

    if (TSS2_RC_SUCCESS != r)
    {
        LOGR("An error -- %d -- occurred while creating key, exiting...", r)
        // [TRCD]
        goto error;
    }



    r = Fapi_Sign(fapi_context,
                  "HS/SRK/mySigningKey",
                  NULL,
                  digest,
                  DIGEST_SIZE,
                  &signature,
                  &signatureSize,
                  &publicKey,
                  NULL);

    if (TSS2_RC_SUCCESS != r)
    {
        LOGR("An error -- %d -- occurred while signing the key, exiting...", r)
        // [TRCD]
        goto error;
    }


    Fapi_Finalize(&fapi_context);

    for (size_t i = 0; i < signatureSize; i++)
    {
        printf("%02x", signature[i]);
    }

    printf("\n");

    return TSS2_RC_SUCCESS;

    error:
        Fapi_Finalize(&fapi_context);
        return r;

}

```

**Comment by JuergenReppSIT** [comment]
The EK certificates should be stored on the TPM. e.g:
`$ tpm2_getcap  handles-nv-index`
`- 0x1C00002`
`- 0x1C0000A`
Ìf there ar no certifcates you can use the option `"ek_cert_less":"yes"` in the fapi config file. Normally stored at:
/usr/local/etc/tpm2-tss/fapi-config.json

**Comment by JordanLBogdanov** [comment]
Thank you for your reply @JuergenReppSIT .

I have set the "ek_cert_less" : "yes" in the fapi config file and the first time I executed that 
piece of code it ran seemingly fine and it printed some encrypted data within the signature array.

**BUT** when I ran this code again, it started throwing all kinds of other errors which baffled me.

**Fapi_CreateKey(...)** throws -- **TSS2_FAPI_RC_PATH_ALREADY_EXISTS**.
Lets say this is fine and the key already exists (thought it says that the path already exists).

**Fapi_Sign(...)** throws -- **TSS2_FAPI_RC_KEY_NOT_FOUND**.
Does that mean that the path exists, but the key is not there?

P.S. 
I tried to clear the TPM through BIOS, but it continues to throw the same errors. 
Could the   **BIOS**   **Pending Operation: TPM Clear** have cleared the key in the path, but no the path itself?

**Comment by JuergenReppSIT** [comment]
After a tpm clear the fapi keystore has to be deleted. If tss is installed to /usr/local you should delete the files in:
`/usr/local/var/lib/tpm2-tss/system/keystore`
`$HOME/.local/share/tpm2-tss/user/keystore`
Now you can execute tss2_provisioning again.

**Comment by JordanLBogdanov** [comment]
Thank @JuergenReppSIT . 
The solution worked fine. 
This is in the case of "ek_cert_less" --> "yes".
On the other hand it seems like there is an EK certificate on the TPM, but I am not quite able to retrive it.
How should I to use the **tpm2_getcap  handles-nv-index** - returned indexes to retrieve the EK cert data?
