### ISSUE TITLE
P_RSA2048SHA256 profile --- TSS2_FAPI_RC_BAD_VALUE

### ISSUE THREAD

**Issue by JordanLBogdanov** [tpm2-software/tpm2-tss#2583]
Hello.

When I change the profile (in fapi-config.json), from **P_ECCP256SHA256**   -to-    **P_RSA2048SHA256** and I call 
**Fapi_Provision(...)** it returns error code **TSS2_FAPI_RC_BAD_VALUE**.
(with **P_ECCP256SHA256** it executes fine).

Any thoughts?

**Comment by JordanLBogdanov** [comment]
I dont recall making any changes to the P_RSA2048SHA256.json.
I will get the default anew and try that way.

The source file and the line number are not present when the error occurs.
When I call **Tss2_RC_Decode(...)** the library crashes.

Where should I add **TSS2_LOG=fapi+trace**?

**Comment by JuergenReppSIT** [comment]
@JordanLBogdanov could you please create a trace:
TSS2_LOG=fapi+trace <your application which calls the provisioning>

**Comment by JuergenReppSIT** [comment]
@JordanLBogdanov I have updated the previous comment

**Comment by JordanLBogdanov** [comment]
Setting an environment variable **TSS2_LOG=fapi+trace** did nothing for me (or I couldn't figure it out what it should have done), but setting other such variable **TSS2_LOGFILE=tss2_log_RSA_prof.txt** generate such .txt log file with the console output.

It seems that the error is generated from Fapi_Provision.c:1112 line and it says that the **SRK persistent handle already defined**.

Here is the generated file:
[tss2_log_RSA_prof.txt](https://github.com/tpm2-software/tpm2-tss/files/10978586/tss2_log_RSA_prof.txt)

**Comment by JordanLBogdanov** [comment]
I managed to fix the Fapi_Provision(...) throwing errros by clearing the TPM from the BIOS. 
I think that cleared the SRK persistent handle.

After that functions: 
- Fapi_Provision(...); 
- Fapi_CreateKey(...);
- Fapi_Sign(...);
... they all execute **fine** (returning TSS2_RC_SUCCESS), but when the **Fapi_Encrypt(...)** is called, it returns **error 386**.
This is kind of strange, because all errors, up until this moment, where all six-figured.

Here is the log file, generated when calling the aforementioned functions.
[tss2_log.txt](https://github.com/tpm2-software/tpm2-tss/files/10980215/tss2_log.txt)

**Comment by JuergenReppSIT** [comment]
@JordanLBogdanov From the log I saw that you crated only the key  /P_RSA2048SHA256/HS/SRK/mySigningKey
For encryption the key should be created with the decrypt attribute e.g.:
` r = Fapi_CreateKey(context, "HS/SRK/myRsaCryptKey", "decrypt",NULL , NULL);`

**Comment by JordanLBogdanov** [comment]
@JuergenReppSIT should that key, created with the "decrypt" attribute, be used for encryption? Or you just mean that there must always be a pair of encryption and decryption keys created?

Initially I assumed that a key, created with the "sign" attributed, will work for encryption as well as for signing, because of this piece of code, which I believe is the one parsing the Fapi_CreateKey(...) 's type attribute:


--------------------------------------------------------------------------------------------------------------------------------------------------------

/* Loop over all comma or space separated flags */
    while (flag != NULL) {
        if (strcasecmp(flag, "system") == 0)
        {
            template->system = TPM2_YES;
        }
        else if (strcasecmp(flag, "sign") == 0)
        {
            attributes |= TPMA_OBJECT_SIGN_ENCRYPT;
        }
        else if (strcasecmp(flag, "user") == 0)
        {
	        attributes |= TPMA_OBJECT_USERWITHAUTH;
        }
        else if (strcasecmp(flag, "decrypt") == 0)
        {
            attributes |= TPMA_OBJECT_DECRYPT;
        }
        else if (strcasecmp(flag, "restricted") == 0)
        {
            attributes |= TPMA_OBJECT_RESTRICTED;
        }
        else if (strcasecmp(flag, "exportable") == 0)
        {
            /* TPMA_OBJECT_ENCRYPTEDDUPLICATION will not be set because no inner
               symmetric encryption will be used */
            exportable = true;
        }
        else if (strcasecmp(flag, "noda") == 0)
        {
            attributes |= TPMA_OBJECT_NODA;
        }
        else if (strncmp(flag, "0x", 2) == 0)
        {
            sscanf(&flag[2], "%"SCNx32 "%n", &handle, &pos);
            if ((size_t)pos != strlen(flag) - 2) {
                goto_error(r, TSS2_FAPI_RC_BAD_VALUE, "Invalid flag: %s",
                           error, flag);
            }
            template->persistent_handle = handle;
            template->persistent = TPM2_YES;
        }
        else
        {
            goto_error(r, TSS2_FAPI_RC_BAD_VALUE, "Invalid flag: %s",
                       error, flag);
        }
        flag = strtok_r(NULL, " ,", &saveptr);
    }

--------------------------------------------------------------------------------------------------------------------------------------------------------



It is taken from the **ifapi_helpers.c**. From the function **TSS2_RC ifapi_set_key_flags(...)**

Line 76 from the ifapi_helpers.c says: **attributes |= TPMA_OBJECT_SIGN_ENCRYPT;**
SIGN_ENCRYPT.

Can you please clear that out for me?
Thank you for your patience.

**Comment by JuergenReppSIT** [comment]
The comment in read the docs is wrong the documentation has to be fixed. If you provide the decrypt attribute the TPM 
the TPM funcktion RSA_Encrypt/Decrypt will be used.

**Comment by JordanLBogdanov** [comment]
> 

I did not quite understand what you meant by that.
Can you periphrase it?

Also can you please explain if I lose some security by using Fapi_Encrypt/Decrypt?

Thanks.

**Comment by JuergenReppSIT** [comment]
@JordanLBogdanov  you don't loose security. When you youse Fapi_Encrypt/Decrypt the TPM will be used for encryption/decryption.

**Comment by JordanLBogdanov** [comment]
@JuergenReppSIT that sounds good. 

I am missing something though.

I want the **Encrypt/Decrypt** functionality we implement to do it as a Public Key Cryptography.
Which I see as a **public key encrypting** the data, and **private key decrypting** it.
In the way I managed to do it it seems I am only using 1 key.

What am I missing?

**Comment by JuergenReppSIT** [comment]
@JordanLBogdanov yes that's true. Fapi supports the loading of external public keys. You can export the a key with `Fapi_ExportKey` and import such a key with `Fapi_Import`.
But unfortunately Fapi_Encrypt currently does not support the usage of external keys. I will create a PR to fix this problem.

**Comment by JordanLBogdanov** [comment]
Example pseudo-code setting:

```
Computer pc_1(); // got available TPM
Computer pc_2(); // got available TPM

// the target data to transmit safely between Computer's
const char * data = "Hello there!";

char * encryptedData = nullptr;
char * decryptedData = nullptr;

encryptedData = pc_1.encrypt(data);
decryptedData = pc_2.decryptData(encryptedData);
```

**The big Q**: is that achievable at this moment? 
For one **PC (with TPM)** to encrypt data, and for other **PC (with TPM)** to decrypt that same data?

**Comment by JuergenReppSIT** [comment]
@JordanLBogdanov I have tried to encrypt data with an exported public tpm key with OAEP.
But unfortunately the TPM produces an error in the OaepDecode function.
I will investigate this problem and create the fix for Fapi_Encrypt as soon as I find the time.

**Comment by JuergenReppSIT** [comment]
> Is there a way for me to stay in touch and get notification when that happens?

we can leave this issue open. And I will inform you about the progress.

**Comment by JordanLBogdanov** [comment]
I would very much appreciate that.

Thank you for your support.
Have a great weekend.

**Comment by JuergenReppSIT** [comment]
@JordanLBogdanov I found a solution for encrypting data with a public key exported by FAPI. The example above did not work because `openssl rsautl -encrypt -oaep` did use sha1 for oaep. If the hash alg for rsa_decrypt_scheme in the default profile was changed to sha1 encryption and decryption did work. But the following example works for the default profile (jq should be installed):
`tss2_createkey -p /SRK/mykey -t decrypt`
`tss2_exportkey -p /SRK/mykey -o pubkey.json`
`cat pubkey.json| jq -r ".pem_ext_public" > pub.pem`
`cat secret > /tmp/secret`
`openssl pkeyutl -in /tmp/secret -encrypt -pubin -inkey pub.pem -pkeyopt rsa_padding_mode:oaep -pkeyopt   rsa_oaep_md:sha256 -pkeyopt rsa_mgf1_md:sha256 -out cipher`
`tss2_decrypt -p /SRK/mykey -i cipher -o -`

I will change Fapi_Encrypt that for imported public keys can be used  the encryption with openssl will be executed.

**Comment by JuergenReppSIT** [comment]
@JordanLBogdanov Now PR #2587 enables the encryption with an exported public key:

`tss2_createkey -p /SRK/my_rsa_key -t decrypt`
`tss2_exportkey -p /SRK/my_rsa_key -o my_rsa_key_pub.json`
`tss2_import -p /ext/my_rsa_key -i my_rsa_key_pub.json`
`echo secret | tss2_encrypt -p /ext/my_rsa_key -i - -o cipher`
`tss2_decrypt -p /SRK/my_rsa_key -i cipher -o -`

I think we can close this issue?

**Comment by JordanLBogdanov** [comment]
@JuergenReppSIT I assume that this this solution will work when I transform it into a FAPI C++.
I will close this issue for now and will try this solution first thing in the morning. 

Thank you.

**Comment by JordanLBogdanov** [comment]
@JuergenReppSIT how should I used the Fapi_ExportKey function?
