### ISSUE TITLE
TSS looking for searching for older libjson

### ISSUE THREAD

**Issue by JordanLBogdanov** [tpm2-software/tpm2-tss#2586]
After upgrading from Ubuntu 18.04 -> 20.04 -> 22.04 the OS lost track of the **libjson-c.so.3**.

When executing some code, involving the **TSS**, I got the following error:
### _libjson-c.so.3: cannot open shared object file: No such file or directory_

From what I can tell:
- the package **libjson-c-dev** contains libjson-c.so;
- the package **libjson-c5** contains libjson-c.so.5

But installing those libraries didnt help me much.

Is the aforementioned **libjson-c.so.3** is contained in an older version of the libjson-c5 or some kind of obsolete library, which isn't around anymore? And is it compatible with 22.04 LTS?
Where should I get it so I can shut this error down.

Thanks.

**Comment by JuergenReppSIT** [comment]
I have installed tss 4.0.1 on ubuntu 22.04 and see:
`$ ldd /usr/local/lib/libtss2-fapi.so| grep json-c`
`	libjson-c.so.5 => /lib/x86_64-linux-gnu/libjson-c.so.5 (0x00007f2776cef000)`
Fapi uses libjson-c.so.5 . If you install tss 4.0.1 what do you see with this command?

**Comment by JordanLBogdanov** [comment]
I have installed the 4.0.1 version and it now works fine.

Apparently earlier I installed older version of the library.

Thank you.
