### ISSUE TITLE
Imported key not recognized as a key

### ISSUE THREAD

**Issue by JordanLBogdanov** [tpm2-software/tpm2-tss#2588]
@JuergenReppSIT when I import a key and try to use it I get the following error:
-- P_RSA2048SHA256/HS/SRK/myRsaCryptKeyimported **is no key** 

Which is thrown by fapi_util.c:1902

**Comment by JordanLBogdanov** [comment]
I may have found a glitch.
In the ifapi_keystore.h the defines are as follows:

#define IFAPI_KEY_OBJ                    1    /*< Tag for key resource */
#define IFAPI_EXT_PUB_KEY_OBJ   3    /*< Tag for key resource */

It seem that when a key is exported its **"objectType" : "IFAPI_EXT_PUB_KEY_OBJ"** , but when this same key is imported and loaded the function is looking for **"objectType" : "IFAPI_KEY_OBJ"**.

**Comment by JordanLBogdanov** [comment]
I tried importing the key into P_RSA2048SHA256/HS/SRK/**ext**/myRsaCryptKey, but it still throws the same error.

**Comment by JuergenReppSIT** [comment]
you should not use the profile path. Just use `/ext/myRsaCryptKey` without `P_RSA...`

**Comment by JordanLBogdanov** [comment]
When I try to import the key into **/ext/myRsaCryptKey** I get this error:
trace:fapi:src/tss2-fapi/fapi_util.c:1669:ifapi_load_keys_async() Load key: /ext/myRsaCryptKey 
ERROR:fapi:src/tss2-fapi/fapi_util.c:263:init_explicit_key_path() Hierarchy cannot be determined. 


Tried to import the key into **/ext/HS/SRK/myRsaCryptKey** I get this error:
trace:fapi:src/tss2-fapi/fapi_util.c:1669:ifapi_load_keys_async() Load key: /ext/HS/SRK/myRsaCryptKey 
ERROR:fapi:src/tss2-fapi/fapi_util.c:263:init_explicit_key_path() Hierarchy cannot be determined.

**Comment by JuergenReppSIT** [comment]
@JordanLBogdanov Did you get this error during Fapi_Decrypt? Unfortunately the PR for using /ext key in Fapi_Encrypt is not merged, because currently none of the other maintainers finds time to approve the PRs.
I have pushed a version to my private git, where most of the important current PRs are included:
https://github.com/JuergenReppSIT/tpm2-tss/tree/priv

**Comment by JordanLBogdanov** [comment]
@JuergenReppSIT I am so sorry. Yes, I get this error when I call Fapi_Decrypt(...) over data, that was encrypted earlier on another PC.

**Comment by JordanLBogdanov** [comment]
Is there an easy way of pulling only the changed items from your private git?

**Comment by JuergenReppSIT** [comment]
@JordanLBogdanov  you could clone https://github.com/JuergenReppSIT/tpm2-tss/tree/priv and cherry-pick the last commits.

**Comment by JordanLBogdanov** [comment]
@JuergenReppSIT I tried to clone your repository and execute the:
```
./bootstrap
./configure
make -j
sudo make install
```
They all execute fine, but the older version, without your last changes, is still used. I get the same error: **Hierarchy cannot be determined. **

**Comment by JordanLBogdanov** [comment]
Now that I take a closer look at the files in the cloned repository I see that even they does not have necessary changes. This is kinda strange.

**Comment by JuergenReppSIT** [comment]
@JordanLBogdanov You should execute the following command:
`git clone https://github.com/JuergenReppSIT/tpm2-tss.git`
`cd tpm2-tss`
`git checkout priv`
`./bootstrap`
`...`

**Comment by JordanLBogdanov** [comment]
Thank you. That did the trick. I am closing this one.
