### ISSUE TITLE
./bootstrap fails

### ISSUE THREAD

**Issue by kgoldman** [tpm2-software/tpm2-tss#2589]
Fedora 37, master branch

 ./bootstrap
Generating file lists: src_vars.mk
configure.ac:21: error: possibly undefined macro: AC_SUBST
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:60: error: possibly undefined macro: AS_IF
configure.ac:121: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:151: error: possibly undefined macro: AC_MSG_WARN
autoreconf: error: /usr/bin/autoconf failed with exit status: 1

**Comment by JuergenReppSIT** [comment]
I could run bootstrap on fedora 3.7 with the following autoconf packages:
```
[root@764daf5a1093 tpm2-tss]# cat /etc/fedora-release
Fedora release 37 (Thirty Seven)
[root@764daf5a1093 tpm2-tss]# dnf list installed| grep autoconf
autoconf.noarch                             2.71-4.fc37                    @updates        
autoconf-archive.noarch                     2022.09.03-1.fc37              @fedora         
[root@764daf5a1093 tpm2-tss]# ./bootstrap 
Generating file lists: src_vars.mk
aminclude_static.am:63: warning: GITIGNOREFILES was already defined in condition TRUE, which includes condition AUTOCONF_CODE_COVERAGE_2019_01_06 and CODE_COVERAGE_ENABLED ...
Makefile.am:56:   'aminclude_static.am' included from here
Makefile.am:52: ... 'GITIGNOREFILES' previously defined here
[root@764daf5a1093 tpm2-tss]# 
```

**Comment by kgoldman** [comment]
I was missing autoconf-archive.  I assumed that dnf builddep tpm2-tss installed all the dependencies on Fedora, but apparently not.  The Fedora instructions are unclear.

Next error:

configure: error: Package requirements (uuid) were not met:

Package 'uuid', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables UUID_CFLAGS
and UUID_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

It is installed:

Package uuid-1.6.2-56.fc37.x86_64 is already installed.

**Comment by JuergenReppSIT** [comment]
I think the problem was that `dnf builddep tpm2-tss` did use tpm2-tss 3.2.2 which does not need libuuid while the current master needs libuuid
After `dnf install libuuid-devel` configure worked. Yes this problem should be mentioned in INSTALL.md.
