### ISSUE TITLE
Fapi_Decrypt with data, generated with imported key, returns: 589835

### ISSUE THREAD

**Issue by JordanLBogdanov** [tpm2-software/tpm2-tss#2591]
This error code: **589835** was returned by **Fapi_Decrypt**. The same data that was encrypted with imported key originating from the decrypting TPM.

I didn't managed to find out what the problem was from the TSS2_LOGFILE.
Here it is:
[tss2_logfile.txt](https://github.com/tpm2-software/tpm2-tss/files/11102027/tss2_logfile.txt)

**Comment by JuergenReppSIT** [comment]
@JordanLBogdanov For me it looks like the format of the passed TPM2B cipher is not ok. It should be a TPM2B probably with size 256 and the cipher text

**Comment by JuergenReppSIT** [comment]
> Does this process seem OK to you?

yes. But from your trace I saw that you did use an ECC key: P_ECCP256SHA256/HS/SRK/myRsaCryptKey.
Fapi_Enrypt/Decrypt only works for RSA keys.

**Comment by JordanLBogdanov** [comment]
Hmm.
That is very interesting. For me using ECC.
This is probably because of installing your private repository.
After that I cant seem to remember if I changed the profile in the fapi-config.json.

I will see to that first thing in the morning.

Thank you very much.

**Comment by JuergenReppSIT** [comment]
@JordanLBogdanov Sorry I forgot to mention that after make install the current fapi config file will be overwritten. So if this file was changed you should create a backup before make install. You also could create a own fapi config file and use `export TSS2_FAPICONF=your_config`.

**Comment by JordanLBogdanov** [comment]
@JuergenReppSIT I successfully encrypted and then decrypted data on different PC's using the same key.

Thank you very much for your cooperation.

**Comment by JuergenReppSIT** [comment]
@JordanLBogdanov And thank you very much for patiently testing FAPI!
