### ISSUE TITLE
Shorter encrypted data as hexadecimal value

### ISSUE THREAD

**Issue by JordanLBogdanov** [tpm2-software/tpm2-tss#2593]
When I use **Fapi_Encrypt(...)** (even on data of 12 bytes) the cipherText array contains the encrypted data as **-256 x 8bit-** values.

The length of the encrypted data is of no matter when the encr. data transfer happens via file.
In our case though we want to transfer the encr. data as human readable code.
Something of sorts: **73a3c81bb12f8f45de3918cc** (for authorization purposes).

My question:
- Can I get the encrypted data as a shorter hexadecimal code?

Thanks.

**Comment by JordanLBogdanov** [comment]
What is the reason for cipherText being 256 bytes long after encrypting data of 12 bytes?

**Comment by JuergenReppSIT** [comment]
> What is the reason for cipherText being 256 bytes long after encrypting data of 12 bytes?

because of the used padding.

**Comment by JordanLBogdanov** [comment]
Can we turn down this padding?

**Comment by JuergenReppSIT** [comment]
Without padding TPM will treat message as an unsigned integer and perform a modular exponentiation of message using the public exponent of the key. Also here you will get the size 256 for a RSA 2048 key.

**Comment by JordanLBogdanov** [comment]
Can I safely assume that 256 bytes is the smallest amount of produced encrypted data?
In other words, will data, bigger than 256 bytes, be encrypted in more than 256 bytes.

**Comment by JuergenReppSIT** [comment]
you can't encrypt data bigger than 256 bytes with RSA_Encrypt. The restrictions are described in the Specification (Table 44):
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjp1LeM9I3-AhVH26QKHZFPAaAQFnoECA4QAQ&url=https%3A%2F%2Ftrustedcomputinggroup.org%2Fwp-content%2Fuploads%2FTPM-Rev-2.0-Part-3-Commands-01.38.pdf&usg=AOvVaw3G7giIT7r5RJ3GWWF8aF4o

**Comment by JordanLBogdanov** [comment]
Thank you.
