### ISSUE TITLE
Fapi_NvRead(...) throws TSS2_FAPI_RC_NOT_PROVISIONED

### ISSUE THREAD

**Issue by JordanLBogdanov** [tpm2-software/tpm2-tss#2596]
When I try to read a **non-existing** nv index path (/nv/TPM/idx) the Fapi_NvRead throws this error, **TSS2_FAPI_RC_NOT_PROVISIONED**, which as stated in the readthedocs article on the function, points to FAPI was not provisioned. 

At this point of program execution fapi WAS provisioned.
Does it actually mean that the path is not-existent? 
And if so, shouldn't it throw:
**TSS2_FAPI_RC_BAD_PATH | if nvPath is not found.** or maybe even

**TSS2_FAPI_RC_PATH_NOT_FOUND | if a FAPI object path was not found during authorization.**

**Comment by JuergenReppSIT** [comment]
If i try to read I non existing nv index using the fapi command line tools I get the following output:
```
$ tss2_nvread -p /nv/Owner/not_existing -o-
ERROR:fapi:src/tss2-fapi/ifapi_keystore.c:523:rel_path_to_abs_path() ErrorCode (0x00060024) File /nv/Owner/not_existing does not exist. 
ERROR:fapi:src/tss2-fapi/ifapi_keystore.c:582:ifapi_keystore_load_async() ErrorCode (0x00060024) Object /nv/Owner/not_existing not found. 
ERROR:fapi:src/tss2-fapi/api/Fapi_NvRead.c:179:Fapi_NvRead_Async() ErrorCode (0x00060024) Could not open: /nv/Owner/not_existing 
ERROR:fapi:src/tss2-fapi/api/Fapi_NvRead.c:96:Fapi_NvRead() ErrorCode (0x00060024) NV_Read 
Fapi_NvRead(0x60024) - fapi:The path was not found
```
What was the FAPI nv path you did use?

**Comment by JordanLBogdanov** [comment]
The path was: "/nv/TPM/sampleID"

I will add TSS2_LOG_FILE in a couple of minutes.

**Comment by JordanLBogdanov** [comment]
Here it is the TSS2_LOGFILE:
[tss2_logfile.txt](https://github.com/tpm2-software/tpm2-tss/files/11178818/tss2_logfile.txt)

**Comment by JuergenReppSIT** [comment]
@JordanLBogdanov I can't reproduce this error.
Could you please attach the part of your C Program where you call Fapi_Provision and afterwards Fapi_NvRead?

**Comment by JordanLBogdanov** [comment]
There it is:

```
void Authenticator::authenticate()
{
    // holds the current parameters
    struct  core_parameters params;

    if (EXIT_SUCCESS !=  core_get_id(&params))
    {
        LOGERR("There was an error getting the IDs. Aborting...")
        return;
    }


    FAPI_CONTEXT * context;

    char const * uri = nullptr;

    int32_t r = Fapi_Initialize(&context, uri);

    if (TSS2_RC_SUCCESS != r)
    {
        LOGERR("There was an error initializing the FAPI -- %d", r)
    }


    r = Fapi_Provision(context, nullptr, nullptr, nullptr);

    if (TSS2_RC_SUCCESS != r)
    {
        LOGERR("There was an error while provisioning the FAPI -- %d", r)
    }

    uint8_t * data = nullptr;
    uint64_t dataSize = 0;

    // read from the TPM nvram
    r = Fapi_NvRead(context,
                    TPM_NV_LOCATION,
                    &data,
                    &dataSize,
                    nullptr);

    if (TSS2_FAPI_RC_BAD_PATH == r)
    {
        LOGERR("TPM NV path not found!")
        showMismatchCriticalError();
        return;
    }

    if (TSS2_RC_SUCCESS != r)
    {
        LOGERR("There was an error while reading from the TPM nvram."
                    "Error code: %d. Aborting...", r)
        return;
    }

    // at first check if the sizes of both the current BOARD ID and the one
    //      read from the NVRAM are equal
    if (static_cast<uint64_t>(params.buf_size) != dataSize)
    {
        LOGERR("The TPM nvram ID size and the current ID size "
                    "do not match. Aborting...")
        return;
    }

// ...
}
```

**Comment by JuergenReppSIT** [comment]
@JordanLBogdanov Thank you for sending the C file.
I tested your example with: `#define TPM_NV_LOCATION "/nv/TPM/sampleID"`
and got the return code `TSS2_FAPI_RC_PATH_NOT_FOUND`

**Comment by JordanLBogdanov** [comment]
Can you toss me a TSS_LOG_FILE please?

**Comment by JuergenReppSIT** [comment]
yes, here the log.
[fapi-log-nv-not-exists.txt](https://github.com/tpm2-software/tpm2-tss/files/11182948/fapi-log-nv-not-exists.txt)

**Comment by JordanLBogdanov** [comment]
Did you have an existing /nv folder in either:

**Comment by JordanLBogdanov** [comment]
Does an /nv folder existed, at the time of execution, in either locations: 
- /usr/local/var/lib/tpm2-tss/system/keystore
- ~/.local/share/tpm2-tss/user/keystore
... ?

**Comment by JuergenReppSIT** [comment]
@JordanLBogdanov  Thank you for debugging the problem.
Yes that's true. I think one solution would be to create the nv folder during provisioning  to indicate for this case that provisioning was executed.  I will create a PR next week.

**Comment by JordanLBogdanov** [comment]
What I saw during debugging made me thing that the problem is not of the not-existing /nv folder, but because the program execution enters the below-mentioned IF statement.

Here is the post I finished writing just as you answered the last Q

------------------------------------------------------------------------------------------------------------------------------------------------

While debugging **ifapi_check_provisioned(...)** I got confused a lot.
The **if** comment on line **1779** the comment says: **/* Check whether the path starts with a profile. */**

The **else** comment on line **1803** the comment says: **/* No check needed because no profile found in the path. */**

... even when the path doesnt have a profile (P_ | /P_) in its name, the IF statement is entered all the same.

Because of entering the IF statement, and subsequently checking for an existing folder **/nv**, the **OUT** parameter  is left with the initialization value of false.
When the **OUT**  parameter OK is left as it was, the following piece of code produces the error, that I get on my end, which is:  **TSS2_FAPI_RC_NOT_PROVISIONED**

```
        /* Check whether provisioning was made for the path profile. */
        r = ifapi_check_provisioned(keystore, rel_path, &provision_check_ok);
        goto_if_error(r, "Provisioning check.", cleanup);

        if (!provision_check_ok) {
            goto_error(r, TSS2_FAPI_RC_NOT_PROVISIONED,
                       "FAPI not provisioned for path: %s.",
                       cleanup, rel_path);
        }
```

![Screenshot_2023-04-08_15-28-29](https://user-images.githubusercontent.com/125969822/230721119-7b95d217-2f88-4d05-9ea5-114ba285615d.png)

**Comment by JordanLBogdanov** [comment]
I will try creating the /nv folder for now thought, and see what happens.

**Comment by JordanLBogdanov** [comment]
Creating the /nv folder did the trick. Thanks.

**Comment by JuergenReppSIT** [comment]
> Please notify me when the fix is added and to which repository: **yours** or the **main** one.

@JordanLBogdanov There is a PR: #2597.
The commit is also include in my private branch which includes all commits from the PR congestion. You can use this branch:
`git clone https://github.com/JuergenReppSIT/tpm2-tss.git`
`git checkout priv`
`bootstrap`
`configure`
`...`

**Comment by JordanLBogdanov** [comment]
@JuergenReppSIT I was away for 2 weeks and didnt get the chance to try it.
Will do now.

Thank you.
