### ISSUE TITLE
failed: tpm:parameter(1):structure is the wrong size (RC: 0x1d5)

### ISSUE THREAD

**Issue by wjzu2023** [tpm2-software/tpm2-tss#2601]
When set nvWriteDataSize of Tss2_Sys_NV_Write too big, it will take a error "failed: tpm:parameter(1):structure is the wrong size (RC: 0x1d5)",src code below: ` nvWriteData.size = 1024;
    for (i = 0; i < nvWriteData.size; i++) {
        nvWriteData.buffer[i] = 'a';
    }

    /* Attempt write with the correct password. It should pass. */
    rval = TSS2_RETRY_EXP (Tss2_Sys_NV_Write (sapi_context,
                              TPM20_INDEX_PASSWORD_TEST,
                              TPM20_INDEX_PASSWORD_TEST,
                              &cmd_auths,
                              &nvWriteData,
                              0,
                              &rsp_auths));

    //return_if_error (rval, "Tss2_Sys_NV_Write");
    /* Check that the function passed as expected.  Otherwise, exit. */
    if (rval != TSS2_RC_SUCCESS) {
            RC_WARN("Tss2_Sys_NV_Write: ... ", rval);

	g_warning("Failed to write in NV with correct password. RC = 0x%x", rval);
	return 1;
    }`
What is the maximum write data size  Tss2_Sys_NV_Write  support ?

**Comment by JuergenReppSIT** [comment]
The property TPM2_PT_NV_BUFFER_MAX defines the max size.
Example similar to what FAPI does to determine this size:
```
TPMI_YES_NO moreData;
TPMS_CAPABILITY_DATA *capability;
UINT32 nv_buffer_max; 
r = Esys_GetCapability(esys_ctx, ESYS_TR_NONE, ESYS_TR_NONE, ESYS_TR_NONE,
                       TPM2_CAP_TPM_PROPERTIES, TPM2_PT_NV_BUFFER_MAX, 1,
                       &moreData, &capability);
// check r
if (capability->data.tpmProperties.count == 1 &&
   capability->data.tpmProperties.tpmProperty[0].property ==
   TPM2_PT_NV_BUFFER_MAX) {
   nv_buffer_max = capability->data.tpmProperties.tpmProperty[0].value;
} else {
   nv_buffer_max = 64;
}
```

**Comment by wjzu2023** [comment]
> The property TPM2_PT_NV_BUFFER_MAX defines the max size. Example similar to what FAPI does to determine this size:
> 
> ```
> TPMI_YES_NO moreData;
> TPMS_CAPABILITY_DATA *capability;
> UINT32 nv_buffer_max; 
> r = Esys_GetCapability(esys_ctx, ESYS_TR_NONE, ESYS_TR_NONE, ESYS_TR_NONE,
>                        TPM2_CAP_TPM_PROPERTIES, TPM2_PT_NV_BUFFER_MAX, 1,
>                        &moreData, &capability);
> // check r
> if (capability->data.tpmProperties.count == 1 &&
>    capability->data.tpmProperties.tpmProperty[0].property ==
>    TPM2_PT_NV_BUFFER_MAX) {
>    nv_buffer_max = capability->data.tpmProperties.tpmProperty[0].value;
> } else {
>    nv_buffer_max = 64;
> }
> ```

The macro TPM2_PT_NV_BUFFER_MAX value is 300, but I use Tss2_Sys_NV_Write to write 712 bytes data one write (no error). So what is the maximum value for one write?

**Comment by wjzu2023** [comment]
> > The macro TPM2_PT_NV_BUFFER_MAX value is 300, but I use Tss2_Sys_NV_Write to write 712 bytes data one write (no error). So what is the maximum value for one write?
> 
> The TPM Spec (https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p59_Part2_Structures_pub.pdf) Table 23 says TPM2_PT_NV_BUFFER_MAX is the maximum value. I would recommend to split the writing of larger buffers according to this value.

In fact, I can write 768 bytes data one write and also can read 768 bytes data one read. Could you double check that?

**Comment by JuergenReppSIT** [comment]
> In fact, I can write 768 bytes data one write and also can read 768 bytes data one read. Could you double check that?

That might be vendor specific.  As I said I would recommend to split the writes according to the value of  TPM2_PT_NV_BUFFER_MAX to be vendor independent.

**Comment by wjzu2023** [comment]
> > In fact, I can write 768 bytes data one write and also can read 768 bytes data one read. Could you double check that?
> 
> That might be vendor specific. As I said I would recommend to split the writes according to the value of TPM2_PT_NV_BUFFER_MAX to be vendor independent.

Thanks.
