### ISSUE TITLE
Implement a tpm_send.exe

### ISSUE THREAD

**Issue by AndreasFuchsTPM** [tpm2-software/tpm2-tss#2619]
In order to support access to TPMs from WSL2, we can implement a tpm_send.exe Windows version, that is then opened via the tcti-cmd using stdin/stdout in order to transfer commands.

**Comment by joholl** [comment]
Why take a detour like that? Wouldn't it be better to have a tcti-wsl2 instead (without extra process, pipes and the need to compile another binary). This would probably be less work.

Any idea on how to access the TPM on Windows/WSL2?

**Comment by joholl** [comment]
@AndreasFuchsTPM I did [a thing](https://github.com/joholl/tpm2-send).

Currently, this uses static 4k buffers (stdin handling in linux didn't let me fseek and than malloc easily). There are other things, which can be improved, but for now it should serve our needs. I did test it on WSL2, but not in combination with the TSS. Let me know if it works for you.

Also, we can move this to the `tpm2-software` namespace, if you want.

**Comment by joholl** [comment]
Ok, we have [tpm2-send-tbs](https://github.com/tpm2-software/tpm2-send-tbs) now. Granted, it still has limitations, but it is a start.

Example:

```bash
tpm2_getrandom -T "cmd: build/hex | build/tpm2-send-tbs.exe | build/unhex" --hex 4
```
