### ISSUE TITLE
NVram with sensitive data

### ISSUE THREAD

**Issue by JordanLBogdanov** [tpm2-software/tpm2-tss#2634]
I have 2 questions about writing sensitive data in the **TPM's NVRAM** :
- Can the data be **extracted**?
- When is the data **permanently lost**?

**Comment by JuergenReppSIT** [comment]
* Sensitive data stored in NVRAM should be protected by passwords or extended authorization (EA) policies.
* The data will be lost after executing `TPM2_Clear` or `TPM2_NV_UndefineSpace`

**Comment by JuergenReppSIT** [comment]
@JordanLBogdanov you should check the technical info of your BIOS what's exactly the functionality of "BIOS NVram Clear".

**Comment by JordanLBogdanov** [comment]
Thank you.
