### ISSUE TITLE
TPM's Nvram writing capabilities

### ISSUE THREAD

**Issue by JordanLBogdanov** [tpm2-software/tpm2-tss#2635]
What is TPM's NVram memory lifetime number of **writes**?
That is before it starts experiencing glitches, or even a breakdown.

If this is not in your area of expertise I am sorry.

**Comment by JordanLBogdanov** [comment]
Thank you @JuergenReppSIT .

**Comment by JordanLBogdanov** [comment]
@JuergenReppSIT does **Fapi_NvRead** counts toward that maximum number of cycles, or only just **Fapi_NvWrite**.

I know it says: Maximum number of **write** cycles, but I need to be sure.

**Comment by JuergenReppSIT** [comment]
@JordanLBogdanov To be sure I would say you should contact the vendor of your TPM.

**Comment by JordanLBogdanov** [comment]
Thank you.
