### ISSUE TITLE
Is FAPI supposed to work without `HAVE_CONFIG_H`?

### ISSUE THREAD

**Issue by Akuli** [tpm2-software/tpm2-tss#2660]
In a project I am working on, `#include <config.h>` tends to pick up whatever garbage is already in the include path and cannot be used. So I added a file that `#undef`s `HAVE_CONFIG_H`.

Turns out that wasn't enough, and I also had to include `<ctype.h>` in my new file:

https://github.com/tpm2-software/tpm2-tss/blob/74e8294ca7b0280957a518c1bab0266510962870/src/tss2-fapi/ifapi_keystore.c#L7-L11

Are the standard-library includes supposed to be inside the ifdef?

**Comment by JuergenReppSIT** [comment]
> Are the standard-library includes supposed to be inside the ifdef

No I will fix it.
