### ISSUE TITLE
TCTI for TBS on Windows

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#268]
Windows support requires a TCTI for use of the TBS (https://msdn.microsoft.com/en-us/library/windows/desktop/aa446792(v=vs.85).aspx). The TBS is effectively the a resource manager / tpm access broker for Windows.

There is a PR from almost a year ago in the PR queue. @wcarthur1 asked the author for some cleanup that never happened. This must be done, and built as a library (see #267) before we advertise Windows support.

**Comment by flihp** [comment]
superseded by #276

**Comment by flihp** [comment]
PR #82 has an implementation of a TCTI for use with TBS. Anyone interested in Windows support should us this as a starting place.

**Comment by flihp** [comment]
Reopening and tagging 'help wanted'.

**Comment by tstruk** [comment]
At this stage resource manager & access broker for Windows is out of scope for this project.
ABRMD lives in a separate repo https://github.com/tpm2-software/tpm2-abrmd.
Closing the issue.

**Comment by flihp** [comment]
This issue may have been closed a bit prematurely. This isn't so much about implementing any sort of resource management on Windows. Instead it's intended to track the implementation of a TCTI capable of communicating with the existing resource manager in Windows. Microsoft calls this interface / component TBS: https://docs.microsoft.com/en-us/windows/desktop/tbs/about-tbs

This is required if we intend for Windows users to interact with the TPM integrated into their platform. Without it we can only support the software TPM2 simulator and that's not useful for anything other than testing.

If I'm missing something feel free to close this issue again and fill me in on what I'm misunderstanding.

**Comment by tstruk** [comment]
The title was a bit misleading.
In this case I would rename it to something like:
"TCTI for TBS on Windows"

**Comment by flihp** [comment]
works for me
