### ISSUE TITLE
Support for cmake build on Windows

### ISSUE THREAD

**Issue by pulsejet** [tpm2-software/tpm2-tss#2687]
Question for maintainers: would it make sense to support a cmake build on Windows, especially on Windows? I _might_ be able to contribute this but wanted to make sure it makes sense and a PR could be accepted.

**Comment by JuergenReppSIT** [comment]
Unfortunately I can't review such a PR because I have no Windows. @AndreasFuchsTPM what do you think of this suggestion?

**Comment by AndreasFuchsTPM** [comment]
Would be great.
Please provide a PR on this.
