### ISSUE TITLE
Esys_TR_Close needs to reference count

### ISSUE THREAD

**Issue by ddstreet** [tpm2-software/tpm2-tss#2693]
The Esys_TR_Close() function needs to reference count before removing the handle reference, as it may still be in use by other callers that use the same context.

**Comment by ddstreet** [comment]
Example reproducer:

```
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>

#include <tss2/tss2_esys.h>
#include <tss2/tss2_rc.h>
#include <tss2/tss2_tcti_swtpm.h>

int create_tcti(TSS2_TCTI_CONTEXT **ret_tcti) {
        TSS2_RC rc;
        size_t tcti_sz;
        rc = Tss2_Tcti_Swtpm_Init(NULL, &tcti_sz, NULL);
        if (rc != TSS2_RC_SUCCESS) {
                printf("Failed to get TCTI size: %s\n", Tss2_RC_Decode(rc));
                return -1;
        }

        TSS2_TCTI_CONTEXT *tcti;
        tcti = malloc(tcti_sz);
        if (!tcti) {
                printf("OOM\n");
                return -ENOMEM;
        }
        memset(tcti, 0, tcti_sz);

        rc = Tss2_Tcti_Swtpm_Init(tcti, &tcti_sz, "path=/tmp/swtpm/socket");
        if (rc != TSS2_RC_SUCCESS) {
                printf("Failed to init TCTI: %s\n", Tss2_RC_Decode(rc));
                return -1;
        }

        *ret_tcti = tcti;

        return 0;
}

int main(int argc, char *argv[]) {
        TSS2_TCTI_CONTEXT *tcti;
        ESYS_CONTEXT *c;
        TSS2_RC rc;
        int r;

        r = create_tcti(&tcti);
        if (r < 0)
                return r;

        rc = Esys_Initialize(&c, tcti, NULL);
        if (rc != TSS2_RC_SUCCESS) {
                printf("Failed to initialize: %s\n", Tss2_RC_Decode(rc));
                return -1;
        }

        TPM2B_PUBLIC template = {
                .size = sizeof(TPMT_PUBLIC),
                .publicArea = {
                        .type = TPM2_ALG_RSA,
                        .nameAlg = TPM2_ALG_SHA256,
                        .objectAttributes = TPMA_OBJECT_RESTRICTED|TPMA_OBJECT_DECRYPT|TPMA_OBJECT_FIXEDTPM|TPMA_OBJECT_FIXEDPARENT|TPMA_OBJECT_SENSITIVEDATAORIGIN|TPMA_OBJECT_USERWITHAUTH,
                        .parameters.rsaDetail = {
                                .symmetric = {
                                        .algorithm = TPM2_ALG_AES,
                                        .keyBits.aes = 128,
                                        .mode.aes = TPM2_ALG_CFB,
                                },
                                .scheme.scheme = TPM2_ALG_NULL,
                                .keyBits = 2048,
                        },
                },
        };
        ESYS_TR handle1;
        rc = Esys_CreatePrimary(c,
                                ESYS_TR_RH_OWNER,
                                ESYS_TR_PASSWORD, ESYS_TR_NONE, ESYS_TR_NONE,
                                &(TPM2B_SENSITIVE_CREATE){},
                                &template,
                                NULL,
                                &(TPML_PCR_SELECTION){},
                                &handle1,
                                NULL, NULL, NULL, NULL);
        if (rc != TSS2_RC_SUCCESS) {
                printf("Failed to create primary: %s\n", Tss2_RC_Decode(rc));
                return -1;
        }

        TPM2_HANDLE index1;
        rc = Esys_TR_GetTpmHandle(c, handle1, &index1);
        if (rc != TSS2_RC_SUCCESS) {
                printf("Failed to get index1: %s\n", Tss2_RC_Decode(rc));
                return -1;
        }

        printf("Created primary at handle index 0x%08x\n", index1);

        ESYS_TR handle2;
        rc = Esys_TR_FromTPMPublic(c, index1, ESYS_TR_NONE, ESYS_TR_NONE, ESYS_TR_NONE, &handle2);
        if (rc != TSS2_RC_SUCCESS) {
                printf("Failed to get handle2 for index1 0x%08x: %s\n", index1, Tss2_RC_Decode(rc));
                return -1;
        }

        TPM2_HANDLE index2;
        rc = Esys_TR_GetTpmHandle(c, handle2, &index2);
        if (rc != TSS2_RC_SUCCESS) {
                printf("Failed to get index2: %s\n", Tss2_RC_Decode(rc));
                return -1;
        }

        printf("Now have handle1 with index 0x%08x and handle2 with index 0x%08x\n", index1, index2);

        rc = Esys_TR_Close(c, &handle2);
        if (rc != TSS2_RC_SUCCESS) {
                printf("Failed to close handle2: %s\n", Tss2_RC_Decode(rc));
                return -1;
        }

        printf("Closed handle2, now flushing handle1\n");

        rc = Esys_FlushContext(c, handle1);
        if (rc != TSS2_RC_SUCCESS) {
                printf("Failed to flush handle1: %s\n", Tss2_RC_Decode(rc));
                return -1;
        }

        return 0;
}

```

**Comment by ddstreet** [comment]
Note, that reproducer obviously is using a swtpm at /tmp/swtpm/socket, adjust as necessary if using swtpm somewhere else or using a real tpm.

**Comment by ddstreet** [comment]
> From the docu: "This function can be used to create ESYS_TR object for Tpm Resources that are **not** created or loaded (e.g. using ESys_CreatePrimary or ESys_Load) but **pre-exist** inside the TPM. Examples are NV-Indices or persistent object."
> 
> The the actual bug here would be that
> 
> ```
> rc = Esys_TR_FromTPMPublic(c, index1, ESYS_TR_NONE, ESYS_TR_NONE, ESYS_TR_NONE, &handle2);
> ```
> 
> is supposed to fail.

That is incorrect. The transient handle *does* exist in the TPM, we just created it.

> 
> Now the question is, if we actually want to do this, or if we think that this functionality is useful, but we add a **huge** warning to the documentation.

I think you misunderstand this bug.

**Comment by JuergenReppSIT** [comment]
In the example `Esys_TR_FromTPMPublic` called with the TPM handle `index1` returns  the handle of the existing esys object with TPM handle `index1`.  So `handle1 == handle2`

**Comment by ddstreet** [comment]
> In the example `Esys_TR_FromTPMPublic` called with the TPM handle `index1` returns the handle of the existing esys object with TPM handle `index1`. So `handle1 == handle2`

This is an API; to the application using the API, they are opaque handles. You shouldn't provide applications a way to 'remove' an opaque handle if the application could have multiple references to the opaque handle and you don't perform reference counting. I mean, that is the entire point of reference counting.

**Comment by AndreasFuchsTPM** [comment]
The API was explicitly designed to not require reference counting.
The two problems here are:
- The implementation allows calling Esys_TR_FromTPMPublic() on transient handles, which it should not. This by itself was however not a problem in the past.
- The call for Esys_TR_GetTpmHandle() was only introduced later.

What I am trying to say is: Using a combination of Esys_TR_GetTpmHandle() to retrieve a transient handle that is then passed into Esys_TR_FromTPMPublic() was never envisioned or is an encouraged use.

However, I looked back over what is shown in the code, and I agree that it should not fail.

The sequence
```
Create()->handle1
FromTPMPublic()->handle2
Close(handle2)
Flush(handle1)
```
should work.
(Note, if we switch the Flush and the Close it will obviously fail)

This also has nothing to do with reference counting. handle1 and handle2 should be independent objects and the Close(handle2) should have no side-effect on handle1 whatsoever.

I guess we will need to look into why this Close(handle2) influences handle1.

**Comment by AndreasFuchsTPM** [comment]
Thinking about it: We did the handle1==handle2 thin because for global singletons (Hierarchies and similar) we wanted to synchronize them. But they also do not allow for Close().
I wonder what we should do for e.g. NV-indices ? handle1==handle2 oder separate ?
I guess we have handle1==handle2 there as well, since we synchronize e.g. setAuth() / changeAuth values.
I guess this needs even more rework... :-(

**Comment by JuergenReppSIT** [comment]
> I guess we have handle1==handle2 there as well, since we synchronize e.g. setAuth() / changeAuth values

yes nv_tr_handle1==nv_tr_handle2 was introduced with:
https://github.com/tpm2-software/tpm2-tss/commit/6c88eea4a3d2440dc95f1a3dbc48c39dde017c92

**Comment by ddstreet** [comment]
> * The implementation allows calling Esys_TR_FromTPMPublic() on transient handles, which it should not.

why? if this is true, then there is no way in the EAPI to access a transient handle object/key using only its handle 'index'. Since there is no way for end users to specify a TPM handle other than using its 'index', that means there is no way for code to accept input from end users that specifies a transient object/key.

unless i'm misunderstanding something, that sounds like an unnecessary artificial limitation.

> This by itself was however not a problem in the past.
> * The call for Esys_TR_GetTpmHandle() was only introduced later.
> 
> What I am trying to say is: Using a combination of Esys_TR_GetTpmHandle() to retrieve a transient handle that is then passed into Esys_TR_FromTPMPublic() was never envisioned or is an encouraged use.

the combination of these two has nothing to do with the problem. Consider this:

```
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>

#include <tss2/tss2_esys.h>
#include <tss2/tss2_rc.h>
#include <tss2/tss2_tctildr.h>

int main(int argc, char *argv[]) {
        TSS2_TCTI_CONTEXT *tcti;
        ESYS_CONTEXT *c;
        TSS2_RC rc;

        char *tcti_conf = NULL;
        if (argc > 1)
                tcti_conf = argv[1];

        rc = Tss2_TctiLdr_Initialize(tcti_conf, &tcti);
        if (rc != TSS2_RC_SUCCESS) {
                printf("Failed to init TCTI: %s\n", Tss2_RC_Decode(rc));
                return -1;
        }

        rc = Esys_Initialize(&c, tcti, NULL);
        if (rc != TSS2_RC_SUCCESS) {
                printf("Failed to initialize: %s\n", Tss2_RC_Decode(rc));
                return -1;
        }

        ESYS_TR handle1;
        rc = Esys_TR_FromTPMPublic(c, 0x81000001, ESYS_TR_NONE, ESYS_TR_NONE, ESYS_TR_NONE, &handle1);
        if (rc != TSS2_RC_SUCCESS) {
                printf("Failed to get handle1 for index 0x81000001: %s\n", Tss2_RC_Decode(rc));
                return -1;
        }

        printf("Got handle1 %x\n", handle1);

        ESYS_TR handle2;
        rc = Esys_TR_FromTPMPublic(c, 0x81000001, ESYS_TR_NONE, ESYS_TR_NONE, ESYS_TR_NONE, &handle2);
        if (rc != TSS2_RC_SUCCESS) {
                printf("Failed to get handle2 for index 0x81000001: %s\n", Tss2_RC_Decode(rc));
                return -1;
        }

        printf("Got handle2 %x\n", handle2);

        rc = Esys_TR_Close(c, &handle1);
        if (rc != TSS2_RC_SUCCESS) {
                printf("Failed to close handle1: %s\n", Tss2_RC_Decode(rc));
                return -1;
        }

        printf("Closed handle1, now closing handle2\n");

        rc = Esys_TR_Close(c, &handle2);
        if (rc != TSS2_RC_SUCCESS) {
                printf("Failed to close handle2: %s\n", Tss2_RC_Decode(rc));
                return -1;
        }

        return 0;
}

```

>  ./test
> Got handle1 40418488
> Got handle2 40418488
> Closed handle1, now closing handle2
> ERROR:esys:src/tss2-esys/esys_tr.c:434:Esys_TR_Close() Error: Esys handle does not exist (0x00070018). 
> Failed to close handle2: esapi:The ESYS_TR resource object is bad
> 

no use of GetTPMHandle() at all. And it's not using a transient handle, either (it's getting a handle for the SRK). And yet once the handle1 is 'closed', handle2 becomes unusable. This is why I said the library needs to implement reference counting (or, don't return the same handle for multiple callers).

> 
> However, I looked back over what is shown in the code, and I agree that it should not fail.
> 
> The sequence
> 
> ```
> Create()->handle1
> FromTPMPublic()->handle2
> Close(handle2)
> Flush(handle1)
> ```
> 
> should work. (Note, if we switch the Flush and the Close it will obviously fail)
> 
> This also has nothing to do with reference counting. handle1 and handle2 should be independent objects and the Close(handle2) should have no side-effect on handle1 whatsoever.

right, that's the other way to handle it (reference counting the same handle object would work as well).

> 
> I guess we will need to look into why this Close(handle2) influences handle1.
> 
> Edit: Even worse, handle1 and handle2 should not be the same value.

since it's an opaque handle, it doesn't (and shouldn't) matter to the caller if they are the same value or not; that's totally an implementation detail.
