### ISSUE TITLE
TPM2_MAX_SYM_DATA should be 128

### ISSUE THREAD

**Issue by ddstreet** [tpm2-software/tpm2-tss#2694]
TPM2_MAX_SYM_DATA is defined as 256, but per spec should be 128.

TPM specification Part 2 ("Structures") section "TPMU_SENSITIVE_CREATE" states "For interoperability, MAX_SYM_DATA should be 128."

It actually used to be set to 128, but commit 35750de13af0b2aa4e82e24308a99c7e0f06c961 incorrectly (probably accidentally?) changed the value to 256.

**Comment by ddstreet** [comment]
Since libtpms uses the spec-mandated value (https://github.com/stefanberger/libtpms/blob/master/src/tpm2/TpmProfile.h#L302) this means the widely-used swtpm enforces MAX_SYM_DATA at 128, so any system using tpm2-tss for the MAX_SYM_DATA size while interacting with a swtpm-provided TPM will fail if it tries to seal between 129-256 bytes.

**Comment by AndreasFuchsTPM** [comment]
Actually, we use higher values for all buffers in the TSS in order to be future proof wrt the ABI, if the TPMs decide to support larger stuff in the future.
So this was intentional.
Of course you can only fill the buffer up to the max value supported by the TPM.
