### ISSUE TITLE
How to change encryption scheme from ECC to RSA?

### ISSUE THREAD

**Issue by dj-d** [tpm2-software/tpm2-tss#2698]
Hello,

I am trying to use the ```encryption``` function but I receive the following error:
```
ERROR:fapi:src/tss2-fapi/api/Fapi_Encrypt.c:332:Fapi_Encrypt_Finish() ErrorCode (0x00060002) ECC Encryption not yet supported
fapi:If called functionality isn't implemented
ERROR:fapi:src/tss2-fapi/api/Fapi_Encrypt.c:126:Fapi_Encrypt() ErrorCode(0x00060002) Data_Encrypt
```

How can I change the encryption scheme from ECC to RSA?

Thanks

**Comment by JuergenReppSIT** [comment]
You can change the used profile in FAPI config file from P_ECCP256SHA256 to P_RSA2048SHA256.  If you still want to use the ECC profile as default you could create a second config file and execute the provisioning with the environment variable TSS2_FAPICONF set. If you use the tpm tools e.g. as follows:
 `TSS2_FAPICONF=/usr/local/etc/tpm2-tss/fapi-config-rsa.json tss2_provision`
But you must change or remove the default handle 0x81000001 for the SRK in the RSA profile file. Afterwards you can create a RSA key e.g.:
```
 tss2_createkey -p /P_RSA2048SHA256/HS/SRK/mykey
 echo secret| tss2_encrypt -p /P_RSA2048SHA256/HS/SRK/mykey -i- -o encsecret
 tss2_decrypt -i encsecret -p /P_RSA2048SHA256/HS/SRK/mykey -o-
```
To find the files which have to be changed you can display the paths used by FAPI with:
`tss2_getinfo -o-| more`

**Comment by dj-d** [comment]
Perfect, it works

However, I had to add `"ek_cert_less": "yes"` to the `fapi-config-rsa.json` file because it was giving me error on certificates when running `tss2_provision`.

Is this correct as a solution or should I do it some other way?

**Comment by JuergenReppSIT** [comment]
If the provisioning did work for the ecc profile it should also work for the rsa profile without adding the `ek_cert_less` option for your TPM?

**Comment by dj-d** [comment]
No, even for ECC I had to add this option.
What should I do to avoid adding this option?

**Comment by JuergenReppSIT** [comment]
FAPI has a list of vendor certificates which can be used to verify the EK. If your vendor is not in this list or if you are using a simulator you have to use the `ek_cert_less` option.
you can get the vendor information with the tpm tools:
`tpm2_getcap properties-fixed| grep -A 2 VENDOR`

**Comment by dj-d** [comment]
Perfect, since I am using a simulator the use of the `ek_cert_less` option is correct.

Thank you
