### ISSUE TITLE
new release containig ltt2go

### ISSUE THREAD

**Issue by holgerfriedrich** [tpm2-software/tpm2-tss#2703]
Can you give an estimate when a new release containing ltt2go (also with the final naming) will be done?

Debian is currently updating to 4.0.1
https://tracker.debian.org/pkg/tpm2-tss

It would be good to include the tpm2go into the official packaging, but 4.0.1 is probably not a good choice due to later renaming.

Thanks!

**Comment by AndreasFuchsTPM** [comment]
The plan is: "Before end of the year"
