### ISSUE TITLE
Fapi_NvRead occasionally throws error 2337

### ISSUE THREAD

**Issue by JordanLBogdanov** [tpm2-software/tpm2-tss#2705]
When calling the Fapi_NvRead function, it **sometimes** returns this error code: 2337, which I cannot find what it is about.

I am attaching log file.
[tss2_logfile.txt](https://github.com/tpm2-software/tpm2-tss/files/13320779/tss2_logfile.txt)

And the code where it is used:
[get_current_date.txt](https://github.com/tpm2-software/tpm2-tss/files/13320785/get_current_date.txt)

**Comment by JuergenReppSIT** [comment]
The TPM is in lockout mode.  From fapi-profile man page: 
newMaxTries: Count of authorization failures before the lockout is imposed.  If not set the default is 5.
So there were more than 5 unsuccessful authorizations previously?

**Comment by JordanLBogdanov** [comment]
We are not using any functions for authorization.

Currently we are only storing data in TPM's NVram

The functions called are:
Fapi_Init
Fapi_Provision
And the functions to create, read and write to the TPM's NVram.

**Comment by JuergenReppSIT** [comment]
If the TPM is available  again and the TPM tools are installed you can check the counters related to the lockout with:
` tss2_getinfo -o- | grep -A 18 LOCKOUT_COUNTER`
If the command which did produce your log is executed the LOCKOUT_COUNTER should not be incremented?

**Comment by JordanLBogdanov** [comment]
Where can I get these tools?

**Comment by JuergenReppSIT** [comment]
The fapi commands do not seem to be not included in the ubuntu package which is installed with the package manager.
You can use ` tpm2_getcap properties-variable` instead.

**Comment by JordanLBogdanov** [comment]
I did manage to bring up the counters using the last command.


I am uploading the result of executing this command when it is not throwing the aforementioned error so you could see if there is something else in these counters that could point to the issue.

**TPM2_PT_PERMANENT**:
  ownerAuthSet:              0
  endorsementAuthSet:        0
  lockoutAuthSet:            0
  reserved1:                 0
  disableClear:              0
  inLockout:                 0
  tpmGeneratedEPS:           1
  reserved2:                 0
TPM2_PT_STARTUP_CLEAR:
  phEnable:                  1
  shEnable:                  1
  ehEnable:                  1
  phEnableNV:                1
  reserved1:                 0
  orderly:                   1
TPM2_PT_HR_NV_INDEX: 0x9
TPM2_PT_HR_LOADED: 0x0
TPM2_PT_HR_LOADED_AVAIL: 0x5
TPM2_PT_HR_ACTIVE: 0x0
TPM2_PT_HR_ACTIVE_AVAIL: 0x40
TPM2_PT_HR_TRANSIENT_AVAIL: 0x5
TPM2_PT_HR_PERSISTENT: 0x1
TPM2_PT_HR_PERSISTENT_AVAIL: 0x9
TPM2_PT_NV_COUNTERS: 0x0
TPM2_PT_NV_COUNTERS_AVAIL: 0xC
TPM2_PT_ALGORITHM_SET: 0xFFFFFFFF
TPM2_PT_LOADED_CURVES: 0x3
**TPM2_PT_LOCKOUT_COUNTER**: 0x0
TPM2_PT_MAX_AUTH_FAIL: 0x5
TPM2_PT_LOCKOUT_INTERVAL: 0x3E8
TPM2_PT_LOCKOUT_RECOVERY: 0x3E8
TPM2_PT_NV_WRITE_RECOVERY: 0x0
TPM2_PT_AUDIT_COUNTER_0: 0x0
TPM2_PT_AUDIT_COUNTER_1: 0x0

Currently I am trying to recreate the error to see what will be the value of the **TPM2_PT_LOCKOUT_COUNTER**.

**Comment by JordanLBogdanov** [comment]
I did manage to recreate the error.
These are the reading from executing: **tpm2_getcap properties-variable**

**TPM2_PT_PERMANENT**:
  ownerAuthSet:              0
  endorsementAuthSet:        0
  lockoutAuthSet:            0
  reserved1:                 0
  disableClear:              0
  inLockout:                 0
  tpmGeneratedEPS:           1
  reserved2:                 0
TPM2_PT_STARTUP_CLEAR:
  phEnable:                  1
  shEnable:                  1
  ehEnable:                  1
  phEnableNV:                1
  reserved1:                 0
  orderly:                   0
TPM2_PT_HR_NV_INDEX: 0x9
TPM2_PT_HR_LOADED: 0x0
TPM2_PT_HR_LOADED_AVAIL: 0x5
TPM2_PT_HR_ACTIVE: 0x0
TPM2_PT_HR_ACTIVE_AVAIL: 0x40
TPM2_PT_HR_TRANSIENT_AVAIL: 0x5
TPM2_PT_HR_PERSISTENT: 0x1
TPM2_PT_HR_PERSISTENT_AVAIL: 0x9
TPM2_PT_NV_COUNTERS: 0x0
TPM2_PT_NV_COUNTERS_AVAIL: 0xC
TPM2_PT_ALGORITHM_SET: 0xFFFFFFFF
TPM2_PT_LOADED_CURVES: 0x3
TPM2_PT_LOCKOUT_COUNTER: 0x2
TPM2_PT_MAX_AUTH_FAIL: 0x5
TPM2_PT_LOCKOUT_INTERVAL: 0x3E8
TPM2_PT_LOCKOUT_RECOVERY: 0x3E8
TPM2_PT_NV_WRITE_RECOVERY: 0x0
TPM2_PT_AUDIT_COUNTER_0: 0x0
TPM2_PT_AUDIT_COUNTER_1: 0x0

**Comment by JuergenReppSIT** [comment]
you could temporally increase the max lockout counter to e.g. 100 with:
`tpm2_dictionarylockout  --setup-parameters --max-tries=100 --clear-lockout`
to avoid the lockout mode.
and try to produce a trace of the command which causes to increase the lockout counter. There should be a bad auth message in the log.

**Comment by JordanLBogdanov** [comment]
Will try that, but could there be an auth problem, when we are only using the TPM to read/write to/from the TPM's NVRAM?

**Comment by JuergenReppSIT** [comment]
There should be no problem with your application. But obviously the lockout counter was incremented. So we should try to get a log where the counter is incremented before the lockout mode is activated.

**Comment by JordanLBogdanov** [comment]
I tried to increase the LOCKOUT_COUNTER to 100 with the aforementioned command, but I feel like it didnt worked, because it still gets to only 5, and not more.
How can I check if the command has worked or not? Where is this value stored?

**Comment by JuergenReppSIT** [comment]
Example how to set and check MAX_AUTH_FAIL:
```
$ tpm2_getcap properties-variable| grep MAX_AUTH_FAIL
TPM2_PT_MAX_AUTH_FAIL: 0x5
$ tpm2_dictionarylockout --setup-parameters --max-tries=100 --clear-lockout
$ tpm2_getcap properties-variable| grep MAX_AUTH_FAIL
TPM2_PT_MAX_AUTH_FAIL: 0x64
```
You could produce a trace for every command.  And check whether the fail counter was increased afterwards.

**Comment by JordanLBogdanov** [comment]
Result:
root@ubuntu:/home/user# tpm2_getcap properties-variable| grep MAX_AUTH_FAIL
TPM2_PT_MAX_AUTH_FAIL: 0x5
root@ubuntu:/home/user# tpm2_dictionarylockout --setup-parameters --max-tries=100 --clear-lockout
root@ubuntu:/home/user# tpm2_getcap properties-variable| grep MAX_AUTH_FAIL
TPM2_PT_MAX_AUTH_FAIL: 0x5

**Comment by JordanLBogdanov** [comment]
I will do that as soon as I get a chance. Thank you.

**Comment by JordanLBogdanov** [comment]
@JuergenReppSIT I am struggling a bit to find exactly where does this counter increments.
One other thought came to me. 
I do not call **Fapi_Finalize()** when I am done with the context. Will do surely.
Just wanted to ask you, could this be the problem?

I found that some file descriptors are not being closed when a Fapi_NvRead finishes execution, which causes a crash after a while. But will describe that issue in another thread.

**Comment by JuergenReppSIT** [comment]
> Just wanted to ask you, could this be the problem?

@JordanLBogdanov  I would say that could not cause your problem.

**Comment by JordanLBogdanov** [comment]
Hello @JuergenReppSIT. 
This week I managed to get back to work on the aforementioned problem.
I have not found any place in our codebase where the **TPM2_PT_LOCKOUT_COUNTER** is being incremented.

Here is a sample of the logs I generated whenever a **Fapi_*** function is being called

```
Counter BEFORE Fapi_Initialize(...) ----------- TPM2_PT_LOCKOUT_COUNTER: 0x1
Counter AFTER Fapi_Initialize(...) ----------- TPM2_PT_LOCKOUT_COUNTER: 0x1


Counter BEFORE Fapi_Provision(...) ----------- TPM2_PT_LOCKOUT_COUNTER: 0x1
Counter AFTER Fapi_Provision(...) ----------- TPM2_PT_LOCKOUT_COUNTER: 0x1


Counter BEFORE Fapi_NvRead(...) ----------- TPM2_PT_LOCKOUT_COUNTER: 0x1
Counter AFTER Fapi_NvRead(...) ----------- TPM2_PT_LOCKOUT_COUNTER: 0x1


Counter BEFORE Fapi_Finalize(...) ----------- TPM2_PT_LOCKOUT_COUNTER: 0x1
Counter AFTER Fapi_Finalize(...) ----------- TPM2_PT_LOCKOUT_COUNTER: 0x1

-------------------------------------------

currentDate - 202311291642


-------------------------------------------

Counter BEFORE Fapi_Initialize(...) ----------- TPM2_PT_LOCKOUT_COUNTER: 0x1
Counter AFTER Fapi_Initialize(...) ----------- TPM2_PT_LOCKOUT_COUNTER: 0x1


Counter BEFORE Fapi_Provision(...) ----------- TPM2_PT_LOCKOUT_COUNTER: 0x1
Counter AFTER Fapi_Provision(...) ----------- TPM2_PT_LOCKOUT_COUNTER: 0x1


Counter BEFORE Fapi_NvRead(...) ----------- TPM2_PT_LOCKOUT_COUNTER: 0x1
Counter AFTER Fapi_NvRead(...) ----------- TPM2_PT_LOCKOUT_COUNTER: 0x1


Counter BEFORE Fapi_Finalize(...) ----------- TPM2_PT_LOCKOUT_COUNTER: 0x1
Counter AFTER Fapi_Finalize(...) ----------- TPM2_PT_LOCKOUT_COUNTER: 0x1

-------------------------------------------

fromDate - 202311010900

-------------------------------------------


Counter BEFORE Fapi_Initialize(...) ----------- TPM2_PT_LOCKOUT_COUNTER: 0x1
Counter AFTER Fapi_Initialize(...) ----------- TPM2_PT_LOCKOUT_COUNTER: 0x1


Counter BEFORE Fapi_Provision(...) ----------- TPM2_PT_LOCKOUT_COUNTER: 0x1
Counter AFTER Fapi_Provision(...) ----------- TPM2_PT_LOCKOUT_COUNTER: 0x1


Counter BEFORE Fapi_NvRead(...) ----------- TPM2_PT_LOCKOUT_COUNTER: 0x1
Counter AFTER Fapi_NvRead(...) ----------- TPM2_PT_LOCKOUT_COUNTER: 0x1


Counter BEFORE Fapi_Finalize(...) ----------- TPM2_PT_LOCKOUT_COUNTER: 0x1
Counter AFTER Fapi_Finalize(...) ----------- TPM2_PT_LOCKOUT_COUNTER: 0x1

-------------------------------------------

toDate - 202312010900

-------------------------------------------
```


More investigation showed me that the problem occurs when the power of the machine, on which the library is operating, goes out the hardway (**power outage** or power cable **unplugging**).

Can you please try to recreate that situation? To cut the power when executing some sample code, to see what will happen.

**Comment by JordanLBogdanov** [comment]
@JuergenReppSIT did you got the chance to test the aforementioned configuration?

**Comment by JuergenReppSIT** [comment]
> @JuergenReppSIT did you got the chance to test the aforementioned configuration?

@JordanLBogdanov No currently I'm testing with a physical TPM on my Laptop where it's difficult to produce power outage.
If the counter is incremented by one after the power outage  wouldn't it solve your problem if you reset the lockout counter during the system startup. E.g: with `tpm2_dictionarylockout -c`

**Comment by JuergenReppSIT** [comment]
@JordanLBogdanov If you can send me a small program which did produce your problem that can be compiled on linux I will try it.

**Comment by JordanLBogdanov** [comment]
@JuergenReppSIT here is a small program, which, if running and the power is cut out, then the LOCKOUT_COUNTER is incremented.

[test_TPM_program.tar.gz](https://github.com/tpm2-software/tpm2-tss/files/13615123/test_TPM_program.tar.gz)

**Comment by JordanLBogdanov** [comment]
@JuergenReppSIT  @AndreasFuchsTPM If I am to speculate, I would say that the FAPI library doesnt have enough time to properly deinitialize its current state in the event of power failure.

**Comment by JordanLBogdanov** [comment]
@JuergenReppSIT @AndreasFuchsTPM Did you got the chance to check this out?

> I could reproduce the error on a raspberry pi with an Infineon TPM. After one write operation to NV ram the lockout counter was incremented after cable unplugging.

@JuergenReppSIT @AndreasFuchsTPM did you got the change to check this out?

**Comment by AndreasFuchsTPM** [comment]
I will have to put a "works as intended" on this behavior.

The background is: The security goal is that an attacker cannot attempt to perform an authorization and by cleverly cutting power prevent the lockout counter from increasing.
The lockout counter on NV could of course be incremented by 1 at the start of each command execution and decremented by 1 after auth checking, but this would result in 2 NVM accesses per command, which slows down execution time and increases NVM wear.

Consequentially, the lockout counter written on NV is always 1 larger than the actual current value.

Whenever you call `tpm2_shutdown (-c)` the lockout counter on NV is set to its actual value (0 in your case). And as soon as any command is executed, it will be set to the actual value + 1.

The solution is to not cut power without calling tpm2_shutdown first, or if you cannot prevent cutting of power, call tpm2_shutdown (-c) regularly. Note however that this may increase wear on the NVM.

**Comment by JordanLBogdanov** [comment]
@AndreasFuchsTPM I get why you did it, but something else comes to mind.
I am no expert in this stuff, but isn't attacking with false credentials supposed to be fast, like doing it hundreds of times per second?

If someone tries to "cleverly" cut the power to **NOT** get busted, wouldn't it take too much time for even a single such operation, like at least 10 to 30 seconds depending on the PC configuration? In that case it would take the supposed attacker a rough 4 months to guess a single 6 digits password. Not to mention if we throw letters in that password.

**Comment by JordanLBogdanov** [comment]
I am closing this as complete. Thank you both for you cooperation.
@AndreasFuchsTPM  @JuergenReppSIT
