### ISSUE TITLE
ERROR: The data to be encrypted might be too large

### ISSUE THREAD

**Issue by dj-d** [tpm2-software/tpm2-tss#2706]
Hi,

I performed encryption of a file of size 6 bytes via the `tss2_encrypt` API. Through the `-o` parameter, the function returned me a file of size 256 bytes. 

What I would like to do is encrypt the cipher returned by the `tss2_encrypt` function but I get the following error: `The data to be encrypted might be too large. Common values are 256 bytes for no OAEP or 190 with OAEP`.

Since the file I sheet encrypt is 256 bytes, should I be able to do it or not?

Thank you

**Comment by JuergenReppSIT** [comment]
The command 'tss2_encrypt` has no parameter to set the scheme. But you can change the scheme in the profile P_RSA2048SHA256.json where the default scheme is OAEP:
```
  "rsa_decrypt_scheme": {
        "scheme":"TPM2_ALG_NULL",
    },
```
Now encryption of 256 byte should be possible.

**Comment by dj-d** [comment]
Great now it works, thx
