### ISSUE TITLE
Call Esys_Import on keys generated with openssl.

### ISSUE THREAD

**Issue by JK-microsoft** [tpm2-software/tpm2-tss#2714]
Hello I have openssl keys generated on one system, that I have moved to another system and want to import them (explaining scenario though should not matter much from commands point of view)

Now I want to import these keys then load and persist the handle.

Basically sequence of steps are below: 

openssl ecparam -name prime256v1 -genkey -noout -out keyA.pem 
openssl ec -in keyA.pem -pubout -out publicA.pem
tpm2_createprimary -C o -c prim.ctx -Q 
tpm2_import -C prim.ctx -G ecc:ecdh -i keyA.pem -u key.pub -r key.priv 
tpm2_load -C prim.ctx -u key.pub -r key.priv -c key.ctx
tpm2_evictcontrol -C o -c key.ctx 0x81000007

Now the thing is I want to be able to do the import part by calling the Esys_Import directly instead of calling the tpm2_import command. I can convert the openssl public key into TPM2B_PUBLIC but I cannot get how to convert the openssl private key into TPM2B_PRIVATE.

I get how to convert the private key into TPM2B_SENSITIVE but not getting how to convert it into TPM2B_PRIVATE. I will then be able to do something like this, I am assuming from documentation of spec that the wrapper and symmetric key are all optional:

Snippet

        TSS2_ABI_VERSION abiVer = TSS2_ABI_VERSION_CURRENT; // These are the current default values of the TPM2-TSS library.

        ESYS_TR *parent;
        if (parentHandle && parentHandle != TPM2_RH_OWNER) {
                printf("Connecting to a persistent parent key.\n");
                r = Esys_TR_FromTPMPublic(ectx, parentHandle,
                                  ESYS_TR_NONE, ESYS_TR_NONE, ESYS_TR_NONE,
                                  parent);
        }

        r = Esys_Import(ectx, *parent,
                    ESYS_TR_NONE, ESYS_TR_NONE, ESYS_TR_NONE,
                    NULL, pub, priv, NULL, &symmetric,
                    &priv);

        return 1;
}

Any help is appreciated.

**Comment by JK-microsoft** [comment]
It seems issue https://github.com/tpm2-software/tpm2-tss/issues/2697 also tracked something similar, but the solution to the problem is not posted on the issue.

**Comment by JuergenReppSIT** [comment]
@JK-microsoft Sorry I can't post a complete example. You can investigate how to initialize `object_public` and `sensitive`, which are used in the following code snippet, from an opensl key in:
https://github.com/tpm2-software/tpm2-tools/blob/master/lib/tpm2_identity_util.c
```
TPM2B_SENSITIVE *sensitive;
TPM2B_PUBLIC *object_public,

TPM2B_PRIVATE private;
TPM2B_PRIVATE *outPrivate

size_t marshalled_sensitive_size = 0;
size_t marshalled_length = 0;
    
rc = Tss2_MU_TPMT_SENSITIVE_Marshal(&sensitive->sensitiveArea,
                                    &private.buffer[sizeof(uint16_t)],
                                    TPM2_MAX_DIGEST_BUFFER, &marshalled_sensitive_size);
// check rc
rc = Tss2_MU_UINT16_Marshal(marshalled_sensitive_size,
                            &private.buffer[0], sizeof(uint16_t),
                            &marshalled_length);
// check rc

private.size = marshalled_sensitive_size + sizeof(uint16_t);

TPMT_SYM_DEF_OBJECT symmetric_alg;
symmetric_alg.algorithm = TPM2_ALG_NULL;

rc = Esys_Import(esys_context, parent_obj->tr_handle,
                 parenthandle, ESYS_TR_NONE, ESYS_TR_NONE, NULL,
                 object_public, &private, NULL, symmetric_alg, &out_private);
// check rc

```

**Comment by JK-microsoft** [comment]
Thanks for your reply.

I added the suggested snippet to get the final code below, for some reason I am getting 0xa0003 which I believe is to do with bad context, I am digging further but if there is something obvious please let me know.

sudo ./main pubkey private_guest.pem 0x81000007
Success parsed TPM2B_PUBLIC in reading public from file [pubkey]
Success parsed the TPM2B_SENSITIVE which is the private from the file [private_guest.pem]
Success initializeing esys [0x55db80d9d810]
Importing openssl key Connecting to a persistent parent key.
ERROR:esys:src/tss2-esys/api/Esys_ReadPublic.c:198:Esys_ReadPublic_Async() Finish (Execute Async) ErrorCode (0x000a0003)
ERROR:esys:src/tss2-esys/esys_tr.c:154:Esys_TR_FromTPMPublic_Async() Error ReadPublic ErrorCode (0x000a0003)
ERROR:esys:src/tss2-esys/esys_tr.c:299:Esys_TR_FromTPMPublic() Error TR FromTPMPublic ErrorCode (0x000a0003)
Failed to get parent resource handlectx 0x55db80d9d810 from parent handle for handle 2164260864 error 655363


In tpm2_helper:


int importOpensslKey(ESYS_CONTEXT*ctx, TPM2B_PUBLIC *pub, TPM2B_SENSITIVE *privateKeySensitive, TPM2_HANDLE parentHandle)
{
        printf ("Importing openssl key ");
        TSS2_RC r;
        ESYS_TR parent = { 0 };
        if (parentHandle && parentHandle != TPM2_RH_OWNER) {
                printf("Connecting to a persistent parent key.\n");
                r = Esys_TR_FromTPMPublic(ctx, 0x81000007, /*parentHandle*/
                                  ESYS_TR_NONE, ESYS_TR_NONE, ESYS_TR_NONE,
                                 &parent);
                if (r != TPM2_RC_SUCCESS)
                {
                        printf("Failed to get parent resource handlectx %p from parent handle for handle %u error %d", ctx, TPM2_PERSISTENT_FIRST, r);
                        return static_cast<int>(r);
                }
                else
                {
                        printf("Successfully got the parent handle");
                }

        }

        TPM2B_PRIVATE privateKey;
        TPM2B_PRIVATE *outPrivate;

        size_t marshalled_sensitive_size = 0;
        size_t marshalled_length = 0;

        r = Tss2_MU_TPMT_SENSITIVE_Marshal(&privateKeySensitive->sensitiveArea,
                                    &privateKey.buffer[sizeof(uint16_t)],
                                    TPM2_MAX_DIGEST_BUFFER, &marshalled_sensitive_size);
        if (r != TPM2_RC_SUCCESS)
        {
                printf("Failed to marshall the sensitive into the priveate buffer %d", r);
                return static_cast<int>(r);
        }
        else
        {
                printf("Successfully marshalled the sensitive into the private buffer");
        }
        // check rc
        r = Tss2_MU_UINT16_Marshal(marshalled_sensitive_size,
                            &privateKey.buffer[0], sizeof(uint16_t),
                            &marshalled_length);
        if (r != TPM2_RC_SUCCESS)
        {
                printf("Failed to marshall extra unint_16 field %d", r);
                return static_cast<int>(r);
        }
        else
        {
                printf("Successfully marshalled the extra uint16_t field");
        }
        // check rc

        privateKey.size = marshalled_sensitive_size + sizeof(uint16_t);

        TPMT_SYM_DEF_OBJECT symmetric_alg;
        symmetric_alg.algorithm = TPM2_ALG_ECC;

        r = Esys_Import(ctx, parent,
                 ESYS_TR_NONE, ESYS_TR_NONE, ESYS_TR_NONE, NULL,
                 pub, &privateKey, NULL, &symmetric_alg, &outPrivate);
        // check rc
        if (r != TPM2_RC_SUCCESS)
        {
                printf("Failed to import the key given %d", r);
                return static_cast<int>(r);
        }
 return 0;
}
/**
 * Initializes TCTI interface. Uses a direct connection to the tpm resource
 * resource manager device file.
 */
TSS2_TCTI_CONTEXT* InitializeTcti()
{
    TSS2_RC ret { TSS2_TCTI_RC_GENERAL_FAILURE };
    size_t size {0};
    const char* device = "/dev/tpm0";
    // Get tcti size
    ret = Tss2_Tcti_Device_Init(nullptr, &size, nullptr);
    if (ret != TSS2_RC_SUCCESS) {
        throw "Failed to get TCTI context size";
    }

    auto tctiCtx = std::make_unique<unsigned char[]>(size);
    if (tctiCtx == nullptr) {
        throw ("Failed to allocate TCTI context memory");
    }

    // Populate TCTI context
    ret = Tss2_Tcti_Device_Init((TSS2_TCTI_CONTEXT*)tctiCtx.get(), &size, device);

    if (ret != TSS2_RC_SUCCESS)
    {
        throw "Failed to initialize TCTI context";
    }

    return (TSS2_TCTI_CONTEXT*)tctiCtx.get();
}


In main:

   TPM2_HANDLE parentHandle = std::stoull(argv[3], &pos, 16);
        TSS2_ABI_VERSION abiVer = TSS2_ABI_VERSION_CURRENT; // These are the current default values of the TPM2-TSS library.
        auto tcti = InitializeTcti();

        TSS2_RC r = Esys_Initialize(&ctx, tcti, &abiVer);
        if (r != TSS2_RC_SUCCESS)
        {
                throw "Failed to initialize TSS context";
        }
        else
        {
                printf ("Success initializeing esys [%p] \n", ctx);
        }
        r =  importOpensslKey(ctx, &pub, &privateSensitive, parentHandle);

**Comment by JK-microsoft** [comment]
That worked! Thanks a lot. I am putting the complete function that worked here for completeness if it helps someone in the future.


int importOpensslKey(ESYS_CONTEXT*ctx, TPM2B_PUBLIC *pub, TPM2B_SENSITIVE *privateKeySensitive, TPM2_HANDLE parentHandle)
{
        printf ("Importing openssl key ");
        TSS2_RC r;
        ESYS_TR parent = { 0 };
        if (parentHandle && parentHandle != TPM2_RH_OWNER) {
                printf("Connecting to a persistent parent key.\n");
                r = Esys_TR_FromTPMPublic(ctx, parentHandle,
                                  ESYS_TR_NONE, ESYS_TR_NONE, ESYS_TR_NONE,
                                 &parent);
                if (r != TPM2_RC_SUCCESS)
                {
                        printf("Failed to get parent resource handlectx %p from parent handle for handle %u error %d", ctx, parentHandle, r);
                        return static_cast<int>(r);
                }
                else
                {
                        printf("Successfully got the parent handle \n");
                }

        }

        TPM2B_PRIVATE privateKey;
        TPM2B_PRIVATE *outPrivate;

        size_t marshalled_sensitive_size = 0;
        size_t marshalled_length = 0;

        r = Tss2_MU_TPMT_SENSITIVE_Marshal(&privateKeySensitive->sensitiveArea,
                                    &privateKey.buffer[sizeof(uint16_t)],
                                    TPM2_MAX_DIGEST_BUFFER, &marshalled_sensitive_size);
        if (r != TPM2_RC_SUCCESS)
        {
                printf("Failed to marshall the sensitive into the priveate buffer %d", r);
                return static_cast<int>(r);
        }
        else
        {
                printf("Successfully marshalled the sensitive into the private buffe \nr");
        }
        // check rc
        r = Tss2_MU_UINT16_Marshal(marshalled_sensitive_size,
                            &privateKey.buffer[0], sizeof(uint16_t),
                            &marshalled_length);
        if (r != TPM2_RC_SUCCESS)
        {
                printf("Failed to marshall extra unint_16 field %d \n", r);
                return static_cast<int>(r);
        }
        else
        {
                printf("Successfully marshalled the extra uint16_t field \n");
        }
        // check rc

        privateKey.size = marshalled_sensitive_size + sizeof(uint16_t);

        TPMT_SYM_DEF_OBJECT symmetric_alg;
        symmetric_alg.algorithm = TPM2_ALG_NULL /* TPM2_ALG_ECC */;

        r = Esys_Import(ctx, parent,
                 ESYS_TR_PASSWORD, ESYS_TR_NONE, ESYS_TR_NONE, NULL,
                 pub, &privateKey, NULL, &symmetric_alg, &outPrivate);
        // check rc
        if (r != TPM2_RC_SUCCESS)
        {
                printf("Failed to import the key given %d \n", r);
                return static_cast<int>(r);
        }
        else
        {
                printf("Successfully imported the key given \n");
        }

        return 0;
}
