### ISSUE TITLE
TPM seems to freeze

### ISSUE THREAD

**Issue by crcook01** [tpm2-software/tpm2-tss#2746]
Currently in my software I am making repetitive calls to the tpm using the tpm2-tss library and eventually the software just hangs. I can restart my process if I am using the device as the tcti, and it works again until it eventually freezes again. If I use the tpm2-abrmd I have to restart the tpm2-abrmd to get it to work again. Anyone have any thoughts on why this could be?

**Comment by AndreasFuchsTPM** [comment]
export TSS2_LOG=tcti+trace
and run it again. This way we can see the log of the interaction and know better what is freezing.
