### ISSUE TITLE
Help with build error

### ISSUE THREAD

**Issue by ramrattle** [tpm2-software/tpm2-tss#2777]
Hi, I'm getting this build error during make, can someone help me with this please

.la libutil.la src/tss2-tcti/libtss2-tctildr.la )
/usr/bin/ld: src/tss2-fapi/.libs/libtss2_fapi_la-fapi_util.o: in function `ifapi_authorize_object':
/home/test/ram/tpm2-tss/src/tss2-fapi/fapi_util.c:2178: undefined reference to `Esys_TRSess_GetAuthRequired'
collect2: error: ld returned 1 exit status
libtool:   error: error: relink 'src/tss2-fapi/libtss2-fapi.la' with the above command before installing it

**Comment by JuergenReppSIT** [comment]
This problem also did also occur here: https://github.com/tpm2-software/tpm2-tss/issues/2294#issuecomment-1019960721 and was solved.

**Comment by ramrattle** [comment]
Thanks a lot, this solved my problem
