### ISSUE TITLE
Cannot run tpm2_createprimary

### ISSUE THREAD

**Issue by fsl3118** [tpm2-software/tpm2-tss#2802]
I tried to create a primary key, but there's something wrong.
![image](https://github.com/tpm2-software/tpm2-tss/assets/134755278/ec43787c-6225-435d-a481-72751531f87b)
I just followed a strategy on CSDN, and I confused. WHY can't I reproduce their result?
Strategy: https://blog.csdn.net/weixin_46447549/article/details/123788198
Env: Dell Inspiron 7510 (TPM 2.0 Enable)
OS: Deepin V23 Beta3
Kernel: 6.1.32-amd64-desktop-hwe

**Comment by JuergenReppSIT** [comment]
It looks like you are using the wrong auth value (`-P 1`) for the endorsemen hierarchy (`-H e`).
