### ISSUE TITLE
Error 2446

### ISSUE THREAD

**Issue by JordanLBogdanov** [tpm2-software/tpm2-tss#2808]
Hello there.

Lets say we have two PC's.
We have created some NvRam entities on both of them and we use the Fapi_NvRead and Fapi_NvWrite functions. 
There are the appropriate *.json files created in the appropriate system directories and everything.
So far they work nice.

When we swap the hard disks though, and try to perform the usual tasks of read/write to/from the TPM's nvram, we get the **2446 error.** 
Is it happening because the *.json files are not matched to actual data written in the TPM's nvram (comming from swapping the hard disks)?

There is the generated tss2_logfile.txt.

[tss2_logfile.txt](https://github.com/tpm2-software/tpm2-tss/files/14997199/tss2_logfile.txt)

Thanks!

**Comment by JuergenReppSIT** [comment]
You can't exchange the keystore between two PCs with different TPMs. If the  json files for the nv objects on the to PCs are equal you could read the nv data, if you would use the file 
/usr/local/var/lib/tpm2-tss/system/keystore/P_ECCP256SHA256/HS/SRK/object.json which is created during provisioning for the current TPM.

**Comment by JordanLBogdanov** [comment]
Thank you @JuergenReppSIT.
