### ISSUE TITLE
Get rid of SHA1 in tests

### ISSUE THREAD

**Issue by AndreasFuchsTPM** [tpm2-software/tpm2-tss#2818]

**Comment by joholl** [comment]
The main problem to me is the [policy-execute](
https://github.com/tpm2-software/tpm2-tss/blob/master/test/integration/policy-execute.int.c) integration test.

It is backed by this header and I do not really know how to calculate these:

https://github.com/tpm2-software/tpm2-tss/blob/4e2fe02fca8409f875a8693ece06b8b5e5baf5ce/test/data/test-fapi-policies.h#L12-L92

**Comment by joholl** [comment]
I am working on this. Once I submit a PR, it should also address #2862.
