### ISSUE TITLE
Add support for new (post-quantum) algorithms

### ISSUE THREAD

**Issue by graziadonghia** [tpm2-software/tpm2-tss#2872]
Hello, I'm studying how to integrate new algorithms (more in details, post-quantum algorithms using [liboqs](https://github.com/open-quantum-safe/liboqs) library. Is it possible to find some existing solutions? So far I didn't find too much. I'm aware that it is a pretty complex task but it's a cutting edge topic that everyone is investigating more day by day. Which files should I modify in order to add this new support and make some experiments?

Thank you in advance

**Comment by AndreasFuchsTPM** [comment]
We have to wait for TCG to standardize and TPM vendors to implement PQC algorithms before we can add interfaces to interact with them.
