### ISSUE TITLE
Tss2_Sys_Unseal returns 0x99d.

### ISSUE THREAD

**Issue by Dvergatal** [tpm2-software/tpm2-tss#2903]
Like in title the function is returning me this error code and I dunno what it is. Can somebody point me what can it be?

**Comment by Dvergatal** [comment]
OK after few more investigations I have came to a place where this error code is from [Tss2_Sys_Execute.c](https://github.com/tpm2-software/tpm2-tss/blob/master/src/tss2-sys/api/Tss2_Sys_Execute.c#L161).

According to the code it means that I have received a TPM error, but what shall be done than? In addition the code which I'm running is not mine it is from https://github.com/jiazhang0/cryptfs-tpm2 and I have a bug on it in https://github.com/jiazhang0/cryptfs-tpm2/issues/26

**Comment by JuergenReppSIT** [comment]
0x99d indicates that the correct policy for the authorization of the object was not executed.

**Comment by Dvergatal** [comment]
> 0x99d indicates that the correct policy for the authorization of the object was not executed.

Is it possible that when I'm sealing object to TPM from different kernel image (some live USB used for installment) that the object won't be accessible from the kernel installed from the OS image?

**Comment by Dvergatal** [comment]
OK, my bad everything is working as expected I had to turn on secure boot in UEFI :+1:
