### ISSUE TITLE
Doxygen / Readthedocs page not working

### ISSUE THREAD

**Issue by gubertoli** [tpm2-software/tpm2-tss#2917]
Hi all,

I am trying to browse the documentation directly on [tpm2-tss.readthedocs.io](https://tpm2-tss.readthedocs.io/). 

I tried the versions `latest`, `stable`, and `4.1.x` but only `2.4.5` is working.

**Comment by JuergenReppSIT** [comment]
With  the versions latest and 4.1.x the problem is fixed. Only with stable you still get the empty page.
