### ISSUE TITLE
tpmClient / TestRsaEncryptDecrypt() not fully implemented 

### ISSUE THREAD

**Issue by danglus** [tpm2-software/tpm2-tss#294]
It seems that TestRsaEncryptDecrypt() in tpmClient is not fully implemented:

--------------------
...
  // Load private key into TPM
    INIT_SIMPLE_TPM2B_SIZE( rsaKeyName );
    rval = Tss2_Sys_Load ( sysContext, handle2048rsa, 0, &outPrivate, &outPublic,
            &loadedSha1KeyHandle, &rsaKeyName, &sessionsDataOut);
    CheckPassed( rval );

    // Encrypt message with public key

    // Print encrypted message.

    // Decrypt message with private key.

    // Print decrypted message.

}
--------------------

  is that a bug?
  Thanks,
Dan

**Comment by wcarthur1** [comment]
Not a bug, just never got done.

But we're open to volunteers!

**Comment by AndreasFuchsSIT** [comment]
This code got remove during the dissection of tpmclient.
