### ISSUE TITLE
Unit test for unsuccessful transmit calls

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#379]
The most complicated part of this is enumerating all of the possible failure scenarios.

**Comment by pdxjohnny** [comment]
which calls are these? I could try to get started on this and #381

**Comment by flihp** [comment]
The common successful case is tested here:
* https://github.com/01org/TPM2.0-TSS/blob/master/test/unit/tcti-device.c#L224
* https://github.com/01org/TPM2.0-TSS/blob/master/test/unit/tcti-device.c#L205

Failures would need to use the __wrap / mock pattern to simulate failures from the system calls (read / write) used by the TCTI.

**Comment by tstruk** [comment]
Currently we have these for swtpm:
```
test/unit/tcti-swtpm.c:tcti_swtpm_transmit_null_test (void **state)
test/unit/tcti-swtpm.c:tcti_swtpm_transmit_fail_header_test (void **state)
```
