### ISSUE TITLE
KDFa unit tests

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#427]
KDFa function recently caused @wcarthur1 a few problems. Turned out to be a bug in transcribing the function from the TPM spec to the source repo. Probably worth while to create a unit test to cover some of the edges in this function. From #418:

> Re test case, call the KDFa:
> TPM_RC KDFa( TPMI_ALG_HASH hashAlg, TPM2B *key, char *label,
> TPM2B *contextU, TPM2B *contextV, UINT16 bits, TPM2B_MAX_BUFFER *resultKey )
> 
> with SHA256 as the hashAlg with bits greater than 32*8. For the rest of the parameters just select something. You'll get a different resultKey with the bad code than you'll get with my fix.

**Comment by AndreasFuchsSIT** [comment]
I guess you were referring to https://github.com/tpm2-software/tpm2-tss/blob/2aa35c422c85deaabb5ded93aefecbec5a069f3d/test/integration/sapi-session-util.c#L88

IMHO we don't need a unit-test for things that are helpers in the integration tests.
I.e. don't test the tests ? ;-)

P.S. Re-Open if you disagree...
