### ISSUE TITLE
TPMA_NV_POLICY_DELETE is inconsistent with others

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tss#465]
TPMA_NV_POLICY_DELETE departs from the toher TPMA_NV_POLICY* defines, in that
TPMA_NV_POLICY_DELETE has an _ between POLICY and DELETE, where as READ and WRITE do not:
```
TPMA_NV_POLICYREAD
TPMA_NV_POLICYWRITE
```
This seems inconsistent.

**Comment by flihp** [comment]
meh. It's how the spec is written.

**Comment by flihp** [comment]
Not sure what to do this this one though. Not something we can fix here. Will leave this open for a bit if you wanna clarify.

**Comment by AndreasFuchsSIT** [comment]
I guess this can be closed, since it's how the TPM spec is written...
