### ISSUE TITLE
TPM clear and lock out.

### ISSUE THREAD

**Issue by Iyer-VivekAnand** [tpm2-software/tpm2-tss#480]
I am using TPM2.0-TSS library for a product in my company. During our product testing(which involves updating our application software and rebooting the server) I found that the TPM was getting cleared after 5 reboots. I got a hint and found that I missed to shutdown the TPM before reboot.

Also after ~25 reboot, the TPM got locked out. I could not find why the TPM got locked out. Is there anything I am missing?

Is there anything in the SPEC which tells  that TPM should get cleared because it was not shutdown properly and TPM  should get locked because of continuous reboots?

My use case is as follows:
1. Generate EK and AK
2. Lock the TPM
3. Use TPM to decrypt small set of data(not to frequent) using ActivateCredentials.

**Comment by flihp** [comment]
AFAIK no application should have to do something special to the TPM on shutdown. This is something that the device driver should do, maybe the platform firmware. You may want to take a look at the device driver in the kernel. Depending on what your platform is like there may be some clues in the relevant TCG platform specification.

**Comment by crogers1** [comment]
According to the TCG spec Section 19.8.6:
https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-1-Architecture-01.38.pdf

I ran into the same problem.  You need to make sure the last component that issues any TPM calls before your platform shuts down (whether it be the device driver or something lower on the stack) calls TPM2_Shutdown.  After some testing, I found that firmware won't do this for you.  It's also worthy to note that any TPM commands sent after a TPM2_Shutdown invalidates the shutdown.

So, if you don't make this call, the failed tries NV variable will increment until it passes max tries and your tpm goes into lockout mode.

**Comment by martinezjavier** [comment]
@snits any comment on this? Since you are much more familiar with the kernel side of the TPM2 support.

**Comment by AndreasFuchsSIT** [comment]
Both of these things are considered to be Firmware/Driver questions.

1. A userspace application using the TSS must not even be able to clear the TPM. That requires Platform-Auth and thus PhysicalPresence / FirmwarePresence.

2. The increment in DAcount seemed to have been a linux kernel issue. See also https://github.com/tpm2-software/tpm2-tools/issues/583.

So I'll close this issue since it's not a tpm2-tss bug.
