### ISSUE TITLE
Helper macros for functions in tss2_tcti.h are not friendly to FFIs

### ISSUE THREAD

**Issue by cardoe** [tpm2-software/tpm2-tss#490]
When trying to use this toolstack from another language you must do so via a FFI (foreign function interface). Unfortunately the opposite function to `InitSocketTcti()` and `InitDeviceTcti()` appears to be a macro called `tss2_tcti_finalize()`. By using this approach its not possible to call this from another language that is calling into the C API. There really needs to be wrapper functions that do these actions and have them exported by the library. There are a few other TCTI macros in here but at this point I am not sure if I would have to call them if I intend on only using the SAPI from my FFI.

**Comment by cardoe** [comment]
Ultimately other languages can call C functions directly but cannot execute C macros. So to properly wrap up the API every implementer of a binding will have to write some C code to call the macros. The best scenario would be if the API included no macros and instead used C functions to call everything.

A parallel would be something like serializing an `int` over the network and sending it to your program. While that works when you're on the same architecture, as soon as you move to another architecture you'll run into problems. Its possible to work around it but the best solution would be for the code to use a properly sized type like `uint32_t`.

**Comment by flihp** [comment]
How about something like this: https://github.com/flihp/tpm2-tss/tree/libtcti-util ?

**Comment by cardoe** [comment]
Perfect. 👍

**Comment by tstruk** [comment]
That is covered by https://github.com/tpm2-software/tpm2-pytss
