### ISSUE TITLE
Tss2_Sys_PolicyCounterTimer should fix endiness of OperandB

### ISSUE THREAD

**Issue by danglus** [tpm2-software/tpm2-tss#495]
Hi,
  It seems that Tss2_Sys_PolicyCounterTimer does not take into account the CPU endiness when it marshal's OperandB.

To make it work on Intel, I had to add the following for loop:

for (i=0 ; i < operandB.t.size ; i ++ ) {
   j= operandB.t.size - i - 1;
   operandB.t.buffer[i] = *((UINT8 *)&max_clock + j);
}
rval = Tss2_Sys_PolicyCounterTimer(sapi_ctx, sessionHandle, 0, 	&operandB , 8, TPM_EO_UNSIGNED_LT, 0);

**Comment by flihp** [comment]
@danglus can you provide some version information for me? Something like a version # if it's a release or a git hash if it's directly from git.

**Comment by flihp** [comment]
This could be related to the recent change in the type marshalling stuff @tstruk? I suppose it's equally likely that we just don't have a good test for this part of the API and it's a bug in the 1.x branch.

**Comment by tstruk** [comment]
Regardless of the CPU endianess the TPM always expects big endian. The part 3 of the spec in "23.10 TPM2_PolicyCounterTimer" says:

"Magnitude comparisons assume that the octet at offset zero in the referenced location and in operandB
contain the most significant octet of the data."

It is upto the caller to format the input parameters in the way TPM expects it.
