### ISSUE TITLE
HMAC and encrypt sessions can't coexist on the same command

### ISSUE THREAD

**Issue by wcarthur1** [tpm2-software/tpm2-tss#525]
I found this when working on my ESAPI-like layer for my current employer.  I wrote a fairly comprehensive test for all options of HMAC, encrypt, decrypt, etc for sessions and found this issue.  It's kind of a chicken and egg problem, and I spent a few days debugging and fixing this.  

I have a fix--insert the following code just before the return from Tss2_Sys_ExecuteFinish():

    //
    // Following is kind of a kludge to allow HMAC and encrypt sessions to co-exist on the same
    // command.  Maybe better than a kludge since it's the only way I know to make this work.
    //
    // The order in which things need to happen is:
    // 1.  response HMAC check
    // 2.  decryption of first TPM2b return paramter.
    // 3.  XXXX_Complete call.
    //
    // If parameter decryption is done before the response HMAC check, the HMAC check fails.
    //
    // If _Complete is called before the decryption of the first TPM2B return parameter, the parameter
    //  is returned incorrectly, i.e. in it's encrypted state.
    //
    // We have to get rpBufferUsedSize set correctly so that the encrypted return params can found and
    // decrypted correctly.
    //
    // But we also have to leave nextData in it's original state so that the _Complete call can get returned
    // handles and params correctly.
    //
    // Without this fix, it is impossible for HMAC and encrypt sessions to co-exist on the same command.
    // 
    if( rval == TSS2_RC_SUCCESS )
    {
        // Save nextData so that we can restore it.
        UINT8 *savedNextData = SYS_CONTEXT->nextData;
        
        SYS_CONTEXT->nextData = (UINT8 *)( SYS_CONTEXT->rspParamsSize );

        UINT32 rspSize = CHANGE_ENDIAN_DWORD( ( (TPM20_Header_Out *)( SYS_CONTEXT->tpmOutBuffPtr )  )->responseSize );

        // Save response params size if command has authorization area.
        if( CHANGE_ENDIAN_WORD( ( (TPM20_Header_Out *)( SYS_CONTEXT->tpmOutBuffPtr )  )->tag ) == TPM_ST_SESSIONS )
        {
            Unmarshal_UINT32( SYS_CONTEXT->tpmOutBuffPtr, SYS_CONTEXT->maxResponseSize, &( SYS_CONTEXT->nextData ),
                    &( SYS_CONTEXT->rpBufferUsedSize ), &(SYS_CONTEXT->rval ) );
        }

        SYS_CONTEXT->rpBuffer = SYS_CONTEXT->nextData;

        // Save response params size if command does not have an authorization area.
        if( CHANGE_ENDIAN_WORD( ( (TPM20_Header_Out *)( SYS_CONTEXT->tpmOutBuffPtr )  )->tag ) != TPM_ST_SESSIONS )
        {
            SYS_CONTEXT->rpBufferUsedSize = rspSize - ( SYS_CONTEXT->rpBuffer - SYS_CONTEXT->tpmOutBuffPtr );
        }

        // Restore nextData to it's original value.
        SYS_CONTEXT->nextData = savedNextData;
    }

**Comment by tstruk** [comment]
We have ESAPI that does exactly that so it this is not a problem. Closing the issue.
