### ISSUE TITLE
test harness documentation

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#566]
The migration from tpmclient to the automake test harness has made slow but steady progress. To encourage additional work in this area we need to document our use of the test harness as well as the differentiation between unit and integration tests.

**Comment by leeehui** [comment]
I am a beginner of TSS. according your comment above, if I want to use test package, I have to write my own makefile for test, is that right?

**Comment by flihp** [comment]
hi @leeehui. No you would only need to add new test cases either to an existing unit test (if it's appropriate) or to a new test executable to the existing `Makefile.am`.

**Comment by leeehui** [comment]
hi @flihp. Thank you! we wrote an independent cmake file to compile the test program, and it works well.
Also, according to your reply, I took more attention on configure file, and found the parameter "--with-simulatorbin=tpm_server", I think this is trigger of test executable file.
In my opinion, an independent cmake file is more convenient, because  I probably will change the test file frequently.

**Comment by flihp** [comment]
> I took more attention on configure file, and found the parameter "--with-simulatorbin=tpm_server", I think this is trigger of test executable file.

Looks like we didn't get that configuration option documented in the INSTALL.md file. We use the same option for the tabrmd tests and have docs for it in that repo: https://github.com/01org/tpm2-abrmd/blob/master/INSTALL.md#enable-integration-tests---with-simulatorbin. Copying that over should be easy enough.

**Comment by RashmicaG** [comment]
Hi @flihp,
Just to clarify, if I want to run unit tests I use the '--enable-unit'  option with configure and for the integration tests I use '--with-simulatorbin'? What would I use to run the tpmclient tests?

**Comment by leeehui** [comment]
Hi @RashmicaG ,
I think write your own cmake file is more convenient.  I am now using a standalone CMakeLists file to compile my own test, and it works fine.

**Comment by flihp** [comment]
the `tpmclient` program is run as an integration test these days. So by giving a path to the simulator and enabling the integration tests you should have `tpmclient` executed when you run `make check`. This should be visible in the console output as well as the `$(srcdir)/test-suite.log` file. Output from the `tpmclient` program should be in `$(srcdir)/test/tpmclient/tpmclient.log`.

Are these log files showing what you're expecting to see?

**Comment by flihp** [comment]
verbosity of the output from the `tpmclient` program has been reduced a bit: #587

**Comment by leeehui** [comment]
in my opinion, test package should be compiled separately. 
I am now using a standalone CMakeLists to generate Makefiles of test package

**Comment by RashmicaG** [comment]
@flihp  Indeed it is being run there - thank you.

**Comment by tstruk** [comment]
What is described in https://github.com/tpm2-software/tpm2-tss/blob/master/README.md#testing should be sufficient for a start.
