### ISSUE TITLE
implement --debug option for configure script

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#589]
Our use of the CONFIG_SITE file for enabling debug output doesn't work now that we have _FORTIFY_SOURCE and the like enabled @ configure time. These flags require optimizations so they should be disabled for debug builds. We should remove the CONFIG_SITE file completely and replace it with a `--debug` option to the config script

**Comment by tstruk** [comment]
Desn't commit a3260d8 do this already?

**Comment by flihp** [comment]
hu, I forgot about that (thought I probably reviewed the patch :\). This can then be down-scoped to just moving the specific debug preprocessor stuff (-DDEBUG_SOCKETS) out of the CONFIG_SITE file and into the configure.ac? This is basically set up to aligning our debug mechanisms etc.

**Comment by tstruk** [comment]
I will add the DEBUG_SOCKETS to configure.ac

**Comment by flihp** [comment]
@tstruk did this get resolved?

**Comment by tstruk** [comment]
We do have --enable-debug that switches off _FORTIFY_SOURCE and enables debug output.
I'm not sure what was the DEBUG_SOCKETS all about. Was about debug prints? Now that we have TSS2_LOG is it still relevant?
