### ISSUE TITLE
LocalTpmReceiveTpmResponse does not return size of response buffer

### ISSUE THREAD

**Issue by LukasJaegerSIT** [tpm2-software/tpm2-tss#628]
The TCTI-specification states that TSS2_TCTI_receive should return the size of the response buffer, if NULL is given as a response buffer and the size of the answer is known (see the command description on page 12). The method _LocalTpmReceiveTpmResponse_ (in _tcti\_device.c_) that implements this method for a local device calls _check\_receive_ (in _tcti.c_) which returns TSS2_TCTI_BAD_REFERENCE in that case.

**Comment by flihp** [comment]
looks like a bug to me

**Comment by flihp** [comment]
This was resolved in the recent round of TCTI re-writes. I lost track of this ticket.
