### ISSUE TITLE
race condition for parallel 'check' target

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#659]
There's already a work-around in place for this: https://github.com/intel/tpm2-tss/commit/24fb1306e0204c931bb0cab63d04c6534d49bb78#diff-c949f93d03f44a4217d7a138f9e2e54a.

Fixing the issue at the source would be better. The bug is most likely in the integration test script.

**Comment by flihp** [comment]
A fix for this issue went into the tabrmd a few days back. This needs to be ported to the tss.

**Comment by AndreasFuchsSIT** [comment]
@flihp I think this is done, since I use `make -j8 check` all the time ?

**Comment by flihp** [comment]
yeah good catch, thx
