### ISSUE TITLE
async I/O for simulator TCTI

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#668]
This issue covers the implementation of asynchronous I/O for the simulator TCTI. When completed callers of the 'receive' function should be able to expect the timeout mechanism (include a timeout of 0) to function as expected.

**Comment by tstruk** [comment]
Not really an async io, since it would require introducing threads, but this commit https://github.com/tpm2-software/tpm2-tss/commit/313445cdf8d88b96bb4096877f0b669902d1d2cf
make is good enough to be able to run async API against mssim
