### ISSUE TITLE
Implement TPM_CC_CreateLoaded

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#681]
This command was added in v1.38 of the TPM spec. See list of command codes in table 12 here: https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-2-Structures-01.38.pdf

**Comment by tstruk** [comment]
Fixed in commit 23d8635972b3ad1a1cfb3be94aeeee16cd4ee9d4
