### ISSUE TITLE
AC testing in 1.x

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#717]
With the AC commands going into master and 1.x we need the 1.x branch tested before we can do a release. I'm trying to find someone to test these who has the appropriate hardware.

**Comment by lugong** [comment]
I will help to test this feature.
The new TSS code about AC is slightly different from the code which is used for the application, it will needs some adaption. If the test result is available, I will give it here.

**Comment by flihp** [comment]
this is done, we've verified 2 of the 3 since that's all that's implemented
