### ISSUE TITLE
TPMU_NAME marshalling

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#720]
See the discussion here: #719 

The `TPMU_NAME` marshalling and unmarshalling functions are special cases. There is no selector defined for this type. Instead part 2 of the spec [1] describes (in section 10.5.3) how the selector should be determined. It uses the size of the `TPMU_NAME` as indicated by the `size` field in the `TPM2B_NAME` structure. This is mentioned in a note in the marshalling spec. Thus our selector is effectively the size field where acceptable size values are:
4 (aka sizeof (UINT32)) -> selects TPMU_NAME->handle and does marshalling for a handle
0 -> no name value present (marshal / unmarshal no-op)
sizeof (hash) -> hash specific marshal / unmarshal (one for each supported hash function)

The marshalling spec requires that `TSS2_MU_RC_BAD_VALUE` be returned for invalid selector values so all other size values should produce this RC.

The thing that's bothering me is that [1] defines the TPM2B_NAME structure in table 84 as:

|Parameter | Type | Description|
|-----------|-------|-------------|
|size|UINT16|size of the name structure|
|name[size]{:sizeof(TPMU_NAME)}|BYTE|the Name structure|

This seems wrong to me though since the `name` field cannot be treated as a BYTE array when it's a handle. Treating it as one will result in the handle being marshalled in network byte order. The text in the spec: `If size is four, then the Name is a handle.` clarifies this but it makes me wonder if there are other structures that suffer from this similar issue.

@tstruk : Interested in your thoughts on this whole thing. Likely it's something you've thought a great deal about while doing the implementation.

[1] - https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-2-Structures-01.38.pdf
[2] - https://trustedcomputinggroup.org/wp-content/uploads/TSS_Marshaling_Unmarshaling_API_Version-1.0_Revision-04_review_ENDS030918.pdf

**Comment by tstruk** [comment]
Actually we don't have any marshal/unmarshal functions for TPMU_NAME type currently because it wasn't needed. I'll have a look at it now.

**Comment by tstruk** [comment]
To me it looks like the size instead of selector_value should be applied only to unmarshal. For marshal the selector has to be provided. Is the missing marshaling selector a gap?

**Comment by flihp** [comment]
My understanding of the TPMU marshalling stuff (a fancy way of saying "I could be wrong here but...") is that the selector comes from the parent structure. According to a note in the draft spec (https://trustedcomputinggroup.org/wp-content/uploads/TSS_Marshaling_Unmarshaling_API_Version-1.0_Revision-04_review_ENDS030918.pdf) from section 3.6.2:
```
NOTE: In some cases there is no selector given in the tables of TPM library specification Part 2. In those cases the size is used as selector.
```
Going on this, a TPMU_NAME would need to have an associated `size` field in the parent structure. If the size is 4 then it's marshalled as a handle, otherwise the size should be that of a supported hash algorithm and it should be marshalled as such.

After spending some time in your TPMU_* macros I don't think adding this should be too difficult. I'll take a swing at it in your absence.

**Comment by tstruk** [comment]
There is no such TPM struct type that the TPMU_NAME is a member of, so the selector can not come form a parent structure. The spec says that the type is determined by context and the size, although it doesn't clarify what the context is.

**Comment by flihp** [comment]
Not sure I follow your bit about the context. Marshalling based on size really just means the size tells you what's being marshalled. So if it's 4 bytes then it's a handle, if it's one of the supported hash algorithm sizes (https://github.com/tpm2-software/tpm2-tss/blob/master/include/sapi/tss2_tpm2_types.h#L56) then it's marshalled as a hash. At least that seems to be the most simple reading of it and it seems logical to me. Agree / Disagree?
