### ISSUE TITLE
libssl-dev missing in INSTALL.md dependencies

### ISSUE THREAD

**Issue by DomiNic5787** [tpm2-software/tpm2-tss#770]
Reproduced on Ubuntu 16.04:
* Installing all required dependencies described in INSTALL.md
* ./bootstrap
* ./configure
* make

```
CC       test/integration/test-options.lo
test/integration/sapi-util.c:27:25: fatal error: openssl/sha.h: No such file or directory
```

This issue is related to 15220e89ff86087afc8661f3f2b7bac71a83649d.
libssl-dev was added to .travis.yml in 57d372e092b413ca3a2a9dd0ec9e02b221bab99f.
But it is missing in INSTALL.md sice then.

**Comment by flihp** [comment]
This is a good catch. OpenSSL is only used in the integration tests but it looks like the test library is being built regardless of whether or not the integration tests are enabled.

**Comment by flihp** [comment]
looks like this can be closed ...
