### ISSUE TITLE
ESAPI: Support TPM2.0-r1.38 functions

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tss#786]
Currently ESAPI "only" supports the TPM2.0-r1.16 functions.
We shall extend the support to the new functions of TPM2.0-r1.38.

Namely this includes: FieldUpgradeStart, FieldUpgradeData, FirmwareRead, PolicyAuthorizeNV, CreateLoaded, PolicyTemplate, EncryptDecrypt2

**Comment by flihp** [comment]
@AndreasFuchsSIT : AFAIK this was resolved in #803. Is this correct? Can you please close this issue if so? Thanks!

**Comment by AndreasFuchsSIT** [comment]
Yep, that's correct...
