### ISSUE TITLE
New milestone to cleanup depnedency checking @ configure time

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#790]
A deficiency in our dependency checking came up recently in #784 and was then clarified in #788. It boils down to a dependency that's found to be missing / not satisfied at configure time but the configure script not failing like it should. As part of fixing this one issue in #789 it's clear that our dependency checking needs some love. We need to spend some time making sure the appropriate dependencies are checked and that they cause the configure script to fail as noisily as appropriate.

This issue tracks the creation of a collection of issues for each dependency that we're not handling appropriately under a milestone (if there's enough issues to warrant one).

**Comment by tstruk** [comment]
See related https://github.com/tpm2-software/tpm2-tss/issues/1059

**Comment by flihp** [comment]
I'm pretty satisfied with the state of this given the recent changes made to the integration test flag (--enable-integration) and the checking for programs required by the test harness / script. If we run into additional issues we can handle them as they arise.
