### ISSUE TITLE
Remove TPMA_OBJECT_SIGN

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tss#799]
Since 1.38, TPMA_OBJECT_SIGN was renamed to TPMA_OBJECT_SIGN_ENCRYPT.
Currently, we have both, for backwards compatibility. TPMA_OBJECT_SIGN should be remove before 2.0 though.

**Comment by flihp** [comment]
@AndreasFuchsSIT is this still unresolved?
