### ISSUE TITLE
long term mirror

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#816]
Our CI should pull from a mirror that we control. This is to prevent the blackouts we've been experiencing at the hands of sourceforge and others. This will also reduce strain on the web servers of upstream projects like cmocka.org since our CI is pumping out a growing number of builds each day.

**Comment by williamcroberts** [comment]
Probably want to switch to a docker container and then mirror that docker image. conjecture warning: i think docker is set up with this in mind and travis builds a local cache.

**Comment by tstruk** [comment]
Fixed in #1000
