### ISSUE TITLE
SAPI: Fix tss2_tpm2_types.h

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tss#834]
I just looked at https://trustedcomputinggroup.org/wp-content/uploads/TSS_Overview_Common_Structures_Version-0.9_Revision-03_Review_030918.pdf
The way the spec works is the following:
#define TPMA_NV_RESERVED1_MASK    ((TPMA_NV) 0x00000300)
#define TPMA_NV_RESERVED2_MASK    ((TPMA_NV) 0x01f00000)
#define TPM2_NV_INDEX_INDEX_MASK      ((TPM2_NV_INDEX) 0x00ffffff)
#define TPM2_NV_INDEX_INDEX_SHIFT     (0)
#define TPM2_NV_INDEX_RH_NV_MASK      ((TPM2_NV_INDEX) 0xff000000)
#define TPM2_NV_INDEX_RH_NV_SHIFT     (24)

Also
TPMA_NV_ instead of TPMA_NV_TPMA_NV_

**Comment by AndreasFuchsSIT** [comment]
#define TPMA_ALGORITHM_RESERVED1_MASK     ((TPMA_ALGORITHM) 0x000000f0) 
#define TPMA_ALGORITHM_RESERVED2_MASK     ((TPMA_ALGORITHM) 0xfffff800) 
#define TPMA_OBJECT_RESERVED1_MASK            ((TPMA_OBJECT) 0x00000001) 
#define TPMA_OBJECT_RESERVED2_MASK            ((TPMA_OBJECT) 0x00000008) 
#define TPMA_OBJECT_RESERVED3_MASK            ((TPMA_OBJECT) 0x00000300) 
#define TPMA_OBJECT_RESERVED4_MASK            ((TPMA_OBJECT) 0x0000f000) 
#define TPMA_OBJECT_RESERVED5_MASK            ((TPMA_OBJECT) 0xfff80000) 
#define TPMA_SESSION_RESERVED1_MASK       ((TPMA_SESSION) 0x18) 
#define TPMA_LOCALITY_EXTENDED_MASK       ((TPMA_LOCALITY) 0xe0)
#define TPMA_LOCALITY_EXTENDED_SHIFT      (5) 
#define TPMA_PERMANENT_RESERVED1_MASK         ((TPMA_PERMANENT) 0x000000f8) 
#define TPMA_PERMANENT_RESERVED2_MASK         ((TPMA_PERMANENT) 0xfffff800) 
#define TPMA_STARTUP_CLEAR_RESERVED1_MASK     ((TPMA_STARTUP_CLEAR) 0x7ffffff0) 
#define TPMA_MEMORY_RESERVED1_MASK        ((TPMA_MEMORY) 0xfffffff8) 
#define TPMA_CC_COMMANDINDEX_MASK     ((TPMA_CC) 0x0000ffff)
#define TPMA_CC_COMMANDINDEX_SHIFT    (0) 
#define TPMA_CC_RESERVED1_MASK        ((TPMA_CC) 0x003f0000) 
#define TPMA_CC_CHANDLES_MASK         ((TPMA_CC) 0x0e000000)
#define TPMA_CC_CHANDLES_SHIFT        (25) 
#define TPMA_CC_RES_MASK              ((TPMA_CC) 0xc0000000)
#define TPMA_CC_RES_SHIFT             (30) 
#define TPMA_MODES_RESERVED1_MASK     ((TPMA_MODES) 0xfffffffe) 
#define TPM2_NV_INDEX_INDEX_MASK      ((TPM2_NV_INDEX) 0x00ffffff) 
#define TPM2_NV_INDEX_INDEX_SHIFT     (0) 
#define TPM2_NV_INDEX_RH_NV_MASK      ((TPM2_NV_INDEX) 0xff000000) 
#define TPM2_NV_INDEX_RH_NV_SHIFT     (24) 
#define TPMA_NV_TPM2_NT_MASK      ((TPMA_NV) 0x000000f0) 
#define TPMA_NV_TPM2_NT_SHIFT     (4) 
#define TPMA_NV_RESERVED1_MASK    ((TPMA_NV) 0x00000300)
#define TPMA_NV_RESERVED2_MASK    ((TPMA_NV) 0x01f00000)

Also check
#define TPMA_NV_PPWRITE           ((TPMA_NV) 0x00000001) 
#define TPMA_NV_OWNERWRITE        ((TPMA_NV) 0x00000002) 
#define TPMA_NV_AUTHWRITE         ((TPMA_NV) 0x00000004)
#define TPMA_NV_POLICYWRITE       ((TPMA_NV) 0x00000008)
#define TPMA_NV_TPM2_NT_MASK      ((TPMA_NV) 0x000000f0) 
#define TPMA_NV_TPM2_NT_SHIFT     (4) 
#define TPMA_NV_RESERVED1_MASK    ((TPMA_NV) 0x00000300) 
#define TPMA_NV_POLICY_DELETE     ((TPMA_NV) 0x00000400) 
#define TPMA_NV_WRITELOCKED       ((TPMA_NV) 0x00000800) 
#define TPMA_NV_WRITEALL          ((TPMA_NV) 0x00001000) 
#define TPMA_NV_WRITEDEFINE       ((TPMA_NV) 0x00002000) 
#define TPMA_NV_WRITE_STCLEAR     ((TPMA_NV) 0x00004000) 
#define TPMA_NV_GLOBALLOCK        ((TPMA_NV) 0x00008000) 
#define TPMA_NV_PPREAD            ((TPMA_NV) 0x00010000) 
#define TPMA_NV_OWNERREAD         ((TPMA_NV) 0x00020000) 
#define TPMA_NV_AUTHREAD          ((TPMA_NV) 0x00040000) 
#define TPMA_NV_POLICYREAD        ((TPMA_NV) 0x00080000) 
#define TPMA_NV_RESERVED2_MASK    ((TPMA_NV) 0x01f00000) 
#define TPMA_NV_NO_DA             ((TPMA_NV) 0x02000000) 
#define TPMA_NV_ORDERLY           ((TPMA_NV) 0x04000000) 
#define TPMA_NV_CLEAR_STCLEAR     ((TPMA_NV) 0x08000000) 
#define TPMA_NV_READLOCKED        ((TPMA_NV) 0x10000000)
#define TPMA_NV_WRITTEN           ((TPMA_NV) 0x20000000) 
#define TPMA_NV_PLATFORMCREATE    ((TPMA_NV) 0x40000000) 
#define TPMA_NV_READ_STCLEAR      ((TPMA_NV) 0x80000000)

**Comment by tstruk** [comment]
It looks like for the masks we have these defined, but the definitions are missing the _MASK prefix. I'll add them. For the shifts there is bunch of them missing. I'll add them as well.
