### ISSUE TITLE
Create a dissect prototype

### ISSUE THREAD

**Issue by tstruk** [tpm2-software/tpm2-tss#835]
Create a new dissect prototype integrated with wireshark

**Comment by flihp** [comment]
'dissect' is what they call the bits that decode a binary blob?

**Comment by tstruk** [comment]
Yep, https://www.wireshark.org/docs/wsdg_html_chunked/ChWorksDissectPackets.html

**Comment by tstruk** [comment]
Done:
https://code.wireshark.org/review/#/c/26866/
