### ISSUE TITLE
Initialize TPMS_ and TPML_ to 0 on _Unmarshal ?

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tss#847]
There is this weirdness that TPM2B_s' `dest` parameters need to be initialized, because their `size`-field is tested for `==0`. This is because of the sad "underallocation logic".

For TPMS_ and TPML_ this is not the case from the spec. Therefore it should be possible to pass in uninitialized variables as `dest`.

Currently, if a TPMS_ or TPML_ contains a TPM2B_, the outer unmarshaling will call the inner unmarshalling directly. This again leads to access to uninitialized memory.

Instead, TPMS_ and TPML_ unmarshalling should memset the `dest` parameter first and then call the embedded unmarshaling.

**Comment by tstruk** [comment]
If we do this then every member of TPMS and TPML will need to be initialized, because the unmarshaling doesn't really know the type of what is being unmarshaled.

**Comment by AndreasFuchsSIT** [comment]
My though was just to add
```
if (dst != NULL)
    memset(dst, 0, sizeof(*dst));
```
to all {TPMS_,TPML_}*_Unmarshal makros.

I know that we will set memory to 0 repeatedly for TPMSes inside TPMSes, but I see no other way.
I wish we could do it for TPM2B_ as well.

Makes sense ?
