### ISSUE TITLE
tss2_common.h: typo in ESAP RCs

### ISSUE THREAD

**Issue by JuergenReppSIT** [tpm2-software/tpm2-tss#855]
tss2_common.h contains `TSS2_BASE_RC_BAD_IO_ERROR` instead of `TSS2_BASE_RC_IO_ERROR` in line 224.

https://github.com/tpm2-software/tpm2-tss/blob/master/include/sapi/tss2_common.h#L224

**Comment by AndreasFuchsSIT** [comment]
Fixed by c2817fb52527bed416d4dc89696cae7c03db5c0c
