### ISSUE TITLE
rename tpm20.h to tss2.h

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#861]
Providing a convenience header is nice but `tpm20.h` is the wrong name now that we've rebranded everything to `tss2`. This should be a simple rename but a lot of one line changes in every source file that includes this header. It may be a good opportunity to have source files just include the file that they need since we don't force people to use only this header any longer.

**Comment by flihp** [comment]
with the way we've cleaned up the headers this convenience header is really not all that convenient. It's also promoting some bad habbits since it pulls in a pile of system headers. I've got an RFC PR ready to go that removes it completely. We'll see how bad that review goes.

**Comment by flihp** [comment]
#862

**Comment by liuqun** [comment]
A candidate C/C++ API header naming style:
```
#include <tpm2dot0/tss.h>
```
or:
```
#include <intel_tpm20_tss.h>
```
