### ISSUE TITLE
Integrate name resolution into mssim TCTI

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#875]
The configuration string should be able to take FQDNs and short names, turn them into IP addresses and make the appropriate connection.

Currently we only support stuff like: `tcp://127.0.0.1:2321/`.
After this we should be able to do something like: `tcp://localhost:2321/` and `tcp://some.domain.name:2321/`

**Comment by flihp** [comment]
@dantpm fixed this some back back

**Comment by danintel** [comment]
The IPv6 fix also added general name resolution--#876
