### ISSUE TITLE
support IPv6 in mssim TCTI

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#876]
Pretty much every distro now supports dual IPv4 and 6 stacks. We should accept conf strings in the mssim TCTI not just with v4 IP addresses, but also v6 like: `tcp://::1:2321/`, also see https://www.ietf.org/rfc/rfc2732.txt

**Comment by dantpm** [comment]
The traditional method is to use brackets to enclose the ipv6 address. E.g.,
https://[2001:470:7c:5e7::a00:27ff:febc:6f2c]:2321
Otherwise the port number and address portions are ambiguous.

Also use of hostnames mapped to IPv6 addresses are OK.

**Comment by AndreasFuchsSIT** [comment]
I think this comes down to counting ':'s...

I have some code hanging around here that basically did the following:
- If there are 0 or 1 ':', it's an ipv4 address or a hostname without or with port
- If there are [] and a ':' afterwards, it's an ipv6 address with a port
- If there are [] without a ':' afterwards, it's an ipv6 without a port
- If there are 8 ':', 'it's an ipv6 address with a port after the last ':'
- If there are 7 ':', with 2 ':' touching, it's an ipv6 address with a port after the last ':'
- If there are 7 or less non-touching ':', it's an ipv6 address without a port

This should give you maximum flexibility on inputs...
Hope I did not miss a case...

In any case, there should be more intelligent people out there that already solved this thing in a library, one might think...

**Comment by dantpm** [comment]
Nobody counts colons in existing practice--that's why everyone uses [] to disambiguate. Here's an example:
https://2001:470:7c:5e7::a00:27ff:febc:2321

Does this mean IP address https://2001:470:7c:5e7::a00:27ff:febc:2321 and the default port?
Or does it mean IP address https://2001:470:7c:5e7::a00:27ff:febc port 2321?

It also makes it a lot simpler to read for the cases where it is not ambiguous.

**Comment by AndreasFuchsSIT** [comment]
I agree that I would write an IPv6 as [1234::1234]:2321 wherever I can.

The idea that I referred to was merely maximizing input possibilities for "the others"... ;-)
We can of course leave it out if people think it's not worth it...

**Comment by dantpm** [comment]
I see the point you are making to be more flexible, but I rather keep to the standard formats. The [] brackets are not optional. From RFC 3986 https://www.ietf.org/rfc/rfc3986.txt  section 3.2.2: Host

> A host identified by an Internet Protocol literal address, version 6 [RFC3513] or later, is distinguished by enclosing the IP literal within square brackets ("[" and "]"). This is the only place where square bracket characters are allowed in the URI syntax. In anticipation of future, as-yet-undefined IP literal address formats, an implementation may use an optional version flag to indicate such a format explicitly rather than rely on heuristic determination.

**Comment by AndreasFuchsSIT** [comment]
Less code, less testing... Fine with me...

**Comment by danintel** [comment]
FYI, it looks like the IBM simulator will have my IPv6 patch incorporated:
https://sourceforge.net/p/ibmswtpm2/tickets/6/

This will add support to the tpm_simulator server (in addition to the fix to this issue, which fixes the client side only).

> From: Ken Goldman
> Sent: Wednesday, April 25, 2018 2:42 PM
> Subject: [ibmswtpm2:tickets] #6 Simulator does not support IPv6
> •	status: open --> accepted
> •	Comment:
> Thanks. I have a set of TPM changes coming, and I'll include this. Any hint on how to test the patch?

Here's a link to the patch in question (on github gist):
https://gist.github.com/danintel/a15fa70e94b28dee96a77c9d1bb70387
