### ISSUE TITLE
Attestation scenario test in TSS

### ISSUE THREAD

**Issue by dinhthienkhai** [tpm2-software/tpm2-tss#877]
Hi all,
I am researching about Attestation (or Quote) of PCR Extend. I looked in the tpmclient.cpp file, just had a test case about Quote is TestQuote() and it seems unfinished. It like that:
......
......
......
    // Test with wrong type of key.
    INIT_SIMPLE_TPM2B_SIZE( quoted );
    rval = Tss2_Sys_Quote ( sysContext, loadedSha1KeyHandle, &sessionsData, &qualifyingData, &inScheme,
            &pcrSelection,  &quoted, &signature, &sessionsDataOut );
    CheckPassed( rval );

    // Create signing key

    // Now test quote operation
//    Tpm20Quote ( ??TPMI_DH_OBJECT signHandle, TPM2B_DATA *qualifyingData,
//    TPMT_SIG_SCHEME *inScheme, TPML_PCR_SELECTION *pcrSelect,
//    TPMS_AUTH_COMMAND *sessionsData)

So, Can someone suggest or send me a full Quote test case, please! 
Other question, is DAA (Direct Anonymous Attestation) local attestation?
Thank you!

**Comment by AndreasFuchsSIT** [comment]
You can find a complete test of Quote here: https://github.com/tpm2-software/tpm2-tss/blob/master/test/integration/esys-quote.int.c and here: https://github.com/tpm2-software/tpm2-tools/blob/master/tools/tpm2_quote.c
You will need to implement validation yourself though...

Besides, this is not a bug. For contact to other users please see at tpm2@lists.01.org

**Comment by dinhthienkhai** [comment]
Thank you for sharing, @AndreasFuchsSIT 
I want to find a method to attestation PCR at local TPM. Can you suggest any method which support that?
Tks!
