### ISSUE TITLE
ESAPI: Set a meaningful default TCTI

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tss#881]
Current code uses the simulator on localhost as default tcti. This is of course not meaningful in any sense.

We need to set a meaningful default behaviour, maybe even probe for a list of tctis on the system.

**Comment by dantpm** [comment]
I think this would be useful if it was documented somewhere.

**Comment by dantpm** [comment]
I can extend the doxygen doc, but I need to find out how to run doxygen.  The following two methods fail (produce a empty document with just headers but no content in the ./html subdirectory:

```
doxygen doc/doxygen.dox
cd doc
doxygen doxygen.dox
```

**Comment by AndreasFuchsSIT** [comment]
@dantpm `./configure --enable-doxygen-doc && make doxygen-doc`

**Comment by dantpm** [comment]
Running 
`./configure --enable-doxygen-doc && make doxygen-doc`
Does not 

Does not work for me. It generates empty files with just the title, but no text from the source file comment blocks.  I filed this issue:
https://github.com/tpm2-software/tpm2-tss/issues/912

I'll close it if there's another step required or the above is incorrect.
