### ISSUE TITLE
Backport TSS2_SYS_RC_ABI_MISMATCH stuffs to 1.x branch

### ISSUE THREAD

**Issue by liuqun** [tpm2-software/tpm2-tss#883]
TSS2_SYS_RC_ABI_MISMATCH is not implementd in 1.x branch

https://github.com/tpm2-software/tpm2-tss/blob/5a580d470262323f3764158c999e3144b89a6dd2/sysapi/sysapi/ContextManagement.c#L44-L57

https://github.com/tpm2-software/tpm2-tss/blob/5a580d470262323f3764158c999e3144b89a6dd2/include/sapi/tss2_common.h#L188-L189

Related issues from 2.x branch:
- issue #864 Update ABI defines
- https://github.com/tpm2-software/tpm2-tss/commit/28164ade0e00c0177bec85f74440a36dbd7de877 in issue #868 SAPI: Two minor fixes

**Comment by tstruk** [comment]
1.x branch is not supported
