### ISSUE TITLE
Add separate TCTI_MAGIC for tcti_mssim and tcti_dev

### ISSUE THREAD

**Issue by tstruk** [tpm2-software/tpm2-tss#887]
Do we need to have two separate TCTI_MAGICs. Can one initialize a tcti object with Tss2_Tcti_Device_Init() and then call tcti_platform_command() on it? Also does the tcti_platform_command() function need to validate TCTI_MAGIC in similar way to how transfer() or recv() do?

**Comment by flihp** [comment]
I don't think this makes sense till we give each TCTI a separate context structure. I should have made a ticket for creating separate structures back when @AndreasFuchsSIT asked about it in some other thread a few weeks back. I'll do that now and link the issue to this one.
