### ISSUE TITLE
SAPI: Sanity-Check sizes

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tss#896]
Splitting this out from #879
Tss2_Sys_Execute should check TCTI Receive size against Header.size.

**Comment by tstruk** [comment]
@AndreasFuchsSIT this is already done in the TCTI receive function. What else should the Tss2_Sys_Execute() do?

**Comment by AndreasFuchsSIT** [comment]
We don't know that all TCTIs (esp external ones) will do this sanity check.
So having SAPI to it would not hurt.

**Comment by tstruk** [comment]
Fixed with commit https://github.com/tpm2-software/tpm2-tss/commit/fa423ad53c17d76284181d1715aeadecd9f438d6
