### ISSUE TITLE
ESAPI: Fix unchecked return value

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tss#899]
src/tss2-esys/esys_tr.c: Line 323: Tss2_MU_TPM2_HANDLE_Marshal

**Comment by dantpm** [comment]
This **can** be caught and detected by gcc, but, **unfortunately**, only if the function has `__attribute__((warn_unused_result));`
For functions without that attribute, no warning is issued, even with `gcc -Wall -Wextra -Wunused-result`  (or just one of the -W flags):

```
$ cat gcctest.c
int test() __attribute__((warn_unused_result));
int test(void) {
    return 4;
}
int main(void) {
    test();
    return 0;
}
$ gcc -Wunused-result -o gcctest gcctest.c
gcctest.c: In function â€˜mainâ€™:
gcctest.c:6:5: warning: ignoring return value of â€˜testâ€™, declared with attribute warn_unused_result [-Wunused-result]
     test();
     ^
```
