### ISSUE TITLE
Undefined Refs in Builds

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tss#907]
Im seeing this locally and: https://api.travis-ci.org/v3/job/359973671/log.txt
```
  CCLD     test/helper/tpm_transientempty
test/helper/test_helper_tpm_transientempty-tpm_transientempty.o: In function `main':
/workspace/tpm2-tss/test/helper/tpm_transientempty.c:27: undefined reference to `get_test_opts_from_env'
/workspace/tpm2-tss/test/helper/tpm_transientempty.c:28: undefined reference to `sanity_check_test_opts'
/workspace/tpm2-tss/test/helper/tpm_transientempty.c:31: undefined reference to `sapi_init_from_opts'
/workspace/tpm2-tss/test/helper/tpm_transientempty.c:47: undefined reference to `sapi_teardown_full'
collect2: error: ld returned 1 exit status
Makefile:4330: recipe for target 'test/helper/tpm_transientempty' failed
```

**Comment by flihp** [comment]
Same. To reproduce run the configure script with no parameters. This causes the unit tests to be disabled (no `--enable-unit`) and the integration tests to be disabled (no `--with-simulatorbin`). Looks like this `tpm_transientempty` module depends on symbols that aren't being built when the test cases are disabled.

**Comment by AndreasFuchsSIT** [comment]
correct...
tpm_transientempty should be guarded by if simulatorbin as well...

**Comment by flihp** [comment]
easy enough, PR incoming

**Comment by dantpm** [comment]
This also appears in builds of tpm2-abrmd, not just tpm2-tss
