### ISSUE TITLE
test-suite failure: FAIL test/unit/esys-resubmissions (exit status: 1)

### ISSUE THREAD

**Issue by cjpn** [tpm2-software/tpm2-tss#915]
I have just installed the software on a Raspberry Pi 3 running:

     Linux raspberrypi3 4.14.30-v7+ #1 SMP Thu Mar 29 15:55:34 BST 2018 armv7l

The test suite fails on: test/unit/esys-resubmissions and the log is attached.

[test-suite.log](https://github.com/tpm2-software/tpm2-tss/files/1866447/test-suite.log)

**Comment by JuergenReppSIT** [comment]
Will be fixed with some other errors in this test together with the next  version of the tss2-esys/api files.

**Comment by cjpn** [comment]
Thank you for your prompt reply and also for making this code available for others to use and experiment with.
