### ISSUE TITLE
EOF in 'read_all'

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#946]
The `read_all` function from the I/O module doesn't handle `EOF` gracefully. It's so graceless in fact that if a read from the provided `fd` does return `EOF` then we end up in an infinite loop. This bug is currently making the device TCTI unusable.

**Comment by martinezjavier** [comment]
@flihp right, I mentioned this bug in https://github.com/tpm2-software/tpm2-tss/pull/890#issuecomment-376460273 but didn't file an issue nor propose a fix, sorry about that.

**Comment by flihp** [comment]
thanks for the link. I remembered your comment but couldn't find it when I repro'd the issue yesterday.

**Comment by flihp** [comment]
@martinezjavier: you may also find #947 interesting / relevant. I backtracked to the EOF issue you mentioned while trying to figure out why the device TCTI was failing on account of the behavior described there. I guess assuming the behavior described in `man 2 read` would hold for the device driver was a bad idea :unamused:

**Comment by flihp** [comment]
this was resolved in #948
