### ISSUE TITLE
hash checks in travis-ci do nothing

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#999]
When we added this we were assuming that a failed command (non-zero exit code) would result in the build stopping / failing. Not the case, and this is a very old issue / feature request that travis-ci hasn't implemented for some weird reason: https://github.com/travis-ci/travis-ci/issues/1066

The more I use travis, the less I like it.

At the very least our hash checks should stop the build early. Using the `travis_terminate 1` trick in this case looks like the path of least resistance.

**Comment by tstruk** [comment]
Fixed in #1000
